<cfquery name="GET_CHAPTER" datasource="#dsn#">
	SELECT
		CH.CHAPTER_ID,
		CH.CHAPTER ,
		CC.CONTENTCAT
	FROM
		CONTENT_CAT CC,
		CONTENT_CHAPTER CH
	WHERE
		CC.LANGUAGE_ID = '#SESSION.EP.LANGUAGE#'
	AND
		CC.CONTENTCAT_ID <> 0
	AND
		CC.CONTENTCAT_ID = CH.CONTENTCAT_ID			
	ORDER BY 
		CH.CHAPTER
</cfquery>