<cfquery name="GET_OFFTIME" datasource="#DSN#">
	SELECT 
		OFFTIME.OFFTIMECAT_ID,
		SETUP_OFFTIME.OFFTIMECAT
	FROM 
		OFFTIME,
		SETUP_OFFTIME		 
	WHERE
		OFFTIME.VALID=1 AND
		OFFTIME.STARTDATE <= #NOW()# AND
		OFFTIME.FINISHDATE >= #NOW()# AND
		OFFTIME.EMPLOYEE_ID = #EMPLOYEE_ID# AND
		OFFTIME.OFFTIMECAT_ID = SETUP_OFFTIME.OFFTIMECAT_ID
</cfquery>