<cfquery name="GET_CHAPTER_HIER" datasource="#dsn#">
	SELECT CC.CONTENTCAT, 
		CC.CONTENTCAT_ID,
		CH.CHAPTER_ID,
		CH.CHAPTER 
	FROM
		CONTENT_CAT CC, CONTENT_CHAPTER CH
	WHERE 
	CC.CONTENTCAT_ID = CH.CONTENTCAT_ID 				  		
	AND CC.CONTENTCAT_ID IN 
	(
	SELECT
		CONTENTCAT_ID
	FROM
		CONTENT_CAT
	WHERE
		CONTENTCAT_ID <> 0									
		AND
		LANGUAGE_ID = '#SESSION.EP.LANGUAGE#'
	)
	ORDER BY
		CC.CONTENTCAT_ID
</cfquery>