<cfquery name="GET_OUR_COMP_AND_BRANCHS" datasource="#DSN#">
	SELECT
		OC.NICK_NAME,
		B.BRANCH_NAME,
		BRANCH_ID,
		COMPANY_NAME
	FROM
		BRANCH B,
		OUR_COMPANY OC
	WHERE
		B.COMPANY_ID=OC.COMP_ID
		AND B.BRANCH_STATUS = 1
		<cfif session.ep.ehesap neq 1>
			AND B.BRANCH_ID IN (
							SELECT
								BRANCH_ID
							FROM
								EMPLOYEE_POSITION_BRANCHES
							WHERE
								POSITION_CODE = #SESSION.EP.POSITION_CODE#
							)
		</cfif>
	ORDER BY
		BRANCH_NAME
</cfquery>
