<!--- FBS 20080728 sevk irsaliyesi history --->
<cfquery name="GET_SHIP" datasource="#DSN2#">
	SELECT * FROM SHIP WHERE SHIP_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#attributes.upd_id#">
</cfquery>
<cfquery name="GET_SHIP_ROW" datasource="#DSN2#">
	SELECT * FROM SHIP_ROW WHERE SHIP_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#attributes.upd_id#">
</cfquery>
<cf_date tarih = 'deliver_date'>
<cf_date tarih = 'ship_date'>
<cf_date tarih = 'due_date'>
<cf_date tarih = 'update_date'>
<cf_date tarih = 'record_date'>

<cflock name="#CREATEUUID()#" timeout="20">
	<cftransaction>
		<cfloop query="get_ship">
			<cfquery name="ADD_SHIP_HISTORY" datasource="#DSN2#" result="MAX_ID">
				INSERT INTO
					SHIP_HISTORY
				(
					SHIP_ID,
					WRK_ID,
					PURCHASE_SALES,
					SHIP_NUMBER,
					SHIP_TYPE,
					SHIP_METHOD,
					SHIP_DATE,
					SHIP_STATUS,
					IS_WITH_SHIP,
					COMPANY_ID,
					PARTNER_ID,
					CONSUMER_ID,
					DELIVER_DATE,
					LOCATION,
					DELIVER_STORE_ID,
					DELIVER_EMP,
					DEPARTMENT_IN,
					LOCATION_IN,
					OTHER_MONEY,
					OTHER_MONEY_VALUE,
					DISCOUNTTOTAL,
					GROSSTOTAL,
					NETTOTAL,
					TAXTOTAL,
					OTV_TOTAL,
					ADDRESS,
					PAYMETHOD_ID,
					ORDER_ID,
					PROJECT_ID,
					PROCESS_CAT,
					DISPATCH_SHIP_ID,
					IS_EXPORTED,
					IS_DELIVERED,
					CITY_ID,
					COUNTY_ID,
					DUE_DATE,
					SA_DISCOUNT,
					REF_NO,
					GENERAL_PROM_ID,
					GENERAL_PROM_LIMIT,
					GENERAL_PROM_AMOUNT,
					GENERAL_PROM_DISCOUNT,
					FREE_PROM_ID,
					FREE_PROM_LIMIT,
					FREE_PROM_COST,
					FREE_PROM_AMOUNT,
					FREE_PROM_STOCK_ID,
					FREE_STOCK_PRICE,
					FREE_STOCK_MONEY,
					PROD_ORDER_NUMBER,
					PROD_ORDER_RESULT_NUMBER,
					CARD_PAYMETHOD_ID,
					CARD_PAYMETHOD_RATE,
					SHIP_DETAIL,
					SALE_EMP,
					IS_SHIP_IPTAL,
					DELIVER_EMP_ID,
					COMMETHOD_ID,
					DELIVER_PAR_ID,
					RECORD_DATE,
					RECORD_EMP
				)
				VALUES
				(
					#ship_id#,
					<cfqueryparam cfsqltype="cf_sql_varchar" value="#wrk_id#">,
					#purchase_sales#,
					<cfif len(ship_number)><cfqueryparam cfsqltype="cf_sql_varchar" value="#ship_number#"><cfelse>NULL</cfif>,
					<cfif len(ship_type)>#ship_type#<cfelse>NULL</cfif>,
					<cfif len(ship_method)>#ship_method#<cfelse>NULL</cfif>,
					<cfif len(ship_date)>'#ship_date#'<cfelse>NULL</cfif>,
					<cfif len(ship_status)>#ship_status#<cfelse>NULL</cfif>,
					<cfif len(is_with_ship)>#is_with_ship#<cfelse>NULL</cfif>,
					<cfif len(company_id)>#company_id#<cfelse>NULL</cfif>,
					<cfif len(partner_id)>#partner_id#<cfelse>NULL</cfif>,
					<cfif len(consumer_id)>#consumer_id#<cfelse>NULL</cfif>,
					<cfif len(deliver_date)>'#deliver_date#'<cfelse>NULL</cfif>,
					<cfif len(location)>#location#<cfelse>NULL</cfif>,
					<cfif len(deliver_store_id)>#deliver_store_id#<cfelse>NULL</cfif>,
					<cfif len(deliver_emp)><cfqueryparam cfsqltype="cf_sql_varchar" value="#deliver_emp#"><cfelse>NULL</cfif>,
					<cfif len(department_in)>#department_in#<cfelse>NULL</cfif>,
					<cfif len(location_in)>#location_in#<cfelse>NULL</cfif>,
					<cfif len(other_money)><cfqueryparam cfsqltype="cf_sql_varchar" value="#other_money#"><cfelse>NULL</cfif>,
					<cfif len(other_money_value)>#other_money_value#<cfelse>NULL</cfif>,
					<cfif len(discounttotal)>#discounttotal#<cfelse>NULL</cfif>,
					<cfif len(grosstotal)>#grosstotal#<cfelse>NULL</cfif>,
					<cfif len(nettotal)>#nettotal#<cfelse>NULL</cfif>,
					<cfif len(taxtotal)>#taxtotal#<cfelse>NULL</cfif>,
					<cfif len(otv_total)>#otv_total#<cfelse>NULL</cfif>,
					<cfif len(address)>'#address#'<cfelse>NULL</cfif>,
					<cfif len(paymethod_id)>#paymethod_id#<cfelse>NULL</cfif>,
					<cfif len(order_id)>#order_id#<cfelse>NULL</cfif>,
					<cfif len(project_id)>#project_id#<cfelse>NULL</cfif>,
					<cfif len(process_cat)>#process_cat#<cfelse>NULL</cfif>,
					<cfif len(dispatch_ship_id)>#dispatch_ship_id#<cfelse>NULL</cfif>,
					<cfif len(is_exported)>#is_exported#<cfelse>NULL</cfif>,
					<cfif len(is_delivered)>#is_delivered#<cfelse>0</cfif>,
					<cfif len(city_id)>#city_id#<cfelse>NULL</cfif>,
					<cfif len(county_id)>#county_id#<cfelse>NULL</cfif>,
					<cfif len(due_date)>'#due_date#'<cfelse>NULL</cfif>,
					<cfif len(sa_discount)>#sa_discount#<cfelse>NULL</cfif>,
					<cfif len(ref_no)><cfqueryparam cfsqltype="cf_sql_varchar" value="#ref_no#"><cfelse>NULL</cfif>,
					<cfif len(general_prom_id)>#general_prom_id#<cfelse>NULL</cfif>,
					<cfif len(general_prom_limit)>#general_prom_limit#<cfelse>NULL</cfif>,
					<cfif len(general_prom_amount)>#general_prom_amount#<cfelse>NULL</cfif>,
					<cfif len(general_prom_discount)>#general_prom_discount#<cfelse>NULL</cfif>,
					<cfif len(free_prom_id)>#free_prom_id#<cfelse>NULL</cfif>,
					<cfif len(free_prom_limit)>#free_prom_limit#<cfelse>NULL</cfif>,
					<cfif len(free_prom_cost)>#free_prom_cost#<cfelse>NULL</cfif>,
					<cfif len(free_prom_amount)>#free_prom_amount#<cfelse>NULL</cfif>,
					<cfif len(free_prom_stock_id)>#free_prom_stock_id#<cfelse>NULL</cfif>,
					<cfif len(free_stock_price)>#free_stock_price#<cfelse>NULL</cfif>,
					<cfif len(free_stock_money)><cfqueryparam cfsqltype="cf_sql_varchar" value="#free_stock_money#"><cfelse>NULL</cfif>,
					<cfif len(prod_order_number)>#prod_order_number#<cfelse>NULL</cfif>,
					<cfif len(prod_order_result_number)>#prod_order_result_number#<cfelse>NULL</cfif>,
					<cfif len(card_paymethod_id)>#card_paymethod_id#<cfelse>NULL</cfif>,
					<cfif len(card_paymethod_rate)>#card_paymethod_rate#<cfelse>NULL</cfif>,
					<cfif len(ship_detail)><cfqueryparam cfsqltype="cf_sql_varchar" value="#ship_detail#"><cfelse>NULL</cfif>,
					<cfif len(sale_emp)>#sale_emp#<cfelse>NULL</cfif>,
					<cfif len(is_ship_iptal)>#is_ship_iptal#<cfelse>NULL</cfif>,
					<cfif len(deliver_emp_id)>#deliver_emp_id#<cfelse>NULL</cfif>,
					<cfif len(commethod_id)>#commethod_id#<cfelse>NULL</cfif>,
					<cfif len(deliver_par_id)>#deliver_par_id#<cfelse>NULL</cfif>,
					<cfif len(update_date)>'#update_date#'<cfelseif len(record_date)>'#record_date#'<cfelse>NULL</cfif>,
					<cfif len(update_emp)>#update_emp#<cfelseif len(record_emp)>#record_emp#<cfelse>NULL</cfif>
				)
			</cfquery>
		</cfloop>
		<cfloop query="get_ship_row">
			<cfquery name="ADD_SHIP_ROW_HISTORY" datasource="#DSN2#">
				INSERT INTO
					SHIP_ROW_HISTORY
				(
					SHIP_HISTORY_ID,
					SHIP_ROW_ID,
					SHIP_ID,
					PURCHASE_SALES,
					SHIP_STATUS,
					PRODUCT_ID,
					PRICE,
					PRICE_OTHER,
					AMOUNT,
					UNIT,
					UNIT_ID,
					TAX,
					PAYMETHOD_ID,
					ORDER_ROW,
					CATALOG_ID,
					STOCK_ID,
					NAME_PRODUCT,
					SHIP_DATE,
					SPECT_VAR_ID,
					SPECT_VAR_NAME,
					COST_ID,
					COST_PRICE,
					MARGIN,
					EXTRA_COST,
					DISCOUNT,
					DISCOUNT2,
					DISCOUNT3,
					DISCOUNT4,
					DISCOUNT5,
					DISCOUNT6,
					DISCOUNT7,
					DISCOUNT8,
					DISCOUNT9,
					DISCOUNT10,
					DISCOUNTTOTAL,
					GROSSTOTAL,
					NETTOTAL,
					TAXTOTAL,
					DELIVER_DATE,
					DELIVER_DEPT,
					DELIVER_LOC,
					OTHER_MONEY,
					OTHER_MONEY_VALUE,
					OTHER_MONEY_GROSS_TOTAL,
					LOT_NO,
					DARALI,
					DARA,
					ROW_ORDER_ID,
					PROM_COMISSION,
					PROM_COST,
					DISCOUNT_COST,
					IS_PROMOTION,
					PROM_ID,
					PROM_STOCK_ID,
					IMPORT_INVOICE_ID,
					IMPORT_PERIOD_ID,
					IS_COMMISSION,
					UNIQUE_RELATION_ID,
					PRODUCT_NAME2,
					EXTRA_PRICE_OTHER_TOTAL,
					AMOUNT2,
					UNIT2,
					EXTRA_PRICE,
					SHELF_NUMBER,
					PRODUCT_MANUFACT_CODE,
					EXTRA_PRICE_TOTAL,
					OTV_ORAN,
					OTVTOTAL,
					BASKET_EXTRA_INFO_ID,
					SELECT_INFO_EXTRA,
                	DETAIL_INFO_EXTRA,
					PROM_RELATION_ID,
					RELATED_SHIP_ID,
					RELATED_SHIP_PERIOD,
					BASKET_EMPLOYEE_ID,
					LIST_PRICE,
					NUMBER_OF_INSTALLMENT,
					DUE_DATE,
					PRICE_CAT,
					KARMA_PRODUCT_ID,
					SERVICE_ID,
					EK_TUTAR_PRICE,
					ROW_INTERNALDEMAND_ID,
					WIDTH_VALUE,
					DEPTH_VALUE,
					HEIGHT_VALUE,
					ROW_PROJECT_ID,
					WRK_ROW_ID,
					WRK_ROW_RELATION_ID
				)
				VALUES
				(
					#MAX_ID.IDENTITYCOL#,
					#ship_row_id#,
					#ship_id#,
					<cfif len(purchase_sales)>#purchase_sales#<cfelse>NULL</cfif>,
					<cfif len(ship_status)>#ship_status#<cfelse>NULL</cfif>,
					<cfif len(product_id)>#product_id#<cfelse>NULL</cfif>,
					<cfif len(price)>#price#<cfelse>NULL</cfif>,
					<cfif len(price_other)>#price_other#<cfelse>NULL</cfif>,
					<cfif len(amount)>#amount#<cfelse>NULL</cfif>,
					<cfif len(unit)><cfqueryparam cfsqltype="cf_sql_varchar" value="#unit#"><cfelse>NULL</cfif>,
					<cfif len(unit_id)>#unit_id#<cfelse>NULL</cfif>,
					<cfif len(tax)>#tax#<cfelse>NULL</cfif>,
					<cfif len(paymethod_id)>#paymethod_id#<cfelse>NULL</cfif>,
					<cfif len(order_row)>#order_row#<cfelse>NULL</cfif>,
					<cfif len(catalog_id)>#catalog_id#<cfelse>NULL</cfif>,
					<cfif len(stock_id)>#stock_id#<cfelse>NULL</cfif>,
					<cfif len(name_product)><cfqueryparam cfsqltype="cf_sql_varchar" value="#name_product#"><cfelse>NULL</cfif>,
					<cfif len(ship_date)>'#ship_date#'<cfelse>NULL</cfif>,
					<cfif len(spect_var_id)>#spect_var_id#<cfelse>NULL</cfif>,
					<cfif len(spect_var_name)><cfqueryparam cfsqltype="cf_sql_varchar" value="#spect_var_name#"><cfelse>NULL</cfif>,
					<cfif len(cost_id)>#cost_id#<cfelse>NULL</cfif>,
					<cfif len(cost_price)>#cost_price#<cfelse>NULL</cfif>,
					<cfif len(margin)>#margin#<cfelse>NULL</cfif>,
					<cfif len(extra_cost)>#extra_cost#<cfelse>NULL</cfif>,
					<cfif len(discount)>#discount#<cfelse>NULL</cfif>,
					<cfif len(discount2)>#discount2#<cfelse>NULL</cfif>,
					<cfif len(discount3)>#discount3#<cfelse>NULL</cfif>,
					<cfif len(discount4)>#discount4#<cfelse>NULL</cfif>,
					<cfif len(discount5)>#discount5#<cfelse>NULL</cfif>,
					<cfif len(discount6)>#discount6#<cfelse>NULL</cfif>,
					<cfif len(discount7)>#discount7#<cfelse>NULL</cfif>,
					<cfif len(discount8)>#discount8#<cfelse>NULL</cfif>,
					<cfif len(discount9)>#discount9#<cfelse>NULL</cfif>,
					<cfif len(discount10)>#discount10#<cfelse>NULL</cfif>,
					<cfif len(discounttotal)>#discounttotal#<cfelse>NULL</cfif>,
					<cfif len(grosstotal)>#grosstotal#<cfelse>NULL</cfif>,
					<cfif len(nettotal)>#nettotal#<cfelse>NULL</cfif>,
					<cfif len(taxtotal)>#taxtotal#<cfelse>NULL</cfif>,
					<cfif len(deliver_date)>'#deliver_date#'<cfelse>NULL</cfif>,
					<cfif len(deliver_dept)>#deliver_dept#<cfelse>NULL</cfif>,
					<cfif len(deliver_loc)>#deliver_loc#<cfelse>NULL</cfif>,
					<cfif len(other_money)><cfqueryparam cfsqltype="cf_sql_varchar" value="#other_money#"><cfelse>NULL</cfif>,
					<cfif len(other_money_value)>#other_money_value#<cfelse>NULL</cfif>,
					<cfif len(other_money_gross_total)>#other_money_gross_total#<cfelse>NULL</cfif>,
					<cfif len(lot_no)><cfqueryparam cfsqltype="cf_sql_varchar" value="#lot_no#"><cfelse>NULL</cfif>,
					<cfif len(darali)>#darali#<cfelse>NULL</cfif>,
					<cfif len(dara)>#dara#<cfelse>NULL</cfif>,
					<cfif len(row_order_id)>#row_order_id#<cfelse>NULL</cfif>,
					<cfif len(prom_comission)>#prom_comission#<cfelse>NULL</cfif>,
					<cfif len(prom_cost)>#prom_cost#<cfelse>NULL</cfif>,
					<cfif len(discount_cost)>#discount_cost#<cfelse>NULL</cfif>,
					<cfif len(is_promotion)>#is_promotion#<cfelse>NULL</cfif>,
					<cfif len(prom_id)>#prom_id#<cfelse>NULL</cfif>,
					<cfif len(prom_stock_id)>#prom_stock_id#<cfelse>NULL</cfif>,
					<cfif len(import_invoice_id)>#import_invoice_id#<cfelse>NULL</cfif>,
					<cfif len(import_period_id)>#import_period_id#<cfelse>NULL</cfif>,
					<cfif len(is_commission)>#is_commission#<cfelse>NULL</cfif>,
					<cfif len(unique_relation_id)><cfqueryparam cfsqltype="cf_sql_varchar" value="#unique_relation_id#"><cfelse>NULL</cfif>,
					<cfif len(product_name2)><cfqueryparam cfsqltype="cf_sql_varchar" value="#product_name2#"><cfelse>NULL</cfif>,
					<cfif len(extra_price_other_total)>#extra_price_other_total#<cfelse>NULL</cfif>,
					<cfif len(amount2)>#amount2#<cfelse>NULL</cfif>,
					<cfif len(unit2)><cfqueryparam cfsqltype="cf_sql_varchar" value="#unit2#"><cfelse>NULL</cfif>,
					<cfif len(extra_price)>#extra_price#<cfelse>NULL</cfif>,
					<cfif len(shelf_number)><cfqueryparam cfsqltype="cf_sql_varchar" value="#shelf_number#"><cfelse>NULL</cfif>,
					<cfif len(product_manufact_code)><cfqueryparam cfsqltype="cf_sql_varchar" value="#product_manufact_code#"><cfelse>NULL</cfif>,
					<cfif len(extra_price_total)>#extra_price_total#<cfelse>NULL</cfif>,
					<cfif len(otv_oran)>#otv_oran#<cfelse>NULL</cfif>,
					<cfif len(otvtotal)>#otvtotal#<cfelse>NULL</cfif>,
					<cfif len(basket_extra_info_id)>#basket_extra_info_id#<cfelse>NULL</cfif>,
					<cfif len(select_info_extra)>#select_info_extra#<cfelse>NULL</cfif>,
					<cfif len(detail_info_extra)>'#DETAIL_INFO_EXTRA#'<cfelse>NULL</cfif>,
					<cfif len(prom_relation_id)><cfqueryparam cfsqltype="cf_sql_varchar" value="#prom_relation_id#"><cfelse>NULL</cfif>,
					<cfif len(related_ship_id)>#related_ship_id#<cfelse>NULL</cfif>,
					<cfif len(related_ship_period)>#related_ship_period#<cfelse>NULL</cfif>,
					<cfif len(basket_employee_id)>#basket_employee_id#<cfelse>NULL</cfif>,
					<cfif len(list_price)>#list_price#<cfelse>NULL</cfif>,
					<cfif len(number_of_installment)>#number_of_installment#<cfelse>NULL</cfif>,
					<cfif len(due_date)>'#due_date#'<cfelse>NULL</cfif>,
					<cfif len(price_cat)>#price_cat#<cfelse>NULL</cfif>,
					<cfif len(karma_product_id)>#karma_product_id#<cfelse>NULL</cfif>,
					<cfif len(service_id)>#service_id#<cfelse>NULL</cfif>,
					<cfif len(ek_tutar_price)>#ek_tutar_price#<cfelse>NULL</cfif>,
					<cfif len(row_internaldemand_id)>#row_internaldemand_id#<cfelse>NULL</cfif>,
					<cfif len(width_value)>#width_value#<cfelse>NULL</cfif>,
					<cfif len(depth_value)>#depth_value#<cfelse>NULL</cfif>,
					<cfif len(height_value)>#height_value#<cfelse>NULL</cfif>,
					<cfif len(row_project_id)>#row_project_id#<cfelse>NULL</cfif>,
					<cfif Len(wrk_row_id)><cfqueryparam cfsqltype="cf_sql_varchar" value="#wrk_row_id#"><cfelse>NULL</cfif>,
					<cfif Len(wrk_row_relation_id)><cfqueryparam cfsqltype="cf_sql_varchar" value="#wrk_row_relation_id#"><cfelse>NULL</cfif>
				)
			</cfquery>
		</cfloop>
	</cftransaction>
</cflock>
