<cfquery name="DEFAULT_MONEY" datasource="#dsn#">
	SELECT
		MONEY,
		RATE1,
		RATE2
	FROM
		SETUP_MONEY
	WHERE
		PERIOD_ID = #SESSION.EP.PERIOD_ID# AND
		PERIOD_ID = #SESSION.EP.PERIOD_ID# AND
		RATE1=1 AND RATE2=1
</cfquery>
