<cfquery name="SHIP" datasource="#dsn2#">
	SELECT
		SHIP.PURCHASE_SALES,
		SHIP.SHIP_NUMBER,
		SHIP.SHIP_DATE,
		SHIP.COMPANY_ID,
		SHIP.PARTNER_ID,
		SHIP.CONSUMER_ID,
		SHIP.DELIVER_DATE,
		SHIP.DELIVER_STORE_ID,
		SHIP.DEPARTMENT_IN,	
		SHIP.LOCATION_IN,		
		SHIP.DELIVER_EMP,
		<!--- SHIP.MONEY, --->
		SHIP.PAYMETHOD_ID,
		<!--- SHIP.RATE1,
		SHIP.RATE2, --->
		SHIP.DISCOUNTTOTAL,
		SHIP.GROSSTOTAL,
		SHIP.NETTOTAL,
		SHIP.TAXTOTAL,
		SHIP.RECORD_DATE,
		SHIP.RECORD_EMP,
		SHIP.SHIP_TYPE,
		SHIP.SHIP_METHOD,
		SHIP.DELIVER_EMP,
		DEPARTMENT.DEPARTMENT_HEAD,
		DEPARTMENT_2.DEPARTMENT_HEAD AS DEPARTMENT_HEAD_IN
		
	FROM
		SHIP,
		#dsn_alias#.DEPARTMENT AS DEPARTMENT,
		#dsn_alias#.DEPARTMENT AS DEPARTMENT_2
	WHERE
		SHIP.SHIP_ID = #attributes.UPD_ID#		
		AND
		(
				DEPARTMENT_2.DEPARTMENT_ID = SHIP.DEPARTMENT_IN
			OR
				DEPARTMENT.DEPARTMENT_ID = SHIP.DELIVER_STORE_ID
		)
		AND DEPARTMENT_2.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID		
</cfquery>
<cfif isnumeric(SHIP.DELIVER_EMP)>
	<cfquery name="get_ship_deliver" datasource="#DSN#">
		SELECT
			EMPLOYEE_NAME,
			EMPLOYEE_SURNAME
		FROM
			EMPLOYEES
		WHERE
			EMPLOYEE_ID=#SHIP.DELIVER_EMP#		
	</cfquery>
</cfif>
