<cfquery name="GET_STOCK_INFO" datasource="#DSN3#">
	SELECT
		PRODUCT.PRODUCT_NAME,
		STOCKS.STOCK_CODE,
		STOCKS.BARCOD,
		PRODUCT.MANUFACT_CODE
	FROM
		PRODUCT,
		STOCKS 
	WHERE 
		STOCKS.PRODUCT_ID=PRODUCT.PRODUCT_ID
	AND
		STOCKS.STOCK_ID=#attributes.stock_id#
</cfquery>
