<!---<cf_wrk_query name="GET_SIMILAR_SERVICES" datasource="#dsn#" case_value="SERVICE.SERVICE_ID">--->
<cfquery name="GET_SIMILAR_SERVICES" datasource="#dsn#">
	SELECT
		SERVICE.APPLY_DATE,
		SERVICE.SERVICE_ID,
		SERVICE.SERVICE_HEAD,
		SERVICE_APPCAT.SERVICECAT,
		SETUP_COMMETHOD.COMMETHOD,
		SETUP_PRIORITY.PRIORITY,
		SETUP_PRIORITY.COLOR
	FROM
		G_SERVICE AS SERVICE,
		G_SERVICE_APPCAT AS SERVICE_APPCAT,
		SETUP_COMMETHOD,
		SETUP_PRIORITY
	WHERE
		SERVICE.SERVICECAT_ID=SERVICE_APPCAT.SERVICECAT_ID
		AND 
		SETUP_COMMETHOD.COMMETHOD_ID=SERVICE.COMMETHOD_ID 
		AND
		SETUP_PRIORITY.PRIORITY_ID = SERVICE.PRIORITY_ID		
		<cfif isdefined("attributes.keyword") and LEN(attributes.keyword)>
		   AND 
			SERVICE.SERVICE_HEAD LIKE '%#attributes.keyword#%'
		</cfif>		
		<cfif isdefined("attributes.id")>
			AND
			SERVICE.SERVICE_ID <> #attributes.id#
		</cfif>		
	ORDER BY 
		SERVICE.RECORD_DATE
</cfquery>
