<cfquery name="GET_INTERNALDEMAND" datasource="#DSN3#">
SELECT * FROM INTERNALDEMAND WHERE INTERNAL_ID = #attributes.id#
</cfquery>
<cfquery name="GET_INTERNALDEMAND_ROW" datasource="#DSN3#">
SELECT * FROM INTERNALDEMAND_ROW  WHERE I_ID = #attributes.id#
</cfquery>
<cfif len(GET_INTERNALDEMAND.TARGET_DATE)>
	<cfset attributes.tarih = Dateformat(GET_INTERNALDEMAND.TARGET_DATE,dateformat_style)>
	<cf_date tarih='attributes.tarih'>
</cfif>
<cfquery name="ADD_INTERNALDEMAND_HISTORY" datasource="#DSN3#">
	INSERT INTO 
		INTERNALDEMAND_HISTORY
		(
            INTERNAL_ID,
            TO_POSITION_CODE,
            SUBJECT,
            RECORD_EMP,
            RECORD_DATE,
            UPDATE_EMP,
            UPDATE_DATE,
            TOTAL,
            DISCOUNT,
            TOTAL_TAX,
            OTV_TOTAL,
            NET_TOTAL,
            INTERNALDEMAND_STATUS,
            PRIORITY,
            NOTES,
            FROM_POSITION_CODE,
            TARGET_DATE,
            PROJECT_ID,
            INTERNALDEMAND_STAGE,
            DEPARTMENT_IN,
            LOCATION_IN,
            DEPARTMENT_OUT,
            LOCATION_OUT,
            REF_NO,
            SHIP_METHOD,
            INTERNAL_NUMBER,
            OTHER_MONEY,
            OTHER_MONEY_VALUE,
            WORK_ID,
            DEMAND_TYPE
		)
		VALUES
		(
			#get_internaldemand.internal_id#,
			<cfif len(get_internaldemand.to_position_code)>#get_internaldemand.to_position_code#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.subject)><cfqueryparam cfsqltype="cf_sql_varchar" value="#get_internaldemand.subject#"><cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.record_emp)>#get_internaldemand.record_emp# <cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.record_date)>#CreateOdbcDateTime(get_internaldemand.record_date)#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.update_emp)>#get_internaldemand.update_emp#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.update_date)>#CreateOdbcDateTime(get_internaldemand.update_date)#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.total)>#get_internaldemand.total#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.discount)>#get_internaldemand.discount#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.total_tax)>#get_internaldemand.total_tax#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.otv_total)>#get_internaldemand.otv_total#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.net_total)>#get_internaldemand.net_total#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.internaldemand_status)>#get_internaldemand.internaldemand_status#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.priority)>#get_internaldemand.priority#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.notes)><cfqueryparam cfsqltype="cf_sql_varchar" value="#get_internaldemand.notes#"><cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.from_position_code)>#get_internaldemand.from_position_code#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.target_date)>#attributes.tarih#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.project_id)>#get_internaldemand.project_id#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.internaldemand_stage)>#get_internaldemand.internaldemand_stage#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.department_in)>#get_internaldemand.department_in#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.location_in)>#get_internaldemand.location_in#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.department_out)>#get_internaldemand.department_out#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.location_out)>#get_internaldemand.location_out#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.ref_no)><cfqueryparam cfsqltype="cf_sql_varchar" value="#get_internaldemand.ref_no#"><cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.ship_method)>#get_internaldemand.ship_method#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.internal_number)><cfqueryparam cfsqltype="cf_sql_varchar" value="#get_internaldemand.internal_number#"><cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.other_money)><cfqueryparam cfsqltype="cf_sql_varchar" value="#get_internaldemand.other_money#"><cfelse>NULL</cfif>,
			<cfif len (get_internaldemand.other_money_value)><cfqueryparam cfsqltype="cf_sql_varchar" value="#get_internaldemand.other_money_value#"><cfelse>NULL</cfif>,
			<cfif len(get_internaldemand.work_id)>#get_internaldemand.work_id#<cfelse>NULL</cfif>,
            <cfif len(get_internaldemand.demand_type)>#get_internaldemand.demand_type#<cfelse>NULL</cfif> 
		)
</cfquery>
<cfquery name="get_internal_history_id" datasource="#DSN3#">
	SELECT MAX(INTERNAL_HISTORY_ID) INTERNAL_HISTORY_ID FROM INTERNALDEMAND_HISTORY 
</cfquery>
<cfloop query="GET_INTERNALDEMAND_ROW">
	<cfif len(GET_INTERNALDEMAND_ROW.DELIVER_DATE)>
		<cfset attributes.DELIVER_DATE = Dateformat(GET_INTERNALDEMAND_ROW.DELIVER_DATE,dateformat_style)>
		<cf_date tarih='attributes.DELIVER_DATE'>
	</cfif>
	<cfquery name="ADD_INTERNALDEMAND_ROW_HISTORY" datasource="#DSN3#">
		INSERT INTO 
			INTERNALDEMAND_ROW_HISTORY 
			(
				I_HISTORY_ID,
				I_ID,
				I_ROW_ID, 
				PRODUCT_ID,
				STOCK_ID,
				QUANTITY,
				UNIT,
				UNIT_ID,
				PRICE,
				PRICE_OTHER,
				OTHER_MONEY,
				OTHER_MONEY_VALUE,
				TAX,
				DUEDATE,
				PRODUCT_NAME,
				PAY_METHOD_ID,
				DELIVER_DATE,
				DISCOUNT_1,
				DISCOUNT_2,
				DISCOUNT_3,
				DISCOUNT_4,
				DISCOUNT_5,					
				DISCOUNT_6,
				DISCOUNT_7,
				DISCOUNT_8,
				DISCOUNT_9,
				DISCOUNT_10,
				TAXTOTAL,
				NETTOTAL,				
				OTV_ORAN,
				OTVTOTAL,
				COST_PRICE,
				EXTRA_COST,
				MARJ,
				PROM_COMISSION,
				PROM_COST,
				DISCOUNT_COST,
				PROM_ID,
				IS_PROMOTION,
				PROM_STOCK_ID,
				IS_COMMISSION,
				UNIQUE_RELATION_ID,
				PROM_RELATION_ID,
				AMOUNT2,
				UNIT2,
				EXTRA_PRICE,
				EK_TUTAR_PRICE,
				EXTRA_PRICE_TOTAL,
				EXTRA_PRICE_OTHER_TOTAL,
				SHELF_NUMBER,
				BASKET_EXTRA_INFO_ID,
				SELECT_INFO_EXTRA,
				DETAIL_INFO_EXTRA,
				PRICE_CAT,
				CATALOG_ID,
				LIST_PRICE,
				NUMBER_OF_INSTALLMENT,
				BASKET_EMPLOYEE_ID,
				KARMA_PRODUCT_ID,
				PRODUCT_NAME2,
				PRODUCT_MANUFACT_CODE,
				PRO_MATERIAL_ID,
				SPECT_VAR_ID,
				SPECT_VAR_NAME,
				RESERVE_DATE,
				WIDTH_VALUE,
				DEPTH_VALUE,
				HEIGHT_VALUE,
				ROW_PROJECT_ID
			)
		VALUES 
		(
			#get_internal_history_id.internal_history_id#,
			#get_internaldemand_row.I_ID#,
			<cfif len(get_internaldemand_row.I_ROW_ID)>#get_internaldemand_row.I_ROW_ID#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.PRODUCT_ID)>#get_internaldemand_row.product_id#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.STOCK_ID)>#get_internaldemand_row.STOCK_ID#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.QUANTITY)>#get_internaldemand_row.QUANTITY#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.UNIT)><cfqueryparam cfsqltype="cf_sql_varchar" value="#get_internaldemand_row.UNIT#"><cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.UNIT_ID)>#get_internaldemand_row.UNIT_ID#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.PRICE)>#get_internaldemand_row.PRICE#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.PRICE_OTHER)>#get_internaldemand_row.PRICE_OTHER#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.OTHER_MONEY)><cfqueryparam cfsqltype="cf_sql_varchar" value="#get_internaldemand_row.OTHER_MONEY#"><cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.OTHER_MONEY_VALUE)><cfqueryparam cfsqltype="cf_sql_varchar" value="#get_internaldemand_row.OTHER_MONEY_VALUE#"><cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.TAX)>#get_internaldemand_row.TAX#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.DUEDATE)>#get_internaldemand_row.DUEDATE#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.PRODUCT_NAME)><cfqueryparam cfsqltype="cf_sql_varchar" value="#get_internaldemand_row.PRODUCT_NAME#"><cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.PAY_METHOD_ID)>#get_internaldemand_row.PAY_METHOD_ID#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.DELIVER_DATE)>#attributes.DELIVER_DATE#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.DISCOUNT_1)>#get_internaldemand_row.DISCOUNT_1#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.DISCOUNT_2)>#get_internaldemand_row.DISCOUNT_2#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.DISCOUNT_3)>#get_internaldemand_row.DISCOUNT_3#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.DISCOUNT_4)>#get_internaldemand_row.DISCOUNT_4#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.DISCOUNT_5)>#get_internaldemand_row.DISCOUNT_5#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.DISCOUNT_6)>#get_internaldemand_row.DISCOUNT_6#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.DISCOUNT_7)>#get_internaldemand_row.DISCOUNT_7#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.DISCOUNT_8)>#get_internaldemand_row.DISCOUNT_8#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.DISCOUNT_9)>#get_internaldemand_row.DISCOUNT_9#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.DISCOUNT_10)>#get_internaldemand_row.DISCOUNT_10#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.TAXTOTAL)>#get_internaldemand_row.TAXTOTAL#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.NETTOTAL)>#get_internaldemand_row.NETTOTAL#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.OTV_ORAN)>#get_internaldemand_row.OTV_ORAN#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.OTVTOTAL)>#get_internaldemand_row.OTVTOTAL#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.COST_PRICE)>#get_internaldemand_row.COST_PRICE#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.EXTRA_COST)>#get_internaldemand_row.EXTRA_COST#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.MARJ)>#get_internaldemand_row.MARJ#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.PROM_COMISSION)>#get_internaldemand_row.PROM_COMISSION#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.PROM_COST)>#get_internaldemand_row.PROM_COST#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.DISCOUNT_COST)>#get_internaldemand_row.DISCOUNT_COST#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.PROM_ID)>#get_internaldemand_row.PROM_ID#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.IS_PROMOTION)>#get_internaldemand_row.IS_PROMOTION#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.PROM_STOCK_ID)>#get_internaldemand_row.PROM_STOCK_ID#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.IS_COMMISSION)>#get_internaldemand_row.IS_COMMISSION#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.UNIQUE_RELATION_ID)><cfqueryparam cfsqltype="cf_sql_varchar" value="#get_internaldemand_row.UNIQUE_RELATION_ID#"><cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.PROM_RELATION_ID)>#get_internaldemand_row.PROM_RELATION_ID#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.AMOUNT2)>#get_internaldemand_row.AMOUNT2#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.UNIT2)><cfqueryparam cfsqltype="cf_sql_varchar" value="#get_internaldemand_row.UNIT2#"><cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.EXTRA_PRICE)>#get_internaldemand_row.EXTRA_PRICE#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.EK_TUTAR_PRICE)>#get_internaldemand_row.EK_TUTAR_PRICE#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.EXTRA_PRICE_TOTAL)>#get_internaldemand_row.EXTRA_PRICE_TOTAL#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.EXTRA_PRICE_OTHER_TOTAL)>#get_internaldemand_row.EXTRA_PRICE_OTHER_TOTAL#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.SHELF_NUMBER)>#get_internaldemand_row.SHELF_NUMBER#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.BASKET_EXTRA_INFO_ID)>#get_internaldemand_row.BASKET_EXTRA_INFO_ID#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.SELECT_INFO_EXTRA)>#get_internaldemand_row.SELECT_INFO_EXTRA#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.DETAIL_INFO_EXTRA)>'#get_internaldemand_row.DETAIL_INFO_EXTRA#'<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.PRICE_CAT)>#get_internaldemand_row.PRICE_CAT#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.CATALOG_ID)>#get_internaldemand_row.CATALOG_ID#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.LIST_PRICE)>#get_internaldemand_row.LIST_PRICE#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.NUMBER_OF_INSTALLMENT)>#get_internaldemand_row.NUMBER_OF_INSTALLMENT#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.BASKET_EMPLOYEE_ID)>#get_internaldemand_row.BASKET_EMPLOYEE_ID#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.KARMA_PRODUCT_ID)>#get_internaldemand_row.KARMA_PRODUCT_ID#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.PRODUCT_NAME2)><cfqueryparam cfsqltype="cf_sql_varchar" value="#get_internaldemand_row.PRODUCT_NAME2#"><cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.PRODUCT_MANUFACT_CODE)><cfqueryparam cfsqltype="cf_sql_varchar" value="#get_internaldemand_row.PRODUCT_MANUFACT_CODE#"><cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.PRO_MATERIAL_ID)>#get_internaldemand_row.PRO_MATERIAL_ID#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.SPECT_VAR_ID)>#get_internaldemand_row.SPECT_VAR_ID#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.SPECT_VAR_NAME)><cfqueryparam cfsqltype="cf_sql_varchar" value="#get_internaldemand_row.SPECT_VAR_NAME#"><cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.RESERVE_DATE)><cfqueryparam cfsqltype="cf_sql_varchar" value="#get_internaldemand_row.RESERVE_DATE#"><cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.WIDTH_VALUE)>#get_internaldemand_row.WIDTH_VALUE#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.DEPTH_VALUE)>#get_internaldemand_row.DEPTH_VALUE#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.HEIGHT_VALUE)>#get_internaldemand_row.HEIGHT_VALUE#<cfelse>NULL</cfif>,
			<cfif len(get_internaldemand_row.ROW_PROJECT_ID)>#get_internaldemand_row.ROW_PROJECT_ID#<cfelse>NULL</cfif>
		)
	</cfquery>
</cfloop>
