<cfquery name="GET_CASH_BAKIYE" datasource="#dsn2#">
	SELECT     
		0 AS BORC, 
		SUM(CASH_ACTIONS.CASH_ACTION_VALUE) AS ALACAK, 
		CASH.CASH_ID, 
		CASH.CASH_NAME,
		CASH.CASH_CURRENCY_ID,
		SETUP_MONEY.RATE1,
		SETUP_MONEY.RATE2
	FROM         
		CASH_ACTIONS, CASH, SETUP_MONEY
	WHERE     
		CASH_ACTIONS.CASH_ACTION_FROM_CASH_ID = CASH.CASH_ID
		AND SETUP_MONEY.MONEY = CASH.CASH_CURRENCY_ID
	GROUP BY 
		CASH.CASH_ID, CASH.CASH_NAME,CASH.CASH_CURRENCY_ID,
		SETUP_MONEY.RATE1,
		SETUP_MONEY.RATE2
UNION
	SELECT     
		SUM(CASH_ACTIONS.CASH_ACTION_VALUE) AS BORC, 
		0 AS ALACAK, 
		CASH.CASH_ID, 
		CASH.CASH_NAME,
		CASH.CASH_CURRENCY_ID,
		SETUP_MONEY.RATE1,
		SETUP_MONEY.RATE2
	FROM         
		CASH_ACTIONS, CASH, SETUP_MONEY
	WHERE     
		CASH_ACTIONS.CASH_ACTION_TO_CASH_ID = CASH.CASH_ID
		AND SETUP_MONEY.MONEY = CASH.CASH_CURRENCY_ID
	GROUP BY 
		CASH.CASH_ID, CASH.CASH_NAME,CASH.CASH_CURRENCY_ID,
		SETUP_MONEY.RATE1,
		SETUP_MONEY.RATE2
</cfquery>
<cfquery name="GET_ACCOUNT_BAKIYE" datasource="#dsn2#">
	SELECT     
		0 AS ALACAK, 
		SUM(BANK_ACTIONS.ACTION_VALUE) AS BORC, 
		ACCOUNTS.ACCOUNT_ID, 
		<cfif session.ep.period_year lt 2009>
			CASE WHEN(ACCOUNTS.ACCOUNT_CURRENCY_ID = 'TL') THEN 'YTL' ELSE ACCOUNTS.ACCOUNT_CURRENCY_ID END AS  ACCOUNT_CURRENCY_ID,
		<cfelse>
			ACCOUNTS.ACCOUNT_CURRENCY_ID,
		</cfif>
		SETUP_MONEY.RATE1,
		SETUP_MONEY.RATE2 
	FROM         
		BANK_ACTIONS, 
		#dsn3_alias#.ACCOUNTS AS ACCOUNTS,
		SETUP_MONEY
	WHERE    
		ACCOUNTS.ACCOUNT_ID = BANK_ACTIONS.ACTION_TO_ACCOUNT_ID AND 
		BANK_ACTIONS.ACTION_TYPE_ID <> 93
		AND (SETUP_MONEY.MONEY = ACCOUNTS.ACCOUNT_CURRENCY_ID OR ACCOUNTS.ACCOUNT_CURRENCY_ID = 'TL')
	GROUP BY 
		ACCOUNTS.ACCOUNT_ID,
		ACCOUNTS.ACCOUNT_CURRENCY_ID,
		SETUP_MONEY.RATE1,
		SETUP_MONEY.RATE2 
UNION
	SELECT     
		SUM(BANK_ACTIONS.ACTION_VALUE) AS ALACAK, 
		0 AS BORC, 
		ACCOUNTS.ACCOUNT_ID, 
		<cfif session.ep.period_year lt 2009>
			CASE WHEN(ACCOUNTS.ACCOUNT_CURRENCY_ID = 'TL') THEN 'YTL' ELSE ACCOUNTS.ACCOUNT_CURRENCY_ID END AS  ACCOUNT_CURRENCY_ID,
		<cfelse>
			ACCOUNTS.ACCOUNT_CURRENCY_ID,
		</cfif>
		SETUP_MONEY.RATE1,
		SETUP_MONEY.RATE2  
	FROM        
		BANK_ACTIONS, 
		#dsn3_alias#.ACCOUNTS AS ACCOUNTS,SETUP_MONEY
	WHERE    
		ACCOUNTS.ACCOUNT_ID = BANK_ACTIONS.ACTION_FROM_ACCOUNT_ID AND 
		BANK_ACTIONS.ACTION_TYPE_ID <> 93
		AND (SETUP_MONEY.MONEY = ACCOUNTS.ACCOUNT_CURRENCY_ID OR ACCOUNTS.ACCOUNT_CURRENCY_ID = 'TL')
	GROUP BY 
		ACCOUNTS.ACCOUNT_ID, 
		ACCOUNTS.ACCOUNT_CURRENCY_ID,
		SETUP_MONEY.RATE1,
		SETUP_MONEY.RATE2 
</cfquery>
