<cfquery name="GET_DEP_STORE" datasource="#DSN#">
	SELECT
		BRANCH_NAME,
		DEPARTMENT_HEAD,
		DEPARTMENT_ID
	FROM
		BRANCH B,
		DEPARTMENT D
	WHERE
		D.BRANCH_ID=B.BRANCH_ID
	ORDER BY
		BRANCH_NAME,
		DEPARTMENT_HEAD
</cfquery>
