--GO3-TİGER3 Dönem Açılışı ch.form_upd_account_open

DECLARE @SQLString NVARCHAR(max)
DECLARE @YERELPARA nvarchar(3)
set @YERELPARA=(SELECT top 1 CURCODE FROM L_CURRENCYLIST WHERE  CURTYPE=(SELECT LOCALCTYP FROM L_CAPIFIRM A WHERE A.NR=@FirmNr) )
 
SET @SQLString = N'select 
	'''' as IslemTipi,
	CLCARD.CODE as CariKod,
	CLFLINE.CLPRJREF as ProjeID,
	'''' as AboneNo,
	'''' as FizikiVarlik,
	CLFLINE.BRANCH as Sube,
	ISNULL(CLFLINE.DEVIRPROCDATE,CLFLINE.DATE_) as IslemTarihi,
	PAYTRANS.DATE_ as OdemeTarihi,
	CLFLINE.DOCODE as BelgeNo,
	CASE WHEN CLFLINE.SIGN=0 THEN  PAYTRANS.TOTAL ELSE 0 END as Borc,
	CASE WHEN CLFLINE.SIGN=1 THEN  PAYTRANS.TOTAL ELSE 0 END as Alacak,
	ISNULL( (SELECT top 1 CURCODE FROM L_CURRENCYLIST WHERE  CURTYPE = CLFLINE.TRCURR),'''+@YERELPARA+''')  as IslemDovizi,
	  '''+@YERELPARA +'''  as SistemDovizi

from LG_'+@FirmNr+'_'+@DonemNr+'_CLFLINE   CLFLINE INNER JOIN LG_'+@FirmNr+'_CLCARD CLCARD
ON CLFLINE.CLIENTREF=CLCARD.LOGICALREF LEFT OUTER JOIN LG_'+@FirmNr+'_'+@DonemNr+'_PAYTRANS PAYTRANS
ON CLFLINE.LOGICALREF=PAYTRANS.FICHEREF AND PAYTRANS.MODULENR=5 AND PAYTRANS.TRCODE=14
where CLFLINE.TRCODE=14' 

EXECUTE sp_executesql @SQLString

 

 