/*
LogoGo3/LogoTiger3 Databaselerinden bilgi alır
Banka Hesabı Aktarım
fusaction=settings.form_add_bank_account_import
*/
use Tiger3
DECLARE @SubeId int
DECLARE @SQLString NVARCHAR(max)
set @SubeId=1

 SET @SQLString = N'select 
	 '+str(@SubeId)+' as SubeId,
	 BANKACC.IBAN as IbanKodu , 
	 BANKACC.DEFINITION_ HesapAdı,
	 (SELECT LOGICALREF FROM L_BANKCODE B WHERE B.CODE=BNCARD.CODE) as BankaId,
	 BNCARD.LOGICALREF  as SubeId,
	 ACCOUNTNO HesapNo,
	 (case when CARDTYPE in(1,3) then 2 else 1 end ) as HesapTuru ,
	 (SELECT top 1 CURCODE FROM L_CURRENCYLIST WHERE  CURTYPE=CURRENCY) as DovizCinsi,
	  WTHCLTRLLIMIT as KrediLimiti,
	 (SELECT EMUHACC.CODE
	   FROM LG_'+@FirmNr+'_CRDACREF AS CRDACREF INNER JOIN
			LG_'+@FirmNr+'_EMUHACC AS EMUHACC ON CRDACREF.ACCOUNTREF = EMUHACC.LOGICALREF
	   WHERE(CRDACREF.TRCODE = (CASE WHEN CARDTYPE IN (1, 3) THEN 6 WHEN CARDTYPE IN (2, 4) THEN 7 
	   WHEN CARDTYPE IN (5, 6) THEN 18 END)) AND (CRDACREF.TYP = 1) AND (CRDACREF.CARDREF = BANKACC.LOGICALREF)) as MuhasebeKodu,
	  '''' BankaTalimatı,
	  (SELECT EMUHACC.CODE
	   FROM LG_'+@FirmNr+'_CRDACREF AS CRDACREF INNER JOIN
			LG_'+@FirmNr+'_EMUHACC AS EMUHACC ON CRDACREF.ACCOUNTREF = EMUHACC.LOGICALREF
	   WHERE(CRDACREF.TRCODE = (CASE WHEN CARDTYPE IN (1, 3) THEN 6 WHEN CARDTYPE IN (2, 4) THEN 7 
	   WHEN CARDTYPE IN (5, 6) THEN 18 END)) AND (CRDACREF.TYP =4) AND (CRDACREF.CARDREF = BANKACC.LOGICALREF)) as VerilenCekler,
	(SELECT EMUHACC.CODE
	   FROM LG_'+@FirmNr+'_CRDACREF AS CRDACREF INNER JOIN
			LG_'+@FirmNr+'_EMUHACC AS EMUHACC ON CRDACREF.ACCOUNTREF = EMUHACC.LOGICALREF
	   WHERE(CRDACREF.TRCODE = (CASE WHEN CARDTYPE IN (1, 3) THEN 6 WHEN CARDTYPE IN (2, 4) THEN 7 
	   WHEN CARDTYPE IN (5, 6) THEN 18 END)) AND (CRDACREF.TYP =3) AND (CRDACREF.CARDREF = BANKACC.LOGICALREF)) as TakasCekleri,
	(SELECT EMUHACC.CODE
	   FROM LG_'+@FirmNr+'_CRDACREF AS CRDACREF INNER JOIN
			LG_'+@FirmNr+'_EMUHACC AS EMUHACC ON CRDACREF.ACCOUNTREF = EMUHACC.LOGICALREF
	   WHERE(CRDACREF.TRCODE = (CASE WHEN CARDTYPE IN (1, 3) THEN 6 WHEN CARDTYPE IN (2, 4) THEN 7 
	   WHEN CARDTYPE IN (5, 6) THEN 18 END)) AND (CRDACREF.TYP =3) AND (CRDACREF.CARDREF = BANKACC.LOGICALREF)) as TakasSenetleri,
	(SELECT EMUHACC.CODE
	   FROM LG_'+@FirmNr+'_CRDACREF AS CRDACREF INNER JOIN
			LG_'+@FirmNr+'_EMUHACC AS EMUHACC ON CRDACREF.ACCOUNTREF = EMUHACC.LOGICALREF
	   WHERE(CRDACREF.TRCODE = (CASE WHEN CARDTYPE IN (1, 3) THEN 6 WHEN CARDTYPE IN (2, 4) THEN 7 
	   WHEN CARDTYPE IN (5, 6) THEN 18 END)) AND (CRDACREF.TYP =2) AND (CRDACREF.CARDREF = BANKACC.LOGICALREF)) as TeminatCekleri,
	 (SELECT EMUHACC.CODE
	   FROM LG_'+@FirmNr+'_CRDACREF AS CRDACREF INNER JOIN
			LG_'+@FirmNr+'_EMUHACC AS EMUHACC ON CRDACREF.ACCOUNTREF = EMUHACC.LOGICALREF
	   WHERE(CRDACREF.TRCODE = (CASE WHEN CARDTYPE IN (1, 3) THEN 6 WHEN CARDTYPE IN (2, 4) THEN 7 
	   WHEN CARDTYPE IN (5, 6) THEN 18 END)) AND (CRDACREF.TYP =1) AND (CRDACREF.CARDREF = BANKACC.LOGICALREF)) as Teminatsenetleri,
	 (SELECT EMUHACC.CODE
	   FROM LG_'+@FirmNr+'_CRDACREF AS CRDACREF INNER JOIN
			LG_'+@FirmNr+'_EMUHACC AS EMUHACC ON CRDACREF.ACCOUNTREF = EMUHACC.LOGICALREF
	   WHERE(CRDACREF.TRCODE = (CASE WHEN CARDTYPE IN (1, 3) THEN 6 WHEN CARDTYPE IN (2, 4) THEN 7 
	   WHEN CARDTYPE IN (5, 6) THEN 18 END)) AND (CRDACREF.TYP =20) AND (CRDACREF.CARDREF = BANKACC.LOGICALREF)) as KarsiliksizCekler,
	 ''''  ProtestoluSenetler,
	 '''' as Açıklama,
	 case when  BANKACC.ACTIVE=0 then 1 else 0 end  as	Durumu 
FROM   LG_'+@FirmNr+'_BANKACC BANKACC INNER JOIN LG_'+@FirmNr+'_BNCARD BNCARD ON
BANKACC.BANKREF=BNCARD.LOGICALREF'

EXECUTE sp_executesql @SQLString

 
 