/*
LogoGo3/LogoTiger3 
Vardiya İmport
hr.import_shift
*/

SET @SQLString = N'SELECT        
	EMPLY.LOGICALREF CalısanID, 
	SHIFT.LOGICALREF AS VardiyaID, 
	CONVERT(VARCHAR, SHFTASGN.BEGDATE , 104) BaslangicTarihi , 

	(SELECT TOP 1 CONVERT(VARCHAR, SHFTASGN.BEGDATE , 104)  FROM LG_'+@FirmNr+'_SHFTASGN A 
	WHERE A.SOURCEREF=EMPLY.LOGICALREF AND SOURCETYPE=0 AND
	 A.LOGICALREF>SHFTASGN.LOGICALREF) BitisTarihi

FROM            LG_'+@FirmNr+'_SHIFT AS SHIFT WITH (NOLOCK) LEFT OUTER JOIN
                         LG_'+@FirmNr+'_SHFTASGN AS SHFTASGN WITH (NOLOCK) ON SHIFT.LOGICALREF = SHFTASGN.SHIFTREF LEFT OUTER JOIN
                         LG_'+@FirmNr+'_EMPLOYEE AS EMPLY WITH (NOLOCK) ON SHFTASGN.SOURCEREF = EMPLY.LOGICALREF
WHERE        (EMPLY.LOGICALREF = SHFTASGN.SOURCEREF) AND (SHFTASGN.SOURCETYPE = 0)
ORDER BY  EMPLY.LOGICALREF,SHFTASGN.LOGICALREF'

EXECUTE sp_executesql @SQLString
