--BORDRO PLUS-TIGER IK Eğitim Katılımcı Aktarımı settings.form_add_edu_participant_import

DECLARE @SQLString NVARCHAR(max)
 
SET @SQLString = N'select 

	 KIMLIK.MERNISNO as TCKimlikNo,
	 EGITIM.EGTGERCEKID as EgitimID,
	 0 as Yoklama,
	 CONVERT(VARCHAR, EGITIM.TARIH, 104)as YoklamaBaslangıcTarihi,
	 CONVERT(VARCHAR(5), EGITIM.BASSAAT, 8)as YoklamaBaslangıcSaati,
	 CONVERT(VARCHAR, EGITIM.BITTAR , 104)as YoklamaBitisTarihi,
	 CONVERT(VARCHAR(5), EGITIM.BITSAAT, 8)as YoklamaBitisSaati,
	KATILIMCILAR.EGTONCEDURUM as OnTest,
	KATILIMCILAR.EGTSONRADURUM as SonTest

from TBLEGTGERCEK EGITIM INNER JOIN TBLEGITIM KATILIMCILAR
ON EGITIM.EGTGERCEKID=KATILIMCILAR.EGTGERCEKID LEFT OUTER JOIN TBLKIMLIK KIMLIK
ON KATILIMCILAR.OZLUKID=KIMLIK.OZLUKID'

 EXECUTE sp_executesql @SQLString


 