
/*
LogoGo3/LogoTiger3 Databaselerinden bilgi alır
İş İstasyonu Masraf Merkezi Yansıma Oranı Aktarımı
settings.form_add_workstations_expense_center_import
*/
 
DECLARE @SQLString NVARCHAR(max)
SET @SQLString = N'select 

WORKSTAT.LOGICALREF as IstasyonID,
COSTPRDREF as PeriodID,
OVRHDCENTER.EXPCENTERREF as MasrafMerkeziID,
OVRHDCENTER.DISTRATE as YansımaOranı,
CASE WHEN OVRHDCENTER.CPCTYDRIVER= 1 THEN 2 ELSE 1 END as MaliyetTipi  

FROM    LG_'+@FirmNr+'_WORKSTAT AS WORKSTAT INNER JOIN
        LG_'+@FirmNr+'_WSOVHCASGN AS WSOVHCASGN ON WSOVHCASGN.WSREF = WORKSTAT.LOGICALREF INNER JOIN
        LG_'+@FirmNr+'_OVRHDCENTER AS OVRHDCENTER ON WSOVHCASGN.OVHDCENTERREF = OVRHDCENTER.LOGICALREF INNER JOIN
        LG_'+@FirmNr+'_OVRHDCENTERLN AS OVRHDCENTERLN ON OVRHDCENTER.LOGICALREF = OVRHDCENTERLN.OVRHDCENTERREF'

EXECUTE sp_executesql @SQLString
 