<cfquery name="get_branch_emps" datasource="#DSN#">
	SELECT
		EMPLOYEE_POSITIONS.EMPLOYEE_ID,
		EMPLOYEE_POSITIONS.EMPLOYEE_NAME,
		EMPLOYEE_POSITIONS.EMPLOYEE_SURNAME,
		EBA.BANK_BRANCH_CODE,
		EBA.BANK_ACCOUNT_NO
	FROM
		BRANCH,
		DEPARTMENT,
		EMPLOYEE_POSITIONS,
		EMPLOYEES_BANK_ACCOUNTS AS EBA
	WHERE
		BRANCH.BRANCH_ID=#attributes.BRANCH_ID#
	AND
		DEPARTMENT.BRANCH_ID=BRANCH.BRANCH_ID
	AND
		EMPLOYEE_POSITIONS.DEPARTMENT_ID=DEPARTMENT.DEPARTMENT_ID
	AND
		EMPLOYEE_POSITIONS.EMPLOYEE_ID <> 0
	AND
		EMPLOYEE_POSITIONS.EMPLOYEE_ID=EBA.EMPLOYEE_ID
	AND
		EBA.DEFAULT_ACCOUNT = 1
	AND
		EBA.BANK_NAME = 'TEB'
	AND
		EBA.MONEY LIKE '%TL%'
</cfquery>


