<cfquery name="GET_PR" datasource="#DSN3#">
	SELECT 
		PRICE,MONEY
	FROM
		PRICE_STANDART 
	WHERE
		PRICESTANDART_STATUS = 1
		AND PRODUCT_ID= #PRODUCT_ID# 
		AND PURCHASESALES = 1 
		AND UNIT_ID = #PRODUCT_UNIT_ID#
</cfquery>

