<cfquery name="GET_ALTERNATE_PRODUCT_EXCEPT" datasource="#dsn3#">
	SELECT
		AP.ALTERNATIVE_ID, 
		P.PRODUCT_NAME, 
		P.PRODUCT_ID 
	FROM
		PRODUCT AS P, 
		ALTERNATIVE_PRODUCTS_EXCEPT AS AP
	WHERE
		AP.ALTERNATIVE_PRODUCT_ID = P.PRODUCT_ID AND
		AP.PRODUCT_ID = #attributes.pid#
</cfquery>
