<CFQUERY name="GET_CATALOG_PROMOTION_PLUSES" datasource="#DSN3#">
	SELECT 
		CPP.*,
		E.EMPLOYEE_NAME,
		E.EMPLOYEE_SURNAME 
	FROM 
		CATALOG_PROMOTION_PLUS CPP,
		#dsn_alias#.EMPLOYEES E
	WHERE 
		CPP.CATALOG_PROMOTION_ID = #ATTRIBUTES.CATALOG_PROMOTION_ID#
		AND 
		CPP.PLUS_SUBJECT LIKE '%#ATTRIBUTES.KEYWORD#%'
		AND
		E.EMPLOYEE_ID = CPP.RECORD_EMP
</CFQUERY>
