<cfquery name="GET_PRICE_CAT_ROWS" datasource="#DSN3#">
	SELECT 
		PRODUCT_CAT.PRODUCT_CAT,
		PRODUCT_CAT.PROFIT_MARGIN,
		PRODUCT_CAT.PRODUCT_CATID,
		PRICE_CAT_ROWS.MARGIN
	FROM
		PRODUCT_CAT,
		PRICE_CAT_ROWS
	WHERE 
		PRODUCT_CAT.PRODUCT_CATID = PRICE_CAT_ROWS.PRODUCT_CATID AND
		PRICE_CAT_ROWS.PRICE_CATID = #attributes.pcat_id#
	ORDER BY 
		HIERARCHY
</cfquery>

