<cfquery name="GET_STOCK_DETAIL" datasource="#dsn1#">
	SELECT
		S.PRODUCT_ID,
		S.STOCK_ID,
		S.STOCK_CODE,
		S.STOCK_CODE_2,
		PU.ADD_UNIT,
		S.PROPERTY,
		S.STOCK_STATUS,
		S.BARCOD,
		S.ASSORTMENT_DEFAULT_AMOUNT
	FROM
		STOCKS S INNER JOIN PRODUCT_UNIT AS PU ON PU.PRODUCT_UNIT_ID = S.PRODUCT_UNIT_ID
	WHERE
		S.PRODUCT_ID = #url.pid#
</cfquery>