<cfquery name="get_quiz_training" datasource="#dsn#">
	SELECT
		TRAINING_CAT.TRAINING_CAT,
		TRAINING_SEC.SECTION_NAME,
		TRAINING.TRAIN_HEAD
	FROM
		TRAINING,
		TRAINING_SEC,
		TRAINING_CAT
	WHERE
		TRAINING.TRAIN_ID = #attributes.TRAINING_ID#
		AND
		TRAINING.TRAINING_SEC_ID = TRAINING_SEC.TRAINING_SEC_ID 
		AND
		TRAINING_SEC.TRAINING_CAT_ID = TRAINING_CAT.TRAINING_CAT_ID
</cfquery>

