<cfquery name="get_emp_att" datasource="#dsn#">
	SELECT 
		TCA.CLASS_ID,
		TCA.EMP_ID,
		TCA.CON_ID,
		TCA.PAR_ID,
		E.EMPLOYEE_NAME+' '+E.EMPLOYEE_SURNAME AS AD
	FROM 
		TRAINING_CLASS_ATTENDER TCA,
		EMPLOYEES E,
		EMPLOYEE_POSITIONS EP,
		DEPARTMENT,
		BRANCH,
		OUR_COMPANY C
	WHERE 
		EP.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID AND
		DEPARTMENT.BRANCH_ID=BRANCH.BRANCH_ID AND 
		BRANCH.BRANCH_ID IN (
                                SELECT
                                    BRANCH_ID
                                FROM
                                    EMPLOYEE_POSITION_BRANCHES
                                WHERE
                                    POSITION_CODE = #SESSION.EP.POSITION_CODE#	
                            ) AND 
		C.COMP_ID=BRANCH.COMPANY_ID AND 
		EP.EMPLOYEE_ID = TCA.EMP_ID AND
		TCA.EMP_ID = E.EMPLOYEE_ID AND
		TCA.CLASS_ID=#attributes.CLASS_ID#
	UNION
	SELECT	
		TCA.CLASS_ID,
		TCA.EMP_ID,
		TCA.CON_ID,
		TCA.PAR_ID,
		CON.CONSUMER_NAME+' '+CON.CONSUMER_SURNAME AS AD
	FROM 
		TRAINING_CLASS_ATTENDER TCA,
		CONSUMER CON
	WHERE 
		TCA.CON_ID = CON.CONSUMER_ID AND 
		TCA.CLASS_ID=#attributes.CLASS_ID#
	UNION
	SELECT	
		TCA.CLASS_ID,
		TCA.EMP_ID,
		TCA.CON_ID,
		TCA.PAR_ID,
		COMP.COMPANY_PARTNER_NAME+' '+ COMP.COMPANY_PARTNER_SURNAME AS AD
	FROM 
		TRAINING_CLASS_ATTENDER TCA,
		COMPANY_PARTNER COMP
	WHERE 
		TCA.PAR_ID = COMP.PARTNER_ID AND 
		TCA.CLASS_ID=#attributes.CLASS_ID#
	ORDER BY
		AD
</cfquery>

