<cfquery name="GET_PARTNER" datasource="#dsn#">
	SELECT 
		CP.PARTNER_ID,	
		CP.COMPANY_PARTNER_NAME,
		CP.COMPANY_PARTNER_SURNAME,
		CP.COMPANY_ID,
		CP.DEPARTMENT,
		C.FULLNAME,
		C.COMPANY_ID,
		CP.COMPANY_PARTNER_EMAIL
	FROM 
		COMPANY_PARTNER AS CP,
		COMPANY AS C
	WHERE
		CP.PARTNER_ID = #attributes.PARTNER_ID#
	AND
		C.COMPANY_ID=CP.COMPANY_ID
</cfquery>
