<cfquery name="GET_REPORT_POSITIONS" datasource="#DSN#">
	SELECT 
		RAR.POS_CODE,
		EP.POSITION_NAME,
		EP.EMPLOYEE_NAME,
		EP.EMPLOYEE_SURNAME
	FROM 
		REPORT_ACCESS_RIGHTS RAR,
		EMPLOYEE_POSITIONS EP
	WHERE
		RAR.REPORT_ID = #attributes.report_id# AND
		EP.POSITION_CODE = RAR.POS_CODE
</cfquery>
