<cfquery name="GET_COMPANY_BRANCH" datasource="#DSN#">
	SELECT
		COMPBRANCH__NAME,
		COMPBRANCH_ID,
		COMPBRANCH_TELCODE,
		COMPBRANCH_TEL1,
		COMPBRANCH_EMAIL,
		COUNTY_ID,
		CITY_ID,
		COUNTRY_ID
	FROM
		COMPANY_BRANCH
	WHERE
		COMPANY_ID = #url.cpid#
	ORDER BY
		COMPBRANCH__NAME
</cfquery>
