<cfquery name="get_company_service_info_list" datasource="#DSN#">
	SELECT 
		COMPANY_PARTNER_STORES_RELATED.COMPANY_ID, 
		COMPANY_PARTNER_STORES_RELATED.PARTNER_ID,
		OUR_COMPANY.NICK_NAME
	FROM 
		COMPANY_PARTNER_STORES_RELATED, 
		OUR_COMPANY
	WHERE 
		COMPANY_PARTNER_STORES_RELATED.PARTNER_ID = #attributes.cpid# AND
		COMPANY_PARTNER_STORES_RELATED.COMPANY_ID = OUR_COMPANY.COMP_ID
		<!--- BRANCH.COMPANY_ID = OUR_COMPANY.COMP_ID   --->
</cfquery>
