<cfquery name="GET_CONSUMER_ANALYSIS_S" datasource="#dsn#">
	SELECT 
		ANALYSIS_ID,
		ANALYSIS_HEAD,
		ANALYSIS_CONSUMERS	
	FROM 
		MEMBER_ANALYSIS,
		CONSUMER,
		CONSUMER_CAT
	WHERE
		MEMBER_ANALYSIS.IS_ACTIVE=1
		AND
		MEMBER_ANALYSIS.IS_PUBLISHED=1
		AND
		CONSUMER.CONSUMER_ID = #attributes.CID# 
		AND
		CONSUMER_CAT.CONSCAT_ID = CONSUMER.CONSUMER_CAT_ID		
</cfquery>

