<cfquery name="GET_TIME_COST" datasource="#dsn#">
	SELECT 
		TIME_COST.* ,
		EMPLOYEES.EMPLOYEE_ID,
		EMPLOYEES.EMPLOYEE_NAME,
		EMPLOYEES.EMPLOYEE_SURNAME
	FROM 
		TIME_COST,
		EMPLOYEES
	WHERE 
		EMPLOYEES.EMPLOYEE_ID = TIME_COST.EMPLOYEE_ID
	ORDER BY
		TIME_COST.TIME_COST_ID
</cfquery>
