<cfquery name="get_norm" datasource="#DSN#">
		SELECT
				BRANCH_ID,
				SUM(EMPLOYEE_COUNT1*AVERAGE_SALARY*(RATE2/RATE1)) AS E_COUNT1,
				SUM(EMPLOYEE_COUNT2*AVERAGE_SALARY*(RATE2/RATE1)) AS E_COUNT2,
				SUM(EMPLOYEE_COUNT3*AVERAGE_SALARY*(RATE2/RATE1)) AS E_COUNT3,
				SUM(EMPLOYEE_COUNT4*AVERAGE_SALARY*(RATE2/RATE1)) AS E_COUNT4,
				SUM(EMPLOYEE_COUNT5*AVERAGE_SALARY*(RATE2/RATE1)) AS E_COUNT5,
				SUM(EMPLOYEE_COUNT6*AVERAGE_SALARY*(RATE2/RATE1)) AS E_COUNT6,
				SUM(EMPLOYEE_COUNT7*AVERAGE_SALARY*(RATE2/RATE1)) AS E_COUNT7,
				SUM(EMPLOYEE_COUNT8*AVERAGE_SALARY*(RATE2/RATE1)) AS E_COUNT8,
				SUM(EMPLOYEE_COUNT9*AVERAGE_SALARY*(RATE2/RATE1)) AS E_COUNT9,
				SUM(EMPLOYEE_COUNT10*AVERAGE_SALARY*(RATE2/RATE1)) AS E_COUNT10,
				SUM(EMPLOYEE_COUNT11*AVERAGE_SALARY*(RATE2/RATE1)) AS E_COUNT11,
				SUM(EMPLOYEE_COUNT12*AVERAGE_SALARY*(RATE2/RATE1)) AS E_COUNT12,
				SUM(EMPLOYEE_COUNT1*AVERAGE_SALARY*(RATE2/RATE1))+
				SUM(EMPLOYEE_COUNT2*AVERAGE_SALARY*(RATE2/RATE1))+
				SUM(EMPLOYEE_COUNT3*AVERAGE_SALARY*(RATE2/RATE1))+
				SUM(EMPLOYEE_COUNT4*AVERAGE_SALARY*(RATE2/RATE1))+
				SUM(EMPLOYEE_COUNT5*AVERAGE_SALARY*(RATE2/RATE1))+
				SUM(EMPLOYEE_COUNT6*AVERAGE_SALARY*(RATE2/RATE1))+
				SUM(EMPLOYEE_COUNT7*AVERAGE_SALARY*(RATE2/RATE1))+
				SUM(EMPLOYEE_COUNT8*AVERAGE_SALARY*(RATE2/RATE1))+
				SUM(EMPLOYEE_COUNT9*AVERAGE_SALARY*(RATE2/RATE1))+
				SUM(EMPLOYEE_COUNT10*AVERAGE_SALARY*(RATE2/RATE1))+
				SUM(EMPLOYEE_COUNT11*AVERAGE_SALARY*(RATE2/RATE1))+
				SUM(EMPLOYEE_COUNT12*AVERAGE_SALARY*(RATE2/RATE1))  AS TOTAL_AMOUNT
			FROM
				EMPLOYEE_NORM_POSITIONS,
				SETUP_MONEY SM
			WHERE
					SM.PERIOD_ID = #SESSION.EP.PERIOD_ID# AND
					SM.MONEY=EMPLOYEE_NORM_POSITIONS.MONEY AND
					DEPARTMENT_ID=#attributes.DEPARTMENT_ID#
					<cfif isdefined("attributes.year_") and len(attributes.year_)>
						AND NORM_YEAR=#attributes.year_#
					<cfelse>
						AND NORM_YEAR=#attributes.budget_year#
					</cfif>
			GROUP BY 
				DEPARTMENT_ID,BRANCH_ID
</cfquery>
