<!--- Varlık Talepleri --->
<cfquery name="get_assetp_demand" datasource="#dsn#">
	SELECT 
		ASSET_P_DEMAND.DEMAND_ID,
		ASSET_P_DEMAND.EMPLOYEE_ID,
		ASSET_P_DEMAND.REQUEST_DATE,
		ASSET_P_DEMAND.RESULT_ID,
		ASSET_P_DEMAND.RECORD_DATE,
		ASSET_P_CAT.ASSETP_CAT,
		SETUP_USAGE_PURPOSE.USAGE_PURPOSE,
        PTR.STAGE,
        E.EMPLOYEE_NAME,
        E.EMPLOYEE_SURNAME
	FROM 
		ASSET_P_DEMAND 
        LEFT JOIN PROCESS_TYPE_ROWS PTR ON PTR.PROCESS_ROW_ID = ASSET_P_DEMAND.STAGE
        LEFT JOIN EMPLOYEES E ON E.EMPLOYEE_ID = ASSET_P_DEMAND.EMPLOYEE_ID,
		ASSET_P_CAT,
		SETUP_USAGE_PURPOSE
	WHERE
		ASSET_P_DEMAND.ASSETP_CATID = ASSET_P_CAT.ASSETP_CATID AND
		ASSET_P_DEMAND.USAGE_PURPOSE_ID = SETUP_USAGE_PURPOSE.USAGE_PURPOSE_ID AND
		ASSET_P_DEMAND.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEE_POSITIONS WHERE 
											POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">
                                            AND IS_MASTER=1)
	ORDER BY 
		ASSET_P_DEMAND.REQUEST_DATE DESC,
		ASSET_P_DEMAND.RESULT_ID
		
</cfquery>
<!--- Varlık Talep Edenler --->
<cfquery name="get_assetp_demand_valid" datasource="#dsn#">
	SELECT
		ASSET_P_DEMAND.DEMAND_ID,
		ASSET_P_DEMAND.EMPLOYEE_ID,
		ASSET_P_DEMAND.REQUEST_DATE,
		ASSET_P_DEMAND.RESULT_ID,
		ASSET_P_DEMAND.RECORD_DATE,
		ASSET_P_DEMAND.RECORD_EMP,
		ASSET_P_CAT.ASSETP_CAT,
		SETUP_USAGE_PURPOSE.USAGE_PURPOSE,
        PTR.STAGE,
        E.EMPLOYEE_NAME,
        E.EMPLOYEE_SURNAME
	FROM 
		ASSET_P_DEMAND
        LEFT JOIN PROCESS_TYPE_ROWS PTR ON PTR.PROCESS_ROW_ID = ASSET_P_DEMAND.STAGE
        LEFT JOIN EMPLOYEES E ON E.EMPLOYEE_ID = ASSET_P_DEMAND.EMPLOYEE_ID,
		ASSET_P_CAT,
		SETUP_USAGE_PURPOSE
	WHERE
		ASSET_P_DEMAND.ASSETP_CATID = ASSET_P_CAT.ASSETP_CATID AND
		ASSET_P_DEMAND.USAGE_PURPOSE_ID = SETUP_USAGE_PURPOSE.USAGE_PURPOSE_ID AND
		ASSET_P_DEMAND.RESULT_ID IS NULL AND
        (ASSET_P_DEMAND.VALIDATOR_POS_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#"> OR
        ASSET_P_DEMAND.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEE_POSITIONS WHERE 
                                            	(UPPER_POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#"> 
                                                OR UPPER_POSITION_CODE2 = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">) 
                                            AND IS_MASTER=1))
	ORDER BY 
		ASSET_P_DEMAND.REQUEST_DATE DESC,
		ASSET_P_DEMAND.EMPLOYEE_ID
</cfquery>

