<cfquery name="GET_FORUM_NAME" datasource="#dsn#">
	SELECT 
		FORUMNAME,
		FORUMID, 
		ADMIN_POS,
		ADMIN_CONS,
		ADMIN_PARS,
		FORUM_CONS_CATS, 
		FORUM_COMP_CATS,
		FORUM_EMPS,
		DESCRIPTION,
		LAST_MSG_USERKEY,
		LAST_MSG_DATE,
		REPLY_COUNT,
        RECORD_EMP,
		TOPIC_COUNT
	FROM 
		FORUM_MAIN
	WHERE
		FORUMID = #attributes.FORUMID#
</cfquery>