<cfquery name="GET_CLASS_INFORM_EMPS" datasource="#dsn#">
	SELECT
		TRAINING_CLASS_INFORM.EMP_ID,
		EMPLOYEES.EMPLOYEE_NAME,
		EMPLOYEES.EMPLOYEE_SURNAME,
		TRAINING_CLASS_INFORM.STATUS,
		EMPLOYEES.EMPLOYEE_ID
	FROM
		TRAINING_CLASS_INFORM,
		EMPLOYEES,
		EMPLOYEE_POSITIONS,
		DEPARTMENT,
		BRANCH,
		OUR_COMPANY C
	WHERE
		TRAINING_CLASS_INFORM.CLASS_ID = #attributes.CLASS_ID# AND 
		EMPLOYEES.EMPLOYEE_ID = TRAINING_CLASS_INFORM.EMP_ID AND 
		TRAINING_CLASS_INFORM.EMP_ID = EMPLOYEE_POSITIONS.EMPLOYEE_ID AND 
		DEPARTMENT.BRANCH_ID=BRANCH.BRANCH_ID AND 
		C.COMP_ID=BRANCH.COMPANY_ID AND 
		EMPLOYEE_POSITIONS.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID AND 
		EMPLOYEE_POSITIONS.IS_MASTER = 1 AND 
		TRAINING_CLASS_INFORM.EMP_ID IS NOT NULL
	<cfif branch_id_list gt 0>
		AND BRANCH.BRANCH_ID IN (#branch_id_list#)
	</cfif>
	ORDER BY 
		EMPLOYEES.EMPLOYEE_ID
</cfquery>
<cfquery name="GET_CLASS_INFORM_PARS" datasource="#dsn#">
	SELECT
		TRAINING_CLASS_INFORM.PAR_ID,
		TRAINING_CLASS_INFORM.STATUS,
		COMPANY_PARTNER.COMPANY_PARTNER_NAME,
		COMPANY_PARTNER.COMPANY_PARTNER_SURNAME,
		COMPANY.NICKNAME,
		COMPANY.COMPANY_ID,
		COMPANY_PARTNER.PARTNER_ID
	FROM
		TRAINING_CLASS_INFORM,
		COMPANY_PARTNER,
		COMPANY
	WHERE
		TRAINING_CLASS_INFORM.CLASS_ID = #attributes.CLASS_ID# AND
		COMPANY_PARTNER.PARTNER_ID = TRAINING_CLASS_INFORM.PAR_ID AND
		COMPANY_PARTNER.COMPANY_ID = COMPANY.COMPANY_ID AND
		TRAINING_CLASS_INFORM.PAR_ID IS NOT NULL
	ORDER BY 
		COMPANY_PARTNER.COMPANY_PARTNER_NAME
</cfquery>

<cfquery name="GET_CLASS_INFORM_CONS" datasource="#dsn#">
	SELECT
		TRAINING_CLASS_INFORM.CON_ID,
		TRAINING_CLASS_INFORM.STATUS,
		CONSUMER.CONSUMER_NAME,
		CONSUMER.CONSUMER_SURNAME,
		CONSUMER.COMPANY,
		CONSUMER.CONSUMER_ID
	FROM
		TRAINING_CLASS_INFORM,
		CONSUMER
	WHERE
		TRAINING_CLASS_INFORM.CLASS_ID = #attributes.CLASS_ID# AND
		CONSUMER.CONSUMER_ID = TRAINING_CLASS_INFORM.CON_ID AND
		TRAINING_CLASS_INFORM.CON_ID IS NOT NULL
	ORDER BY 
		CONSUMER.CONSUMER_NAME
</cfquery>
<cfquery name="GET_CLASS_INFORM_GRPS" datasource="#dsn#">
	SELECT
		TRAINING_CLASS_INFORM.GRP_ID,
		TRAINING_CLASS_INFORM.STATUS,
		USERS.GROUP_NAME
	FROM
		TRAINING_CLASS_INFORM,
		USERS
	WHERE
		TRAINING_CLASS_INFORM.CLASS_ID = #attributes.CLASS_ID# AND
		USERS.GROUP_ID = TRAINING_CLASS_INFORM.GRP_ID AND
		TRAINING_CLASS_INFORM.GRP_ID IS NOT NULL
	ORDER BY 
		USERS.GROUP_NAME
</cfquery>

<cfset all_inform_ids = "">
<cfloop query="get_class_inform_emps">
	<cfset all_inform_ids = listappend(all_inform_ids,"emp-#emp_id#")>
</cfloop>
<cfloop query="get_class_inform_pars">
	<cfset all_inform_ids = listappend(all_inform_ids,"par-#par_id#-#company_id#")>
</cfloop>
<cfloop query="get_class_inform_cons">
	<cfset all_inform_ids = listappend(all_inform_ids,"con-#con_id#")>
</cfloop>
<cfloop query="get_class_inform_grps">
	<cfset all_inform_ids = listappend(all_inform_ids,"grp-#grp_id#")>
</cfloop>
