<cfquery name="GET_DEPARTMENTS" datasource="#dsn#">
	SELECT 
		DEPARTMENT.DEPARTMENT_ID,
		DEPARTMENT.DEPARTMENT_HEAD,
		DEPARTMENT.BRANCH_ID,
		DEPARTMENT.DEPARTMENT_STATUS,
		BRANCH.BRANCH_NAME,
		BRANCH.BRANCH_STATUS
	FROM 
		DEPARTMENT,
		BRANCH
	WHERE
		BRANCH.BRANCH_STATUS = 1
		AND
		BRANCH.BRANCH_ID = DEPARTMENT.BRANCH_ID
		AND
		DEPARTMENT.DEPARTMENT_STATUS = 1
	ORDER BY DEPARTMENT.BRANCH_ID
</cfquery>
