<cfquery name="GET_CLASS_ATTENDER_EMPS" datasource="#DSN#">
	SELECT
		TRAINING_CLASS_ATTENDER.EMP_ID,
		EMPLOYEES.EMPLOYEE_NAME,
		EMPLOYEES.EMPLOYEE_SURNAME,
		TRAINING_CLASS_ATTENDER.STATUS,
		EMPLOYEES.EMPLOYEE_ID
	FROM
		TRAINING_CLASS_ATTENDER,
		EMPLOYEES,
		EMPLOYEE_POSITIONS,
		DEPARTMENT,
		BRANCH,
		OUR_COMPANY C
	WHERE
		TRAINING_CLASS_ATTENDER.CLASS_ID = #attributes.CLASS_ID# AND
		EMPLOYEES.EMPLOYEE_ID = TRAINING_CLASS_ATTENDER.EMP_ID AND
		TRAINING_CLASS_ATTENDER.EMP_ID = EMPLOYEE_POSITIONS.EMPLOYEE_ID AND
		DEPARTMENT.BRANCH_ID = BRANCH.BRANCH_ID AND
		C.COMP_ID = BRANCH.COMPANY_ID AND
        EMPLOYEE_POSITIONS.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID AND
        EMPLOYEE_POSITIONS.IS_MASTER = 1 AND
        TRAINING_CLASS_ATTENDER.EMP_ID IS NOT NULL
	<!---<cfif branch_id_list gt 0>
		AND BRANCH.BRANCH_ID IN (#branch_id_list#)
	</cfif>--->
	ORDER BY
    	EMPLOYEES.EMPLOYEE_NAME,
        EMPLOYEES.EMPLOYEE_SURNAME
</cfquery>
<cfquery name="GET_CLASS_ATTENDER_PARS" datasource="#DSN#">
	SELECT
		TRAINING_CLASS_ATTENDER.PAR_ID,
		TRAINING_CLASS_ATTENDER.STATUS,
		COMPANY_PARTNER.COMPANY_PARTNER_NAME,
		COMPANY_PARTNER.COMPANY_PARTNER_SURNAME,
		COMPANY.NICKNAME,
		COMPANY.COMPANY_ID,
		COMPANY_PARTNER.PARTNER_ID
	FROM
		TRAINING_CLASS_ATTENDER,
		COMPANY_PARTNER,
		COMPANY
	WHERE
		TRAINING_CLASS_ATTENDER.CLASS_ID = #attributes.class_id# AND
		COMPANY_PARTNER.PARTNER_ID = TRAINING_CLASS_ATTENDER.PAR_ID AND
		COMPANY_PARTNER.COMPANY_ID = COMPANY.COMPANY_ID AND
		TRAINING_CLASS_ATTENDER.PAR_ID IS NOT NULL
	ORDER BY
    	COMPANY.NICKNAME,
    	COMPANY_PARTNER.COMPANY_PARTNER_NAME
</cfquery>
<cfquery name="GET_CLASS_ATTENDER_CONS" datasource="#DSN#">
	SELECT
		TRAINING_CLASS_ATTENDER.CON_ID,
		TRAINING_CLASS_ATTENDER.STATUS,
		CONSUMER.CONSUMER_NAME,
		CONSUMER.CONSUMER_SURNAME,
		CONSUMER.COMPANY,
		CONSUMER.CONSUMER_ID
	FROM
		TRAINING_CLASS_ATTENDER,
		CONSUMER
	WHERE
		TRAINING_CLASS_ATTENDER.CLASS_ID = #attributes.class_id# AND
		CONSUMER.CONSUMER_ID = TRAINING_CLASS_ATTENDER.CON_ID AND
		TRAINING_CLASS_ATTENDER.CON_ID IS NOT NULL
	ORDER BY 
    	CONSUMER.CONSUMER_NAME
</cfquery>
<cfquery name="GET_CLASS_ATTENDER_GRPS" datasource="#DSN#">
	SELECT
		TRAINING_CLASS_ATTENDER.GRP_ID,
		TRAINING_CLASS_ATTENDER.STATUS,
		USERS.GROUP_NAME
	FROM
		TRAINING_CLASS_ATTENDER,
		USERS
	WHERE
		TRAINING_CLASS_ATTENDER.CLASS_ID = #attributes.class_id# AND
		USERS.GROUP_ID = TRAINING_CLASS_ATTENDER.GRP_ID AND
		TRAINING_CLASS_ATTENDER.GRP_ID IS NOT NULL
	ORDER BY
    	USERS.GROUP_NAME
</cfquery>

<cfset all_attender_ids = "">
<cfloop query="get_class_attender_emps">
	<cfset all_attender_ids = listappend(all_attender_ids,"emp-#emp_id#")>
</cfloop>
<cfloop query="get_class_attender_pars">
	<cfset all_attender_ids = listappend(all_attender_ids,"par-#par_id#-#company_id#")>
</cfloop>
<cfloop query="get_class_attender_cons">
	<cfset all_attender_ids = listappend(all_attender_ids,"con-#con_id#")>
</cfloop>
<cfloop query="get_class_attender_grps">
	<cfset all_attender_ids = listappend(all_attender_ids,"grp-#grp_id#")>
</cfloop>
