<cfquery name="GET_QUIZ_QUESTION" datasource="#dsn#">
	DECLARE AU_CURSOR SCROLL CURSOR FOR

			SELECT 
				*
			FROM 
				QUESTION,
				QUIZ_QUESTIONS
			WHERE
				QUIZ_QUESTIONS.QUESTION_ID = QUESTION.QUESTION_ID
				AND
				QUIZ_QUESTIONS.QUIZ_ID=#attributes.QUIZ_ID#

	OPEN AU_CURSOR
	
	FETCH ABSOLUTE #attributes.QUESTION_ROW# FROM AU_CURSOR
	
	CLOSE AU_CURSOR
	DEALLOCATE AU_CURSOR
</cfquery>		

