<cfquery name="GET_QUIZS" datasource="#dsn#">
	SELECT 
		QUIZ.QUIZ_ID,
		QUIZ.QUIZ_HEAD,
		QUIZ.QUIZ_OBJECTIVE,
		QUIZ.QUIZ_PARTNERS,
		QUIZ.QUIZ_CONSUMERS,
		QUIZ.QUIZ_DEPARTMENTS,
		QUIZ.TAKE_LIMIT,
		QUIZ.QUIZ_STARTDATE,
		QUIZ.QUIZ_FINISHDATE,
		QUIZ.RECORD_EMP,
		QUIZ.RECORD_PAR,
		QUIZ.RECORD_DATE,
		QUIZ.TOTAL_TIME,
		SETUP_QUIZ_STAGE.STAGE_NAME
	FROM 
		QUIZ,
		SETUP_QUIZ_STAGE
	WHERE
		QUIZ.QUIZ_DEPARTMENTS IS NOT NULL
		AND
		QUIZ.STAGE_ID = SETUP_QUIZ_STAGE.STAGE_ID
	<cfif isDefined("attributes.TRAINING_CAT_ID") and len(attributes.TRAINING_CAT_ID)>
		AND
		QUIZ.TRAINING_CAT_ID=#attributes.TRAINING_CAT_ID#
	</cfif>
	<cfif isDefined("attributes.KEYWORD") and len(attributes.KEYWORD)>
		AND
		(
		QUIZ.QUIZ_HEAD LIKE '%#attributes.KEYWORD#%' COLLATE SQL_Latin1_General_CP1_CI_AI
		OR
		QUIZ.QUIZ_OBJECTIVE LIKE '%#attributes.KEYWORD#%' COLLATE SQL_Latin1_General_CP1_CI_AI
		)
	</cfif>
</cfquery>
