<cfquery name="GET_SALE_ADD_OPTIONS" datasource="#DSN3#">
	SELECT SALES_ADD_OPTION_ID,SALES_ADD_OPTION_NAME FROM SETUP_SALES_ADD_OPTIONS WHERE IS_INTERNET = 1 ORDER BY SALES_ADD_OPTION_ID ASC
</cfquery>
