<cfif not len(listsort(attributes.employee_ids,"numeric"))>
	<cfset attributes.employee_ids = 0>
</cfif>
<cfif not len(LISTSORT(attributes.partner_ids,"NUMERIC"))>
	<cfset attributes.partner_ids = 0> 
</cfif>
<cfif not len(LISTSORT(attributes.consumer_ids,"NUMERIC"))>
	<cfset attributes.consumer_ids = 0>
</cfif>
<cfif not len(LISTSORT(attributes.group_ids,"NUMERIC"))>
	<cfset attributes.group_ids = 0>
</cfif>

<cfquery name="get_organization_attender" datasource="#DSN#">
	SELECT
		'employee' AS TYPE,
		ORGANIZATION_ATTENDER.ORGANIZATION_ID,
		ORGANIZATION_ATTENDER.IS_SELFSERVICE SELF_SERVICE,
		ORGANIZATION_ATTENDER.EMP_ID AS K_ID,
        ORGANIZATION_ATTENDER.STATUS,
        ORGANIZATION_ATTENDER.COMMENT,
        ORGANIZATION_ATTENDER.ORGANIZATION_ATTENDER_ID,
        ORGANIZATION_ATTENDER.PARTICIPATION_RATE,
		EMPLOYEES.EMPLOYEE_NAME AS AD,
		EMPLOYEES.EMPLOYEE_SURNAME AS SOYAD,
		EMPLOYEES.EMPLOYEE_ID AS IDS,
		EMPLOYEE_POSITIONS.POSITION_NAME AS POSITION,
		DEPARTMENT.DEPARTMENT_HEAD AS DEPARTMAN,
		C.NICK_NAME AS NICK_NAME,
		BRANCH.BRANCH_NAME AS BRANCH_NAME
	FROM
		ORGANIZATION_ATTENDER INNER JOIN EMPLOYEES ON ORGANIZATION_ATTENDER.EMP_ID = EMPLOYEES.EMPLOYEE_ID 
		LEFT JOIN EMPLOYEE_POSITIONS ON EMPLOYEE_POSITIONS.EMPLOYEE_ID = ORGANIZATION_ATTENDER.EMP_ID
		LEFT JOIN DEPARTMENT ON EMPLOYEE_POSITIONS.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID
		LEFT JOIN BRANCH ON DEPARTMENT.BRANCH_ID=BRANCH.BRANCH_ID
		LEFT JOIN OUR_COMPANY C ON C.COMP_ID=BRANCH.COMPANY_ID
	WHERE
		EMP_ID IS NOT NULL
		<cfif isdefined("attributes.EX_ORGANIZATION_ID") and len(attributes.EX_ORGANIZATION_ID)>
			AND ORGANIZATION_ATTENDER.EX_ORGANIZATION_ID = #attributes.EX_ORGANIZATION_ID#
		</cfif>
		AND ORGANIZATION_ATTENDER.EMP_ID IN (<cfqueryparam cfsqltype="cf_sql_integer" list="true" value="#listsort(attributes.employee_ids,'numeric')#">)
		<!---AND EMPLOYEE_POSITIONS.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID
		 AND EMPLOYEE_POSITIONS.IS_MASTER = 1 --->
		AND ORGANIZATION_ATTENDER.EMP_ID IS NOT NULL
		<cfif isdefined("attributes.ORGANIZATION_ID") and len(attributes.ORGANIZATION_ID)>
			AND ORGANIZATION_ATTENDER.ORGANIZATION_ID=<cfqueryparam cfsqltype="cf_sql_integer" value="#attributes.ORGANIZATION_ID#">
		</cfif>
		<!--- AND BRANCH.BRANCH_ID IN (#branch_id_list#) --->
UNION
	SELECT 
		'partner' AS TYPE,
		ORGANIZATION_ATTENDER.ORGANIZATION_ID,
		ORGANIZATION_ATTENDER.IS_SELFSERVICE SELF_SERVICE,
		ORGANIZATION_ATTENDER.PAR_ID K_ID,
        ORGANIZATION_ATTENDER.STATUS,
        ORGANIZATION_ATTENDER.COMMENT,
        ORGANIZATION_ATTENDER.ORGANIZATION_ATTENDER_ID,
        ORGANIZATION_ATTENDER.PARTICIPATION_RATE,
		COMPANY_PARTNER.COMPANY_PARTNER_NAME AS AD,
		COMPANY_PARTNER.COMPANY_PARTNER_SURNAME AS SOYAD,
		COMPANY_PARTNER.PARTNER_ID AS IDS,
		COMPANY_PARTNER.TITLE AS POSITION,
		' ' AS DEPARTMAN, 	
		COMPANY.NICKNAME AS NICK_NAME,
		' ' AS BRANCH_NAME
	FROM
		ORGANIZATION_ATTENDER,
		COMPANY_PARTNER,
		COMPANY
	WHERE
		ORGANIZATION_ATTENDER.ORGANIZATION_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#attributes.ORGANIZATION_ID#">
		AND ORGANIZATION_ATTENDER.PAR_ID IN (<cfqueryparam cfsqltype="cf_sql_integer" list="true" value="#listsort(attributes.partner_ids,'numeric')#">)
		AND COMPANY_PARTNER.PARTNER_ID = ORGANIZATION_ATTENDER.PAR_ID
		AND COMPANY_PARTNER.COMPANY_ID = COMPANY.COMPANY_ID
UNION
	SELECT
		'consumer' AS TYPE,
		ORGANIZATION_ATTENDER.ORGANIZATION_ID,
		ORGANIZATION_ATTENDER.IS_SELFSERVICE SELF_SERVICE,
		ORGANIZATION_ATTENDER.CON_ID AS K_ID,
        ORGANIZATION_ATTENDER.STATUS,
        ORGANIZATION_ATTENDER.COMMENT,
        ORGANIZATION_ATTENDER.ORGANIZATION_ATTENDER_ID,
        ORGANIZATION_ATTENDER.PARTICIPATION_RATE,
		CONSUMER.CONSUMER_NAME AS AD,
		CONSUMER.CONSUMER_SURNAME AS SOYAD,
		CONSUMER.CONSUMER_ID AS IDS,
		CONSUMER.TITLE AS POSITION,
		' ' AS DEPARTMAN,
		CONSUMER.COMPANY AS NICK_NAME,
		' ' AS BRANCH_NAME
	FROM
		ORGANIZATION_ATTENDER,
		CONSUMER
	WHERE
		ORGANIZATION_ATTENDER.ORGANIZATION_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#attributes.ORGANIZATION_ID#">
		AND ORGANIZATION_ATTENDER.CON_ID IN (<cfqueryparam cfsqltype="cf_sql_integer" list="true" value="#listsort(attributes.consumer_ids,'numeric')#">)
		AND CONSUMER.CONSUMER_ID = ORGANIZATION_ATTENDER.CON_ID
		AND ORGANIZATION_ATTENDER.CON_ID IS NOT NULL
UNION 
	SELECT
			'group' AS TYPE,
			ORGANIZATION_ATTENDER.ORGANIZATION_ID,
			ORGANIZATION_ATTENDER.IS_SELFSERVICE SELF_SERVICE,
			ORGANIZATION_ATTENDER.GRP_ID K_ID,
            ORGANIZATION_ATTENDER.STATUS,
            ORGANIZATION_ATTENDER.COMMENT,
            ORGANIZATION_ATTENDER.ORGANIZATION_ATTENDER_ID,
            ORGANIZATION_ATTENDER.PARTICIPATION_RATE,
			USERS.GROUP_NAME AS AD,
			' ' AS SOYAD,
			USERS.GROUP_ID AS IDS,
			' ' AS POSITION,
			' ' AS DEPARTMAN,
			' ' AS NICK_NAME,
			' ' AS BRANCH_NAME
		FROM
			ORGANIZATION_ATTENDER,
			USERS
		WHERE
			ORGANIZATION_ATTENDER.ORGANIZATION_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#attributes.ORGANIZATION_ID#">
			AND ORGANIZATION_ATTENDER.GRP_ID IN (<cfqueryparam cfsqltype="cf_sql_integer" list="true" value="#listsort(attributes.group_ids,'numeric')#">)
			AND USERS.GROUP_ID = ORGANIZATION_ATTENDER.GRP_ID
			AND ORGANIZATION_ATTENDER.GRP_ID IS NOT NULL
		ORDER BY AD,SOYAD
</cfquery>
