<cfquery name="GET_OUTOF_TARGET_MASS" datasource="#dsn3#">
	SELECT
		*
	FROM
		CAMPAIGN_TARGET_PEOPLE
	WHERE
		CAMP_ID = #attributes.CAMP_ID#
	AND
	(
		TMARKET_ID IS NULL
		OR TMARKET_ID=0
	)
</cfquery>
<cfset CONSUMER_LIST = listsort(ValueList(GET_OUTOF_TARGET_MASS.CON_ID,','),'numeric','ASC')>
<cfset PARTNER_LIST = listsort(ValueList(GET_OUTOF_TARGET_MASS.PAR_ID,','),'numeric','ASC')>
<cfif ListLen(listsort(ValueList(GET_OUTOF_TARGET_MASS.CON_ID),'numeric','ASC'))>
	<cfquery name="GET_OUTOF_TARGET_USERS" datasource="#DSN#">
		SELECT
			CONSUMER_ID,
			CONSUMER_CAT_ID,
			CONSUMER_NAME,
			CONSUMER_SURNAME,
			CONSUMER_USERNAME,
			CONSUMER_EMAIL AS USER_EMAIL,
			CONSUMER_FAXCODE,
			CONSUMER_FAX,
			CONSUMER_WORKTELCODE,
			CONSUMER_WORKTEL,
			CONSUMER_TEL_EXT,
			CONSUMER_HOMETELCODE,
			CONSUMER_HOMETEL,
			WORKPOSTCODE,
			WORK_COUNTY_ID,
			WORK_CITY_ID,
			MOBIL_CODE,
			MOBILTEL,
			LTRIM(RTRIM(MOBIL_CODE+MOBILTEL)) AS U_MOBILEPHONE,
			COMPANY,
			WORKADDRESS,
			TITLE,
			MISSION,
			DEPARTMENT
		FROM
			CONSUMER
		WHERE
			CONSUMER_ID IN (#listsort(ValueList(GET_OUTOF_TARGET_MASS.CON_ID),'numeric','ASC')#)
	</cfquery>
</cfif>
<cfif ListLen(listsort(ValueList(GET_OUTOF_TARGET_MASS.PAR_ID),'numeric','ASC'))>
	<cfquery name="GET_OUTOF_TARGET_PARTNERS" datasource="#dsn#">
		SELECT
			COMPANY_PARTNER.PARTNER_ID,
			COMPANY_PARTNER.COMPANY_PARTNER_NAME,
			COMPANY_PARTNER.COMPANY_PARTNER_EMAIL,
			COMPANY_PARTNER.COMPANY_PARTNER_SURNAME,
			COMPANY_PARTNER.COMPANY_PARTNER_ADDRESS,
			COMPANY_PARTNER.COMPANY_PARTNER_POSTCODE,
			COMPANY_PARTNER.COUNTRY,
			COMPANY_PARTNER.COUNTY,
			COMPANY_PARTNER.CITY,
			COMPANY_PARTNER.MISSION,
			COMPANY_PARTNER.DEPARTMENT,
			COMPANY.COMPANY_ID,
			COMPANY.NICKNAME,
			COMPANY.FULLNAME,
			COMPANY.COMPANYCAT_ID,
			COMPANY_PARTNER.COMPANY_PARTNER_TEL_EXT,
			COMPANY_PARTNER.COMPANY_PARTNER_FAX,
			COMPANY_PARTNER.MOBIL_CODE,
			COMPANY_PARTNER.MOBILTEL,
			LTRIM(RTRIM(COMPANY_PARTNER.MOBIL_CODE+COMPANY_PARTNER.MOBILTEL)) AS CP_MOBILEPHONE
		FROM
			COMPANY,
			COMPANY_PARTNER
		WHERE
			COMPANY.COMPANY_ID = COMPANY_PARTNER.COMPANY_ID AND
			COMPANY_PARTNER.PARTNER_ID IN (#listsort(ValueList(GET_OUTOF_TARGET_MASS.PAR_ID),'numeric','ASC')#) AND
			COMPANY_PARTNER.COMPANY_PARTNER_STATUS = 1 AND
			COMPANY.COMPANY_STATUS = 1
	</cfquery>
</cfif>
