<cfquery name="GET_PARTNER_POSITIONS" datasource="#dsn#">
	SELECT 
		PARTNER_POSITION_ID,
		#dsn#.Get_Dynamic_Language(PARTNER_POSITION_ID,'#session.ep.language#','SETUP_PARTNER_POSITION','PARTNER_POSITION',NULL,NULL,PARTNER_POSITION) AS PARTNER_POSITION
	FROM 
		SETUP_PARTNER_POSITION
	WHERE
		PARTNER_POSITION_ID IS NOT NULL
	ORDER BY
		PARTNER_POSITION
</cfquery>
