<cfquery name="GET_PARTNER_DEPARTMENTS" datasource="#dsn#">
	SELECT
		PARTNER_DEPARTMENT_ID,
		#dsn#.Get_Dynamic_Language(PARTNER_DEPARTMENT_ID,'#session.ep.language#','SETUP_PARTNER_DEPARTMENT','PARTNER_DEPARTMENT',NULL,NULL,PARTNER_DEPARTMENT) AS PARTNER_DEPARTMENT,
		DETAIL,
		RECORD_EMP,
		RECORD_IP,
		RECORD_DATE,
		UPDATE_EMP,
		UPDATE_IP,
		UPDATE_DATE
	FROM 
		SETUP_PARTNER_DEPARTMENT
	WHERE
		PARTNER_DEPARTMENT_ID IS NOT NULL
	ORDER BY
		PARTNER_DEPARTMENT
</cfquery>
