<cfcomponent>
	<cffunction name="get_prod_party_fnc" returntype="query">
		<cfquery name="CFC_GET_PRODUCTION_PARTY" datasource="#this.DSN3#">
					select
						TEXTILE_SAMPLE_REQUEST.*,
						ORDERS.*,
						TEXTILE_PRODUCTION_OPERATION_MAIN.*,
						TEXTILE_PRODUCTION_OPERATION.*,
						PRODUCT_UNIT.*,
						PRODUCT.*,
						0 IS_STAGE,
						OPERATION_TYPES.OPERATION_TYPE
					from 
						TEXTILE_SAMPLE_REQUEST
						JOIN TEXTILE_PRODUCTION_OPERATION_MAIN ON TEXTILE_PRODUCTION_OPERATION_MAIN.REQUEST_ID=TEXTILE_SAMPLE_REQUEST.REQ_ID
						JOIN TEXTILE_PRODUCTION_OPERATION ON TEXTILE_PRODUCTION_OPERATION_MAIN.MAIN_OPERATION_ID=TEXTILE_PRODUCTION_OPERATION.MAIN_OPERATION_ID
						JOIN OPERATION_TYPES ON OPERATION_TYPES.OPERATION_TYPE_ID=TEXTILE_PRODUCTION_OPERATION.OPERATION_TYPE_ID
						JOIN ORDERS ON ORDERS.ORDER_ID=TEXTILE_PRODUCTION_OPERATION_MAIN.ORDER_ID
						JOIN PRODUCT ON PRODUCT.PRODUCT_ID=TEXTILE_SAMPLE_REQUEST.PRODUCT_ID
						JOIN PRODUCT_UNIT ON PRODUCT.PRODUCT_ID=PRODUCT_UNIT.PRODUCT_ID
					
		</cfquery>
		<cfreturn CFC_GET_PRODUCTION_PARTY>
	</cffunction>
	<cffunction name="get_plan_row_detail" returntype="query">
			
			<cfquery name="get_size_detail" datasource="#dsn3#">
					SELECT 
								ISNULL((SELECT SPECT_MAIN_ID FROM SPECTS WHERE SPECT_VAR_ID =ORR.SPECT_VAR_ID),0) AS SPECT_MAIN_ID,
								ORR.ORDER_ROW_ID,
								ORR.QUANTITY,
								ORR.UNIT,
								ORR.ORDER_ROW_CURRENCY,
								ORR.SPECT_VAR_ID,
								S.PROPERTY, 
								CASE WHEN S.STOCK_CODE = '' THEN '_' ELSE ISNULL(S.STOCK_CODE,'_') END AS STOCK_CODE,
								ORR.UNIT2,
								ORR.AMOUNT2,
								ORR.DELIVER_DATE AS ROW_DELIVER_DATE,
								S.STOCK_ID,
								S.PRODUCT_NAME,	
								S.STOCK_CODE_2,			
								O.ORDER_ID,
								O.ORDER_NUMBER,
								O.ORDER_HEAD,
								O.OTHER_MONEY,
								O.TAX,
								O.GROSSTOTAL, 
								O.ORDER_DATE, 
								O.DELIVERDATE, 
								O.RECORD_EMP,
								O.COMPANY_ID,
								S.PRODUCT_ID,
								O.CONSUMER_ID,
								O.PROJECT_ID,
								ORR.WRK_ROW_ID,
								ORR.RESERVE_TYPE,
								CAST(O.ORDER_DETAIL AS NVARCHAR(250)) ORDER_DETAIL,
									RENK.PROPERTY_DETAIL AS RENK_,
								BEDEN.PROPERTY_DETAIL AS BEDEN_,
								BOY.PROPERTY_DETAIL AS BOY_
							FROM 
								ORDERS O,
								ORDER_ROW ORR,
								PRODUCT_UNIT PU,
								STOCKS S
								OUTER APPLY
						(
							SELECT 
								PRP.PROPERTY_ID,PRP.PROPERTY,PRP.PROPERTY_SIZE,PRP.PROPERTY_CODE,PRP.IS_ACTIVE,
								PPD.PROPERTY_DETAIL,PPD.PROPERTY_DETAIL_ID ,PPD.PRPT_ID
							FROM
								#dsn1#.PRODUCT_PROPERTY_DETAIL PPD,
								#dsn1#.PRODUCT_PROPERTY PRP,
								STOCKS_PROPERTY SP
							WHERE
								PRP.PROPERTY_ID = PPD.PRPT_ID AND
								SP.PROPERTY_DETAIL_ID = PPD.PROPERTY_DETAIL_ID AND 
								PRP.PROPERTY_COLOR = 1 AND 
								SP.STOCK_ID = S.STOCK_ID 
						) AS RENK
						OUTER APPLY
						(
							SELECT 
								PRP.PROPERTY_ID,PRP.PROPERTY,PRP.PROPERTY_SIZE,PRP.PROPERTY_CODE,PRP.IS_ACTIVE,
								PPD.PROPERTY_DETAIL,PPD.PROPERTY_DETAIL_ID ,PPD.PRPT_ID
							FROM
								#dsn1#.PRODUCT_PROPERTY_DETAIL PPD,
								#dsn1#.PRODUCT_PROPERTY PRP,
								STOCKS_PROPERTY SP
							WHERE
								PRP.PROPERTY_ID = PPD.PRPT_ID AND
								SP.PROPERTY_DETAIL_ID = PPD.PROPERTY_DETAIL_ID AND 
								PRP.PROPERTY_SIZE = 1 AND 
								SP.STOCK_ID = S.STOCK_ID 
						) AS BEDEN
						OUTER APPLY
						(
							SELECT 
								PRP.PROPERTY_ID,PRP.PROPERTY,PRP.PROPERTY_SIZE,PRP.PROPERTY_CODE,PRP.IS_ACTIVE,
								PPD.PROPERTY_DETAIL,PPD.PROPERTY_DETAIL_ID ,PPD.PRPT_ID
							FROM
								#dsn1#.PRODUCT_PROPERTY_DETAIL PPD,
								#dsn1#.PRODUCT_PROPERTY PRP,
								STOCKS_PROPERTY SP
							WHERE
								PRP.PROPERTY_ID = PPD.PRPT_ID AND
								SP.PROPERTY_DETAIL_ID = PPD.PROPERTY_DETAIL_ID AND 
								PRP.PROPERTY_LEN = 1 AND 
								SP.STOCK_ID = S.STOCK_ID 
						) AS Boy
							WHERE
								( (O.PURCHASE_SALES = 1 AND O.ORDER_ZONE = 0) OR (O.PURCHASE_SALES = 0 AND O.ORDER_ZONE = 1) ) AND  
								PU.PRODUCT_ID = S.PRODUCT_ID AND
								ORR.STOCK_ID = S.STOCK_ID AND
								ORR.PRODUCT_ID = S.PRODUCT_ID AND
								S.IS_PRODUCTION = 1 AND
								ORR.ORDER_ID = O.ORDER_ID AND
								O.ORDER_STATUS = 1
								AND	ORR.ORDER_ROW_CURRENCY = -5
								AND O.ORDER_ID=#attributes.order_id#
							    AND ORR.PRODUCT_ID=#attributes.pid#
				</cfquery>
				<cfreturn get_size_detail>	
	</cffunction>
</cfcomponent>
