<cfquery name="GET_POSITION_DETAIL" datasource="#dsn#">
	SELECT
        EPH.RECORD_DATE,
        EPH.RECORD_EMP,
		DEPARTMENT.DEPARTMENT_ID,
		DEPARTMENT.DEPARTMENT_HEAD,
        DEPARTMENT.BRANCH_ID,
        DEPARTMENT.HIERARCHY_DEP_ID,
		BRANCH.BRANCH_NAME,
		EP.*,
		#dsn#.Get_Dynamic_Language(EP.POSITION_ID,'#session.ep.language#','EMPLOYEE_POSITIONS','POSITION_NAME',NULL,NULL,EP.POSITION_NAME) AS POSITION_NAME_,
		EP.EMPLOYEE_NAME + ' ' + EP.EMPLOYEE_SURNAME AS EMP_NAME_SURNAME
	FROM
		EMPLOYEE_POSITIONS EP,
		DEPARTMENT,
		BRANCH
        LEFT JOIN EMPLOYEE_POSITIONS_HISTORY EPH ON EPH.POSITION_ID=#attributes.POSITION_ID# 
        AND EPH.HISTORY_ID = (SELECT TOP 1 EPH2.HISTORY_ID FROM EMPLOYEE_POSITIONS_HISTORY EPH2 WHERE EPH2.POSITION_ID = #attributes.POSITION_ID# ORDER BY EPH2.HISTORY_ID ASC)
	WHERE
		
        EP.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID AND 
		EP.POSITION_ID = #attributes.POSITION_ID# AND
		DEPARTMENT.BRANCH_ID = BRANCH.BRANCH_ID
		<cfif session.ep.ehesap neq 1>
		AND	DEPARTMENT.BRANCH_ID IN
			(
                SELECT
                    BRANCH_ID
                FROM
                    EMPLOYEE_POSITION_BRANCHES
                WHERE
                    POSITION_CODE = #SESSION.EP.POSITION_CODE#
			)
		</cfif>
</cfquery>
