<cfquery name="GET_TOTAL_PERF_QUIZS" datasource="#dsn#">
	SELECT 
        SURVEY_MAIN.SURVEY_MAIN_ID,
        SURVEY_MAIN.SURVEY_MAIN_HEAD,
        SURVEY_MAIN.SURVEY_MAIN_DETAILS,
        SURVEY_MAIN_RESULT.SURVEY_MAIN_RESULT_ID,
        SURVEY_MAIN_RESULT.IS_CLOSED,
        SURVEY_MAIN_RESULT.START_DATE,
        SURVEY_MAIN_RESULT.ACTION_ID,
        SURVEY_MAIN_RESULT.SCORE_RESULT,
        SURVEY_MAIN_RESULT.FINISH_DATE,
        SURVEY_MAIN_RESULT.PROCESS_ROW_ID AS SMR_PRI,
        SURVEY_MAIN.TYPE,
        SURVEY_MAIN.RECORD_DATE,
        SURVEY_MAIN.FINISH_DATE,
        SURVEY_MAIN.PROCESS_ROW_ID,
        E.EMPLOYEE_NAME+' '+E.EMPLOYEE_SURNAME AS CALISAN,
        ETT.TEST_TIME_TYPE_NAME,
        ET.RECORD_DATE AS ATAMA_TARIHI,
        ET.TEST_TIME_DAY,
        EI.START_DATE AS STARTDATE,
        ET.TEST_TIME_DETAIL,
        PTR.STAGE,
        E.EMPLOYEE_NO,
        D.DEPARTMENT_HEAD,
        ST.TITLE
        ,EPER.PER_ID
		,EPER.START_DATE 
		,EPER.FINISH_DATE
		,EPER.MANAGER_1_POS
		,EPER.MANAGER_2_POS
		,EPER.VALID_1 
		,EPER.VALID_2
		,EPER.VALID_1_DATE 
		,EPER.VALID_2_DATE 
		,EPER.VALID_1_EMP 
		,EPER.VALID_2_EMP 
		,EPER.POWERFUL_ASPECTS
		,EPER.TRAIN_NEED_ASPECTS
		,EPER.MANAGER_2_EVALUATION
		,EPER.DEVELOPMENT_ID 
		,EPER.POSSIBLE_PROMOTE_POS 
		,EPER.POSSIBLE_PROMOTE_TIME
		,EPER.MAX_POSSIBLE_PROMOTE_POS
		,EPER.MAX_POSSIBLE_PROMOTE_TIME
		,EPER.ROTATION_POS
		,EPER.LUCK_TRAIN_SUBJECT_1
		,EPER.LUCK_TRAIN_SUBJECT_2
		,EPER.LUCK_TRAIN_SUBJECT_3
		,EPER.LUCK_TRAIN_SUBJECT_4
		,EPER.LUCK_TRAIN_SUBJECT_5
		,EPER.LUCK_TRAIN_SUBJECT_6
		,EPER.LUCK_TRAIN_SUBJECT_7
		,EPER.LUCK_TRAIN_SUBJECT_8
		,EPER.EMPLOYEE_OPINION
		,EPER.EMPLOYEE_OPINION_ID
		,EPER.PERFORM_POINT_ID
		,EPER.PERFORM_POINT
		,EPER.USER_POINT
		,EPER.USER_POINT_OVER_5
		,EPER.EMPLOYEE_OPINION_DATE
		,EPER.EMPLOYEE_OPINION_EMP_ID
		,EPER.RECORD_KEY
		,EPER.RECORD_DATE
        ,ET.QUIZ_ID
    FROM 
        SURVEY_MAIN,
        SURVEY_MAIN_RESULT
            LEFT JOIN EMPLOYEES_TEST_TIME ET ON  SURVEY_MAIN_RESULT.ACTION_ID = ET.EMPLOYEE_ID  AND SURVEY_MAIN_RESULT.SURVEY_MAIN_ID = ET.QUIZ_ID
            LEFT JOIN EMPLOYEES_TEST_TIME_TYPE ETT ON  ET.TEST_TIME_TYPE = ETT.EMPLOYEES_TEST_TIME_TYPE_ID
            LEFT JOIN EMPLOYEES E ON SURVEY_MAIN_RESULT.ACTION_ID = E.EMPLOYEE_ID
            LEFT JOIN EMPLOYEE_POSITIONS EP ON E.EMPLOYEE_ID = EP.EMPLOYEE_ID
            LEFT JOIN SETUP_TITLE ST ON ST.TITLE_ID = EP.TITLE_ID
            LEFT JOIN DEPARTMENT D ON EP.DEPARTMENT_ID = D.DEPARTMENT_ID
            LEFT JOIN PROCESS_TYPE_ROWS PTR ON PTR.PROCESS_ROW_ID = ET.TEST_TIME_STAGE
            LEFT JOIN EMPLOYEES_IN_OUT EI ON  EI.EMPLOYEE_ID = ET.EMPLOYEE_ID AND EI.START_DATE = (SELECT TOP 1 START_DATE FROM EMPLOYEES_IN_OUT WHERE EMPLOYEE_ID = SURVEY_MAIN_RESULT.ACTION_ID ORDER BY IN_OUT_ID DESC)
            LEFT JOIN EMPLOYEE_PERFORMANCE EPER ON EPER.EMP_ID = #attributes.employee_id#
    WHERE 
        SURVEY_MAIN_RESULT.SURVEY_MAIN_ID = SURVEY_MAIN.SURVEY_MAIN_ID AND
        TYPE IN (6,8,10) <!--- DENEME SÜRESİ, PERFORMANS , İŞTEN ÇIKIŞ  --->
        <cfif len(attributes.employee_id)>
            AND SURVEY_MAIN_RESULT.ACTION_ID = #attributes.employee_id#
        </cfif>
</cfquery>