<cfquery name="GET_POS_LAST_EMP" DATASOURCE="#DSN#" MAXROWS="1">
	SELECT
		EMPLOYEE_ID,
		EMPLOYEE_NAME,
		EMPLOYEE_SURNAME,
		START_DATE,
		FINISH_DATE
	FROM
		EMPLOYEE_POSITIONS
	WHERE
		POSITION_CODE = #attributes.POSITION_CODE#
		AND
		POSITION_STATUS = 0
	ORDER BY
		POSITION_ID DESC
</cfquery>
