<cfquery name="GET_NOTICE_APPS" datasource="#dsn#">
	SELECT
		APP_POS_ID,
		EMPAPP_ID,
		POSITION_ID,
		POSITION_CAT_ID,
		APP_DATE,
		COMPANY_ID,
		OUR_COMPANY_ID,
		BRANCH_ID,
		DEPARTMENT_ID,
		SALARY_WANTED,
		SALARY_WANTED_MONEY,
		STARTDATE_IF_ACCEPTED,
		APP_POS_STATUS,
		DETAIL
	FROM
		EMPLOYEES_APP_POS
	WHERE
		NOTICE_ID = #attributes.NOTICE_ID#
</cfquery>
