<cfquery name="GET_DEPARTMENT_USERS_COUNT" datasource="#dsn#">
	SELECT 
		COUNT(EMPLOYEES_IN_OUT.EMPLOYEE_ID) AS TOTAL
	FROM 
		EMPLOYEE_POSITIONS,
		DEPARTMENT,
		EMPLOYEES_IN_OUT
	WHERE 
		DEPARTMENT.IS_STORE <> 1 AND
		DEPARTMENT.DEPARTMENT_ID = #attributes.DEPARTMENT_ID#
		AND
		EMPLOYEE_POSITIONS.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID
		AND
		EMPLOYEES_IN_OUT.EMPLOYEE_ID = EMPLOYEE_POSITIONS.EMPLOYEE_ID
		AND
		(
			EMPLOYEES_IN_OUT.FINISH_DATE IS NULL
			OR
			(
			EMPLOYEES_IN_OUT.FINISH_DATE IS NOT NULL
			AND
			EMPLOYEES_IN_OUT.FINISH_DATE > #NOW()#
			)
		)
</cfquery>
