<cfquery name="GET_POS_HISTORY" datasource="#dsn#">
	SELECT
		EPH.*,
		D.DEPARTMENT_HEAD,
		B.BRANCH_NAME,
		OC.NICK_NAME,
        FR.REASON,
        UG.USER_GROUP_NAME,
        E.EMPLOYEE_NAME + ' ' + E.EMPLOYEE_SURNAME AS VALID_MEMBER_NAME,
        SPC.POSITION_CAT,
        ST.TITLE,
        (SELECT EMPLOYEE_NAME+' '+EMPLOYEE_SURNAME FROM EMPLOYEES E WHERE E.EMPLOYEE_ID = EPH.RECORD_EMP) AS RECORD_NAME
	FROM
		EMPLOYEE_POSITIONS_HISTORY EPH
		LEFT JOIN SETUP_EMPLOYEE_FIRE_REASONS FR ON FR.REASON_ID = EPH.IN_COMPANY_REASON_ID
		INNER JOIN DEPARTMENT D ON EPH.DEPARTMENT_ID = D.DEPARTMENT_ID
		INNER JOIN BRANCH B ON D.BRANCH_ID = B.BRANCH_ID
		INNER JOIN OUR_COMPANY OC ON B.COMPANY_ID = OC.COMP_ID
		LEFT JOIN USER_GROUP UG ON UG.USER_GROUP_ID = EPH.USER_GROUP_ID
		LEFT JOIN EMPLOYEES E ON E.EMPLOYEE_ID = EPH.RECORD_EMP
		LEFT JOIN SETUP_POSITION_CAT SPC ON SPC.POSITION_CAT_ID = EPH.POSITION_CAT_ID
		LEFT JOIN SETUP_TITLE ST ON ST.TITLE_ID = EPH.TITLE_ID
	WHERE
		EPH.POSITION_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#attributes.position_id#">
	ORDER BY 
	    EPH.VALID_DATE DESC
</cfquery>
