<cfquery name="GET_POSITION" datasource="#dsn#">
	SELECT
		DEPARTMENT.DEPARTMENT_HEAD,
		EMPLOYEE_POSITIONS.DEPARTMENT_ID,
		EMPLOYEE_POSITIONS.POSITION_ID,
		EMPLOYEE_POSITIONS.POSITION_CODE,
		(SELECT POSITION_CAT FROM SETUP_POSITION_CAT WHERE POSITION_CAT_ID = EMPLOYEE_POSITIONS.POSITION_CAT_ID) POSITION_NAME,
		#dsn#.Get_Dynamic_Language(EMPLOYEE_POSITIONS.POSITION_ID,'#session.ep.language#','EMPLOYEE_POSITIONS','POSITION_NAME',NULL,NULL,EMPLOYEE_POSITIONS.POSITION_NAME) AS POSITION_NAME_,
		EMPLOYEE_POSITIONS.EMPLOYEE_ID,
		EMPLOYEE_POSITIONS.POSITION_CAT_ID,
		EMPLOYEE_POSITIONS.USER_GROUP_ID,
		EMPLOYEE_POSITIONS.UPPER_POSITION_CODE,
		EMPLOYEE_POSITIONS.UPPER_POSITION_CODE2,
		EMPLOYEES.EMPLOYEE_NAME,
		EMPLOYEES.EMPLOYEE_SURNAME,
		EMPLOYEES.EMPLOYEE_NO,
		EMPLOYEES.EMPLOYEE_EMAIL,
		SETUP_POSITION_CAT.POSITION_CAT,
		BRANCH.BRANCH_NAME,
		BRANCH.SSK_M,
		BRANCH.SSK_JOB,
		BRANCH.SSK_BRANCH,
		BRANCH.SSK_BRANCH_OLD,
		D2.DEPARTMENT_HEAD AS UPPER_DEPARTMENT_HEAD
	FROM
		EMPLOYEE_POSITIONS,
		EMPLOYEES,
		SETUP_POSITION_CAT,
		BRANCH,
		DEPARTMENT
		LEFT JOIN DEPARTMENT as D2 ON DEPARTMENT.HIERARCHY_DEP_ID  = CONCAT(D2.HIERARCHY_DEP_ID,'.',DEPARTMENT.DEPARTMENT_ID)
	WHERE
		SETUP_POSITION_CAT.POSITION_CAT_ID = EMPLOYEE_POSITIONS.POSITION_CAT_ID
		AND EMPLOYEES.EMPLOYEE_ID = EMPLOYEE_POSITIONS.EMPLOYEE_ID
		AND EMPLOYEE_POSITIONS.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID
		AND EMPLOYEE_POSITIONS.POSITION_STATUS = 1
	<cfif isDefined("attributes.POSITION_CODE") and len(attributes.POSITION_CODE)>
		AND EMPLOYEE_POSITIONS.POSITION_CODE = #attributes.POSITION_CODE#
	</cfif>
	<cfif isDefined("attributes.EMPLOYEE_ID") and len(attributes.EMPLOYEE_ID)>
		AND EMPLOYEE_POSITIONS.EMPLOYEE_ID = #attributes.EMPLOYEE_ID#
	</cfif>
		AND EMPLOYEE_POSITIONS.IS_MASTER = 1
		AND DEPARTMENT.BRANCH_ID = BRANCH.BRANCH_ID
</cfquery>
