<cfquery name="GET_EMP_CODES" datasource="#dsn#">
	SELECT 
		DEPARTMENT.BRANCH_ID, 
		DEPARTMENT.ADMIN1_POSITION_CODE AS DEPT_ADMIN1_POSITION_CODE, 
		BRANCH.ADMIN1_POSITION_CODE AS BRANCH_ADMIN1_POSITION_CODE,
		EMPLOYEE_POSITIONS.POSITION_NAME,
		EMPLOYEE_POSITIONS.POSITION_CODE
	FROM 
		EMPLOYEE_POSITIONS, DEPARTMENT, BRANCH
	WHERE
		EMPLOYEE_POSITIONS.EMPLOYEE_ID = #EMPLOYEE_ID# AND
		EMPLOYEE_POSITIONS.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID AND
		DEPARTMENT.BRANCH_ID = BRANCH.BRANCH_ID
</cfquery>


<cfif IsNumeric(GET_EMP_CODES.DEPT_ADMIN1_POSITION_CODE)>
	<cfquery name="GET_EMP_DEPT_CHIEF" datasource="#dsn#">
		SELECT 
			EMPLOYEE_ID, POSITION_CODE, EMPLOYEE_NAME, EMPLOYEE_SURNAME
		FROM 
			EMPLOYEE_POSITIONS
		WHERE
			POSITION_CODE = #GET_EMP_CODES.DEPT_ADMIN1_POSITION_CODE# 
	</cfquery>
</cfif>

<cfif IsNumeric(GET_EMP_CODES.BRANCH_ADMIN1_POSITION_CODE)>
	<cfquery name="GET_EMP_BRANCH_CHIEF" datasource="#dsn#">
		SELECT 
			EMPLOYEE_ID, POSITION_CODE, EMPLOYEE_NAME, EMPLOYEE_SURNAME
		FROM 
			EMPLOYEE_POSITIONS
		WHERE
			POSITION_CODE = #GET_EMP_CODES.BRANCH_ADMIN1_POSITION_CODE# 
	</cfquery>
</cfif>
	 
