<cfquery name="get_dep" datasource="#DSN#">
	SELECT
		D.DEPARTMENT_HEAD,
		EMPLOYEE_NAME,
		EMPLOYEE_SURNAME,
		EP.POSITION_NAME,
		D.DEPARTMENT_ID,
		B.BRANCH_ID
	FROM
		EMPLOYEE_POSITIONS EP,
		DEPARTMENT D,
		BRANCH B
	WHERE
		D.DEPARTMENT_ID=EP.DEPARTMENT_ID
        AND B.BRANCH_ID=D.BRANCH_ID
		AND
		EP.EMPLOYEE_ID=#attributes.EMPLOYEE_ID#
</cfquery>
