<cfquery name="get_app_history" datasource="#dsn#">
	SELECT
		APP_STATUS,
		NAME,
		SURNAME,
		STEP_NAME,
		STARTED,
		EMPLOYEES_APP_HISTORY.RECORD_DATE,
		EMPLOYEE_NAME,
		EMPLOYEE_SURNAME
	FROM
		EMPLOYEES_APP_HISTORY,
		EMPLOYEES
	WHERE
		EMPLOYEES_APP_HISTORY.EMPAPP_ID = #attributes.EMPAPP_ID# AND
		EMPLOYEES.EMPLOYEE_ID = EMPLOYEES_APP_HISTORY.RECORD_EMP
	ORDER BY
		EMPLOYEES_APP_HISTORY.RECORD_DATE DESC
</cfquery>
