<cfquery name="GET_EMP_QUIZ_ANSWERS" datasource="#dsn#">
	SELECT 
		EMPLOYEE_QUIZ_RESULTS_DETAILS.*,
		EMPLOYEE_QUIZ_RESULTS.USER_POINT
	FROM 
		EMPLOYEE_QUIZ_RESULTS_DETAILS,
		EMPLOYEE_QUIZ_RESULTS
	WHERE
		EMPLOYEE_QUIZ_RESULTS_DETAILS.RESULT_ID = EMPLOYEE_QUIZ_RESULTS.RESULT_ID
		AND EMPLOYEE_QUIZ_RESULTS_DETAILS.RESULT_ID IN ( #GET_APP_PERF_DETAIL.RESULT_ID# )
</cfquery>


