<cfquery name="GET_EMP_DET" datasource="#dsn#">
	SELECT
		EMPLOYEES.EMPLOYEE_NAME,
		EMPLOYEES.EMPLOYEE_SURNAME,
		EMPLOYEE_POSITIONS.ON_MALIYET,
		EMPLOYEE_POSITIONS.POSITION_STATUS,
		EMPLOYEE_POSITIONS.POSITION_NAME,
		EMPLOYEE_POSITIONS.VALID_MEMBER
	FROM
		EMPLOYEES,
		EMPLOYEE_POSITIONS
	WHERE
		EMPLOYEES.EMPLOYEE_ID=#attributes.ID#
	AND 
		EMPLOYEE_POSITIONS.EMPLOYEE_ID=#attributes.ID#
	AND
		EMPLOYEE_POSITIONS.POSITION_STATUS=1
</cfquery>
