<cfquery name="GET_HR_DETAIL" datasource="#DSN#">
	SELECT 
		EA.*,
		ED.*,
		E.EMPLOYEE_NAME,
		E.EMPLOYEE_SURNAME,
		E.RECORD_EMP,
		E.UPDATE_EMP,
		E.RECORD_DATE,
		E.UPDATE_DATE
	FROM 
		EMPLOYEES_DETAIL ED,
		EMPLOYEES E
			INNER JOIN EMPLOYEES_APP EA ON EA.EMPLOYEE_ID = E.EMPLOYEE_ID
	WHERE 
		ED.EMPLOYEE_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#attributes.EMPLOYEE_ID#">
		AND	EA.EMPLOYEE_ID = ED.EMPLOYEE_ID
		AND E.EMPLOYEE_ID = ED.EMPLOYEE_ID
</cfquery>
