<!---  20200420 Fatura history --->
<cfquery name="GET_INVOICE" datasource="#DSN2#">
	SELECT * FROM INVOICE WHERE INVOICE_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#attributes.invoice_id#">
</cfquery>
<cfquery name="GET_INVOICE_ROW" datasource="#DSN2#">
	SELECT * FROM INVOICE_ROW WHERE INVOICE_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#attributes.invoice_id#">
</cfquery>
<cf_date tarih = 'invoice'>
<cf_date tarih = 'ship_date'>
<cf_date tarih = 'due_date'>
<cf_date tarih = 'print_date'>
<cf_date tarih = 'process_date'>
<cf_date tarih = 'update_date'>
<cf_date tarih = 'record_date'>
<cflock name="#CREATEUUID()#" timeout="20">
    <cftransaction>
        <cfloop query="get_invoice">
            <cfquery name="ADD_INVOICE_HISTORY" datasource="#DSN2#" result="MAX_ID">
                INSERT INTO 
                    INVOICE_HISTORY
                (
                    INVOICE_ID,
                    INVOICE_MULTI_ID,
                    WRK_ID,
                    PURCHASE_SALES,
                    INVOICE_CAT,
                    INVOICE_DATE,
                    SHIP_DATE,
                    SERIAL_NUMBER,
                    SERIAL_NO,
                    INVOICE_NUMBER,
                    COMPANY_ID,
                    PARTNER_ID,
                    CONSUMER_ID,
                    EMPLOYEE_ID,
                    DEPARTMENT_LOCATION,
                    DEPARTMENT_ID,
                    GROSSTOTAL,
                    GROSSTOTAL_WITHOUT_ROUND,
                    NETTOTAL,
                    TAXTOTAL,
                    OTV_TOTAL,
                    SA_DISCOUNT,
                    PAY_METHOD,
                    DUE_DATE,
                    NOTE,
                    ORDER_ID,
                    OFFER_ID,
                    DELIVER_EMP,
                    SHIP_METHOD,
                    IS_PROCESSED,
                    IS_CASH,
                    IS_ACCOUNTED,
                    CASH_ID,
                    KASA_ID,
                    UPDATE_DATE,
                    UPDATE_EMP,
                    SALE_EMP,
                    SALE_PARTNER,
                    ZONE_ID,
                    PROJECT_ID,
                    UPD_STATUS,
                    OTHER_MONEY,
                    OTHER_MONEY_VALUE,
                    PROCESS_CAT,
                    IS_WITH_SHIP,
                    STOPAJ,
                    STOPAJ_ORAN,
                    PRINT_COUNT,
                    IS_IPTAL,
                    ROUND_MONEY,
                    IS_ORDERED,
                    REF_NO,
                    IS_COST,
                    GENERAL_PROM_ID,
                    GENERAL_PROM_LIMIT,
                    GENERAL_PROM_DISCOUNT,
                    GENERAL_PROM_AMOUNT,
                    FREE_PROM_ID,
                    FREE_PROM_LIMIT,
                    FREE_PROM_COST,
                    FREE_PROM_AMOUNT,
                    FREE_PROM_STOCK_ID,
                    FREE_STOCK_PRICE,
                    FREE_STOCK_MONEY,
                    SHIP_ADDRESS,
                    SHIP_ADDRESS_ID,
                    IS_RETURN,
                    TEVKIFAT,
                    TEVKIFAT_ORAN,
                    CARD_PAYMETHOD_ID,
                    CARD_PAYMETHOD_RATE,
                    RESOURCE_ID,
                    IMS_CODE_ID,
                    CUSTOMER_VALUE_ID,
                    STOPAJ_RATE_ID,
                    COMMETHOD_ID,
                    IS_TAX_OF_OTV,
                    CONSUMER_REFERENCE_CODE,
                    EXPENSE_CENTER_ID,
                    EXPENSE_ITEM_ID,
                    PARTNER_REFERENCE_CODE,
                    POS_CASH_ID,
                    SALES_CONSUMER_ID,
                    SALES_PARTNER_ID,
                    SALES_TEAM_ID,
                    ADD_FLAG,
                    CARI_ACTION_TYPE,
                    IS_ACC_FLAG,
                    CANCEL_TYPE_ID,
                    ASSETP_ID,
                    ACC_DEPARTMENT_ID,
                    PRINT_DATE,
                    SUBSCRIPTION_ID,
                    CITY_ID,
                    COUNTY_ID,
                    DELIVER_COMP_ID,
                    DELIVER_CONS_ID,
                    CONTRACT_ID,
                    PROGRESS_ID,
                    PROFILE_ID,
                    FROM_PROGRESS,
                    ACC_TYPE_ID,
                    UUID,
                    HOBIM_ID,
                    IS_PDF,
                    RECORD_CONS,
                    RECORD_DATE,
                    RECORD_EMP,
                    TAX_CODE,
                    BANK_ACTION_ID,
                    BANK_PERIOD_ID,
                    TEVKIFAT_ID,
                    CREDITCARD_PAYMENT_ID,
                    SERVICE_ID,
                    IS_CREDIT,
                    RELATED_INVOICE_ID,
                    IS_RECEIVED_WEBSERVICE,
                    IS_RATE_EXTRA_COST,
                    REALIZATION_DATE,
                    PROCESS_TIME,
                    BSMV_TOTAL,
                    OIV_TOTAL,
                    PROCESS_STAGE,
                    IS_EXPORT_REGISTRATION,
                    IS_EXPORT_PRODUCT,
                    VAT_EXCEPTION_ID,
                    PROCESS_DATE,
                    BANK_ID
                )
                VALUES
                (
                    #invoice_id#,
                    <cfif len(invoice_multi_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#invoice_multi_id#"><cfelse>NULL</cfif>,
					<cfqueryparam cfsqltype="cf_sql_varchar" value="#wrk_id#">,
					#purchase_sales#,
					<cfif len(invoice_cat)><cfqueryparam cfsqltype="cf_sql_varchar" value="#invoice_cat#"><cfelse>NULL</cfif>,
                    <cfif len(invoice_date)><cfqueryparam cfsqltype="cf_sql_timestamp" value="#invoice_date#"><cfelse>NULL</cfif>,
                    <cfif len(ship_date)><cfqueryparam cfsqltype="cf_sql_timestamp" value="#ship_date#"><cfelse>NULL</cfif>,
                    <cfif len(serial_number)><cfqueryparam cfsqltype="cf_sql_varchar" value="#serial_number#"><cfelse>NULL</cfif>,
                    <cfif len(serial_no)><cfqueryparam cfsqltype="cf_sql_varchar" value="#serial_no#"><cfelse>NULL</cfif>,
                    <cfif len(invoice_number)><cfqueryparam cfsqltype="cf_sql_varchar" value="#invoice_number#"><cfelse>NULL</cfif>,
                    <cfif len(company_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#company_id#"><cfelse>NULL</cfif>,
                    <cfif len(partner_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#partner_id#"><cfelse>NULL</cfif>,
                    <cfif len(consumer_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#consumer_id#"><cfelse>NULL</cfif>,
                    <cfif len(employee_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#employee_id#"><cfelse>NULL</cfif>,
                    <cfif len(department_location)><cfqueryparam cfsqltype="cf_sql_integer" value="#department_location#"><cfelse>NULL</cfif>,
                    <cfif len(department_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#department_id#"><cfelse>NULL</cfif>,
                    <cfif len(grosstotal)><cfqueryparam cfsqltype="cf_sql_float" value="#grosstotal#"><cfelse>NULL</cfif>,
                    <cfif len(grosstotal_without_round)><cfqueryparam cfsqltype="cf_sql_float" value="#grosstotal_without_round#"><cfelse>NULL</cfif>,
                    <cfif len(nettotal)><cfqueryparam cfsqltype="cf_sql_float" value="#nettotal#"><cfelse>NULL</cfif>,
                    <cfif len(taxtotal)><cfqueryparam cfsqltype="cf_sql_float" value="#taxtotal#"><cfelse>NULL</cfif>,
                    <cfif len(otv_total)><cfqueryparam cfsqltype="cf_sql_float" value="#otv_total#"><cfelse>NULL</cfif>,
                    <cfif len(sa_discount)><cfqueryparam cfsqltype="cf_sql_float" value="#sa_discount#"><cfelse>NULL</cfif>,
                    <cfif len(pay_method)><cfqueryparam cfsqltype="cf_sql_integer" value="#pay_method#"><cfelse>NULL</cfif>,
                    <cfif len(due_date)><cfqueryparam cfsqltype="cf_sql_timestamp" value="#due_date#"><cfelse>NULL</cfif>,
                    <cfif len(note)><cfqueryparam cfsqltype="cf_sql_varchar" value="#note#"><cfelse>NULL</cfif>,
                    <cfif len(order_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#ship_number#"><cfelse>NULL</cfif>,
                    <cfif len(offer_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#offer_id#"><cfelse>NULL</cfif>,
                    <cfif len(deliver_emp)><cfqueryparam cfsqltype="cf_sql_varchar" value="#deliver_emp#"><cfelse>NULL</cfif>,
                    <cfif len(ship_method)><cfqueryparam cfsqltype="cf_sql_integer" value="#ship_method#"><cfelse>NULL</cfif>,
                    <cfif len(is_processed)><cfqueryparam cfsqltype="cf_sql_bit" value="#is_processed#"><cfelse>NULL</cfif>,
                    <cfif len(is_cash)><cfqueryparam cfsqltype="cf_sql_bit" value="#is_cash#"><cfelse>NULL</cfif>,
                    <cfif len(is_accounted)><cfqueryparam cfsqltype="cf_sql_bit" value="#is_accounted#"><cfelse>NULL</cfif>,
                    <cfif len(cash_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#cash_id#"><cfelse>NULL</cfif>,
                    <cfif len(kasa_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#kasa_id#"><cfelse>NULL</cfif>,
                    <cfif len(update_date)><cfqueryparam cfsqltype="cf_sql_timestamp" value="#update_date#"><cfelse>NULL</cfif>,
                    <cfif len(update_emp)><cfqueryparam cfsqltype="cf_sql_integer" value="#update_emp#"><cfelse>NULL</cfif>,
                    <cfif len(sale_emp)><cfqueryparam cfsqltype="cf_sql_integer" value="#sale_emp#"><cfelse>NULL</cfif>,
                    <cfif len(sale_partner)><cfqueryparam cfsqltype="cf_sql_integer" value="#sale_partner#"><cfelse>NULL</cfif>,
                    <cfif len(zone_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#zone_id#"><cfelse>NULL</cfif>,
                    <cfif len(project_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#project_id#"><cfelse>NULL</cfif>,
                    <cfif len(upd_status)><cfqueryparam cfsqltype="cf_sql_bit" value="#upd_status#"><cfelse>NULL</cfif>,
                    <cfif len(other_money)><cfqueryparam cfsqltype="cf_sql_varchar" value="#other_money#"><cfelse>NULL</cfif>,
                    <cfif len(other_money_value)><cfqueryparam cfsqltype="cf_sql_float" value="#other_money_value#"><cfelse>NULL</cfif>,
                    <cfif len(process_cat)><cfqueryparam cfsqltype="cf_sql_integer" value="#process_cat#"><cfelse>NULL</cfif>,
                    <cfif len(is_with_ship)><cfqueryparam cfsqltype="cf_sql_bit" value="#is_with_ship#"><cfelse>NULL</cfif>,
                    <cfif len(stopaj)><cfqueryparam cfsqltype="cf_sql_float" value="#stopaj#"><cfelse>NULL</cfif>,
                    <cfif len(stopaj_oran)><cfqueryparam cfsqltype="cf_sql_float" value="#stopaj_oran#"><cfelse>NULL</cfif>,
                    <cfif len(print_count)><cfqueryparam cfsqltype="cf_sql_integer" value="#print_count#"><cfelse>NULL</cfif>,
                    <cfif len(is_iptal)><cfqueryparam cfsqltype="cf_sql_bit" value="#is_iptal#"><cfelse>NULL</cfif>,
                    <cfif len(round_money)><cfqueryparam cfsqltype="cf_sql_float" value="#round_money#"><cfelse>NULL</cfif>,
                    <cfif len(is_ordered)><cfqueryparam cfsqltype="cf_sql_bit" value="#is_ordered#"><cfelse>NULL</cfif>,
                    <cfif len(ref_no)><cfqueryparam cfsqltype="cf_sql_varchar" value="#ref_no#"><cfelse>NULL</cfif>,
                    <cfif len(is_cost)><cfqueryparam cfsqltype="cf_sql_bit" value="#is_cost#"><cfelse>NULL</cfif>,
                    <cfif len(general_prom_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#general_prom_id#"><cfelse>NULL</cfif>,
                    <cfif len(general_prom_limit)><cfqueryparam cfsqltype="cf_sql_integer" value="#general_prom_limit#"><cfelse>NULL</cfif>,
                    <cfif len(general_prom_discount)><cfqueryparam cfsqltype="cf_sql_float" value="#general_prom_discount#"><cfelse>NULL</cfif>,
                    <cfif len(general_prom_amount)><cfqueryparam cfsqltype="cf_sql_float" value="#general_prom_amount#"><cfelse>NULL</cfif>,
                    <cfif len(free_prom_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#free_prom_id#"><cfelse>NULL</cfif>,
                    <cfif len(free_prom_limit)><cfqueryparam cfsqltype="cf_sql_integer" value="#free_prom_limit#"><cfelse>NULL</cfif>,
                    <cfif len(free_prom_cost)><cfqueryparam cfsqltype="cf_sql_float" value="#free_prom_cost#"><cfelse>NULL</cfif>,
                    <cfif len(free_prom_amount)><cfqueryparam cfsqltype="cf_sql_integer" value="#free_prom_amount#"><cfelse>NULL</cfif>,
                    <cfif len(free_prom_stock_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#free_prom_stock_id#"><cfelse>NULL</cfif>,
                    <cfif len(free_stock_price)><cfqueryparam cfsqltype="cf_sql_float" value="#free_stock_price#"><cfelse>NULL</cfif>,
                    <cfif len(free_stock_money)><cfqueryparam cfsqltype="cf_sql_varchar" value="#free_stock_money#"><cfelse>NULL</cfif>,
                    <cfif len(ship_address)><cfqueryparam cfsqltype="cf_sql_varchar" value="#ship_address#"><cfelse>NULL</cfif>,
                    <cfif len(ship_address_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#ship_address_id#"><cfelse>NULL</cfif>,
                    <cfif len(is_return)><cfqueryparam cfsqltype="cf_sql_bit" value="#is_return#"><cfelse>NULL</cfif>,
                    <cfif len(tevkifat)><cfqueryparam cfsqltype="cf_sql_bit" value="#tevkifat#"><cfelse>NULL</cfif>,
                    <cfif len(tevkifat_oran)><cfqueryparam cfsqltype="cf_sql_float" value="#tevkifat_oran#"><cfelse>NULL</cfif>,
                    <cfif len(card_paymethod_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#card_paymethod_id#"><cfelse>NULL</cfif>,
                    <cfif len(card_paymethod_rate)><cfqueryparam cfsqltype="cf_sql_float" value="#card_paymethod_rate#"><cfelse>NULL</cfif>,
                    <cfif len(resource_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#resource_id#"><cfelse>NULL</cfif>,
                    <cfif len(ims_code_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#ims_code_id#"><cfelse>NULL</cfif>,
                    <cfif len(customer_value_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#customer_value_id#"><cfelse>NULL</cfif>,
                    <cfif len(stopaj_rate_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#stopaj_rate_id#"><cfelse>NULL</cfif>,
                    <cfif len(commethod_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#commethod_id#"><cfelse>NULL</cfif>,
                    <cfif len(is_tax_of_otv)><cfqueryparam cfsqltype="cf_sql_bit" value="#is_tax_of_otv#"><cfelse>NULL</cfif>,
                    <cfif len(consumer_reference_code)><cfqueryparam cfsqltype="cf_sql_varchar" value="#consumer_reference_code#"><cfelse>NULL</cfif>,
                    <cfif len(expense_center_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#expense_center_id#"><cfelse>NULL</cfif>,
                    <cfif len(expense_item_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#expense_item_id#"><cfelse>NULL</cfif>,
                    <cfif len(partner_reference_code)><cfqueryparam cfsqltype="cf_sql_varchar" value="#partner_reference_code#"><cfelse>NULL</cfif>,
                    <cfif len(pos_cash_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#pos_cash_id#"><cfelse>NULL</cfif>,
                    <cfif len(sales_consumer_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#sales_consumer_id#"><cfelse>NULL</cfif>,
                    <cfif len(sales_partner_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#sales_partner_id#"><cfelse>NULL</cfif>,
                    <cfif len(sales_team_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#sales_team_id#"><cfelse>NULL</cfif>,
                    <cfif len(add_flag)><cfqueryparam cfsqltype="cf_sql_bit" value="#add_flag#"><cfelse>NULL</cfif>,
                    <cfif len(cari_action_type)><cfqueryparam cfsqltype="cf_sql_integer" value="#cari_action_type#"><cfelse>NULL</cfif>,
                    <cfif len(is_acc_flag)><cfqueryparam cfsqltype="cf_sql_bit" value="#is_acc_flag#"><cfelse>NULL</cfif>,
                    <cfif len(cancel_type_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#cancel_type_id#"><cfelse>NULL</cfif>,
                    <cfif len(assetp_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#assetp_id#"><cfelse>NULL</cfif>,
                    <cfif len(acc_department_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#acc_department_id#"><cfelse>NULL</cfif>,
                    <cfif len(print_date)><cfqueryparam cfsqltype="cf_sql_timestamp" value="#print_date#"><cfelse>NULL</cfif>,
                    <cfif len(subscription_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#subscription_id#"><cfelse>NULL</cfif>,
                    <cfif len(city_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#city_id#"><cfelse>NULL</cfif>,
                    <cfif len(county_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#county_id#"><cfelse>NULL</cfif>,
                    <cfif len(deliver_comp_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#deliver_comp_id#"><cfelse>NULL</cfif>,
                    <cfif len(deliver_cons_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#deliver_cons_id#"><cfelse>NULL</cfif>,
                    <cfif len(contract_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#contract_id#"><cfelse>NULL</cfif>,
                    <cfif len(progress_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#progress_id#"><cfelse>NULL</cfif>,
                    <cfif len(profile_id)><cfqueryparam cfsqltype="cf_sql_varchar" value="#profile_id#"><cfelse>NULL</cfif>,
                    <cfif len(from_progress)><cfqueryparam cfsqltype="cf_sql_bit" value="#from_progress#"><cfelse>NULL</cfif>,
                    <cfif len(acc_type_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#acc_type_id#"><cfelse>NULL</cfif>,
                    <cfif len(uuid)><cfqueryparam cfsqltype="cf_sql_varchar" value="#uuid#"><cfelse>NULL</cfif>,
                    <cfif len(hobim_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#hobim_id#"><cfelse>NULL</cfif>,
                    <cfif len(is_pdf)><cfqueryparam cfsqltype="cf_sql_bit" value="#is_pdf#"><cfelse>NULL</cfif>,
                    <cfif len(record_cons)><cfqueryparam cfsqltype="cf_sql_integer" value="#record_cons#"><cfelse>NULL</cfif>,
                    <cfif len(record_date)><cfqueryparam cfsqltype="cf_sql_timestamp" value="#record_date#"><cfelse>NULL</cfif>,
                    <cfif len(record_emp)><cfqueryparam cfsqltype="cf_sql_integer" value="#record_emp#"><cfelse>NULL</cfif>,
                    <cfif len(tax_code)><cfqueryparam cfsqltype="cf_sql_varchar" value="#tax_code#"><cfelse>NULL</cfif>,
                    <cfif len(bank_action_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#bank_action_id#"><cfelse>NULL</cfif>,
                    <cfif len(bank_period_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#bank_period_id#"><cfelse>NULL</cfif>,
                    <cfif len(tevkifat_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#tevkifat_id#"><cfelse>NULL</cfif>,
                    <cfif len(creditcard_payment_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#creditcard_payment_id#"><cfelse>NULL</cfif>,
                    <cfif len(service_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#service_id#"><cfelse>NULL</cfif>,
                    <cfif len(is_credit)><cfqueryparam cfsqltype="cf_sql_integer" value="#is_credit#"><cfelse>NULL</cfif>,
                    <cfif len(related_invoice_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#related_invoice_id#"><cfelse>NULL</cfif>,
                    <cfif len(is_received_webservice)><cfqueryparam cfsqltype="cf_sql_bit" value="#is_received_webservice#"><cfelse>NULL</cfif>,
                    <cfif len(is_rate_extra_cost)><cfqueryparam cfsqltype="cf_sql_integer" value="#is_rate_extra_cost#"><cfelse>NULL</cfif>,
                    <cfif len(realization_date)><cfqueryparam cfsqltype="cf_sql_timestamp" value="#realization_date#"><cfelse>NULL</cfif>,
                    <cfif len(process_time)><cfqueryparam cfsqltype="cf_sql_timestamp" value="#process_time#"><cfelse>NULL</cfif>,
                    <cfif len(bsmv_total)><cfqueryparam cfsqltype="cf_sql_float" value="#bsmv_total#"><cfelse>NULL</cfif>,
                    <cfif len(oiv_total)><cfqueryparam cfsqltype="cf_sql_float" value="#oiv_total#"><cfelse>NULL</cfif>,
                    <cfif len(process_stage)><cfqueryparam cfsqltype="cf_sql_integer" value="#process_stage#"><cfelse>NULL</cfif>,
                    <cfif len(is_export_registration)><cfqueryparam cfsqltype="cf_sql_bit" value="#is_export_registration#"><cfelse>NULL</cfif>,
                    <cfif len(is_export_product)><cfqueryparam cfsqltype="cf_sql_bit" value="#is_export_product#"><cfelse>NULL</cfif>,
                    <cfif len(vat_exception_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#vat_exception_id#"><cfelse>NULL</cfif>,
                    <cfif len(process_date)><cfqueryparam cfsqltype="cf_sql_timestamp" value="#process_date#"><cfelse>NULL</cfif>,    
                    <cfif isdefined("attributes.account_id") and len(attributes.account_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#attributes.account_id#"><cfelse>NULL</cfif>            
                )
            </cfquery>
        </cfloop>
        <cfloop query="get_invoice_row">
            <cfquery name="ADD_INVOICE_ROW_HISTORY" datasource="#DSN2#">
                INSERT INTO 
                    INVOICE_ROW_HISTORY
                (
                    INVOICE_HISTORY_ID,
                    INVOICE_ID,
                    INVOICE_ROW_ID,
                    PURCHASE_SALES,
                    STOCK_ID,
                    DESCRIPTION,
                    AMOUNT,
                    PRICE,
                    PRICE_OTHER,
                    UNIT,
                    UNIT_ID,
                    COST_ID,
                    COST_PRICE,
                    MARGIN,
                    EXTRA_COST,
                    DISCOUNTTOTAL,
                    GROSSTOTAL,
                    NETTOTAL,
                    TAXTOTAL,
                    ORDER_ID,
                    PAY_METHOD,
                    DUE_DATE,
                    PROM_ID,
                    NAME_PRODUCT,
                    PRODUCT_ID,
                    TAX,
                    DISCOUNT1,
                    DISCOUNT2,
                    DISCOUNT3,
                    DISCOUNT4,
                    DISCOUNT5,
                    DISCOUNT6,
                    DISCOUNT7,
                    DISCOUNT8,
                    DISCOUNT9,
                    DISCOUNT10,
                    DELIVER_DATE,
                    DELIVER_DEPT,
                    DELIVER_LOC,
                    OTHER_MONEY,
                    OTHER_MONEY_VALUE,
                    OTHER_MONEY_GROSS_TOTAL,
                    SPECT_VAR_ID,
                    SPECT_VAR_NAME,
                    LOT_NO,
                    DARA,
                    SHIP_ID,
                    DARALI,
                    PROM_COMISSION,
                    PROM_COST,
                    DISCOUNT_COST,
                    IS_PROMOTION,
                    PROM_STOCK_ID,
                    IS_COMMISSION,
                    UNIQUE_RELATION_ID,
                    PRODUCT_NAME2,
                    AMOUNT2,
                    UNIT2,
                    EXTRA_PRICE,
                    SHELF_NUMBER,
                    PRODUCT_MANUFACT_CODE,
                    INVENTORY_ID,
                    EXTRA_PRICE_TOTAL,
                    OTV_ORAN,
                    OTVTOTAL,
                    SHIP_PERIOD_ID,
                    BASKET_EXTRA_INFO_ID,
                    SELECT_INFO_EXTRA,
                    DETAIL_INFO_EXTRA,
                    PROM_RELATION_ID,
                    BASKET_EMPLOYEE_ID,
                    LIST_PRICE,
                    NUMBER_OF_INSTALLMENT,
                    KARMA_PRODUCT_ID,
                    EXTRA_PRICE_OTHER_TOTAL,
                    PRICE_CAT,
                    EK_TUTAR_PRICE,
                    CATALOG_ID,
                    WRK_ROW_ID,
                    WRK_ROW_RELATION_ID,
                    RELATED_ACTION_ID,
                    RELATED_ACTION_TABLE,
                    DEPTH_VALUE,
                    WIDTH_VALUE,
                    HEIGHT_VALUE,
                    ROW_PROJECT_ID,
                    ROW_PAYMETHOD_ID,
                    PBS_ID,
                    ROW_WORK_ID,
                    ROW_EXP_CENTER_ID,
                    ROW_EXP_ITEM_ID,
                    ROW_ACC_CODE,
                    REASON_NAME,
                    REASON_CODE,
                    DELIVERY_CONDITION,
                    CONTAINER_TYPE,
                    CONTAINER_NUMBER,
                    CONTAINER_QUANTITY,
                    DELIVERY_COUNTRY,
                    DELIVERY_CITY,
                    DELIVERY_COUNTY,
                    DELIVERY_TYPE,
                    GTIP_NUMBER,
                    ACTIVITY_TYPE_ID,
                    SUBSCRIPTION_ID,
                    ASSETP_ID,
                    BSMV_RATE,
                    BSMV_AMOUNT,
                    BSMV_CURRENCY,
                    OIV_RATE,
                    OIV_AMOUNT,
                    TEVKIFAT_RATE,
                    TEVKIFAT_AMOUNT
                )
                VALUES
                (
                    #MAX_ID.IDENTITYCOL#,
                    #invoice_id#,
                    #invoice_row_id#,
                    <cfif len(purchase_sales)><cfqueryparam cfsqltype="cf_sql_bit" value="#purchase_sales#"><cfelse>NULL</cfif>,
                    <cfif len(stock_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#stock_id#"><cfelse>NULL</cfif>,
                    <cfif len(description)><cfqueryparam cfsqltype="cf_sql_varchar" value="#description#"><cfelse>NULL</cfif>,
                    <cfif len(amount)><cfqueryparam cfsqltype="cf_sql_float" value="#amount#"><cfelse>NULL</cfif>,
                    <cfif len(price)><cfqueryparam cfsqltype="cf_sql_float" value="#price#"><cfelse>NULL</cfif>,
                    <cfif len(price_other)><cfqueryparam cfsqltype="cf_sql_float" value="#price_other#"><cfelse>NULL</cfif>,
                    <cfif len(unit)><cfqueryparam cfsqltype="cf_sql_varchar" value="#unit#"><cfelse>NULL</cfif>,
                    <cfif len(unit_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#unit_id#"><cfelse>NULL</cfif>,
                    <cfif len(cost_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#cost_id#"><cfelse>NULL</cfif>,
                    <cfif len(cost_price)><cfqueryparam cfsqltype="cf_sql_float" value="#cost_price#"><cfelse>NULL</cfif>,
                    <cfif len(margin)><cfqueryparam cfsqltype="cf_sql_float" value="#margin#"><cfelse>NULL</cfif>,
                    <cfif len(extra_cost)><cfqueryparam cfsqltype="cf_sql_float" value="#extra_cost#"><cfelse>NULL</cfif>,
                    <cfif len(discounttotal)><cfqueryparam cfsqltype="cf_sql_float" value="#discounttotal#"><cfelse>NULL</cfif>,
                    <cfif len(grosstotal)><cfqueryparam cfsqltype="cf_sql_float" value="#grosstotal#"><cfelse>NULL</cfif>,
                    <cfif len(nettotal)><cfqueryparam cfsqltype="cf_sql_float" value="#nettotal#"><cfelse>NULL</cfif>,
                    <cfif len(taxtotal)><cfqueryparam cfsqltype="cf_sql_float" value="#taxtotal#"><cfelse>NULL</cfif>,
                    <cfif len(order_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#order_id#"><cfelse>NULL</cfif>,
                    <cfif len(pay_method)><cfqueryparam cfsqltype="cf_sql_integer" value="#pay_method#"><cfelse>NULL</cfif>,
                    <cfif len(due_date)><cfqueryparam cfsqltype="cf_sql_integer" value="#due_date#"><cfelse>NULL</cfif>,
                    <cfif len(prom_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#prom_id#"><cfelse>NULL</cfif>,
                    <cfif len(name_product)><cfqueryparam cfsqltype="cf_sql_varchar" value="#name_product#"><cfelse>NULL</cfif>,
                    <cfif len(product_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#product_id#"><cfelse>NULL</cfif>,
                    <cfif len(tax)><cfqueryparam cfsqltype="cf_sql_float" value="#tax#"><cfelse>NULL</cfif>,
                    <cfif len(discount1)><cfqueryparam cfsqltype="cf_sql_float" value="#discount1#"><cfelse>NULL</cfif>,
                    <cfif len(discount2)><cfqueryparam cfsqltype="cf_sql_float" value="#discount2#"><cfelse>NULL</cfif>,
                    <cfif len(discount3)><cfqueryparam cfsqltype="cf_sql_float" value="#discount3#"><cfelse>NULL</cfif>,
                    <cfif len(discount4)><cfqueryparam cfsqltype="cf_sql_float" value="#discount4#"><cfelse>NULL</cfif>,
                    <cfif len(discount5)><cfqueryparam cfsqltype="cf_sql_float" value="#discount5#"><cfelse>NULL</cfif>,
                    <cfif len(discount6)><cfqueryparam cfsqltype="cf_sql_float" value="#discount6#"><cfelse>NULL</cfif>,
                    <cfif len(discount7)><cfqueryparam cfsqltype="cf_sql_float" value="#discount7#"><cfelse>NULL</cfif>,
                    <cfif len(discount8)><cfqueryparam cfsqltype="cf_sql_float" value="#discount8#"><cfelse>NULL</cfif>,
                    <cfif len(discount9)><cfqueryparam cfsqltype="cf_sql_float" value="#discount9#"><cfelse>NULL</cfif>,
                    <cfif len(discount10)><cfqueryparam cfsqltype="cf_sql_float" value="#discount10#"><cfelse>NULL</cfif>,
                    <cfif len(deliver_date)><cfqueryparam cfsqltype="cf_sql_timestamp" value="#deliver_date#"><cfelse>NULL</cfif>,
                    <cfif len(deliver_dept)><cfqueryparam cfsqltype="cf_sql_integer" value="#deliver_dept#"><cfelse>NULL</cfif>,
                    <cfif len(deliver_loc)><cfqueryparam cfsqltype="cf_sql_integer" value="#deliver_loc#"><cfelse>NULL</cfif>,
                    <cfif len(other_money)><cfqueryparam cfsqltype="cf_sql_varchar" value="#other_money#"><cfelse>NULL</cfif>,
                    <cfif len(other_money_value)><cfqueryparam cfsqltype="cf_sql_float" value="#other_money_value#"><cfelse>NULL</cfif>,
                    <cfif len(other_money_gross_total)><cfqueryparam cfsqltype="cf_sql_float" value="#other_money_gross_total#"><cfelse>NULL</cfif>,
                    <cfif len(spect_var_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#spect_var_id#"><cfelse>NULL</cfif>,
                    <cfif len(spect_var_name)><cfqueryparam cfsqltype="cf_sql_varchar" value="#spect_var_name#"><cfelse>NULL</cfif>,
                    <cfif len(lot_no)><cfqueryparam cfsqltype="cf_sql_varchar" value="#lot_no#"><cfelse>NULL</cfif>,
                    <cfif len(dara)><cfqueryparam cfsqltype="cf_sql_float" value="#dara#"><cfelse>NULL</cfif>,
                    <cfif len(ship_id)><cfqueryparam cfsqltype="cf_sql_varchar" value="#ship_id#"><cfelse>NULL</cfif>,
                    <cfif len(darali)><cfqueryparam cfsqltype="cf_sql_float" value="#darali#"><cfelse>NULL</cfif>,
                    <cfif len(prom_comission)><cfqueryparam cfsqltype="cf_sql_float" value="#prom_comission#"><cfelse>NULL</cfif>,
                    <cfif len(prom_cost)><cfqueryparam cfsqltype="cf_sql_float" value="#prom_cost#"><cfelse>NULL</cfif>,
                    <cfif len(discount_cost)><cfqueryparam cfsqltype="cf_sql_float" value="#discount_cost#"><cfelse>NULL</cfif>,
                    <cfif len(is_promotion)><cfqueryparam cfsqltype="cf_sql_bit" value="#is_promotion#"><cfelse>NULL</cfif>,
                    <cfif len(prom_stock_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#prom_stock_id#"><cfelse>NULL</cfif>,
                    <cfif len(is_commission)><cfqueryparam cfsqltype="cf_sql_bit" value="#is_commission#"><cfelse>NULL</cfif>,
                    <cfif len(unique_relation_id)><cfqueryparam cfsqltype="cf_sql_varchar" value="#unique_relation_id#"><cfelse>NULL</cfif>,
                    <cfif len(product_name2)><cfqueryparam cfsqltype="cf_sql_varchar" value="#product_name2#"><cfelse>NULL</cfif>,
                    <cfif len(amount2)><cfqueryparam cfsqltype="cf_sql_float" value="#amount2#"><cfelse>NULL</cfif>,
                    <cfif len(unit2)><cfqueryparam cfsqltype="cf_sql_varchar" value="#unit2#"><cfelse>NULL</cfif>,
                    <cfif len(extra_price)><cfqueryparam cfsqltype="cf_sql_float" value="#extra_price#"><cfelse>NULL</cfif>,
                    <cfif len(shelf_number)><cfqueryparam cfsqltype="cf_sql_integer" value="#shelf_number#"><cfelse>NULL</cfif>,
                    <cfif len(product_manufact_code)><cfqueryparam cfsqltype="cf_sql_varchar" value="#product_manufact_code#"><cfelse>NULL</cfif>,
                    <cfif len(inventory_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#inventory_id#"><cfelse>NULL</cfif>,
                    <cfif len(extra_price_total)><cfqueryparam cfsqltype="cf_sql_float" value="#extra_price_total#"><cfelse>NULL</cfif>,
                    <cfif len(otv_oran)><cfqueryparam cfsqltype="cf_sql_float" value="#otv_oran#"><cfelse>NULL</cfif>,
                    <cfif len(otvtotal)><cfqueryparam cfsqltype="cf_sql_float" value="#otvtotal#"><cfelse>NULL</cfif>,
                    <cfif len(ship_period_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#ship_period_id#"><cfelse>NULL</cfif>,
                    <cfif len(basket_extra_info_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#basket_extra_info_id#"><cfelse>NULL</cfif>,
                    <cfif len(select_info_extra)><cfqueryparam cfsqltype="cf_sql_integer" value="#select_info_extra#"><cfelse>NULL</cfif>,
                    <cfif len(detail_info_extra)><cfqueryparam cfsqltype="cf_sql_varchar" value="#detail_info_extra#"><cfelse>NULL</cfif>,
                    <cfif len(prom_relation_id)><cfqueryparam cfsqltype="cf_sql_varchar" value="#prom_relation_id#"><cfelse>NULL</cfif>,
                    <cfif len(basket_employee_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#basket_employee_id#"><cfelse>NULL</cfif>,
                    <cfif len(list_price)><cfqueryparam cfsqltype="cf_sql_float" value="#list_price#"><cfelse>NULL</cfif>,
                    <cfif len(number_of_installment)><cfqueryparam cfsqltype="cf_sql_integer" value="#number_of_installment#"><cfelse>NULL</cfif>,
                    <cfif len(karma_product_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#karma_product_id#"><cfelse>NULL</cfif>,
                    <cfif len(extra_price_other_total)><cfqueryparam cfsqltype="cf_sql_float" value="#extra_price_other_total#"><cfelse>NULL</cfif>,
                    <cfif len(price_cat)><cfqueryparam cfsqltype="cf_sql_integer" value="#price_cat#"><cfelse>NULL</cfif>,
                    <cfif len(ek_tutar_price)><cfqueryparam cfsqltype="cf_sql_float" value="#ek_tutar_price#"><cfelse>NULL</cfif>,        
                    <cfif len(catalog_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#catalog_id#"><cfelse>NULL</cfif>,        
                    <cfif len(wrk_row_id)><cfqueryparam cfsqltype="cf_sql_varchar" value="#wrk_row_id#"><cfelse>NULL</cfif>,        
                    <cfif len(wrk_row_relation_id)><cfqueryparam cfsqltype="cf_sql_varchar" value="#wrk_row_relation_id#"><cfelse>NULL</cfif>,        
                    <cfif len(related_action_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#related_action_id#"><cfelse>NULL</cfif>,        
                    <cfif len(related_action_table)><cfqueryparam cfsqltype="cf_sql_varchar" value="#related_action_table#"><cfelse>NULL</cfif>,        
                    <cfif len(depth_value)><cfqueryparam cfsqltype="cf_sql_float" value="#depth_value#"><cfelse>NULL</cfif>,        
                    <cfif len(width_value)><cfqueryparam cfsqltype="cf_sql_float" value="#width_value#"><cfelse>NULL</cfif>,        
                    <cfif len(height_value)><cfqueryparam cfsqltype="cf_sql_float" value="#height_value#"><cfelse>NULL</cfif>,        
                    <cfif len(row_project_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#row_project_id#"><cfelse>NULL</cfif>,        
                    <cfif len(row_paymethod_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#row_paymethod_id#"><cfelse>NULL</cfif>,        
                    <cfif len(pbs_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#pbs_id#"><cfelse>NULL</cfif>,        
                    <cfif len(row_work_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#row_work_id#"><cfelse>NULL</cfif>,        
                    <cfif len(row_exp_center_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#row_exp_center_id#"><cfelse>NULL</cfif>,        
                    <cfif len(row_exp_item_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#row_exp_item_id#"><cfelse>NULL</cfif>,        
                    <cfif len(row_acc_code)><cfqueryparam cfsqltype="cf_sql_varchar" value="#row_acc_code#"><cfelse>NULL</cfif>,        
                    <cfif len(reason_name)><cfqueryparam cfsqltype="cf_sql_varchar" value="#reason_name#"><cfelse>NULL</cfif>,
                    <cfif len(reason_code)><cfqueryparam cfsqltype="cf_sql_varchar" value="#reason_code#"><cfelse>NULL</cfif>,        
                    <cfif len(delivery_condition)><cfqueryparam cfsqltype="cf_sql_varchar" value="#delivery_condition#"><cfelse>NULL</cfif>,
                    <cfif len(container_type)><cfqueryparam cfsqltype="cf_sql_varchar" value="#container_type#"><cfelse>NULL</cfif>,        
                    <cfif len(container_number)><cfqueryparam cfsqltype="cf_sql_varchar" value="#container_number#"><cfelse>NULL</cfif>,
                    <cfif len(container_quantity)><cfqueryparam cfsqltype="cf_sql_varchar" value="#container_quantity#"><cfelse>NULL</cfif>,        
                    <cfif len(delivery_country)><cfqueryparam cfsqltype="cf_sql_varchar" value="#delivery_country#"><cfelse>NULL</cfif>,
                    <cfif len(delivery_city)><cfqueryparam cfsqltype="cf_sql_varchar" value="#delivery_city#"><cfelse>NULL</cfif>,        
                    <cfif len(delivery_county)><cfqueryparam cfsqltype="cf_sql_varchar" value="#delivery_county#"><cfelse>NULL</cfif>,
                    <cfif len(delivery_type)><cfqueryparam cfsqltype="cf_sql_varchar" value="#delivery_type#"><cfelse>NULL</cfif>,        
                    <cfif len(gtip_number)><cfqueryparam cfsqltype="cf_sql_varchar" value="#gtip_number#"><cfelse>NULL</cfif>,
                    <cfif len(activity_type_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#activity_type_id#"><cfelse>NULL</cfif>,        
                    <cfif len(subscription_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#subscription_id#"><cfelse>NULL</cfif>,
                    <cfif len(assetp_id)><cfqueryparam cfsqltype="cf_sql_integer" value="#assetp_id#"><cfelse>NULL</cfif>,        
                    <cfif len(bsmv_rate)><cfqueryparam cfsqltype="cf_sql_float" value="#bsmv_rate#"><cfelse>NULL</cfif>,
                    <cfif len(bsmv_amount)><cfqueryparam cfsqltype="cf_sql_float" value="#bsmv_amount#"><cfelse>NULL</cfif>,        
                    <cfif len(bsmv_currency)><cfqueryparam cfsqltype="cf_sql_float" value="#bsmv_currency#"><cfelse>NULL</cfif>,
                    <cfif len(oiv_rate)><cfqueryparam cfsqltype="cf_sql_float" value="#oiv_rate#"><cfelse>NULL</cfif>,        
                    <cfif len(oiv_amount)><cfqueryparam cfsqltype="cf_sql_float" value="#oiv_amount#"><cfelse>NULL</cfif>,
                    <cfif len(tevkifat_rate)><cfqueryparam cfsqltype="cf_sql_float" value="#tevkifat_rate#"><cfelse>NULL</cfif>,        
                    <cfif len(tevkifat_amount)><cfqueryparam cfsqltype="cf_sql_float" value="#tevkifat_amount#"><cfelse>NULL</cfif>               
                )
            </cfquery>
        </cfloop>
    </cftransaction>
</cflock>
