<cfquery name="GET_PRODUCT_PROPERTY" datasource="#DSN3#">
	SELECT 
		* 
	FROM 
		PRODUCT_OPTIONS,
		#dsn1_alias#.PRODUCT_PROPERTY  PRODUCT_PROPERTY
	WHERE 
		PRODUCT_PROPERTY.PROPERTY_ID = PRODUCT_OPTIONS.PROPERTY_ID AND 
		PRODUCT_ID = #attributes.product_id# AND
		PRODUCT_PROPERTY.PROPERTY_ID IS NOT NULL
	ORDER BY 
		PRODUCT_OPTIONS.PROPERTY_ID 
</cfquery>
