<cfquery name="GET_PAR" datasource="#DSN#">
	SELECT 
		COMPANY_PARTNER.PARTNER_ID,
		COMPANY_PARTNER_NAME,
		COMPANY_PARTNER_SURNAME,
		COMPANY_PARTNER.MEMBER_CODE,
		NICKNAME
	FROM
		COMPANY_PARTNER,
		COMPANY
	WHERE
		COMPANY.COMPANY_ID = COMPANY_PARTNER.COMPANY_ID AND
	  <cfif isdefined("attributes.partner_id")>
		COMPANY_PARTNER.PARTNER_ID = #attributes.PARTNER_ID#
	  <cfelse>
		COMPANY_PARTNER.PARTNER_ID = #PAR_ID#
	  </cfif>
</cfquery>
