<cfquery name="GET_WORK_PARTNER" datasource="#dsn#">
	SELECT
		COMPANY_PARTNER.PARTNER_ID,
		COMPANY_PARTNER.COMPANY_PARTNER_NAME,
		COMPANY_PARTNER.COMPANY_PARTNER_SURNAME,
		COMPANY_PARTNER.COMPANY_PARTNER_EMAIL,
		COMPANY.COMPANY_ID,
		COMPANY.NICKNAME,
		COMPANY.FULLNAME
	FROM
		COMPANY_PARTNER,
		COMPANY
	WHERE
		COMPANY_PARTNER.PARTNER_ID = #CMP_PARTNER_ID#
		AND
		COMPANY.COMPANY_ID = COMPANY_PARTNER.COMPANY_ID
</cfquery>
