<cfquery name="GET_POS" datasource="#dsn#">
	SELECT
		EMPLOYEE_ID,
		EMPLOYEE_NAME,
		EMPLOYEE_SURNAME,
		POSITION_NAME,
		EMPLOYEE_EMAIL
	FROM
		EMPLOYEE_POSITIONS
	WHERE
		EMPLOYEE_ID=#PROJECT_EMP_ID#
		AND
		POSITION_STATUS=1
</cfquery>
