<cfquery name="GET_VOCATION_TYPE" datasource="#DSN#">
	SELECT
		VOCATION_TYPE_ID,
		#dsn#.Get_Dynamic_Language(VOCATION_TYPE_ID,'#session.ep.language#','SETUP_VOCATION_TYPE','VOCATION_TYPE',NULL,NULL,VOCATION_TYPE) AS VOCATION_TYPE
	FROM
		SETUP_VOCATION_TYPE
	ORDER BY
		VOCATION_TYPE
</cfquery>
