<cfquery name="GET_GUARANTY_CAT" datasource="#dsn#">
	SELECT 
		CURRENCY,
		GUARANTYCAT_ID,
		#dsn#.Get_Dynamic_Language(GUARANTYCAT_ID,'#session.ep.language#','SETUP_GUARANTY','GUARANTYCAT',NULL,NULL,GUARANTYCAT) AS GUARANTYCAT,
		GUARANTYCAT_TIME,
		MAX_GUARANTYCAT_TIME,
		DETAIL,
		RECORD_DATE,
		RECORD_EMP,
		RECORD_IP,
		UPDATE_DATE,
		UPDATE_EMP,
		UPDATE_IP
	FROM 
		SETUP_GUARANTY
	ORDER BY
		GUARANTYCAT
</cfquery>
