<cfquery name="GET_OTHER_COMPANIES" datasource="#DSN#">
	SELECT
		*,
        (SELECT TOP 1
            EP.PERIOD_ID
        FROM
            EMPLOYEE_POSITIONS E,
            EMPLOYEE_POSITION_PERIODS EP
        WHERE
            E.POSITION_CODE = #session.ep.position_code# AND
            E.POSITION_ID = EP.POSITION_ID AND EP.PERIOD_ID = SETUP_PERIOD.PERIOD_ID) AUTHORITY_STATUS
	FROM
		SETUP_PERIOD JOIN OUR_COMPANY ON SETUP_PERIOD.OUR_COMPANY_ID = OUR_COMPANY.COMP_ID 
		WHERE OUR_COMPANY.COMP_STATUS = 1 AND ISNULL(SETUP_PERIOD.IS_ACTIVE,1) = 1
	ORDER BY
		PERIOD_YEAR DESC,
		OUR_COMPANY_ID
</cfquery>
<cfquery name="GET_COMPANY_PERIODS" datasource="#DSN#">
	SELECT
		CP.PERIOD_ID,
		C.IS_BUYER,
		C.IS_SELLER,
		C.PERIOD_ID AS DEFAULT_PERIOD
	FROM
		COMPANY_PERIOD CP,
		COMPANY C
	WHERE
		CP.COMPANY_ID = #attributes.cpid# AND 
        CP.COMPANY_ID = C.COMPANY_ID
</cfquery>
<cfquery name="GET_PERIOD_YEAR" datasource="#DSN#">
	SELECT
	DISTINCT 
		PERIOD_YEAR
	FROM
		SETUP_PERIOD

</cfquery>