<cfif contact_type is "E">
	<cfquery name="GET_CONTACT_SIMPLE" datasource="#dsn#">
		SELECT
			EMPLOYEES.EMPLOYEE_ID AS ID,
			EMPLOYEES.EMPLOYEE_NAME AS NAME,
			EMPLOYEES.EMPLOYEE_SURNAME AS SURNAME,
			EMPLOYEES.EMPLOYEE_EMAIL AS EMAIL,
			EMPLOYEES.DIRECT_TELCODE AS PHONE_CODE,
			EMPLOYEES.DIRECT_TEL AS PHONE,
			EMPLOYEES.MOBILCODE AS MOBILE_CAT_ID,
			EMPLOYEES.MOBILTEL AS MOBILE,
			EMPLOYEES.MEMBER_CODE,
            '' AS FAX,
			'' AS COMPANY_NAME,
			'' AS SECTOR_CAT_ID,
			'' AS COMPANY_SIZE_CAT_ID,  
			'' AS AUTHORITY_ID,
			'' AS ISPOTANTIAL,
			'' AS COMPANYCAT_ID,
			'' AS COMPANYCAT,
			'' AS COMPANYCAT_TYPE
		FROM
			EMPLOYEES
		WHERE
			EMPLOYEES.EMPLOYEE_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#contact_id#">
	</cfquery>
<cfelseif contact_type is "comp">
	<cfquery name="GET_CONTACT_SIMPLE" datasource="#dsn#">
		SELECT
			COMPANY_PARTNER.PARTNER_ID AS ID,
			COMPANY_PARTNER.COMPANY_PARTNER_NAME AS NAME,
			COMPANY_PARTNER.COMPANY_PARTNER_SURNAME AS SURNAME,
			COMPANY_PARTNER.COMPANY_PARTNER_EMAIL AS EMAIL,
			COMPANY_PARTNER.COMPANY_PARTNER_TELCODE AS PHONE_CODE,
			COMPANY_PARTNER.COMPANY_PARTNER_TEL AS PHONE,
			COMPANY_PARTNER.MOBIL_CODE,
			COMPANY_PARTNER.MOBILTEL AS MOBILE,
			COMPANY_PARTNER.COMPANY_PARTNER_FAX AS FAX,
			COMPANY_PARTNER.PARTNER_ID AS AUTHORITY_ID,
			COMPANY.MEMBER_CODE,
			COMPANY.COMPANY_ID,
			COMPANY.FULLNAME AS COMPANY_NAME,
			COMPANY.FULLNAME,
			COMPANY.SECTOR_CAT_ID,
			COMPANY.COMPANY_SIZE_CAT_ID,
			COMPANY.ISPOTANTIAL,
			COMPANY.COMPANYCAT_ID,
			COMPANY_CAT.COMPANYCAT,
			COMPANY_CAT.COMPANYCAT_TYPE,
            (SELECT CITY_NAME FROM SETUP_CITY WHERE SETUP_CITY.CITY_ID=COMPANY.CITY) CITY_NAME,
            (SELECT COUNTY_NAME FROM SETUP_COUNTY WHERE COUNTY_ID=COMPANY.COUNTY) COUNTY_NAME,
            (SELECT SZ_NAME FROM SALES_ZONES WHERE SALES_ZONES.SZ_ID=COMPANY.SALES_COUNTY) SZ_NAME
       FROM
			COMPANY,
			COMPANY_CAT,
			COMPANY_PARTNER
		WHERE
			COMPANY.MANAGER_PARTNER_ID = COMPANY_PARTNER.PARTNER_ID AND
			COMPANY.COMPANY_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#contact_id#"> AND
			COMPANY_CAT.COMPANYCAT_ID = COMPANY.COMPANYCAT_ID
	</cfquery>
<cfelseif contact_type is "P">
	<cfquery name="GET_CONTACT_SIMPLE" datasource="#dsn#">
		SELECT
			<cfif  contact_type is "p">
				COMPANY_PARTNER.PARTNER_ID AS ID,
				COMPANY_PARTNER.COMPANY_PARTNER_NAME AS NAME,
				COMPANY_PARTNER.COMPANY_PARTNER_SURNAME AS SURNAME,
				COMPANY_PARTNER.COMPANY_PARTNER_EMAIL AS EMAIL,
				COMPANY_PARTNER.COMPANY_PARTNER_TELCODE AS PHONE_CODE,
				COMPANY_PARTNER.COMPANY_PARTNER_TEL AS PHONE,
				COMPANY_PARTNER.MOBIL_CODE,
				COMPANY_PARTNER.MOBILTEL AS MOBILE,
				COMPANY_PARTNER.COMPANY_PARTNER_FAX AS FAX,
				COMPANY_PARTNER.PARTNER_ID AS AUTHORITY_ID,
			<cfelse>
				-1 AS ID, '' AS NAME , '' AS SURNAME ,
				'' AS EMAIL , '' AS PHONE_CODE , '' AS PHONE,
				'' AS MOBIL_CODE,  '' AS MOBILE,'' AS FAX ,-1  AS AUTHORITY_ID,
			</cfif>	
			COMPANY.MEMBER_CODE,
			COMPANY.COMPANY_ID,
			COMPANY.NICKNAME AS COMPANY_NAME,
			COMPANY.FULLNAME,
			COMPANY.SECTOR_CAT_ID,
			COMPANY.COMPANY_SIZE_CAT_ID,
			COMPANY.ISPOTANTIAL,
			COMPANY.COMPANYCAT_ID,
			COMPANY_CAT.COMPANYCAT,
			COMPANY_CAT.COMPANYCAT_TYPE
		FROM
			<cfif contact_type is "p">COMPANY_PARTNER,</cfif>
			COMPANY,
			COMPANY_CAT
		WHERE
			<cfif contact_type is "comp">
				COMPANY.COMPANY_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#contact_id#">
			<cfelse>
				COMPANY_PARTNER.PARTNER_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#contact_id#"> AND
				COMPANY.COMPANY_ID = COMPANY_PARTNER.COMPANY_ID				
			</cfif>
			AND COMPANY_CAT.COMPANYCAT_ID = COMPANY.COMPANYCAT_ID
	</cfquery>
<cfelseif contact_type is "C">
	<cfquery name="GET_CONTACT_SIMPLE" datasource="#dsn#">
		SELECT
			CONSUMER.CONSUMER_NAME AS NAME,
			CONSUMER.CONSUMER_SURNAME AS SURNAME,
			CONSUMER.CONSUMER_EMAIL AS EMAIL,
			CONSUMER.CONSUMER_HOMETELCODE AS PHONE_CODE,
			CONSUMER.CONSUMER_HOMETEL AS PHONE,
			CONSUMER.MOBIL_CODE,
			CONSUMER.MOBILTEL AS MOBILE,
			CONSUMER.MEMBER_CODE,
			CONSUMER.CONSUMER_FAXCODE,
			CONSUMER.CONSUMER_FAX,
			CONSUMER.COMPANY AS COMPANY_NAME,
			CONSUMER.COMPANY_SIZE_CAT_ID,
			CONSUMER.SECTOR_CAT_ID,
			CONSUMER.ISPOTANTIAL,
			CONSUMER_CAT.CONSCAT,
			CONSUMER_ID AS ID,
			'' AS COMPANYCAT_TYPE
		FROM
			CONSUMER,
			CONSUMER_CAT
		WHERE
			CONSUMER_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#contact_id#"> AND
			CONSUMER_CAT.CONSCAT_ID = CONSUMER.CONSUMER_CAT_ID
	</cfquery>
</cfif>

