<cfquery name="PURCHASE" datasource="#dsn2#">
	SELECT
		SHIP_ROW.*,
		PRODUCT.PRODUCT_NAME,
		STOCKS.PROPERTY,
		PRODUCT.PRODUCT_ID
	FROM
		SHIP_ROW,
		#dsn3_alias#.PRODUCT AS PRODUCT,
		#dsn3_alias#.STOCKS AS STOCKS
	WHERE
		SHIP_ROW.SHIP_ID = #attributes.SHIP_ID#
		AND
		SHIP_ROW.PURCHASE_SALES = 0
		AND
		STOCKS.PRODUCT_ID = PRODUCT.PRODUCT_ID
</cfquery>
