<cfquery name="GET_COMPANY_AUTHORITY" datasource="#dsn#">
	SELECT
		COMPANY_PARTNER.COMPANY_PARTNER_NAME,
		COMPANY_PARTNER.COMPANY_PARTNER_SURNAME
	FROM
		COMPANY_PARTNER,
		COMPANY
	WHERE
		COMPANY.PARTNER_ID = #AUTHORITY_ID#
</cfquery>
