<!---Görev tipi derece/kademe olan calisanlar icin (duty_type 8) 
sgk ve vergi muaf kontrolu yapilarak diger ucretli alanina eklendi --->
<cfsetting showdebugoutput="false">
<cfparam name="attributes.branch_id" default="">
<cfparam name="attributes.sal_mon" default="#month(now())#">
<cfparam name="attributes.sal_mon_end" default="#month(now())#">
<cfparam name="attributes.sal_year" default="#year(now())#">
<cfparam name="attributes.is_excel" default="">
<cfparam name="attributes.page" default=1>
<cfparam name="attributes.maxrows" default='#session.ep.maxrows#'>
<cfset attributes.startrow=((attributes.page-1)*attributes.maxrows)+1>
<cfscript>
	cmp_branch = createObject("component","V16.hr.cfc.get_branches");
	cmp_branch.dsn = dsn;
	get_branches = cmp_branch.get_branch(ehesap_control : 1);
</cfscript>

<cfif isdefined("attributes.is_form_submit")>
	<cfquery name="get_sgk_detail" datasource="#dsn#">
		SELECT
			ISNULL(BRANCH_CITY,'Tanımsız') AS BRANCH_CITY,
			SAL_MON,
			SAL_YEAR,
			SGK_NO,
			SUM(GV_MUAF_KADIN) AS GV_MUAF_KADIN,
			SUM(GV_MUAF_ERKEK) AS GV_MUAF_ERKEK,
			SUM(GV_MUAF_ENGELLI_KADIN) AS GV_MUAF_ENGELLI_KADIN,
			SUM(GV_MUAF_ENGELLI_ERKEK) AS GV_MUAF_ENGELLI_ERKEK,
			SUM(SGK_MUAF_KADIN) AS SGK_MUAF_KADIN,
			SUM(SGK_MUAF_ERKEK) AS SGK_MUAF_ERKEK,
			SUM(SGK_MUAF_ENGELLI_KADIN) AS SGK_MUAF_ENGELLI_KADIN,
			SUM(SGK_MUAF_ENGELLI_ERKEK) AS SGK_MUAF_ENGELLI_ERKEK,
			SUM(ASGARI_UCRETLI_KADIN) AS ASGARI_UCRETLI_KADIN,
			SUM(ASGARI_UCRETLI_ERKEK) AS ASGARI_UCRETLI_ERKEK,
			SUM(ASGARI_UCRETLI_ENGELLI_KADIN) AS ASGARI_UCRETLI_ENGELLI_KADIN,
			SUM(ASGARI_UCRETLI_ENGELLI_ERKEK) AS ASGARI_UCRETLI_ENGELLI_ERKEK,
			SUM(DIGER_UCRETLI_KADIN) AS DIGER_UCRETLI_KADIN,
			SUM(DIGER_UCRETLI_ERKEK) AS DIGER_UCRETLI_ERKEK,
			SUM(DIGER_UCRETLI_ENGELLI_KADIN) AS DIGER_UCRETLI_ENGELLI_KADIN,
			SUM(DIGER_UCRETLI_ENGELLI_ERKEK) AS DIGER_UCRETLI_ENGELLI_ERKEK
		FROM
		(
			SELECT 
				B.BRANCH_CITY,
				EP.SAL_MON,
				EP.SAL_YEAR,
				B.SSK_M + B.SSK_JOB+B.SSK_BRANCH+B.SSK_BRANCH_OLD+B.SSK_NO+B.SSK_CITY+B.SSK_COUNTRY+B.SSK_CD+B.SSK_AGENT AS SGK_NO,
				COUNT(EPR.EMPLOYEE_ID) GV_MUAF_KADIN,
				0 GV_MUAF_ERKEK,
				0 GV_MUAF_ENGELLI_KADIN,
				0 GV_MUAF_ENGELLI_ERKEK,
				0 SGK_MUAF_KADIN,
				0 SGK_MUAF_ERKEK,
				0 SGK_MUAF_ENGELLI_KADIN,
				0 SGK_MUAF_ENGELLI_ERKEK,
				0 ASGARI_UCRETLI_KADIN,
				0 ASGARI_UCRETLI_ERKEK,
				0 ASGARI_UCRETLI_ENGELLI_KADIN,
				0 ASGARI_UCRETLI_ENGELLI_ERKEK,
				0 DIGER_UCRETLI_KADIN,
				0 DIGER_UCRETLI_ERKEK,
				0 DIGER_UCRETLI_ENGELLI_KADIN,
				0 DIGER_UCRETLI_ENGELLI_ERKEK,
                B.BRANCH_ID
			FROM 
				EMPLOYEES_PUANTAJ_ROWS EPR
				INNER JOIN EMPLOYEES_PUANTAJ EP ON EP.PUANTAJ_ID = EPR.PUANTAJ_ID
				INNER JOIN EMPLOYEES_IN_OUT EIO ON EIO.IN_OUT_ID = EPR.IN_OUT_ID
				INNER JOIN DEPARTMENT D ON D.DEPARTMENT_ID = EPR.DEPARTMENT_ID
				INNER JOIN BRANCH B ON B.BRANCH_ID = D.BRANCH_ID
				INNER JOIN EMPLOYEES_DETAIL ED ON ED.EMPLOYEE_ID = EPR.EMPLOYEE_ID
			WHERE
				ED.SEX = 0
				AND EIO.IS_TAX_FREE = 1
				<cfif not session.ep.ehesap>
					AND B.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">)
				</cfif>

			GROUP BY
				B.BRANCH_CITY,B.SSK_M,B.SSK_JOB,B.SSK_BRANCH,B.SSK_BRANCH_OLD,B.SSK_NO,B.SSK_CITY,B.SSK_COUNTRY,B.SSK_CD,B.SSK_AGENT,
				EP.SAL_YEAR,
				EP.SAL_MON,
                B.BRANCH_ID
			UNION ALL
			SELECT 
				B.BRANCH_CITY,
				EP.SAL_MON,
				EP.SAL_YEAR,
				B.SSK_M + B.SSK_JOB+B.SSK_BRANCH+B.SSK_BRANCH_OLD+B.SSK_NO+B.SSK_CITY+B.SSK_COUNTRY+B.SSK_CD+B.SSK_AGENT AS SGK_NO,
				0 GV_MUAF_KADIN,
				COUNT(EPR.EMPLOYEE_ID) GV_MUAF_ERKEK,
				0 GV_MUAF_ENGELLI_KADIN,
				0 GV_MUAF_ENGELLI_ERKEK,
				0 SGK_MUAF_KADIN,
				0 SGK_MUAF_ERKEK,
				0 SGK_MUAF_ENGELLI_KADIN,
				0 SGK_MUAF_ENGELLI_ERKEK,
				0 ASGARI_UCRETLI_KADIN,
				0 ASGARI_UCRETLI_ERKEK,
				0 ASGARI_UCRETLI_ENGELLI_KADIN,
				0 ASGARI_UCRETLI_ENGELLI_ERKEK,
				0 DIGER_UCRETLI_KADIN,
				0 DIGER_UCRETLI_ERKEK,
				0 DIGER_UCRETLI_ENGELLI_KADIN,
				0 DIGER_UCRETLI_ENGELLI_ERKEK,
                B.BRANCH_ID
			FROM 
				EMPLOYEES_PUANTAJ_ROWS EPR
				INNER JOIN EMPLOYEES_PUANTAJ EP ON EP.PUANTAJ_ID = EPR.PUANTAJ_ID
				INNER JOIN EMPLOYEES_IN_OUT EIO ON EIO.IN_OUT_ID = EPR.IN_OUT_ID
				INNER JOIN DEPARTMENT D ON D.DEPARTMENT_ID = EPR.DEPARTMENT_ID
				INNER JOIN BRANCH B ON B.BRANCH_ID = D.BRANCH_ID
				INNER JOIN EMPLOYEES_DETAIL ED ON ED.EMPLOYEE_ID = EPR.EMPLOYEE_ID
			WHERE
				ED.SEX = 1
				AND EIO.IS_TAX_FREE = 1
				<cfif not session.ep.ehesap>
					AND B.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">)
				</cfif>

			GROUP BY
				B.BRANCH_CITY,B.SSK_M,B.SSK_JOB,B.SSK_BRANCH,B.SSK_BRANCH_OLD,B.SSK_NO,B.SSK_CITY,B.SSK_COUNTRY,B.SSK_CD,B.SSK_AGENT,
				EP.SAL_YEAR,
				EP.SAL_MON,
                B.BRANCH_ID
			UNION ALL
			SELECT 
				B.BRANCH_CITY,
				EP.SAL_MON,
				EP.SAL_YEAR,
				B.SSK_M + B.SSK_JOB+B.SSK_BRANCH+B.SSK_BRANCH_OLD+B.SSK_NO+B.SSK_CITY+B.SSK_COUNTRY+B.SSK_CD+B.SSK_AGENT AS SGK_NO,
				0 GV_MUAF_KADIN,
				0 GV_MUAF_ERKEK,
				COUNT(EPR.EMPLOYEE_ID) GV_MUAF_ENGELLI_KADIN,
				0 GV_MUAF_ENGELLI_ERKEK,
				0 SGK_MUAF_KADIN,
				0 SGK_MUAF_ERKEK,
				0 SGK_MUAF_ENGELLI_KADIN,
				0 SGK_MUAF_ENGELLI_ERKEK,
				0 ASGARI_UCRETLI_KADIN,
				0 ASGARI_UCRETLI_ERKEK,
				0 ASGARI_UCRETLI_ENGELLI_KADIN,
				0 ASGARI_UCRETLI_ENGELLI_ERKEK,
				0 DIGER_UCRETLI_KADIN,
				0 DIGER_UCRETLI_ERKEK,
				0 DIGER_UCRETLI_ENGELLI_KADIN,
				0 DIGER_UCRETLI_ENGELLI_ERKEK,
                B.BRANCH_ID
			FROM 
				EMPLOYEES_PUANTAJ_ROWS EPR
				INNER JOIN EMPLOYEES_PUANTAJ EP ON EP.PUANTAJ_ID = EPR.PUANTAJ_ID
				INNER JOIN EMPLOYEES_IN_OUT EIO ON EIO.IN_OUT_ID = EPR.IN_OUT_ID
				INNER JOIN DEPARTMENT D ON D.DEPARTMENT_ID = EPR.DEPARTMENT_ID
				INNER JOIN BRANCH B ON B.BRANCH_ID = D.BRANCH_ID
				INNER JOIN EMPLOYEES_DETAIL ED ON ED.EMPLOYEE_ID = EPR.EMPLOYEE_ID
			WHERE
				ED.SEX = 0
				AND EIO.DEFECTION_LEVEL > 0
				AND EIO.IS_TAX_FREE = 1
				<cfif not session.ep.ehesap>
					AND B.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">)
				</cfif>
				
			GROUP BY
				B.BRANCH_CITY,B.SSK_M,B.SSK_JOB,B.SSK_BRANCH,B.SSK_BRANCH_OLD,B.SSK_NO,B.SSK_CITY,B.SSK_COUNTRY,B.SSK_CD,B.SSK_AGENT,
				EP.SAL_YEAR,
				EP.SAL_MON,
                B.BRANCH_ID
			UNION ALL
			SELECT 
				B.BRANCH_CITY,
				EP.SAL_MON,
				EP.SAL_YEAR,
				B.SSK_M + B.SSK_JOB+B.SSK_BRANCH+B.SSK_BRANCH_OLD+B.SSK_NO+B.SSK_CITY+B.SSK_COUNTRY+B.SSK_CD+B.SSK_AGENT AS SGK_NO,
				0 GV_MUAF_KADIN,
				0 GV_MUAF_ERKEK,
				0 GV_MUAF_ENGELLI_KADIN,
				COUNT(EPR.EMPLOYEE_ID) GV_MUAF_ENGELLI_ERKEK,
				0 SGK_MUAF_KADIN,
				0 SGK_MUAF_ERKEK,
				0 SGK_MUAF_ENGELLI_KADIN,
				0 SGK_MUAF_ENGELLI_ERKEK,
				0 ASGARI_UCRETLI_KADIN,
				0 ASGARI_UCRETLI_ERKEK,
				0 ASGARI_UCRETLI_ENGELLI_KADIN,
				0 ASGARI_UCRETLI_ENGELLI_ERKEK,
				0 DIGER_UCRETLI_KADIN,
				0 DIGER_UCRETLI_ERKEK,
				0 DIGER_UCRETLI_ENGELLI_KADIN,
				0 DIGER_UCRETLI_ENGELLI_ERKEK,
                B.BRANCH_ID
			FROM 
				EMPLOYEES_PUANTAJ_ROWS EPR
				INNER JOIN EMPLOYEES_PUANTAJ EP ON EP.PUANTAJ_ID = EPR.PUANTAJ_ID
				INNER JOIN EMPLOYEES_IN_OUT EIO ON EIO.IN_OUT_ID = EPR.IN_OUT_ID
				INNER JOIN DEPARTMENT D ON D.DEPARTMENT_ID = EPR.DEPARTMENT_ID
				INNER JOIN BRANCH B ON B.BRANCH_ID = D.BRANCH_ID
				INNER JOIN EMPLOYEES_DETAIL ED ON ED.EMPLOYEE_ID = EPR.EMPLOYEE_ID
			WHERE
				ED.SEX = 1
				AND EIO.DEFECTION_LEVEL > 0
				AND EIO.IS_TAX_FREE = 1
				<cfif not session.ep.ehesap>
					AND B.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">)
				</cfif>
				
			GROUP BY
				B.BRANCH_CITY,B.SSK_M,B.SSK_JOB,B.SSK_BRANCH,B.SSK_BRANCH_OLD,B.SSK_NO,B.SSK_CITY,B.SSK_COUNTRY,B.SSK_CD,B.SSK_AGENT,
				EP.SAL_YEAR,
				EP.SAL_MON,
                B.BRANCH_ID
			UNION ALL
			SELECT 
				B.BRANCH_CITY,
				EP.SAL_MON,
				EP.SAL_YEAR,
				B.SSK_M + B.SSK_JOB+B.SSK_BRANCH+B.SSK_BRANCH_OLD+B.SSK_NO+B.SSK_CITY+B.SSK_COUNTRY+B.SSK_CD+B.SSK_AGENT AS SGK_NO,
				0 GV_MUAF_KADIN,
				0 GV_MUAF_ERKEK,
				0 GV_MUAF_ENGELLI_KADIN,
				0 GV_MUAF_ENGELLI_ERKEK,
				COUNT(EPR.EMPLOYEE_ID) SGK_MUAF_KADIN,
				0 SGK_MUAF_ERKEK,
				0 SGK_MUAF_ENGELLI_KADIN,
				0 SGK_MUAF_ENGELLI_ERKEK,
				0 ASGARI_UCRETLI_KADIN,
				0 ASGARI_UCRETLI_ERKEK,
				0 ASGARI_UCRETLI_ENGELLI_KADIN,
				0 ASGARI_UCRETLI_ENGELLI_ERKEK,
				0 DIGER_UCRETLI_KADIN,
				0 DIGER_UCRETLI_ERKEK,
				0 DIGER_UCRETLI_ENGELLI_KADIN,
				0 DIGER_UCRETLI_ENGELLI_ERKEK,
                B.BRANCH_ID
			FROM 
				EMPLOYEES_PUANTAJ_ROWS EPR
				INNER JOIN EMPLOYEES_PUANTAJ EP ON EP.PUANTAJ_ID = EPR.PUANTAJ_ID
				INNER JOIN EMPLOYEES_IN_OUT EIO ON EIO.IN_OUT_ID = EPR.IN_OUT_ID
				INNER JOIN DEPARTMENT D ON D.DEPARTMENT_ID = EPR.DEPARTMENT_ID
				INNER JOIN BRANCH B ON B.BRANCH_ID = D.BRANCH_ID
				INNER JOIN EMPLOYEES_DETAIL ED ON ED.EMPLOYEE_ID = EPR.EMPLOYEE_ID
			WHERE
				ED.SEX = 0
				AND EIO.USE_SSK = 0
				<cfif not session.ep.ehesap>
					AND B.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">)
				</cfif>
				
			GROUP BY
				B.BRANCH_CITY,B.SSK_M,B.SSK_JOB,B.SSK_BRANCH,B.SSK_BRANCH_OLD,B.SSK_NO,B.SSK_CITY,B.SSK_COUNTRY,B.SSK_CD,B.SSK_AGENT,
				EP.SAL_YEAR,
				EP.SAL_MON,
                B.BRANCH_ID
			UNION ALL
			SELECT 
				B.BRANCH_CITY,
				EP.SAL_MON,
				EP.SAL_YEAR,
				B.SSK_M + B.SSK_JOB+B.SSK_BRANCH+B.SSK_BRANCH_OLD+B.SSK_NO+B.SSK_CITY+B.SSK_COUNTRY+B.SSK_CD+B.SSK_AGENT AS SGK_NO,
				0 GV_MUAF_KADIN,
				0 GV_MUAF_ERKEK,
				0 GV_MUAF_ENGELLI_KADIN,
				0 GV_MUAF_ENGELLI_ERKEK,
				0 SGK_MUAF_KADIN,
				COUNT(EPR.EMPLOYEE_ID) SGK_MUAF_ERKEK,
				0 SGK_MUAF_ENGELLI_KADIN,
				0 SGK_MUAF_ENGELLI_ERKEK,
				0 ASGARI_UCRETLI_KADIN,
				0 ASGARI_UCRETLI_ERKEK,
				0 ASGARI_UCRETLI_ENGELLI_KADIN,
				0 ASGARI_UCRETLI_ENGELLI_ERKEK,
				0 DIGER_UCRETLI_KADIN,
				0 DIGER_UCRETLI_ERKEK,
				0 DIGER_UCRETLI_ENGELLI_KADIN,
				0 DIGER_UCRETLI_ENGELLI_ERKEK,
                B.BRANCH_ID
			FROM 
				EMPLOYEES_PUANTAJ_ROWS EPR
				INNER JOIN EMPLOYEES_PUANTAJ EP ON EP.PUANTAJ_ID = EPR.PUANTAJ_ID
				INNER JOIN EMPLOYEES_IN_OUT EIO ON EIO.IN_OUT_ID = EPR.IN_OUT_ID
				INNER JOIN DEPARTMENT D ON D.DEPARTMENT_ID = EPR.DEPARTMENT_ID
				INNER JOIN BRANCH B ON B.BRANCH_ID = D.BRANCH_ID
				INNER JOIN EMPLOYEES_DETAIL ED ON ED.EMPLOYEE_ID = EPR.EMPLOYEE_ID
			WHERE
				ED.SEX = 1
				AND EIO.USE_SSK = 0
				<cfif not session.ep.ehesap>
					AND B.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">)
				</cfif>
				
			GROUP BY
				B.BRANCH_CITY,B.SSK_M,B.SSK_JOB,B.SSK_BRANCH,B.SSK_BRANCH_OLD,B.SSK_NO,B.SSK_CITY,B.SSK_COUNTRY,B.SSK_CD,B.SSK_AGENT,
				EP.SAL_YEAR,
				EP.SAL_MON,
                B.BRANCH_ID
			UNION ALL
			SELECT 
				B.BRANCH_CITY,
				EP.SAL_MON,
				EP.SAL_YEAR,
				B.SSK_M + B.SSK_JOB+B.SSK_BRANCH+B.SSK_BRANCH_OLD+B.SSK_NO+B.SSK_CITY+B.SSK_COUNTRY+B.SSK_CD+B.SSK_AGENT AS SGK_NO,
				0 GV_MUAF_KADIN,
				0 GV_MUAF_ERKEK,
				0 GV_MUAF_ENGELLI_KADIN,
				0 GV_MUAF_ENGELLI_ERKEK,
				0 SGK_MUAF_KADIN,
				0 SGK_MUAF_ERKEK,
				COUNT(EPR.EMPLOYEE_ID) SGK_MUAF_ENGELLI_KADIN,
				0 SGK_MUAF_ENGELLI_ERKEK,
				0 ASGARI_UCRETLI_KADIN,
				0 ASGARI_UCRETLI_ERKEK,
				0 ASGARI_UCRETLI_ENGELLI_KADIN,
				0 ASGARI_UCRETLI_ENGELLI_ERKEK,
				0 DIGER_UCRETLI_KADIN,
				0 DIGER_UCRETLI_ERKEK,
				0 DIGER_UCRETLI_ENGELLI_KADIN,
				0 DIGER_UCRETLI_ENGELLI_ERKEK,
                B.BRANCH_ID
			FROM 
				EMPLOYEES_PUANTAJ_ROWS EPR
				INNER JOIN EMPLOYEES_PUANTAJ EP ON EP.PUANTAJ_ID = EPR.PUANTAJ_ID
				INNER JOIN EMPLOYEES_IN_OUT EIO ON EIO.IN_OUT_ID = EPR.IN_OUT_ID
				INNER JOIN DEPARTMENT D ON D.DEPARTMENT_ID = EPR.DEPARTMENT_ID
				INNER JOIN BRANCH B ON B.BRANCH_ID = D.BRANCH_ID
				INNER JOIN EMPLOYEES_DETAIL ED ON ED.EMPLOYEE_ID = EPR.EMPLOYEE_ID
			WHERE
				ED.SEX = 0
				AND EIO.DEFECTION_LEVEL > 0
				AND EIO.USE_SSK = 0
				<cfif not session.ep.ehesap>
					AND B.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">)
				</cfif>
				
			GROUP BY
				B.BRANCH_CITY,B.SSK_M,B.SSK_JOB,B.SSK_BRANCH,B.SSK_BRANCH_OLD,B.SSK_NO,B.SSK_CITY,B.SSK_COUNTRY,B.SSK_CD,B.SSK_AGENT,
				EP.SAL_YEAR,
				EP.SAL_MON,
                B.BRANCH_ID
			UNION ALL
			SELECT 
				B.BRANCH_CITY,
				EP.SAL_MON,
				EP.SAL_YEAR,
				B.SSK_M + B.SSK_JOB+B.SSK_BRANCH+B.SSK_BRANCH_OLD+B.SSK_NO+B.SSK_CITY+B.SSK_COUNTRY+B.SSK_CD+B.SSK_AGENT AS SGK_NO,
				0 GV_MUAF_KADIN,
				0 GV_MUAF_ERKEK,
				0 GV_MUAF_ENGELLI_KADIN,
				0 GV_MUAF_ENGELLI_ERKEK,
				0 SGK_MUAF_KADIN,
				0 SGK_MUAF_ERKEK,
				0 SGK_MUAF_ENGELLI_KADIN,
				COUNT(EPR.EMPLOYEE_ID) SGK_MUAF_ENGELLI_ERKEK,
				0 ASGARI_UCRETLI_KADIN,
				0 ASGARI_UCRETLI_ERKEK,
				0 ASGARI_UCRETLI_ENGELLI_KADIN,
				0 ASGARI_UCRETLI_ENGELLI_ERKEK,
				0 DIGER_UCRETLI_KADIN,
				0 DIGER_UCRETLI_ERKEK,
				0 DIGER_UCRETLI_ENGELLI_KADIN,
				0 DIGER_UCRETLI_ENGELLI_ERKEK,
                B.BRANCH_ID
			FROM 
				EMPLOYEES_PUANTAJ_ROWS EPR
				INNER JOIN EMPLOYEES_PUANTAJ EP ON EP.PUANTAJ_ID = EPR.PUANTAJ_ID
				INNER JOIN EMPLOYEES_IN_OUT EIO ON EIO.IN_OUT_ID = EPR.IN_OUT_ID
				INNER JOIN DEPARTMENT D ON D.DEPARTMENT_ID = EPR.DEPARTMENT_ID
				INNER JOIN BRANCH B ON B.BRANCH_ID = D.BRANCH_ID
				INNER JOIN EMPLOYEES_DETAIL ED ON ED.EMPLOYEE_ID = EPR.EMPLOYEE_ID
			WHERE
				ED.SEX = 1
				AND EIO.DEFECTION_LEVEL > 0
				AND EIO.USE_SSK = 0
				<cfif not session.ep.ehesap>
					AND B.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">)
				</cfif>
			
			GROUP BY
				B.BRANCH_CITY,B.SSK_M,B.SSK_JOB,B.SSK_BRANCH,B.SSK_BRANCH_OLD,B.SSK_NO,B.SSK_CITY,B.SSK_COUNTRY,B.SSK_CD,B.SSK_AGENT,
				EP.SAL_YEAR,
				EP.SAL_MON,
                B.BRANCH_ID
			UNION ALL
			SELECT 
				B.BRANCH_CITY,
				EP.SAL_MON,
				EP.SAL_YEAR,
				B.SSK_M + B.SSK_JOB+B.SSK_BRANCH+B.SSK_BRANCH_OLD+B.SSK_NO+B.SSK_CITY+B.SSK_COUNTRY+B.SSK_CD+B.SSK_AGENT AS SGK_NO,
				0 GV_MUAF_KADIN,
				0 GV_MUAF_ERKEK,
				0 GV_MUAF_ENGELLI_KADIN,
				0 GV_MUAF_ENGELLI_ERKEK,
				0 SGK_MUAF_KADIN,
				0 SGK_MUAF_ERKEK,
				0 SGK_MUAF_ENGELLI_KADIN,
				0 SGK_MUAF_ENGELLI_ERKEK,
				COUNT(EPR.EMPLOYEE_ID) ASGARI_UCRETLI_KADIN,
				0 ASGARI_UCRETLI_ERKEK,
				0 ASGARI_UCRETLI_ENGELLI_KADIN,
				0 ASGARI_UCRETLI_ENGELLI_ERKEK,
				0 DIGER_UCRETLI_KADIN,
				0 DIGER_UCRETLI_ERKEK,
				0 DIGER_UCRETLI_ENGELLI_KADIN,
				0 DIGER_UCRETLI_ENGELLI_ERKEK,
                B.BRANCH_ID
			FROM 
				EMPLOYEES_PUANTAJ_ROWS EPR
				INNER JOIN EMPLOYEES_PUANTAJ EP ON EP.PUANTAJ_ID = EPR.PUANTAJ_ID
				INNER JOIN EMPLOYEES_IN_OUT EIO ON EIO.IN_OUT_ID = EPR.IN_OUT_ID
				INNER JOIN EMPLOYEES_SALARY ES ON ES.IN_OUT_ID = EIO.IN_OUT_ID
				INNER JOIN DEPARTMENT D ON D.DEPARTMENT_ID = EPR.DEPARTMENT_ID
				INNER JOIN BRANCH B ON B.BRANCH_ID = D.BRANCH_ID
				INNER JOIN EMPLOYEES_DETAIL ED ON ED.EMPLOYEE_ID = EPR.EMPLOYEE_ID
				INNER JOIN OUR_COMPANY_HOURS OCH ON OCH.OUR_COMPANY_ID = B.COMPANY_ID
			WHERE
				ED.SEX = 0
				AND ES.PERIOD_YEAR = EP.SAL_YEAR
				AND EIO.DUTY_TYPE <> 8
				<cfif not session.ep.ehesap>
					AND B.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">)
				</cfif>
				AND 
				(
					(EPR.GROSS_NET = 0 AND (SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) = 
					CASE 
					WHEN EP.SAL_MON = 1 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M1 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M1 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M1 END
					WHEN EP.SAL_MON = 2 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M2 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M2 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M2 END
					WHEN EP.SAL_MON = 3 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M3 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M3 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M3 END
					WHEN EP.SAL_MON = 4 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M4 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M4 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M4 END
					WHEN EP.SAL_MON = 5 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M5 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M5 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M5 END
					WHEN EP.SAL_MON = 6 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M6 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M6 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M6 END
					WHEN EP.SAL_MON = 7 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M7 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M7 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M7 END
					WHEN EP.SAL_MON = 8 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M8 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M8 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M8 END
					WHEN EP.SAL_MON = 9 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M9 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M9 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M9 END
					WHEN EP.SAL_MON = 10 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M10 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M10 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M10 END
					WHEN EP.SAL_MON = 11 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M11 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M11 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M11 END
					WHEN EP.SAL_MON = 12 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M12 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M12 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M12 END
					END)
					OR
					(
						EPR.GROSS_NET <> 0 AND EPR.TOTAL_DAYS <> 0 AND
						(SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) = EPR.TOTAL_AMOUNT / EPR.TOTAL_DAYS * 30
					)
					OR
					(
						EPR.GROSS_NET <> 0 AND EPR.TOTAL_DAYS = 0 AND
						(SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) =
						CASE 
						WHEN EP.SAL_MON = 1 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M1 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M1 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M1 / 0.71491 END
						WHEN EP.SAL_MON = 2 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M2 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M2 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M2 / 0.71491 END
						WHEN EP.SAL_MON = 3 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M3 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M3 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M3 / 0.71491 END
						WHEN EP.SAL_MON = 4 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M4 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M4 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M4 / 0.71491 END
						WHEN EP.SAL_MON = 5 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M5 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M5 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M5 / 0.71491 END
						WHEN EP.SAL_MON = 6 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M6 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M6 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M6 / 0.71491 END
						WHEN EP.SAL_MON = 7 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M7 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M7 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M7 / 0.71491 END
						WHEN EP.SAL_MON = 8 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M8 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M8 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M8 / 0.71491 END
						WHEN EP.SAL_MON = 9 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M9 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M9 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M9 / 0.71491 END
						WHEN EP.SAL_MON = 10 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M10 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M10 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M10 / 0.71491 END
						WHEN EP.SAL_MON = 11 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M11 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M11 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M11 / 0.71491 END
						WHEN EP.SAL_MON = 12 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M12 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M12 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M12 / 0.71491 END
						END
					)
				)
				
			GROUP BY
				B.BRANCH_CITY,B.SSK_M,B.SSK_JOB,B.SSK_BRANCH,B.SSK_BRANCH_OLD,B.SSK_NO,B.SSK_CITY,B.SSK_COUNTRY,B.SSK_CD,B.SSK_AGENT,
				EP.SAL_YEAR,
				EP.SAL_MON,
                B.BRANCH_ID
			UNION ALL
			SELECT 
				B.BRANCH_CITY,
				EP.SAL_MON,
				EP.SAL_YEAR,
				B.SSK_M + B.SSK_JOB+B.SSK_BRANCH+B.SSK_BRANCH_OLD+B.SSK_NO+B.SSK_CITY+B.SSK_COUNTRY+B.SSK_CD+B.SSK_AGENT AS SGK_NO,
				0 GV_MUAF_KADIN,
				0 GV_MUAF_ERKEK,
				0 GV_MUAF_ENGELLI_KADIN,
				0 GV_MUAF_ENGELLI_ERKEK,
				0 SGK_MUAF_KADIN,
				0 SGK_MUAF_ERKEK,
				0 SGK_MUAF_ENGELLI_KADIN,
				0 SGK_MUAF_ENGELLI_ERKEK,
				0 ASGARI_UCRETLI_KADIN,
				COUNT(EPR.EMPLOYEE_ID) ASGARI_UCRETLI_ERKEK,
				0 ASGARI_UCRETLI_ENGELLI_KADIN,
				0 ASGARI_UCRETLI_ENGELLI_ERKEK,
				0 DIGER_UCRETLI_KADIN,
				0 DIGER_UCRETLI_ERKEK,
				0 DIGER_UCRETLI_ENGELLI_KADIN,
				0 DIGER_UCRETLI_ENGELLI_ERKEK,
                B.BRANCH_ID
			FROM 
				EMPLOYEES_PUANTAJ_ROWS EPR
				INNER JOIN EMPLOYEES_PUANTAJ EP ON EP.PUANTAJ_ID = EPR.PUANTAJ_ID
				INNER JOIN EMPLOYEES_IN_OUT EIO ON EIO.IN_OUT_ID = EPR.IN_OUT_ID
				INNER JOIN EMPLOYEES_SALARY ES ON ES.IN_OUT_ID = EIO.IN_OUT_ID
				INNER JOIN DEPARTMENT D ON D.DEPARTMENT_ID = EPR.DEPARTMENT_ID
				INNER JOIN BRANCH B ON B.BRANCH_ID = D.BRANCH_ID
				INNER JOIN EMPLOYEES_DETAIL ED ON ED.EMPLOYEE_ID = EPR.EMPLOYEE_ID
				INNER JOIN OUR_COMPANY_HOURS OCH ON OCH.OUR_COMPANY_ID = B.COMPANY_ID
			WHERE
				ED.SEX = 1
				AND ES.PERIOD_YEAR = EP.SAL_YEAR
				AND EIO.DUTY_TYPE <> 8
				<cfif not session.ep.ehesap>
					AND B.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">)
				</cfif>
				AND 
				(
					(EPR.GROSS_NET = 0 AND (SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) = 
					CASE 
					WHEN EP.SAL_MON = 1 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M1 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M1 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M1 END
					WHEN EP.SAL_MON = 2 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M2 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M2 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M2 END
					WHEN EP.SAL_MON = 3 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M3 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M3 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M3 END
					WHEN EP.SAL_MON = 4 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M4 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M4 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M4 END
					WHEN EP.SAL_MON = 5 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M5 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M5 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M5 END
					WHEN EP.SAL_MON = 6 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M6 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M6 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M6 END
					WHEN EP.SAL_MON = 7 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M7 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M7 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M7 END
					WHEN EP.SAL_MON = 8 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M8 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M8 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M8 END
					WHEN EP.SAL_MON = 9 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M9 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M9 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M9 END
					WHEN EP.SAL_MON = 10 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M10 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M10 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M10 END
					WHEN EP.SAL_MON = 11 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M11 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M11 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M11 END
					WHEN EP.SAL_MON = 12 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M12 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M12 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M12 END
					END)
					OR
					(
						EPR.GROSS_NET <> 0 AND EPR.TOTAL_DAYS <> 0 AND
						(SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) = EPR.TOTAL_AMOUNT / EPR.TOTAL_DAYS * 30
					)
					OR
					(
						EPR.GROSS_NET <> 0 AND EPR.TOTAL_DAYS = 0 AND
						(SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) =
						CASE 
						WHEN EP.SAL_MON = 1 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M1 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M1 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M1 / 0.71491 END
						WHEN EP.SAL_MON = 2 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M2 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M2 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M2 / 0.71491 END
						WHEN EP.SAL_MON = 3 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M3 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M3 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M3 / 0.71491 END
						WHEN EP.SAL_MON = 4 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M4 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M4 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M4 / 0.71491 END
						WHEN EP.SAL_MON = 5 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M5 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M5 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M5 / 0.71491 END
						WHEN EP.SAL_MON = 6 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M6 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M6 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M6 / 0.71491 END
						WHEN EP.SAL_MON = 7 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M7 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M7 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M7 / 0.71491 END
						WHEN EP.SAL_MON = 8 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M8 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M8 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M8 / 0.71491 END
						WHEN EP.SAL_MON = 9 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M9 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M9 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M9 / 0.71491 END
						WHEN EP.SAL_MON = 10 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M10 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M10 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M10 / 0.71491 END
						WHEN EP.SAL_MON = 11 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M11 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M11 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M11 / 0.71491 END
						WHEN EP.SAL_MON = 12 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M12 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M12 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M12 / 0.71491 END
						END
					)
				)
				
			GROUP BY
				B.BRANCH_CITY,B.SSK_M,B.SSK_JOB,B.SSK_BRANCH,B.SSK_BRANCH_OLD,B.SSK_NO,B.SSK_CITY,B.SSK_COUNTRY,B.SSK_CD,B.SSK_AGENT,
				EP.SAL_YEAR,
				EP.SAL_MON,
                B.BRANCH_ID
			UNION ALL
			SELECT 
				B.BRANCH_CITY,
				EP.SAL_MON,
				EP.SAL_YEAR,
				B.SSK_M + B.SSK_JOB+B.SSK_BRANCH+B.SSK_BRANCH_OLD+B.SSK_NO+B.SSK_CITY+B.SSK_COUNTRY+B.SSK_CD+B.SSK_AGENT AS SGK_NO,
				0 GV_MUAF_KADIN,
				0 GV_MUAF_ERKEK,
				0 GV_MUAF_ENGELLI_KADIN,
				0 GV_MUAF_ENGELLI_ERKEK,
				0 SGK_MUAF_KADIN,
				0 SGK_MUAF_ERKEK,
				0 SGK_MUAF_ENGELLI_KADIN,
				0 SGK_MUAF_ENGELLI_ERKEK,
				0 ASGARI_UCRETLI_KADIN,
				0 ASGARI_UCRETLI_ERKEK,
				COUNT(EPR.EMPLOYEE_ID) ASGARI_UCRETLI_ENGELLI_KADIN,
				0 ASGARI_UCRETLI_ENGELLI_ERKEK,
				0 DIGER_UCRETLI_KADIN,
				0 DIGER_UCRETLI_ERKEK,
				0 DIGER_UCRETLI_ENGELLI_KADIN,
				0 DIGER_UCRETLI_ENGELLI_ERKEK,
                B.BRANCH_ID
			FROM 
				EMPLOYEES_PUANTAJ_ROWS EPR
				INNER JOIN EMPLOYEES_PUANTAJ EP ON EP.PUANTAJ_ID = EPR.PUANTAJ_ID
				INNER JOIN EMPLOYEES_IN_OUT EIO ON EIO.IN_OUT_ID = EPR.IN_OUT_ID
				INNER JOIN EMPLOYEES_SALARY ES ON ES.IN_OUT_ID = EIO.IN_OUT_ID
				INNER JOIN DEPARTMENT D ON D.DEPARTMENT_ID = EPR.DEPARTMENT_ID
				INNER JOIN BRANCH B ON B.BRANCH_ID = D.BRANCH_ID
				INNER JOIN EMPLOYEES_DETAIL ED ON ED.EMPLOYEE_ID = EPR.EMPLOYEE_ID
				INNER JOIN OUR_COMPANY_HOURS OCH ON OCH.OUR_COMPANY_ID = B.COMPANY_ID
			WHERE
				ED.SEX = 0
				AND EIO.DEFECTION_LEVEL > 0
				AND ES.PERIOD_YEAR = EP.SAL_YEAR
				AND EIO.DUTY_TYPE <> 8
				<cfif not session.ep.ehesap>
					AND B.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">)
				</cfif>
				AND 
				(
					(EPR.GROSS_NET = 0 AND (SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) = 
					CASE 
					WHEN EP.SAL_MON = 1 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M1 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M1 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M1 END
					WHEN EP.SAL_MON = 2 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M2 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M2 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M2 END
					WHEN EP.SAL_MON = 3 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M3 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M3 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M3 END
					WHEN EP.SAL_MON = 4 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M4 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M4 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M4 END
					WHEN EP.SAL_MON = 5 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M5 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M5 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M5 END
					WHEN EP.SAL_MON = 6 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M6 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M6 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M6 END
					WHEN EP.SAL_MON = 7 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M7 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M7 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M7 END
					WHEN EP.SAL_MON = 8 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M8 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M8 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M8 END
					WHEN EP.SAL_MON = 9 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M9 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M9 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M9 END
					WHEN EP.SAL_MON = 10 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M10 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M10 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M10 END
					WHEN EP.SAL_MON = 11 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M11 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M11 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M11 END
					WHEN EP.SAL_MON = 12 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M12 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M12 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M12 END
					END)
					OR
					(
						EPR.GROSS_NET <> 0 AND EPR.TOTAL_DAYS <> 0 AND
						(SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) = EPR.TOTAL_AMOUNT / EPR.TOTAL_DAYS * 30
					)
					OR
					(
						EPR.GROSS_NET <> 0 AND EPR.TOTAL_DAYS = 0 AND
						(SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) =
						CASE 
						WHEN EP.SAL_MON = 1 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M1 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M1 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M1 / 0.71491 END
						WHEN EP.SAL_MON = 2 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M2 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M2 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M2 / 0.71491 END
						WHEN EP.SAL_MON = 3 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M3 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M3 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M3 / 0.71491 END
						WHEN EP.SAL_MON = 4 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M4 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M4 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M4 / 0.71491 END
						WHEN EP.SAL_MON = 5 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M5 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M5 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M5 / 0.71491 END
						WHEN EP.SAL_MON = 6 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M6 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M6 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M6 / 0.71491 END
						WHEN EP.SAL_MON = 7 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M7 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M7 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M7 / 0.71491 END
						WHEN EP.SAL_MON = 8 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M8 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M8 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M8 / 0.71491 END
						WHEN EP.SAL_MON = 9 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M9 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M9 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M9 / 0.71491 END
						WHEN EP.SAL_MON = 10 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M10 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M10 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M10 / 0.71491 END
						WHEN EP.SAL_MON = 11 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M11 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M11 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M11 / 0.71491 END
						WHEN EP.SAL_MON = 12 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M12 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M12 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M12 / 0.71491 END
						END
					)
				)
				
			GROUP BY
				B.BRANCH_CITY,B.SSK_M,B.SSK_JOB,B.SSK_BRANCH,B.SSK_BRANCH_OLD,B.SSK_NO,B.SSK_CITY,B.SSK_COUNTRY,B.SSK_CD,B.SSK_AGENT,
				EP.SAL_YEAR,
				EP.SAL_MON,
                B.BRANCH_ID
			UNION ALL
			SELECT 
				B.BRANCH_CITY,
				EP.SAL_MON,
				EP.SAL_YEAR,
				B.SSK_M + B.SSK_JOB+B.SSK_BRANCH+B.SSK_BRANCH_OLD+B.SSK_NO+B.SSK_CITY+B.SSK_COUNTRY+B.SSK_CD+B.SSK_AGENT AS SGK_NO,
				0 GV_MUAF_KADIN,
				0 GV_MUAF_ERKEK,
				0 GV_MUAF_ENGELLI_KADIN,
				0 GV_MUAF_ENGELLI_ERKEK,
				0 SGK_MUAF_KADIN,
				0 SGK_MUAF_ERKEK,
				0 SGK_MUAF_ENGELLI_KADIN,
				0 SGK_MUAF_ENGELLI_ERKEK,
				0 ASGARI_UCRETLI_KADIN,
				0 ASGARI_UCRETLI_ERKEK,
				0 ASGARI_UCRETLI_ENGELLI_KADIN,
				COUNT(EPR.EMPLOYEE_ID) ASGARI_UCRETLI_ENGELLI_ERKEK,
				0 DIGER_UCRETLI_KADIN,
				0 DIGER_UCRETLI_ERKEK,
				0 DIGER_UCRETLI_ENGELLI_KADIN,
				0 DIGER_UCRETLI_ENGELLI_ERKEK,
                B.BRANCH_ID
			FROM 
				EMPLOYEES_PUANTAJ_ROWS EPR
				INNER JOIN EMPLOYEES_PUANTAJ EP ON EP.PUANTAJ_ID = EPR.PUANTAJ_ID
				INNER JOIN EMPLOYEES_IN_OUT EIO ON EIO.IN_OUT_ID = EPR.IN_OUT_ID
				INNER JOIN EMPLOYEES_SALARY ES ON ES.IN_OUT_ID = EIO.IN_OUT_ID
				INNER JOIN DEPARTMENT D ON D.DEPARTMENT_ID = EPR.DEPARTMENT_ID
				INNER JOIN BRANCH B ON B.BRANCH_ID = D.BRANCH_ID
				INNER JOIN EMPLOYEES_DETAIL ED ON ED.EMPLOYEE_ID = EPR.EMPLOYEE_ID
				INNER JOIN OUR_COMPANY_HOURS OCH ON OCH.OUR_COMPANY_ID = B.COMPANY_ID
			WHERE
				ED.SEX = 1
				AND EIO.DEFECTION_LEVEL > 0
				AND ES.PERIOD_YEAR = EP.SAL_YEAR
				AND EIO.DUTY_TYPE <> 8
				<cfif not session.ep.ehesap>
					AND B.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">)
				</cfif>
				AND 
				(
					(EPR.GROSS_NET = 0 AND (SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) = 
					CASE 
					WHEN EP.SAL_MON = 1 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M1 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M1 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M1 END
					WHEN EP.SAL_MON = 2 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M2 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M2 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M2 END
					WHEN EP.SAL_MON = 3 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M3 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M3 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M3 END
					WHEN EP.SAL_MON = 4 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M4 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M4 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M4 END
					WHEN EP.SAL_MON = 5 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M5 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M5 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M5 END
					WHEN EP.SAL_MON = 6 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M6 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M6 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M6 END
					WHEN EP.SAL_MON = 7 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M7 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M7 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M7 END
					WHEN EP.SAL_MON = 8 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M8 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M8 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M8 END
					WHEN EP.SAL_MON = 9 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M9 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M9 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M9 END
					WHEN EP.SAL_MON = 10 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M10 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M10 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M10 END
					WHEN EP.SAL_MON = 11 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M11 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M11 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M11 END
					WHEN EP.SAL_MON = 12 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M12 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M12 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M12 END
					END)
					OR
					(
						EPR.GROSS_NET <> 0 AND EPR.TOTAL_DAYS <> 0 AND
						(SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) = EPR.TOTAL_AMOUNT / EPR.TOTAL_DAYS * 30
					)
					OR
					(
						EPR.GROSS_NET <> 0 AND EPR.TOTAL_DAYS = 0 AND
						(SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) =
						CASE 
						WHEN EP.SAL_MON = 1 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M1 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M1 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M1 / 0.71491 END
						WHEN EP.SAL_MON = 2 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M2 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M2 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M2 / 0.71491 END
						WHEN EP.SAL_MON = 3 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M3 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M3 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M3 / 0.71491 END
						WHEN EP.SAL_MON = 4 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M4 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M4 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M4 / 0.71491 END
						WHEN EP.SAL_MON = 5 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M5 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M5 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M5 / 0.71491 END
						WHEN EP.SAL_MON = 6 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M6 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M6 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M6 / 0.71491 END
						WHEN EP.SAL_MON = 7 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M7 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M7 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M7 / 0.71491 END
						WHEN EP.SAL_MON = 8 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M8 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M8 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M8 / 0.71491 END
						WHEN EP.SAL_MON = 9 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M9 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M9 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M9 / 0.71491 END
						WHEN EP.SAL_MON = 10 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M10 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M10 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M10 / 0.71491 END
						WHEN EP.SAL_MON = 11 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M11 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M11 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M11 / 0.71491 END
						WHEN EP.SAL_MON = 12 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M12 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M12 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M12 / 0.71491 END
						END
					)
				)
				
			GROUP BY
				B.BRANCH_CITY,B.SSK_M,B.SSK_JOB,B.SSK_BRANCH,B.SSK_BRANCH_OLD,B.SSK_NO,B.SSK_CITY,B.SSK_COUNTRY,B.SSK_CD,B.SSK_AGENT,
				EP.SAL_YEAR,
				EP.SAL_MON,
                B.BRANCH_ID
			UNION ALL
			SELECT 
				B.BRANCH_CITY,
				EP.SAL_MON,
				EP.SAL_YEAR,
				B.SSK_M + B.SSK_JOB+B.SSK_BRANCH+B.SSK_BRANCH_OLD+B.SSK_NO+B.SSK_CITY+B.SSK_COUNTRY+B.SSK_CD+B.SSK_AGENT AS SGK_NO,
				0 GV_MUAF_KADIN,
				0 GV_MUAF_ERKEK,
				0 GV_MUAF_ENGELLI_KADIN,
				0 GV_MUAF_ENGELLI_ERKEK,
				0 SGK_MUAF_KADIN,
				0 SGK_MUAF_ERKEK,
				0 SGK_MUAF_ENGELLI_KADIN,
				0 SGK_MUAF_ENGELLI_ERKEK,
				0 ASGARI_UCRETLI_KADIN,
				0 ASGARI_UCRETLI_ERKEK,
				0 ASGARI_UCRETLI_ENGELLI_KADIN,
				0 ASGARI_UCRETLI_ENGELLI_ERKEK,
				COUNT(EPR.EMPLOYEE_ID) DIGER_UCRETLI_KADIN,
				0 DIGER_UCRETLI_ERKEK,
				0 DIGER_UCRETLI_ENGELLI_KADIN,
				0 DIGER_UCRETLI_ENGELLI_ERKEK,
                B.BRANCH_ID
			FROM 
				EMPLOYEES_PUANTAJ_ROWS EPR
				INNER JOIN EMPLOYEES_PUANTAJ EP ON EP.PUANTAJ_ID = EPR.PUANTAJ_ID
				INNER JOIN EMPLOYEES_IN_OUT EIO ON EIO.IN_OUT_ID = EPR.IN_OUT_ID
				INNER JOIN EMPLOYEES_SALARY ES ON ES.IN_OUT_ID = EIO.IN_OUT_ID
				INNER JOIN DEPARTMENT D ON D.DEPARTMENT_ID = EPR.DEPARTMENT_ID
				INNER JOIN BRANCH B ON B.BRANCH_ID = D.BRANCH_ID
				INNER JOIN EMPLOYEES_DETAIL ED ON ED.EMPLOYEE_ID = EPR.EMPLOYEE_ID
				INNER JOIN OUR_COMPANY_HOURS OCH ON OCH.OUR_COMPANY_ID = B.COMPANY_ID
			WHERE
				ED.SEX = 0
				AND ES.PERIOD_YEAR = EP.SAL_YEAR
				AND EIO.DUTY_TYPE <> 8
				<cfif not session.ep.ehesap>
					AND B.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">)
				</cfif>
				AND 
				(
					(EPR.GROSS_NET = 0 AND (SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) <> 
					CASE 
					WHEN EP.SAL_MON = 1 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M1 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M1 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M1 END
					WHEN EP.SAL_MON = 2 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M2 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M2 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M2 END
					WHEN EP.SAL_MON = 3 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M3 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M3 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M3 END
					WHEN EP.SAL_MON = 4 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M4 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M4 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M4 END
					WHEN EP.SAL_MON = 5 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M5 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M5 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M5 END
					WHEN EP.SAL_MON = 6 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M6 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M6 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M6 END
					WHEN EP.SAL_MON = 7 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M7 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M7 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M7 END
					WHEN EP.SAL_MON = 8 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M8 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M8 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M8 END
					WHEN EP.SAL_MON = 9 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M9 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M9 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M9 END
					WHEN EP.SAL_MON = 10 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M10 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M10 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M10 END
					WHEN EP.SAL_MON = 11 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M11 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M11 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M11 END
					WHEN EP.SAL_MON = 12 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M12 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M12 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M12 END
					END)
					OR
					(
						EPR.GROSS_NET <> 0 AND EPR.TOTAL_DAYS <> 0 AND
						(SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) <> EPR.TOTAL_AMOUNT / EPR.TOTAL_DAYS * 30
					)
					OR
					(
						EPR.GROSS_NET <> 0 AND EPR.TOTAL_DAYS = 0 AND
						(SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) <>
						CASE 
						WHEN EP.SAL_MON = 1 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M1 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M1 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M1 / 0.71491 END
						WHEN EP.SAL_MON = 2 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M2 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M2 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M2 / 0.71491 END
						WHEN EP.SAL_MON = 3 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M3 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M3 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M3 / 0.71491 END
						WHEN EP.SAL_MON = 4 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M4 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M4 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M4 / 0.71491 END
						WHEN EP.SAL_MON = 5 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M5 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M5 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M5 / 0.71491 END
						WHEN EP.SAL_MON = 6 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M6 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M6 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M6 / 0.71491 END
						WHEN EP.SAL_MON = 7 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M7 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M7 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M7 / 0.71491 END
						WHEN EP.SAL_MON = 8 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M8 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M8 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M8 / 0.71491 END
						WHEN EP.SAL_MON = 9 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M9 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M9 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M9 / 0.71491 END
						WHEN EP.SAL_MON = 10 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M10 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M10 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M10 / 0.71491 END
						WHEN EP.SAL_MON = 11 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M11 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M11 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M11 / 0.71491 END
						WHEN EP.SAL_MON = 12 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M12 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M12 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M12 / 0.71491 END
						END
					)
				)
				
			GROUP BY
				B.BRANCH_CITY,B.SSK_M,B.SSK_JOB,B.SSK_BRANCH,B.SSK_BRANCH_OLD,B.SSK_NO,B.SSK_CITY,B.SSK_COUNTRY,B.SSK_CD,B.SSK_AGENT,
				EP.SAL_YEAR,
				EP.SAL_MON,
                B.BRANCH_ID
			UNION ALL
			SELECT 
				B.BRANCH_CITY,
				EP.SAL_MON,
				EP.SAL_YEAR,
				B.SSK_M + B.SSK_JOB+B.SSK_BRANCH+B.SSK_BRANCH_OLD+B.SSK_NO+B.SSK_CITY+B.SSK_COUNTRY+B.SSK_CD+B.SSK_AGENT AS SGK_NO,
				0 GV_MUAF_KADIN,
				0 GV_MUAF_ERKEK,
				0 GV_MUAF_ENGELLI_KADIN,
				0 GV_MUAF_ENGELLI_ERKEK,
				0 SGK_MUAF_KADIN,
				0 SGK_MUAF_ERKEK,
				0 SGK_MUAF_ENGELLI_KADIN,
				0 SGK_MUAF_ENGELLI_ERKEK,
				0 ASGARI_UCRETLI_KADIN,
				0 ASGARI_UCRETLI_ERKEK,
				0 ASGARI_UCRETLI_ENGELLI_KADIN,
				0 ASGARI_UCRETLI_ENGELLI_ERKEK,
				COUNT(EPR.EMPLOYEE_ID) DIGER_UCRETLI_KADIN,
				0 DIGER_UCRETLI_ERKEK,
				0 DIGER_UCRETLI_ENGELLI_KADIN,
				0 DIGER_UCRETLI_ENGELLI_ERKEK,
                B.BRANCH_ID
			FROM 
				EMPLOYEES_PUANTAJ_ROWS EPR
				INNER JOIN EMPLOYEES_PUANTAJ EP ON EP.PUANTAJ_ID = EPR.PUANTAJ_ID
				INNER JOIN EMPLOYEES_IN_OUT EIO ON EIO.IN_OUT_ID = EPR.IN_OUT_ID
				INNER JOIN DEPARTMENT D ON D.DEPARTMENT_ID = EPR.DEPARTMENT_ID
				INNER JOIN BRANCH B ON B.BRANCH_ID = D.BRANCH_ID
				INNER JOIN EMPLOYEES_DETAIL ED ON ED.EMPLOYEE_ID = EPR.EMPLOYEE_ID
				INNER JOIN OUR_COMPANY_HOURS OCH ON OCH.OUR_COMPANY_ID = B.COMPANY_ID
			WHERE
				ED.SEX = 0
				AND EIO.DUTY_TYPE = 8
				AND (EIO.IS_TAX_FREE = 0 OR EIO.IS_TAX_FREE IS NULL)
				AND EIO.USE_SSK <> 0
				<cfif not session.ep.ehesap>
					AND B.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">)
				</cfif>
				
			GROUP BY
				B.BRANCH_CITY,B.SSK_M,B.SSK_JOB,B.SSK_BRANCH,B.SSK_BRANCH_OLD,B.SSK_NO,B.SSK_CITY,B.SSK_COUNTRY,B.SSK_CD,B.SSK_AGENT,
				EP.SAL_YEAR,
				EP.SAL_MON,
                B.BRANCH_ID
			UNION ALL
			SELECT 
				B.BRANCH_CITY,
				EP.SAL_MON,
				EP.SAL_YEAR,
				B.SSK_M + B.SSK_JOB+B.SSK_BRANCH+B.SSK_BRANCH_OLD+B.SSK_NO+B.SSK_CITY+B.SSK_COUNTRY+B.SSK_CD+B.SSK_AGENT AS SGK_NO,
				0 GV_MUAF_KADIN,
				0 GV_MUAF_ERKEK,
				0 GV_MUAF_ENGELLI_KADIN,
				0 GV_MUAF_ENGELLI_ERKEK,
				0 SGK_MUAF_KADIN,
				0 SGK_MUAF_ERKEK,
				0 SGK_MUAF_ENGELLI_KADIN,
				0 SGK_MUAF_ENGELLI_ERKEK,
				0 ASGARI_UCRETLI_KADIN,
				0 ASGARI_UCRETLI_ERKEK,
				0 ASGARI_UCRETLI_ENGELLI_KADIN,
				0 ASGARI_UCRETLI_ENGELLI_ERKEK,
				0 DIGER_UCRETLI_KADIN,
				COUNT(EPR.EMPLOYEE_ID) DIGER_UCRETLI_ERKEK,
				0 DIGER_UCRETLI_ENGELLI_KADIN,
				0 DIGER_UCRETLI_ENGELLI_ERKEK,
                B.BRANCH_ID
			FROM 
				EMPLOYEES_PUANTAJ_ROWS EPR
				INNER JOIN EMPLOYEES_PUANTAJ EP ON EP.PUANTAJ_ID = EPR.PUANTAJ_ID
				INNER JOIN EMPLOYEES_IN_OUT EIO ON EIO.IN_OUT_ID = EPR.IN_OUT_ID
				INNER JOIN EMPLOYEES_SALARY ES ON ES.IN_OUT_ID = EIO.IN_OUT_ID
				INNER JOIN DEPARTMENT D ON D.DEPARTMENT_ID = EPR.DEPARTMENT_ID
				INNER JOIN BRANCH B ON B.BRANCH_ID = D.BRANCH_ID
				INNER JOIN EMPLOYEES_DETAIL ED ON ED.EMPLOYEE_ID = EPR.EMPLOYEE_ID
				INNER JOIN OUR_COMPANY_HOURS OCH ON OCH.OUR_COMPANY_ID = B.COMPANY_ID
			WHERE
				ED.SEX = 1
				AND ES.PERIOD_YEAR = EP.SAL_YEAR
				AND EIO.DUTY_TYPE <> 8
				<cfif not session.ep.ehesap>
					AND B.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">)
				</cfif>
				AND 
				(
					(EPR.GROSS_NET = 0 AND (SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) <> 
					CASE 
					WHEN EP.SAL_MON = 1 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M1 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M1 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M1 END
					WHEN EP.SAL_MON = 2 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M2 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M2 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M2 END
					WHEN EP.SAL_MON = 3 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M3 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M3 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M3 END
					WHEN EP.SAL_MON = 4 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M4 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M4 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M4 END
					WHEN EP.SAL_MON = 5 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M5 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M5 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M5 END
					WHEN EP.SAL_MON = 6 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M6 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M6 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M6 END
					WHEN EP.SAL_MON = 7 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M7 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M7 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M7 END
					WHEN EP.SAL_MON = 8 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M8 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M8 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M8 END
					WHEN EP.SAL_MON = 9 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M9 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M9 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M9 END
					WHEN EP.SAL_MON = 10 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M10 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M10 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M10 END
					WHEN EP.SAL_MON = 11 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M11 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M11 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M11 END
					WHEN EP.SAL_MON = 12 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M12 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M12 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M12 END
					END)
					OR
					(
						EPR.GROSS_NET <> 0 AND EPR.TOTAL_DAYS <> 0 AND
						(SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) <> EPR.TOTAL_AMOUNT / EPR.TOTAL_DAYS * 30
					)
					OR
					(
						EPR.GROSS_NET <> 0 AND EPR.TOTAL_DAYS = 0 AND
						(SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) <>
						CASE 
						WHEN EP.SAL_MON = 1 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M1 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M1 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M1 / 0.71491 END
						WHEN EP.SAL_MON = 2 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M2 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M2 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M2 / 0.71491 END
						WHEN EP.SAL_MON = 3 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M3 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M3 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M3 / 0.71491 END
						WHEN EP.SAL_MON = 4 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M4 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M4 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M4 / 0.71491 END
						WHEN EP.SAL_MON = 5 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M5 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M5 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M5 / 0.71491 END
						WHEN EP.SAL_MON = 6 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M6 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M6 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M6 / 0.71491 END
						WHEN EP.SAL_MON = 7 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M7 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M7 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M7 / 0.71491 END
						WHEN EP.SAL_MON = 8 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M8 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M8 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M8 / 0.71491 END
						WHEN EP.SAL_MON = 9 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M9 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M9 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M9 / 0.71491 END
						WHEN EP.SAL_MON = 10 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M10 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M10 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M10 / 0.71491 END
						WHEN EP.SAL_MON = 11 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M11 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M11 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M11 / 0.71491 END
						WHEN EP.SAL_MON = 12 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M12 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M12 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M12 / 0.71491 END
						END
					)
				)
				
			GROUP BY
				B.BRANCH_CITY,B.SSK_M,B.SSK_JOB,B.SSK_BRANCH,B.SSK_BRANCH_OLD,B.SSK_NO,B.SSK_CITY,B.SSK_COUNTRY,B.SSK_CD,B.SSK_AGENT,
				EP.SAL_YEAR,
				EP.SAL_MON,
                B.BRANCH_ID
			UNION ALL
			SELECT 
				B.BRANCH_CITY,
				EP.SAL_MON,
				EP.SAL_YEAR,
				B.SSK_M + B.SSK_JOB+B.SSK_BRANCH+B.SSK_BRANCH_OLD+B.SSK_NO+B.SSK_CITY+B.SSK_COUNTRY+B.SSK_CD+B.SSK_AGENT AS SGK_NO,
				0 GV_MUAF_KADIN,
				0 GV_MUAF_ERKEK,
				0 GV_MUAF_ENGELLI_KADIN,
				0 GV_MUAF_ENGELLI_ERKEK,
				0 SGK_MUAF_KADIN,
				0 SGK_MUAF_ERKEK,
				0 SGK_MUAF_ENGELLI_KADIN,
				0 SGK_MUAF_ENGELLI_ERKEK,
				0 ASGARI_UCRETLI_KADIN,
				0 ASGARI_UCRETLI_ERKEK,
				0 ASGARI_UCRETLI_ENGELLI_KADIN,
				0 ASGARI_UCRETLI_ENGELLI_ERKEK,
				0 DIGER_UCRETLI_KADIN,
				COUNT(EPR.EMPLOYEE_ID) DIGER_UCRETLI_ERKEK,
				0 DIGER_UCRETLI_ENGELLI_KADIN,
				0 DIGER_UCRETLI_ENGELLI_ERKEK,
                B.BRANCH_ID
			FROM 
				EMPLOYEES_PUANTAJ_ROWS EPR
				INNER JOIN EMPLOYEES_PUANTAJ EP ON EP.PUANTAJ_ID = EPR.PUANTAJ_ID
				INNER JOIN EMPLOYEES_IN_OUT EIO ON EIO.IN_OUT_ID = EPR.IN_OUT_ID
				INNER JOIN DEPARTMENT D ON D.DEPARTMENT_ID = EPR.DEPARTMENT_ID
				INNER JOIN BRANCH B ON B.BRANCH_ID = D.BRANCH_ID
				INNER JOIN EMPLOYEES_DETAIL ED ON ED.EMPLOYEE_ID = EPR.EMPLOYEE_ID
				INNER JOIN OUR_COMPANY_HOURS OCH ON OCH.OUR_COMPANY_ID = B.COMPANY_ID
			WHERE
				ED.SEX = 1
				AND EIO.DUTY_TYPE = 8
				AND (EIO.IS_TAX_FREE = 0 OR EIO.IS_TAX_FREE IS NULL)
				AND EIO.USE_SSK <> 0
				<cfif not session.ep.ehesap>
					AND B.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">)
				</cfif>
				
			GROUP BY
				B.BRANCH_CITY,B.SSK_M,B.SSK_JOB,B.SSK_BRANCH,B.SSK_BRANCH_OLD,B.SSK_NO,B.SSK_CITY,B.SSK_COUNTRY,B.SSK_CD,B.SSK_AGENT,
				EP.SAL_YEAR,
				EP.SAL_MON,
                B.BRANCH_ID
			UNION ALL
			SELECT 
				B.BRANCH_CITY,
				EP.SAL_MON,
				EP.SAL_YEAR,
				B.SSK_M + B.SSK_JOB+B.SSK_BRANCH+B.SSK_BRANCH_OLD+B.SSK_NO+B.SSK_CITY+B.SSK_COUNTRY+B.SSK_CD+B.SSK_AGENT AS SGK_NO,
				0 GV_MUAF_KADIN,
				0 GV_MUAF_ERKEK,
				0 GV_MUAF_ENGELLI_KADIN,
				0 GV_MUAF_ENGELLI_ERKEK,
				0 SGK_MUAF_KADIN,
				0 SGK_MUAF_ERKEK,
				0 SGK_MUAF_ENGELLI_KADIN,
				0 SGK_MUAF_ENGELLI_ERKEK,
				0 ASGARI_UCRETLI_KADIN,
				0 ASGARI_UCRETLI_ERKEK,
				0 ASGARI_UCRETLI_ENGELLI_KADIN,
				0 ASGARI_UCRETLI_ENGELLI_ERKEK,
				0 DIGER_UCRETLI_KADIN,
				0 DIGER_UCRETLI_ERKEK,
				COUNT(EPR.EMPLOYEE_ID) DIGER_UCRETLI_ENGELLI_KADIN,
				0 DIGER_UCRETLI_ENGELLI_ERKEK,
                B.BRANCH_ID
			FROM 
				EMPLOYEES_PUANTAJ_ROWS EPR
				INNER JOIN EMPLOYEES_PUANTAJ EP ON EP.PUANTAJ_ID = EPR.PUANTAJ_ID
				INNER JOIN EMPLOYEES_IN_OUT EIO ON EIO.IN_OUT_ID = EPR.IN_OUT_ID
				INNER JOIN EMPLOYEES_SALARY ES ON ES.IN_OUT_ID = EIO.IN_OUT_ID
				INNER JOIN DEPARTMENT D ON D.DEPARTMENT_ID = EPR.DEPARTMENT_ID
				INNER JOIN BRANCH B ON B.BRANCH_ID = D.BRANCH_ID
				INNER JOIN EMPLOYEES_DETAIL ED ON ED.EMPLOYEE_ID = EPR.EMPLOYEE_ID
				INNER JOIN OUR_COMPANY_HOURS OCH ON OCH.OUR_COMPANY_ID = B.COMPANY_ID
			WHERE
				ED.SEX = 0
				AND EIO.DEFECTION_LEVEL > 0
				AND ES.PERIOD_YEAR = EP.SAL_YEAR
				AND EIO.DUTY_TYPE <> 8
				<cfif not session.ep.ehesap>
					AND B.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">)
				</cfif>
				AND 
				(
					(EPR.GROSS_NET = 0 AND (SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) <> 
					CASE 
					WHEN EP.SAL_MON = 1 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M1 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M1 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M1 END
					WHEN EP.SAL_MON = 2 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M2 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M2 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M2 END
					WHEN EP.SAL_MON = 3 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M3 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M3 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M3 END
					WHEN EP.SAL_MON = 4 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M4 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M4 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M4 END
					WHEN EP.SAL_MON = 5 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M5 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M5 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M5 END
					WHEN EP.SAL_MON = 6 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M6 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M6 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M6 END
					WHEN EP.SAL_MON = 7 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M7 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M7 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M7 END
					WHEN EP.SAL_MON = 8 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M8 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M8 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M8 END
					WHEN EP.SAL_MON = 9 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M9 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M9 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M9 END
					WHEN EP.SAL_MON = 10 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M10 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M10 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M10 END
					WHEN EP.SAL_MON = 11 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M11 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M11 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M11 END
					WHEN EP.SAL_MON = 12 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M12 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M12 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M12 END
					END)
					OR
					(
						EPR.GROSS_NET <> 0 AND EPR.TOTAL_DAYS <> 0 AND
						(SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) <> EPR.TOTAL_AMOUNT / EPR.TOTAL_DAYS * 30
					)
					OR
					(
						EPR.GROSS_NET <> 0 AND EPR.TOTAL_DAYS = 0 AND
						(SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) <>
						CASE 
						WHEN EP.SAL_MON = 1 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M1 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M1 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M1 / 0.71491 END
						WHEN EP.SAL_MON = 2 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M2 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M2 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M2 / 0.71491 END
						WHEN EP.SAL_MON = 3 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M3 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M3 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M3 / 0.71491 END
						WHEN EP.SAL_MON = 4 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M4 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M4 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M4 / 0.71491 END
						WHEN EP.SAL_MON = 5 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M5 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M5 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M5 / 0.71491 END
						WHEN EP.SAL_MON = 6 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M6 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M6 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M6 / 0.71491 END
						WHEN EP.SAL_MON = 7 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M7 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M7 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M7 / 0.71491 END
						WHEN EP.SAL_MON = 8 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M8 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M8 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M8 / 0.71491 END
						WHEN EP.SAL_MON = 9 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M9 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M9 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M9 / 0.71491 END
						WHEN EP.SAL_MON = 10 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M10 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M10 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M10 / 0.71491 END
						WHEN EP.SAL_MON = 11 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M11 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M11 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M11 / 0.71491 END
						WHEN EP.SAL_MON = 12 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M12 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M12 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M12 / 0.71491 END
						END
					)
				)
				
			GROUP BY
				B.BRANCH_CITY,B.SSK_M,B.SSK_JOB,B.SSK_BRANCH,B.SSK_BRANCH_OLD,B.SSK_NO,B.SSK_CITY,B.SSK_COUNTRY,B.SSK_CD,B.SSK_AGENT,
				EP.SAL_YEAR,
				EP.SAL_MON,
                B.BRANCH_ID
			UNION ALL
			SELECT 
				B.BRANCH_CITY,
				EP.SAL_MON,
				EP.SAL_YEAR,
				B.SSK_M + B.SSK_JOB+B.SSK_BRANCH+B.SSK_BRANCH_OLD+B.SSK_NO+B.SSK_CITY+B.SSK_COUNTRY+B.SSK_CD+B.SSK_AGENT AS SGK_NO,
				0 GV_MUAF_KADIN,
				0 GV_MUAF_ERKEK,
				0 GV_MUAF_ENGELLI_KADIN,
				0 GV_MUAF_ENGELLI_ERKEK,
				0 SGK_MUAF_KADIN,
				0 SGK_MUAF_ERKEK,
				0 SGK_MUAF_ENGELLI_KADIN,
				0 SGK_MUAF_ENGELLI_ERKEK,
				0 ASGARI_UCRETLI_KADIN,
				0 ASGARI_UCRETLI_ERKEK,
				0 ASGARI_UCRETLI_ENGELLI_KADIN,
				0 ASGARI_UCRETLI_ENGELLI_ERKEK,
				0 DIGER_UCRETLI_KADIN,
				0 DIGER_UCRETLI_ERKEK,
				COUNT(EPR.EMPLOYEE_ID) DIGER_UCRETLI_ENGELLI_KADIN,
				0 DIGER_UCRETLI_ENGELLI_ERKEK,
                B.BRANCH_ID
			FROM 
				EMPLOYEES_PUANTAJ_ROWS EPR
				INNER JOIN EMPLOYEES_PUANTAJ EP ON EP.PUANTAJ_ID = EPR.PUANTAJ_ID
				INNER JOIN EMPLOYEES_IN_OUT EIO ON EIO.IN_OUT_ID = EPR.IN_OUT_ID
				INNER JOIN DEPARTMENT D ON D.DEPARTMENT_ID = EPR.DEPARTMENT_ID
				INNER JOIN BRANCH B ON B.BRANCH_ID = D.BRANCH_ID
				INNER JOIN EMPLOYEES_DETAIL ED ON ED.EMPLOYEE_ID = EPR.EMPLOYEE_ID
				INNER JOIN OUR_COMPANY_HOURS OCH ON OCH.OUR_COMPANY_ID = B.COMPANY_ID
			WHERE
				ED.SEX = 0
				AND EIO.DEFECTION_LEVEL > 0
				AND EIO.DUTY_TYPE = 8
				AND (EIO.IS_TAX_FREE = 0 OR EIO.IS_TAX_FREE IS NULL)
				AND EIO.USE_SSK <> 0
				<cfif not session.ep.ehesap>
					AND B.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">)
				</cfif>
				
			GROUP BY
				B.BRANCH_CITY,B.SSK_M,B.SSK_JOB,B.SSK_BRANCH,B.SSK_BRANCH_OLD,B.SSK_NO,B.SSK_CITY,B.SSK_COUNTRY,B.SSK_CD,B.SSK_AGENT,
				EP.SAL_YEAR,
				EP.SAL_MON,
                B.BRANCH_ID
			UNION ALL
			SELECT 
				B.BRANCH_CITY,
				EP.SAL_MON,
				EP.SAL_YEAR,
				B.SSK_M + B.SSK_JOB+B.SSK_BRANCH+B.SSK_BRANCH_OLD+B.SSK_NO+B.SSK_CITY+B.SSK_COUNTRY+B.SSK_CD+B.SSK_AGENT AS SGK_NO,
				0 GV_MUAF_KADIN,
				0 GV_MUAF_ERKEK,
				0 GV_MUAF_ENGELLI_KADIN,
				0 GV_MUAF_ENGELLI_ERKEK,
				0 SGK_MUAF_KADIN,
				0 SGK_MUAF_ERKEK,
				0 SGK_MUAF_ENGELLI_KADIN,
				0 SGK_MUAF_ENGELLI_ERKEK,
				0 ASGARI_UCRETLI_KADIN,
				0 ASGARI_UCRETLI_ERKEK,
				0 ASGARI_UCRETLI_ENGELLI_KADIN,
				0 ASGARI_UCRETLI_ENGELLI_ERKEK,
				0 DIGER_UCRETLI_KADIN,
				0 DIGER_UCRETLI_ERKEK,
				0 DIGER_UCRETLI_ENGELLI_KADIN,
				COUNT(EPR.EMPLOYEE_ID) DIGER_UCRETLI_ENGELLI_ERKEK,
                B.BRANCH_ID
			FROM 
				EMPLOYEES_PUANTAJ_ROWS EPR
				INNER JOIN EMPLOYEES_PUANTAJ EP ON EP.PUANTAJ_ID = EPR.PUANTAJ_ID
				INNER JOIN EMPLOYEES_IN_OUT EIO ON EIO.IN_OUT_ID = EPR.IN_OUT_ID
				INNER JOIN EMPLOYEES_SALARY ES ON ES.IN_OUT_ID = EIO.IN_OUT_ID
				INNER JOIN DEPARTMENT D ON D.DEPARTMENT_ID = EPR.DEPARTMENT_ID
				INNER JOIN BRANCH B ON B.BRANCH_ID = D.BRANCH_ID
				INNER JOIN EMPLOYEES_DETAIL ED ON ED.EMPLOYEE_ID = EPR.EMPLOYEE_ID
				INNER JOIN OUR_COMPANY_HOURS OCH ON OCH.OUR_COMPANY_ID = B.COMPANY_ID
			WHERE
				ED.SEX = 1
				AND EIO.DEFECTION_LEVEL > 0
				AND ES.PERIOD_YEAR = EP.SAL_YEAR
				AND EIO.DUTY_TYPE <> 8
				<cfif not session.ep.ehesap>
					AND B.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">)
				</cfif>
				AND 
				(
					(EPR.GROSS_NET = 0 AND (SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) <> 
					CASE 
					WHEN EP.SAL_MON = 1 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M1 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M1 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M1 END
					WHEN EP.SAL_MON = 2 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M2 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M2 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M2 END
					WHEN EP.SAL_MON = 3 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M3 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M3 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M3 END
					WHEN EP.SAL_MON = 4 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M4 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M4 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M4 END
					WHEN EP.SAL_MON = 5 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M5 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M5 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M5 END
					WHEN EP.SAL_MON = 6 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M6 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M6 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M6 END
					WHEN EP.SAL_MON = 7 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M7 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M7 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M7 END
					WHEN EP.SAL_MON = 8 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M8 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M8 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M8 END
					WHEN EP.SAL_MON = 9 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M9 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M9 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M9 END
					WHEN EP.SAL_MON = 10 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M10 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M10 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M10 END
					WHEN EP.SAL_MON = 11 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M11 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M11 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M11 END
					WHEN EP.SAL_MON = 12 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M12 * OCH.SSK_MONTHLY_WORK_HOURS WHEN EPR.SALARY_TYPE = 1 THEN ES.M12 * 30 WHEN EPR.SALARY_TYPE = 2 THEN ES.M12 END
					END)
					OR
					(
						EPR.GROSS_NET <> 0 AND EPR.TOTAL_DAYS <> 0 AND
						(SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) <> EPR.TOTAL_AMOUNT / EPR.TOTAL_DAYS * 30
					)
					OR
					(
						EPR.GROSS_NET <> 0 AND EPR.TOTAL_DAYS = 0 AND
						(SELECT TOP 1 MIN_GROSS_PAYMENT_NORMAL FROM INSURANCE_PAYMENT WHERE (
						(EP.SAL_YEAR > YEAR(STARTDATE) AND EP.SAL_YEAR < YEAR(FINISHDATE)) OR
						(EP.SAL_YEAR = YEAR(STARTDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR (EP.SAL_YEAR > YEAR(STARTDATE) AND (EP.SAL_YEAR < YEAR(FINISHDATE) OR (EP.SAL_MON <= MONTH(FINISHDATE) AND EP.SAL_YEAR = YEAR(FINISHDATE))))
						OR(EP.SAL_YEAR = YEAR(FINISHDATE) AND EP.SAL_MON >= MONTH(STARTDATE) AND SAL_MON <= MONTH(FINISHDATE)))) <>
						CASE 
						WHEN EP.SAL_MON = 1 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M1 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M1 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M1 / 0.71491 END
						WHEN EP.SAL_MON = 2 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M2 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M2 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M2 / 0.71491 END
						WHEN EP.SAL_MON = 3 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M3 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M3 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M3 / 0.71491 END
						WHEN EP.SAL_MON = 4 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M4 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M4 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M4 / 0.71491 END
						WHEN EP.SAL_MON = 5 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M5 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M5 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M5 / 0.71491 END
						WHEN EP.SAL_MON = 6 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M6 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M6 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M6 / 0.71491 END
						WHEN EP.SAL_MON = 7 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M7 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M7 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M7 / 0.71491 END
						WHEN EP.SAL_MON = 8 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M8 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M8 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M8 / 0.71491 END
						WHEN EP.SAL_MON = 9 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M9 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M9 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M9 / 0.71491 END
						WHEN EP.SAL_MON = 10 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M10 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M10 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M10 / 0.71491 END
						WHEN EP.SAL_MON = 11 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M11 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M11 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M11 / 0.71491 END
						WHEN EP.SAL_MON = 12 THEN CASE WHEN EPR.SALARY_TYPE = 0 THEN ES.M12 * OCH.SSK_MONTHLY_WORK_HOURS / 0.71491 WHEN EPR.SALARY_TYPE = 1 THEN ES.M12 * 30 / 0.71491 WHEN EPR.SALARY_TYPE = 2 THEN ES.M12 / 0.71491 END
						END
					)
				)
				
			GROUP BY
				B.BRANCH_CITY,B.SSK_M,B.SSK_JOB,B.SSK_BRANCH,B.SSK_BRANCH_OLD,B.SSK_NO,B.SSK_CITY,B.SSK_COUNTRY,B.SSK_CD,B.SSK_AGENT,
				EP.SAL_YEAR,
				EP.SAL_MON,
                B.BRANCH_ID
			UNION ALL
			SELECT 
				B.BRANCH_CITY,
				EP.SAL_MON,
				EP.SAL_YEAR,
				B.SSK_M + B.SSK_JOB+B.SSK_BRANCH+B.SSK_BRANCH_OLD+B.SSK_NO+B.SSK_CITY+B.SSK_COUNTRY+B.SSK_CD+B.SSK_AGENT AS SGK_NO,
				0 GV_MUAF_KADIN,
				0 GV_MUAF_ERKEK,
				0 GV_MUAF_ENGELLI_KADIN,
				0 GV_MUAF_ENGELLI_ERKEK,
				0 SGK_MUAF_KADIN,
				0 SGK_MUAF_ERKEK,
				0 SGK_MUAF_ENGELLI_KADIN,
				0 SGK_MUAF_ENGELLI_ERKEK,
				0 ASGARI_UCRETLI_KADIN,
				0 ASGARI_UCRETLI_ERKEK,
				0 ASGARI_UCRETLI_ENGELLI_KADIN,
				0 ASGARI_UCRETLI_ENGELLI_ERKEK,
				0 DIGER_UCRETLI_KADIN,
				0 DIGER_UCRETLI_ERKEK,
				0 DIGER_UCRETLI_ENGELLI_KADIN,
				COUNT(EPR.EMPLOYEE_ID) DIGER_UCRETLI_ENGELLI_ERKEK,
                B.BRANCH_ID
			FROM 
				EMPLOYEES_PUANTAJ_ROWS EPR
				INNER JOIN EMPLOYEES_PUANTAJ EP ON EP.PUANTAJ_ID = EPR.PUANTAJ_ID
				INNER JOIN EMPLOYEES_IN_OUT EIO ON EIO.IN_OUT_ID = EPR.IN_OUT_ID
				INNER JOIN DEPARTMENT D ON D.DEPARTMENT_ID = EPR.DEPARTMENT_ID
				INNER JOIN BRANCH B ON B.BRANCH_ID = D.BRANCH_ID
				INNER JOIN EMPLOYEES_DETAIL ED ON ED.EMPLOYEE_ID = EPR.EMPLOYEE_ID
				INNER JOIN OUR_COMPANY_HOURS OCH ON OCH.OUR_COMPANY_ID = B.COMPANY_ID
			WHERE
				ED.SEX = 1
				AND EIO.DEFECTION_LEVEL > 0
				AND EIO.DUTY_TYPE = 8
				AND (EIO.IS_TAX_FREE = 0 OR EIO.IS_TAX_FREE IS NULL)
				AND EIO.USE_SSK <> 0
				<cfif not session.ep.ehesap>
					AND B.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = <cfqueryparam cfsqltype="cf_sql_integer" value="#session.ep.position_code#">)
				</cfif>
			GROUP BY
				B.BRANCH_CITY,B.SSK_M,B.SSK_JOB,B.SSK_BRANCH,B.SSK_BRANCH_OLD,B.SSK_NO,B.SSK_CITY,B.SSK_COUNTRY,B.SSK_CD,B.SSK_AGENT,
				EP.SAL_YEAR,
				EP.SAL_MON,
                B.BRANCH_ID
		) AS T1
		WHERE
			SAL_YEAR = <cfqueryparam cfsqltype="cf_sql_integer" value="#attributes.sal_year#">
			AND SAL_MON >= <cfqueryparam cfsqltype="cf_sql_integer" value="#attributes.sal_mon#">
			AND SAL_MON <= <cfqueryparam cfsqltype="cf_sql_integer" value="#attributes.sal_mon_end#">
			<cfif isdefined('attributes.branch_id') and len(attributes.branch_id)>
                AND BRANCH_ID IN (<cfqueryparam cfsqltype="cf_sql_integer" list="true" value="#attributes.branch_id#">)
            </cfif>
		GROUP BY
			BRANCH_CITY,
			SAL_YEAR,
			SAL_MON,
			SGK_NO
		ORDER BY
			SAL_YEAR,
			SAL_MON,
			BRANCH_CITY
	</cfquery>
<cfelse>
	<cfset get_sgk_detail.recordcount = 0>
</cfif>
<cfparam name="attributes.totalrecords" default="#get_sgk_detail.recordcount#">
<cfsavecontent variable="head"><cf_get_lang dictionary_id='59319.İş Yeri Çalışan SGK Bilgileri'></cfsavecontent>
<cfform name="search_form" method="post" action="#request.self#?fuseaction=report.employees_sgk_detail_report">
	<cf_report_list_search title="#head#">
        <cf_report_list_search_area>
			<div class="row">
				<div class="col col-12 col-xs-12">
                    <div class="row formContent">
						<div class="row" type="row">
							<div class="col col-4 col-md-6 col-xs-12">
								<div class="col col-12 col-md-12 col-xs-12">
									<div class="col col-12 col-md-12 col-xs-12">
										<div class="form-group">
											<div class="col col-12 col-md-12 col-xs-12">	
												<div id="BRANCH_PLACE" class="multiselect-z1">
													<cf_multiselect_check 
													query_name="get_branches"  
													name="branch_id" 
													option_value="BRANCH_ID"
													option_name="BRANCH_NAME"
													option_text="#getLang('main',41)#"
													value="#attributes.branch_id#">
												</div>
											</div>
										</div>
										<div class="form-group">				
											<div class="col col-4">
												<select name="sal_mon" id="sal_mon">
													<cfloop from="1" to="12" index="i">
														<cfoutput>
															<option value="#i#" <cfif (isdefined("attributes.sal_mon") and attributes.sal_mon eq i) or (not isdefined("attributes.sal_mon") and month(now()) gt 1 and i eq month(now())-1)>selected</cfif>>#listgetat(ay_list(),i,',')#</option>
														</cfoutput>
													</cfloop>
												</select>
											</div>
											<div class="col col-4">
												<select name="sal_mon_end" id="sal_mon_end">
													<cfloop from="1" to="12" index="i">
														<cfoutput>
															<option value="#i#" <cfif (isdefined("attributes.sal_mon_end") and attributes.sal_mon_end eq i) or (not isdefined("attributes.sal_mon_end") and month(now()) gt 1 and i eq month(now())-1)>selected</cfif>>#listgetat(ay_list(),i,',')#</option>
														</cfoutput>
													</cfloop>
												</select>	
											</div>
											<div class="col col-4">
												<select name="sal_year" id="sal_year">
													<cfloop from="#year(now())-3#" to="#year(now())+3#" index="i">
														<cfoutput>
															<option value="#i#" <cfif (isdefined("attributes.sal_year") and attributes.sal_year eq i) or (not isdefined("attributes.sal_year") and year(now()) eq i)>selected</cfif>>#i#</option>
														</cfoutput>
													</cfloop>
												</select>
											</div>					
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="row ReportContentBorder">
						<div class="ReportContentFooter">
							<input type="checkbox" name="is_excel" id="is_excel" value="1" <cfif attributes.is_excel eq 1>checked</cfif>><cf_get_lang dictionary_id='57858.Excel Getir'>
							<cfsavecontent variable="message"><cf_get_lang dictionary_id='57537.Sayi_Hatasi_Mesaj'></cfsavecontent>
							<cfif session.ep.our_company_info.is_maxrows_control_off eq 1>
								<cfinput type="text" name="maxrows" value="#attributes.maxrows#" required="yes" onKeyUp="isNumber(this)" validate="integer" message="#message#" maxlength="3" style="width:25px;">
							<cfelse>
								<cfinput type="text" name="maxrows" value="#attributes.maxrows#" required="yes" onKeyUp="isNumber(this)" validate="integer" range="1,250" message="#message#" maxlength="3" style="width:25px;">
							</cfif>
							<input name="is_form_submit" id="is_form_submit" value="1" type="hidden">
							<cf_wrk_report_search_button button_type="1" is_excel='1' search_function="control()">
						</div>
					</div>
				</div>
			</div>
		</cf_report_list_search_area>
	</cf_report_list_search>
</cfform>
<cfif attributes.is_excel eq 1>
		<cfset type_ = 1>
		<cfset filename = "#createuuid()#">
		<cfheader name="Expires" value="#Now()#">
		<cfcontent type="application/vnd.msexcel;charset=utf-8">
		<cfheader name="Content-Disposition" value="attachment; filename=#filename#.xls">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<cfelse>
		<cfset type_ = 0>
</cfif>
<cfif isdefined("is_form_submit")>
	<cf_report_list>
		<cfif isdefined('attributes.is_excel') and attributes.is_excel eq 1>
			<cfset type_ = 1>
		<cfelse>
			<cfset type_ = 0>
		</cfif>
			<thead>
				<tr>
					<th>&nbsp;</th>
					<th><cf_get_lang dictionary_id='42356.SGK İşyeri No'></th>
					<th colspan="4"><cf_get_lang dictionary_id='60706.Asgari Ücretli'></th>
					<th colspan="4"><cf_get_lang dictionary_id='60707.Diğer Ücretli'></th>
					<th colspan="4"><cf_get_lang dictionary_id='53998.Gelir Vergisi Muaf'></th>
					<th colspan="4"><cf_get_lang dictionary_id='55501.SGK Muaf'></th>
				</tr>
			</thead>
			<tbody>
				<cfif get_sgk_detail.recordcount>
					<cfset temp_year = ''>
					<cfset temp_month = ''>
					<cfoutput query="get_sgk_detail" maxrows="#attributes.maxrows#" startrow="#attributes.startrow#">
						<cfif temp_year neq sal_year or temp_month neq sal_mon>
							<tbody>	
								<tr>
									<th><cf_get_lang dictionary_id='57971.Şehir'></th>
									<th>#listgetAt(ay_list(),sal_mon)#\ #sal_year#</th>
									<th><cf_get_lang dictionary_id='58958.Kadın'></th>
									<th><cf_get_lang dictionary_id='58959.Erkek'></th>
									<th><cf_get_lang dictionary_id='55614.Engelli'> <cf_get_lang dictionary_id='58958.Kadın'></th>
									<th><cf_get_lang dictionary_id='55614.Engelli'> <cf_get_lang dictionary_id='58959.Erkek'></th>
									<th><cf_get_lang dictionary_id='58958.Kadın'></th>
									<th><cf_get_lang dictionary_id='58959.Erkek'></th>
									<th><cf_get_lang dictionary_id='55614.Engelli'> <cf_get_lang dictionary_id='58958.Kadın'></th>
									<th><cf_get_lang dictionary_id='55614.Engelli'> <cf_get_lang dictionary_id='58959.Erkek'></th>
									<th><cf_get_lang dictionary_id='58958.Kadın'></th>
									<th><cf_get_lang dictionary_id='58959.Erkek'></th>
									<th><cf_get_lang dictionary_id='55614.Engelli'> <cf_get_lang dictionary_id='58958.Kadın'></th>
									<th><cf_get_lang dictionary_id='55614.Engelli'> <cf_get_lang dictionary_id='58959.Erkek'></th>
									<th><cf_get_lang dictionary_id='58958.Kadın'></th>
									<th><cf_get_lang dictionary_id='58959.Erkek'></th>
									<th><cf_get_lang dictionary_id='55614.Engelli'> <cf_get_lang dictionary_id='58958.Kadın'></th>
									<th><cf_get_lang dictionary_id='55614.Engelli'> <cf_get_lang dictionary_id='58959.Erkek'></th>
								</tr>
							</tbody>	
							
							<cfset temp_year = sal_year>
							<cfset temp_month = sal_mon>
						</cfif>
						<tr>
							<td>#branch_city#</td>
							<td>#sgk_no#</td>
							<td>#asgari_ucretli_kadin#</td>
							<td>#asgari_ucretli_erkek#</td>
							<td>#asgari_ucretli_engelli_kadin#</td>
							<td>#asgari_ucretli_engelli_erkek#</td>
							<td>#diger_ucretli_kadin#</td>
							<td>#diger_ucretli_erkek#</td>
							<td>#diger_ucretli_engelli_kadin#</td>
							<td>#diger_ucretli_engelli_erkek#</td>
							<td>#gv_muaf_kadin#</td>
							<td>#gv_muaf_erkek#</td>
							<td>#gv_muaf_engelli_kadin#</td>
							<td>#gv_muaf_engelli_erkek#</td>
							<td>#sgk_muaf_kadin#</td>
							<td>#sgk_muaf_erkek#</td>
							<td>#sgk_muaf_engelli_kadin#</td>
							<td>#sgk_muaf_engelli_erkek#</td>
						</tr>
					</cfoutput>
					<cfelse>
								<tbody>
									<tr>
										<td colspan="15"><cfif isdefined('attributes.is_form_submit')><cf_get_lang dictionary_id='57484.Kayıt Yok'>!<cfelse><cf_get_lang dictionary_id ='57701.Filtre Ediniz'>!</cfif></td>
									</tr>
								</tbody>
				</cfif>
			</tbody>
	</cf_report_list>
</cfif>
<cfif attributes.totalrecords gt attributes.maxrows>
            <cfset url_str = "">
            <cfif isdefined("attributes.is_form_submit") and len(attributes.is_form_submit)>
                <cfset url_str = "#url_str#&is_form_submit=#attributes.is_form_submit#">
            </cfif>
			<cfif isdefined("attributes.branch_id") and len(attributes.branch_id)>
                <cfset url_str = "#url_str#&branch_id=#attributes.branch_id#">
            </cfif>
			<cfif len(attributes.sal_mon)>
                <cfset url_str = "#url_str#&sal_mon=#attributes.sal_mon#">
            </cfif>
			<cfif len(attributes.sal_mon_end)>
                <cfset url_str = "#url_str#&sal_mon_end=#attributes.sal_mon_end#">
            </cfif>
			<cfif len(attributes.sal_year)>
                <cfset url_str = "#url_str#&sal_year=#attributes.sal_year#">
            </cfif>
           
                <cf_paging page="#attributes.page#"
                    maxrows="#attributes.maxrows#"
                    totalrecords="#attributes.totalrecords#"
                    startrow="#attributes.startrow#"
                    adres="#attributes.fuseaction#&#url_str#"> 
				<cfif attributes.is_excel eq 0>
                <cf_get_lang dictionary_id='57540.Toplam Kayıt'>:<cfoutput>#attributes.totalrecords#-&nbsp;<cf_get_lang dictionary_id='57581.Sayfa'>:#attributes.page#/#lastpage#</cfoutput>
				</cfif>
		
		</cfif>
<script type="text/javascript">
	function control()	
	{
            if(document.search_form.is_excel.checked==false)
            {
                document.search_form.action="<cfoutput>#request.self#?fuseaction=#attributes.fuseaction#</cfoutput>"
                return true;
            }
            else
                document.search_form.action="<cfoutput>#request.self#?fuseaction=#fusebox.circuit#.emptypopup_employees_sgk_detail_report</cfoutput>"
    }
</script>
