<cfquery name="get_ext_worktime" datasource="#dsn#">
	SELECT
		EMPLOYEES_EXT_WORKTIMES.*,
		EMPLOYEES.EMPLOYEE_NAME,
		EMPLOYEES.EMPLOYEE_SURNAME
	FROM
		EMPLOYEES_EXT_WORKTIMES,
		EMPLOYEES
	WHERE
		EMPLOYEES.EMPLOYEE_ID = EMPLOYEES_EXT_WORKTIMES.EMPLOYEE_ID
		AND EMPLOYEES_EXT_WORKTIMES.EWT_ID = #attributes.EWT_ID#
</cfquery>
