<cfquery name="get_dep" datasource="#DSN#">
	SELECT
		D.DEPARTMENT_HEAD,
		EMPLOYEE_NAME,
		EMPLOYEE_SURNAME,
		POSITION_NAME
	FROM
		EMPLOYEE_POSITIONS EP,
		DEPARTMENT D
	WHERE
		D.DEPARTMENT_ID=EP.DEPARTMENT_ID		
		AND EP.EMPLOYEE_ID=#attributes.EMPLOYEE_ID#
		AND EP.IS_MASTER = 1
</cfquery>
