<cfquery name="GET_SPOTS" datasource="#DSN#" maxrows="3">
	SELECT
		TOP 1
		C.CONT_HEAD, 
		C.CONTENT_ID,
		C.CONT_SUMMARY,
		CI.CONTIMAGE_SMALL
	FROM  
		CONTENT AS C
		LEFT JOIN CONTENT_IMAGE AS CI ON C.CONTENT_ID = CI.CONTENT_ID
	WHERE 
		C.SPOT = 1 AND
		C.STAGE_ID = -2 AND 
		C.EMPLOYEE_VIEW = 1 AND
		CI.CONTIMAGE_SMALL IS NOT NULL
	ORDER BY 
		C.CONTENT_ID DESC 
</cfquery>
