<cfquery name="GET_PURCHASE_GENERAL_DISCOUNT" datasource="#dsn3#">
	SELECT
		1 TYPE,
		GENERAL_DISCOUNT_ID,
		DISCOUNT_HEAD,
		START_DATE,
		FINISH_DATE,
		DISCOUNT
	FROM
		CONTRACT_PURCHASE_GENERAL_DISCOUNT
	<!--- WHERE
		COMPANY_ID LIKE '%#attributes.company_id#%' --->
UNION ALL
	SELECT
		2 TYPE,
		GENERAL_DISCOUNT_ID,
		DISCOUNT_HEAD,
		START_DATE,
		FINISH_DATE,
		DISCOUNT
	FROM
		CONTRACT_SALES_GENERAL_DISCOUNT
	<!--- WHERE
		COMPANY_ID LIKE '%#attributes.company_id#%' --->
</cfquery>
