<cfquery name="GET_POSITIONS" datasource="#dsn#">
	SELECT
		EMPLOYEE_POSITIONS.EMPLOYEE_ID,
		EMPLOYEE_POSITIONS.EMPLOYEE_NAME,
		EMPLOYEE_POSITIONS.EMPLOYEE_SURNAME,
		EMPLOYEE_POSITIONS.EMPLOYEE_EMAIL,
		EMPLOYEE_POSITIONS.POSITION_CODE,
		EMPLOYEE_POSITIONS.POSITION_NAME,
		EMPLOYEE_POSITIONS.POSITION_ID,
		BRANCH.BRANCH_NAME,
		BRANCH.BRANCH_ID,
		DEPARTMENT.DEPARTMENT_HEAD,
		DEPARTMENT.DEPARTMENT_ID,
		EMPLOYEES.GROUP_STARTDATE
	FROM
		EMPLOYEE_POSITIONS,
		DEPARTMENT,
		BRANCH,
		EMPLOYEES
	WHERE
		EMPLOYEE_POSITIONS.POSITION_STATUS=1 AND
		EMPLOYEE_POSITIONS.VALID=2 AND
		EMPLOYEES.EMPLOYEE_STATUS=1 AND
		EMPLOYEE_POSITIONS.EMPLOYEE_ID>0 AND
		EMPLOYEES.EMPLOYEE_ID=EMPLOYEE_POSITIONS.EMPLOYEE_ID AND
		EMPLOYEE_POSITIONS.DEPARTMENT_ID=DEPARTMENT.DEPARTMENT_ID AND
		DEPARTMENT.BRANCH_ID=BRANCH.BRANCH_ID 
	<cfif not isDefined("attributes.show_empty_pos")>
		AND EMPLOYEES.EMPLOYEE_ID=EMPLOYEE_POSITIONS.EMPLOYEE_ID 
		AND EMPLOYEE_POSITIONS.DEPARTMENT_ID=DEPARTMENT.DEPARTMENT_ID
	</cfif>
	<cfif isDefined("attributes.keyword") and len(attributes.keyword)>
		<cfif len(attributes.keyword) eq 1>
			AND EMPLOYEE_POSITIONS.EMPLOYEE_NAME LIKE '#attributes.keyword#%'
		<cfelse>
			<cfif database_type is 'MSSQL'>
			AND EMPLOYEE_POSITIONS.EMPLOYEE_NAME + ' ' + EMPLOYEE_POSITIONS.EMPLOYEE_SURNAME LIKE '%#attributes.keyword#%'
			<cfelseif database_type is 'DB2'>
			AND EMPLOYEE_POSITIONS.EMPLOYEE_NAME || ' ' || EMPLOYEE_POSITIONS.EMPLOYEE_SURNAME LIKE '%#attributes.keyword#%'
			</cfif>
		</cfif>
	</cfif>
	<cfif isDefined("attributes.branch_id") and len(attributes.branch_id)>
		AND BRANCH.BRANCH_ID = #attributes.branch_id#
	</cfif>
	<cfif isDefined("attributes.our_cid")>
		AND BRANCH.COMPANY_ID = #attributes.our_cid# 
	</cfif>
	<cfif isdefined("attributes.branch_related")>
		AND BRANCH.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = #session.pda.position_code#)
	</cfif>
	<cfif isdefined("attributes.employee_list") and attributes.employee_list neq "">
		AND EMPLOYEES.EMPLOYEE_ID IN (
			SELECT
				EMPLOYEE_POSITIONS.EMPLOYEE_ID
			FROM 
				BRANCH,
				EMPLOYEE_POSITIONS,
				DEPARTMENT
			WHERE
				BRANCH.BRANCH_ID IN ( SELECT EMPLOYEE_POSITION_BRANCHES.BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE EMPLOYEE_POSITION_BRANCHES.POSITION_CODE = #session.pda.position_code# )
				AND EMPLOYEE_POSITIONS.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID AND
				DEPARTMENT.BRANCH_ID = BRANCH.BRANCH_ID
		)
	</cfif>
	ORDER BY
		EMPLOYEE_POSITIONS.EMPLOYEE_NAME
</cfquery>

