<cfquery name="add_temp_report" datasource="#dsn_report#">
<cfif attributes.table_name is 'SALES_PRODUCT_MONTH'>
        INSERT INTO SALES_PRODUCT_MONTH
        (
            OUR_COMPANY_ID,
            PERIOD_YEAR,
            PERIOD_MONTH,
            
            STOCK_ID,
            HIERARCHY,
            PRODUCT_CAT,
            STOCK_CODE,
            BARCOD,
            PRODUCT_NAME,
            MIN_MARGIN,
            PRODUCT_STOCK,
            UNIT,
            GROSSTOTAL_DOVIZ,
            GROSSTOTAL_DOVIZ_MONEY,
            PRICE_DOVIZ,
            PRICE_DOVIZ_MONEY,
            NET_KAR_DOVIZ,
            NET_KAR_DOVIZ_MONEY,
            NET_KAR_DOVIZ_RATE,
            NET_KAR_DOVIZ_RECRACTIVE,
            NET_KAR,
            NET_KAR_MONEY,
            NET_KAR_RATE,
            NET_KAR_RATE_RECRACTIVE,
            GROSSTOTAL,
            GROSSTOTAL_MONEY,
            PRICE,
            PRICE_MONEY,
            PRICE_RATE
        )
        VALUES
        (
            #attributes.period_our_company_id#,
            #attributes.period_year#,
            #attributes.period_month#,
            #STOCK_ID#,
            <cfif len(HIERARCHY)>'#HIERARCHY#'<cfelse>NULL</cfif>,
            <cfif len(PRODUCT_CAT)>'#PRODUCT_CAT#'<cfelse>NULL</cfif>,
            <cfif len(STOCK_CODE)>'#STOCK_CODE#'<cfelse>NULL</cfif>,
            <cfif len(BARCOD)>'#BARCOD#'<cfelse>NULL</cfif>,
            <cfif len(PRODUCT_NAME)>'#PRODUCT_NAME# #PROPERTY#'<cfelse>NULL</cfif>,
            <cfif len(MIN_MARGIN)>#MIN_MARGIN#<cfelse>NULL</cfif>,
            <cfif len(PRODUCT_STOCK)>#PRODUCT_STOCK#<cfelse>NULL</cfif>,
            <cfif len(PRODUCT_STOCK)>'#BIRIM#'<cfelse>NULL</cfif>,
            <cfif isdefined('GROSSTOTAL_DOVIZ') and len(GROSSTOTAL_DOVIZ)>#GROSSTOTAL_DOVIZ#<cfelse>NULL</cfif>,
            '#session.ep.money2#',
            <cfif isdefined('PRICE_DOVIZ') and len(PRICE_DOVIZ)>#PRICE_DOVIZ#<cfelse>NULL</cfif>,
            '#session.ep.money2#',
            <cfif isdefined('NET_KAR_DOVIZ') and len(NET_KAR_DOVIZ)>#NET_KAR_DOVIZ#<cfelse>NULL</cfif>,
            '#session.ep.money2#',
            <cfif isdefined('NET_KAR_DOVIZ') and isdefined('diger_butun_kar') and diger_butun_kar neq 0>#filternum(Replace(NumberFormat(NET_KAR_DOVIZ*100/diger_butun_kar,"00.00"),".",","))#<cfelse>NULL</cfif>,
            <cfif isdefined('PRICE_DOVIZ') and PRICE_DOVIZ neq 0>#(NET_KAR_DOVIZ*100)/PRICE_DOVIZ#<cfelse>NULL</cfif>,
            <cfif isdefined('NET_KAR') and len(NET_KAR)>#NET_KAR#<cfelse>NULL</cfif>,
            '#session.ep.money#',
            <cfif isdefined('NET_KAR') and isdefined('butun_kar') and butun_kar neq 0>#filternum(Replace(NumberFormat(NET_KAR*100/butun_kar,"00.00"),".",","))#<cfelse>NULL</cfif>,
            <cfif PRICE neq 0>#(NET_KAR*100)/PRICE#<cfelse>NULL</cfif>,
            <cfif len(GROSSTOTAL)>#GROSSTOTAL#<cfelse>NULL</cfif>,
            '#SESSION.EP.MONEY#',
            <cfif len(PRICE)>#PRICE#<cfelse>NULL</cfif>,
            '#SESSION.EP.MONEY#',
            <cfif butun_toplam neq 0>#filternum(Replace(NumberFormat(PRICE*100/butun_toplam,"00.00"),".",","))#<cfelse>NULL</cfif>
        )
<cfelseif attributes.table_name is 'SALES_CUSTOMER_MONTH'>
        INSERT INTO SALES_CUSTOMER_MONTH
        (
            OUR_COMPANY_ID,
            PERIOD_YEAR,
            PERIOD_MONTH,
            MEMBER_TYPE,
            MEMBER_ID,
            MEMBER_NAME,
            TAXOFFICE,
            TAXNO,
            INVOICE_COUNT,
            CITY_ID,
            CITY_NAME,
            PRODUCT_STOCK,
            GROSSTOTAL_DOVIZ,
            GROSSTOTAL_DOVIZ_MONEY,
            PRICE_DOVIZ,
            PRICE_DOVIZ_MONEY,
            NET_KAR_DOVIZ,
            NET_KAR_DOVIZ_MONEY,
            DOVIZ_RATE,
            NET_KAR,
            NET_KAR_MONEY,
            NET_KAR_RATE,
            GROSSTOTAL,
            GROSSTOTAL_MONEY,
            PRICE,
            PRICE_MONEY,
            PRICE_RATE
		)
        VALUES
        (
            #attributes.period_our_company_id#,
            #attributes.period_year#,
            #attributes.period_month#,
            <cfif type eq 1>'COMPANY'<cfelse>'CONSUMER'</cfif>,
            <cfif len(MUSTERI_ID)>#MUSTERI_ID#<cfelse>NULL</cfif>,
            <cfif len(MUSTERI)>'#MUSTERI#'<cfelse>NULL</cfif>,
            <cfif len(TAXOFFICE)>'#TAXOFFICE#'<cfelse>NULL</cfif>,
            <cfif len(TAXNO)>#TAXNO#<cfelse>NULL</cfif>,
            <cfif len(GET_INVOICE_COUNT.INVOICE_COUNT)>#GET_INVOICE_COUNT.INVOICE_COUNT#<cfelse>NULL</cfif>,
            <cfif len(MUSTERI_CITY)>#MUSTERI_CITY#<cfelse>NULL</cfif>,
            <cfif len(MUSTERI_CITY)and len(GET_MUSTERI_CITY.CITY_NAME)>'#GET_MUSTERI_CITY.CITY_NAME#'<cfelse>NULL</cfif>,
            <cfif len(PRODUCT_STOCK)>#PRODUCT_STOCK#<cfelse>NULL</cfif>,
            <cfif len(GROSSTOTAL_DOVIZ)>#GROSSTOTAL_DOVIZ#<cfelse>NULL</cfif>,
            <cfif len(session.ep.money2)>'#session.ep.money2#'<cfelse>NULL</cfif>,
            <cfif len(PRICE_DOVIZ)>#PRICE_DOVIZ#<cfelse>NULL</cfif>,
            <cfif len(session.ep.money2)>'#session.ep.money2#'<cfelse>NULL</cfif>,
            <cfif len(NET_KAR_DOVIZ)>#NET_KAR_DOVIZ#<cfelse>NULL</cfif>,
            <cfif len(session.ep.money2)>'#session.ep.money2#'<cfelse>NULL</cfif>,
            <cfif diger_butun_kar neq 0>#filternum(Replace(NumberFormat(NET_KAR_DOVIZ*100/diger_butun_kar,"00.00"),".",","))#<cfelse>NULL</cfif>,
			<cfif len(NET_KAR)>#NET_KAR#<cfelse>NULL</cfif>,
            '#session.ep.money#',
            <cfif butun_kar neq 0>#filternum(Replace(NumberFormat(NET_KAR*100/butun_kar,"00.00"),".",","))#<cfelse>NULL</cfif>,
			<cfif len(GROSSTOTAL)>#GROSSTOTAL#<cfelse>NULL</cfif>,
            '#SESSION.EP.MONEY#',
			<cfif len(PRICE)>#PRICE#<cfelse>NULL</cfif>,
            '#SESSION.EP.MONEY#',
            <cfif butun_toplam neq 0>#filternum(Replace(NumberFormat(PRICE*100/butun_toplam,"00.00"),".",","))#<cfelse>NULL</cfif>
        )       
</cfif>
</cfquery>
