<cfquery name="GET_PAYROLL_VOUCHERS" datasource="#dsn2#">
	SELECT
	  DISTINCT	
	  	V.CASH_ID,
		V.VOUCHER_STATUS_ID,
		V.VOUCHER_PURSE_NO ,
		V.DEBTOR_NAME,
		V.VOUCHER_CITY,
		ISNULL(V.VOUCHER_DUEDATE,VH.ACT_DATE) VOUCHER_DUEDATE,
		V.VOUCHER_VALUE,
		V.VOUCHER_NO,
		V.VOUCHER_CODE,
		V.ACCOUNT_NO,
		V.CURRENCY_ID,
		VH.PAYROLL_ID,
		V.ACCOUNT_CODE,
		VH.OTHER_MONEY,
		VH.OTHER_MONEY_VALUE,
		VH.OTHER_MONEY2,
		VH.OTHER_MONEY_VALUE2,
		VH.STATUS,
		VH.VOUCHER_ID,
		VH.ACT_DATE,
		V.SELF_VOUCHER,
		V.IS_PAY_TERM,
        (SELECT TOP 1 PAYROLL_ID FROM VOUCHER_HISTORY VH2 WHERE VH2.VOUCHER_ID = V.VOUCHER_ID ORDER BY HISTORY_ID DESC) AS LAST_PAYROLL_ID,
		(
			SELECT
				MAX(ISNULL(ACT_DATE,RECORD_DATE))
			FROM
				VOUCHER_HISTORY
			WHERE
				VOUCHER_ID = V.VOUCHER_ID
				AND PAYROLL_ID <> #URL.ID#
				AND ISNULL(ACT_DATE,RECORD_DATE) <= VH.ACT_DATE
		)MAX_ACT_DATE
	FROM
		VOUCHER AS V,
		VOUCHER_HISTORY AS VH
	WHERE
		VH.PAYROLL_ID=#URL.ID# AND
		V.VOUCHER_ID = VH.VOUCHER_ID
</cfquery>


