<cfquery name="GET_ACTION_ACCOUNT" datasource="#dsn3#">
	SELECT
		ACCOUNT_NAME,
		<cfif session.ep.period_year lt 2009>
			CASE WHEN(ACCOUNTS.ACCOUNT_CURRENCY_ID = 'TL') THEN 'YTL' ELSE ACCOUNTS.ACCOUNT_CURRENCY_ID END AS  ACCOUNT_CURRENCY_ID
		<cfelse>
			ACCOUNTS.ACCOUNT_CURRENCY_ID
		</cfif>
	FROM
		ACCOUNTS
	WHERE
		ACCOUNT_ID=#ACCOUNT_ID#
</cfquery>
