<cfquery name="GET_PAYROLL_CHEQUES" datasource="#dsn2#">
	SELECT
	  DISTINCT	
		C.CHEQUE_STATUS_ID,
		C.CHEQUE_PURSE_NO ,
		C.BANK_NAME ,
		C.BANK_BRANCH_NAME,
		C.DEBTOR_NAME,
		C.CHEQUE_CITY,
		ISNULL(C.CHEQUE_DUEDATE,CH.ACT_DATE) CHEQUE_DUEDATE,
		C.CHEQUE_VALUE,
		C.CHEQUE_NO,
		C.CHEQUE_CODE,
		C.TAX_PLACE,
		C.TAX_NO,
		C.ACCOUNT_NO,
		C.CURRENCY_ID,
		C.CHEQUE_PAYROLL_ID,
		C.ACCOUNT_ID,
		CH.OTHER_MONEY,
		CH.OTHER_MONEY_VALUE,
		CH.OTHER_MONEY2,
		CH.OTHER_MONEY_VALUE2,
		CH.STATUS,
		CH.CHEQUE_ID,
		CH.ACT_DATE,
		C.SELF_CHEQUE,
		CH.PAYROLL_ID,
		CH.HISTORY_ID,
		C.ENDORSEMENT_MEMBER,
        (SELECT TOP 1 PAYROLL_ID FROM CHEQUE_HISTORY CH2 WHERE CH2.CHEQUE_ID = C.CHEQUE_ID ORDER BY HISTORY_ID DESC) AS LAST_PAYROLL_ID,
		(
			SELECT
				MAX(ISNULL(ACT_DATE,RECORD_DATE))
			FROM
				CHEQUE_HISTORY
			WHERE
				CHEQUE_ID = C.CHEQUE_ID
				AND PAYROLL_ID <> #URL.ID#
				AND ISNULL(ACT_DATE,RECORD_DATE) <= CH.ACT_DATE
		)MAX_ACT_DATE
	FROM
		CHEQUE AS C,
		CHEQUE_HISTORY AS CH
	WHERE
		CH.PAYROLL_ID=#URL.ID# AND
		C.CHEQUE_ID = CH.CHEQUE_ID
	ORDER BY
		CH.HISTORY_ID
</cfquery>
