<cfquery name="GET_VOUCHER_DETAIL" datasource="#DSN2#">
	SELECT 
		V.*
	FROM
		VOUCHER V
		<cfif session.ep.isBranchAuthorization>
			,VOUCHER_HISTORY
			,VOUCHER_PAYROLL
		</cfif>		
	WHERE
		V.VOUCHER_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#attributes.id#">
	<cfif session.ep.isBranchAuthorization>
		AND VOUCHER_HISTORY.PAYROLL_ID = VOUCHER_PAYROLL.ACTION_ID
		AND V.VOUCHER_ID = VOUCHER_HISTORY.VOUCHER_ID 
		AND VOUCHER_HISTORY.HISTORY_ID = (SELECT MAX(HISTORY_ID) HISTORY_ID FROM VOUCHER_HISTORY WHERE VOUCHER_HISTORY.VOUCHER_ID = V.VOUCHER_ID AND VOUCHER_HISTORY.PAYROLL_ID IS NOT NULL)
		AND VOUCHER_HISTORY.PAYROLL_ID = VOUCHER_PAYROLL.ACTION_ID
		AND VOUCHER_PAYROLL.BRANCH_ID IN (SELECT BRANCH_ID FROM #dsn#.EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = #session.ep.position_code#)
	</cfif>			
</cfquery>
<cfquery name="GET_VOUCHER_HISTORY" datasource="#dsn2#">
	SELECT 
		<cfif isdefined("check_our_company.is_remaining_amount") and check_our_company.is_remaining_amount eq 1>
			VH.OTHER_MONEY_VALUE -ISNULL((SELECT ( (ISNULL(SUM(VC.CLOSED_AMOUNT),0))*((V.OTHER_MONEY_VALUE/V.VOUCHER_VALUE))) FROM VOUCHER_PAYROLL VP,VOUCHER_CLOSED VC,VOUCHER_HISTORY VHH WHERE VC.PAYROLL_ID = VP.ACTION_ID AND VP.ACTION_ID = VHH.PAYROLL_ID AND VC.ACTION_ID = VHH.VOUCHER_ID AND VC.ACTION_ID = V.VOUCHER_ID AND VHH.HISTORY_ID <= VH.HISTORY_ID AND ISNULL(VP.PAYROLL_AVG_DUEDATE,DATEADD(day,-1,VP.RECORD_DATE)) <= VH.ACT_DATE GROUP BY VC.ACTION_ID),0) OTHER_MONEY_VALUE_,
			V.VOUCHER_VALUE - ISNULL((SELECT (ISNULL(SUM(VC.OTHER_CLOSED_AMOUNT),0)) FROM VOUCHER_PAYROLL VP,VOUCHER_CLOSED VC,VOUCHER_HISTORY VHH WHERE VC.PAYROLL_ID = VP.ACTION_ID AND VP.ACTION_ID = VHH.PAYROLL_ID AND VC.ACTION_ID = VHH.VOUCHER_ID AND VC.ACTION_ID = V.VOUCHER_ID AND VHH.HISTORY_ID <= VH.HISTORY_ID AND ISNULL(VP.PAYROLL_AVG_DUEDATE,DATEADD(day,-1,VP.RECORD_DATE)) <= VH.ACT_DATE GROUP BY VC.ACTION_ID),0) VOUCHER_VALUE_,
		<cfelse>
			VH.OTHER_MONEY_VALUE OTHER_MONEY_VALUE_,
			V.VOUCHER_VALUE VOUCHER_VALUE_,
		</cfif>
		VH.OTHER_MONEY_VALUE,
		V.VOUCHER_VALUE,
		VH.* 
	FROM
		VOUCHER V,
		VOUCHER_HISTORY VH
	WHERE
		V.VOUCHER_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#attributes.ID#">
		AND VH.VOUCHER_ID = V.VOUCHER_ID
	ORDER BY
		HISTORY_ID
</cfquery>
