<cfquery name="HEAD_TOPIC" datasource="#DSN#">
	SELECT 
		FORUM_MAIN.FORUMID,
		FORUM_MAIN.FORUMNAME,
		FORUM_TOPIC.TITLE, 
		FORUM_TOPIC.FORUM_TOPIC_FILE, 
		FORUM_TOPIC.TOPIC, 
		FORUM_TOPIC.LOCKED, 
		FORUM_TOPIC.IMAGEID,
		FORUM_TOPIC.USERKEY
	FROM 
		FORUM_TOPIC,  
		FORUM_MAIN
	WHERE 
		FORUM_MAIN.FORUMID = FORUM_TOPIC.FORUMID AND
		FORUM_TOPIC.TOPICID = <cfqueryparam cfsqltype="cf_sql_integer" value="#attributes.topicid#">
</cfquery>
