<cfquery name="GET_STOCK_NAME" datasource="#dsn3#">
	SELECT
		PRODUCT.PRODUCT_NAME,
		STOCKS.PROPERTY,
		STOCKS.STOCK_CODE
	FROM
		PRODUCT,
		STOCKS
	WHERE
		STOCKS.STOCK_ID = #attributes.STOCK_ID#
		AND
		PRODUCT.PRODUCT_ID = STOCKS.PRODUCT_ID
</cfquery>

