<cfquery name="GET_PRO_OPERATION" datasource="#dsn3#">
	SELECT
		*
	FROM
		PRODUCT,
		STOCKS,
		PRICE_STANDART
	WHERE
		STOCKS.STOCK_ID=#STOCK_ID#
		AND	STOCKS.PRODUCT_ID=PRODUCT.PRODUCT_ID
		AND	PRODUCT_STANDART.PRODUCT_ID=PRODUCT.PRODUCT_ID
</cfquery>
