<cfquery name="GET_SERVICE_POS" datasource="#dsn#">
	SELECT
		*
	FROM	
		EMPLOYEE_POSITIONS,
		DEPARTMENT,
		BRANCH
	WHERE
		EMPLOYEE_POSITIONS.DEPARTMENT_ID=DEPARTMENT.DEPARTMENT_ID
	AND
		DEPARTMENT.BRANCH_ID=BRANCH.BRANCH_ID
	AND
		EMPLOYEE_ID = #EMP_ID#
	AND
		POSITION_STATUS=1
</cfquery>
