<cfquery name="GET_FUEL_UPD" datasource="#dsn#">
	SELECT
		ASSET_P_FUEL.*,
		ASSET_P.ASSETP,
		COMPANY.FULLNAME
	FROM
		ASSET_P_FUEL,
		ASSET_P,
		COMPANY
	WHERE
		ASSET_P_FUEL.FUEL_ID = #attributes.fuel_id# AND
		ASSET_P.ASSETP_ID = ASSET_P_FUEL.ASSETP_ID AND
		COMPANY.COMPANY_ID = ASSET_P_FUEL.FUEL_COMPANY_ID		
</cfquery>
