<cfquery name="GET_CARE_TYPE" datasource="#DSN#">
	SELECT 
		ASSET_CARE_CAT.*
	FROM 
		ASSET_CARE_CAT,
		ASSET_P,
		ASSET_P_CAT
	WHERE
		ASSET_P.ASSETP_ID = #attributes.asset_id# AND
		ASSET_P.ASSETP_CATID = ASSET_P_CAT.ASSETP_CATID AND
		ASSET_P_CAT.ASSETP_CATID = ASSET_CARE_CAT.ASSETP_CAT
</cfquery>
