<cfquery name="GET_CARE_REFERENCE_UPD" datasource="#dsn#">
	SELECT
		ASSET_P_CARE_REFERENCE.*,
		SETUP_BRAND.BRAND_NAME,
		SETUP_BRAND_TYPE.BRAND_TYPE_NAME
	FROM
		ASSET_P_CARE_REFERENCE,
		SETUP_BRAND,
		SETUP_BRAND_TYPE
	WHERE
		ASSET_P_CARE_REFERENCE.CARE_REFERENCE_ID = #attributes.care_reference_id# AND
		SETUP_BRAND_TYPE.BRAND_TYPE_ID = ASSET_P_CARE_REFERENCE.BRAND_TYPE_ID AND
		SETUP_BRAND.BRAND_ID = SETUP_BRAND_TYPE.BRAND_ID
</cfquery>
