<cfquery name="GET_REQUEST_ROWS" datasource="#DSN#">
 	SELECT
		ASSET_P_REQUEST_ROWS.REQUEST_ROW_ID,
		ASSET_P_REQUEST_ROWS.ASSETP_CATID,
		ASSET_P_REQUEST_ROWS.USAGE_PURPOSE_ID,
		ASSET_P_REQUEST_ROWS.BRAND_TYPE_ID,
		ASSET_P_REQUEST_ROWS.BRANCH_ID,		
		ASSET_P_REQUEST_ROWS.MAKE_YEAR,
		ASSET_P_REQUEST_ROWS.PERT_ID,
		ASSET_P_REQUEST_ROWS.OLD_MAKE_YEAR,
		ASSET_P_REQUEST_ROWS.OLD_BRAND_TYPE_ID,		
		ASSET_P_REQUEST_ROWS.REQUEST_STATE,
		ASSET_P_REQUEST_ROWS.ASSETP_ID,
		ASSET_P_REQUEST_ROWS.EMPLOYEE_ID,
		ASSET_P_REQUEST_ROWS.REQUEST_DATE,
		ASSET_P_REQUEST_ROWS.DETAIL,
		ASSET_P_REQUEST_ROWS.RECORD_EMP,
		ASSET_P_REQUEST_ROWS.RECORD_IP,
		ASSET_P_REQUEST_ROWS.RECORD_DATE,
		ASSET_P_REQUEST_ROWS.UPDATE_DATE,
		ASSET_P_REQUEST_ROWS.UPDATE_EMP,
		ASSET_P_REQUEST_ROWS.UPDATE_IP,
		SETUP_OLD_BRAND.BRAND_NAME AS OLD_BRAND_NAME,
		SETUP_NEW_BRAND.BRAND_NAME,
		SETUP_BRAND_TYPE_BRAND_TYPE_ID.BRAND_TYPE_NAME AS BRAND_TYPE_NAME,
		SETUP_BRAND_TYPE_OLD_BRAND_TYPE_ID.BRAND_TYPE_NAME AS OLD_BRAND_TYPE_NAME,
		ASSET_P_CAT.ASSETP_CAT,
		ASSET_P.ASSETP,
		SETUP_USAGE_PURPOSE.USAGE_PURPOSE,
		EMPLOYEES.EMPLOYEE_NAME,
		EMPLOYEES.EMPLOYEE_SURNAME,
		BRANCH.BRANCH_NAME,
		PROCESS_TYPE_ROWS.LINE_NUMBER
	FROM 
		ASSET_P_REQUEST_ROWS,
		ASSET_P_CAT,
		SETUP_USAGE_PURPOSE,
		SETUP_BRAND_TYPE AS SETUP_BRAND_TYPE_BRAND_TYPE_ID,
		SETUP_BRAND_TYPE AS SETUP_BRAND_TYPE_OLD_BRAND_TYPE_ID,
		SETUP_BRAND AS SETUP_OLD_BRAND,
		SETUP_BRAND AS SETUP_NEW_BRAND,
		EMPLOYEES,
		BRANCH,
		ASSET_P,
		PROCESS_TYPE_ROWS
	WHERE 
		ASSET_P_REQUEST_ROWS.REQUEST_ROW_ID = #attributes.request_row_id# AND
		ASSET_P_REQUEST_ROWS.BRAND_TYPE_ID = SETUP_BRAND_TYPE_BRAND_TYPE_ID.BRAND_TYPE_ID AND
		ASSET_P_REQUEST_ROWS.OLD_BRAND_TYPE_ID =  SETUP_BRAND_TYPE_OLD_BRAND_TYPE_ID.BRAND_TYPE_ID AND
		SETUP_BRAND_TYPE_BRAND_TYPE_ID.BRAND_ID = SETUP_NEW_BRAND.BRAND_ID AND
		SETUP_BRAND_TYPE_OLD_BRAND_TYPE_ID.BRAND_ID = SETUP_OLD_BRAND.BRAND_ID AND
		ASSET_P_REQUEST_ROWS.ASSETP_ID = ASSET_P.ASSETP_ID AND
		ASSET_P_REQUEST_ROWS.USAGE_PURPOSE_ID  = SETUP_USAGE_PURPOSE.USAGE_PURPOSE_ID AND
		ASSET_P_REQUEST_ROWS.ASSETP_CATID = ASSET_P_CAT.ASSETP_CATID AND
		ASSET_P_REQUEST_ROWS.BRANCH_ID = BRANCH.BRANCH_ID AND
		ASSET_P_REQUEST_ROWS.EMPLOYEE_ID = EMPLOYEES.EMPLOYEE_ID AND
		ASSET_P_REQUEST_ROWS.REQUEST_STATE = PROCESS_TYPE_ROWS.PROCESS_ROW_ID
	ORDER BY
		ASSET_P_REQUEST_ROWS.REQUEST_ROW_ID
</cfquery>
