<cfquery name="GET_PUNISHMENT" datasource="#dsn#" maxrows="20">
	SELECT
		ASSET_P_PUNISHMENT.*,
		ASSET_P.ASSETP,
		EMPLOYEES.EMPLOYEE_NAME,
		EMPLOYEES.EMPLOYEE_SURNAME,		
		SETUP_PUNISHMENT_TYPE.PUNISHMENT_TYPE_NAME
	FROM
		ASSET_P_PUNISHMENT,
		ASSET_P,
		EMPLOYEES,
		SETUP_PUNISHMENT_TYPE,
		DEPARTMENT,
		BRANCH,
		ZONE
	WHERE
		ASSET_P_PUNISHMENT.ASSETP_ID = ASSET_P.ASSETP_ID AND
		EMPLOYEES.EMPLOYEE_ID = ASSET_P_PUNISHMENT.EMPLOYEE_ID AND
		SETUP_PUNISHMENT_TYPE.PUNISHMENT_TYPE_ID = ASSET_P_PUNISHMENT.PUNISHMENT_TYPE_ID AND
		<!--- Sadece yetkili olunan şubeler gözüksün. Onur P. --->
		BRANCH.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = #session.ep.position_code#) AND
		DEPARTMENT.DEPARTMENT_ID = ASSET_P_PUNISHMENT.DEPARTMENT_ID AND
		DEPARTMENT.BRANCH_ID = BRANCH.BRANCH_ID AND
		BRANCH.ZONE_ID = ZONE.ZONE_ID AND
		<cfif isDefined("attributes.assetp_id") and len(attributes.assetp_id)>
			ASSET_P_PUNISHMENT.ASSETP_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#attributes.assetp_id#">
		</cfif>
	ORDER BY
		ASSET_P_PUNISHMENT.PUNISHMENT_DATE DESC
</cfquery>