<cfquery name="GET_KM" datasource="#DSN#" maxrows="20">
	SELECT 
		ASSET_P_KM_CONTROL.KM_CONTROL_ID,
		ASSET_P_KM_CONTROL.KM_START,
		ASSET_P_KM_CONTROL.KM_FINISH,
		ASSET_P_KM_CONTROL.START_DATE,
		ASSET_P_KM_CONTROL.FINISH_DATE,
		ASSET_P_KM_CONTROL.DETAIL,
		ASSET_P_KM_CONTROL.EMPLOYEE_ID,
		ASSET_P_KM_CONTROL.IS_OFFTIME,
		ASSET_P_KM_CONTROL.IS_ALLOCATE,
		ASSET_P.ASSETP,
		ZONE.ZONE_NAME,
		BRANCH.BRANCH_NAME,
		DEPARTMENT.DEPARTMENT_HEAD,
		(SELECT MAX(KM_FINISH) FROM ASSET_P_KM_CONTROL WHERE ASSETP_ID = ASSET_P.ASSETP_ID) AS KM_LAST,
		(SELECT MAX(KM_CONTROL_ID) FROM ASSET_P_KM_CONTROL WHERE ASSETP_ID = ASSET_P.ASSETP_ID) AS KM_CONTROL_ID_LAST	
	FROM 
		ASSET_P_KM_CONTROL,
		ASSET_P,
		DEPARTMENT,
		BRANCH,
		ZONE
	WHERE
	<!--- Yakıt-KM baglantisinin haricindekilerin gelmesi icin FB 20071024 --->
		ASSET_P_KM_CONTROL.FUEL_ID IS NULL AND
	<!--- Misir ATS icin yapilan KM Sayac Degeri degistirmek icin onlar gelmesin BK 20080813 --->
	<cfif database_type is 'MSSQL'>
		ISNULL(ASSET_P_KM_CONTROL.IS_COUNTER_CHANGE,0) <> 1 AND
	<cfelseif database_type is 'DB2'>
		COALESCE(ASSET_P_KM_CONTROL.IS_COUNTER_CHANGE,0) <> 1 AND
	</cfif>
		<!--- İlk kayıtların gelmemesi için --->
		ASSET_P_KM_CONTROL.START_DATE IS NOT NULL AND 
		<!--- Tahsiste olan araçların gelmemesi için --->
		ASSET_P_KM_CONTROL.KM_FINISH IS NOT NULL AND
		<!--- Kalıntı kayıtların gelmemesi için --->
		NOT (ASSET_P_KM_CONTROL.IS_RESIDUAL = 1) AND
		ASSET_P_KM_CONTROL.ASSETP_ID = ASSET_P.ASSETP_ID AND
		ASSET_P_KM_CONTROL.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID AND 
		<!--- Sadece yetkili olunan şubeler gözüksün. Onur P. --->
		BRANCH.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = #session.ep.position_code#) AND
		DEPARTMENT.BRANCH_ID = BRANCH.BRANCH_ID AND
		BRANCH.ZONE_ID = ZONE.ZONE_ID
	ORDER BY
		ASSET_P_KM_CONTROL.KM_CONTROL_ID DESC
</cfquery>
