
<cfquery name="GET_FUEL" datasource="#DSN#" maxrows="20">
	SELECT
		ASSET_P_FUEL.*,
		ASSET_P.ASSETP,
		ZONE.ZONE_NAME,
		BRANCH.BRANCH_NAME,
		DEPARTMENT.DEPARTMENT_HEAD,
		SETUP_DOCUMENT_TYPE.DOCUMENT_TYPE_NAME,
		SETUP_FUEL_TYPE.FUEL_NAME,
        EMP.EMPLOYEE_SURNAME,
        EMP.EMPLOYEE_NAME
	FROM
		ASSET_P_FUEL,
		ASSET_P,
		DEPARTMENT,
		BRANCH,
		ZONE,
		SETUP_DOCUMENT_TYPE,
		SETUP_FUEL_TYPE	,
        EMPLOYEES EMP	
	WHERE
		<!--- Yakit- km ekranindan yapilan kayitlarin gelmemesi icin eklendi FB 20071025 --->
		ASSET_P_FUEL.FUEL_ID NOT IN (SELECT FUEL_ID FROM ASSET_P_KM_CONTROL WHERE FUEL_ID IS NOT NULL) AND
		ASSET_P.ASSETP_ID = ASSET_P_FUEL.ASSETP_ID AND
		DEPARTMENT.DEPARTMENT_ID = ASSET_P_FUEL.DEPARTMENT_ID AND
		DEPARTMENT.BRANCH_ID = BRANCH.BRANCH_ID AND
		<!--- Sadece yetkili olunan subeler gozuksun--->
		BRANCH.BRANCH_ID IN (SELECT BRANCH_ID FROM EMPLOYEE_POSITION_BRANCHES WHERE POSITION_CODE = #session.ep.position_code#) AND
		BRANCH.ZONE_ID = ZONE.ZONE_ID AND
		SETUP_DOCUMENT_TYPE.DOCUMENT_TYPE_ID = ASSET_P_FUEL.DOCUMENT_TYPE_ID AND
		SETUP_FUEL_TYPE.FUEL_ID = ASSET_P_FUEL.FUEL_TYPE_ID AND
        EMP.EMPLOYEE_ID = ASSET_P_FUEL.EMPLOYEE_ID
	ORDER BY
		ASSET_P_FUEL.FUEL_DATE DESC
</cfquery>
