<cfquery name="GET_COMPANY_PARTNER" datasource="#dsn#">
	SELECT
		COMPANY_PARTNER.COMPANY_PARTNER_NAME,
		COMPANY_PARTNER.COMPANY_PARTNER_SURNAME,
		COMPANY_PARTNER.COMPANY_ID,		
		COMPANY.NICKNAME,
		COMPANY.FULLNAME
	FROM
		COMPANY_PARTNER,
		COMPANY
	WHERE
		COMPANY_PARTNER.PARTNER_ID = #attributes.PARTNER_ID# AND
		COMPANY.COMPANY_ID = COMPANY_PARTNER.COMPANY_ID
</cfquery>
