<cfquery name="GET_COMPANY_INFO" datasource="#DSN#">
	SELECT 
		COMPANY_PARTNER.PARTNER_ID,
		COMPANY.NICKNAME,
		COMPANY_PARTNER.COMPANY_PARTNER_NAME,
		COMPANY_PARTNER.COMPANY_PARTNER_SURNAME
		COMPANY_PARTNER.COMPANY_ID
	FROM 
		COMPANY,
		COMPANY_PARTNER
	WHERE
		COMPANY_PARTNER.COMPANY_ID = COMPANY.COMPANY_ID
	AND 
		COMPANY_PARTNER.PARTNER_ID=#OUTSOURCE_PARTNER#
</cfquery>

