<cfquery name="GET_PRODUCT_PROPERTY" datasource="#DSN3#" maxrows="2">
	SELECT 
		PRODUCT_OPTIONS.*,
		PRODUCT_PROPERTY.*
	FROM 
		PRODUCT_OPTIONS,
		#dsn1_alias#.PRODUCT_PROPERTY PRODUCT_PROPERTY,
		STOCKS
	WHERE 
		STOCKS.PRODUCT_ID = PRODUCT_OPTIONS.PRODUCT_ID AND
		PRODUCT_PROPERTY.PROPERTY_ID = PRODUCT_OPTIONS.PROPERTY_ID AND 
		STOCKS.STOCK_ID = #attributes.stock_id#	AND
		PRODUCT_PROPERTY.PROPERTY_ID IS NOT NULL
	ORDER BY
		PRODUCT_OPTIONS.PROPERTY_ID 
</cfquery>
