<cfquery name="GET_POSITION" datasource="#dsn#">
	SELECT
		EMPLOYEE_NAME,
		EMPLOYEE_SURNAME,
		POSITION_NAME
	FROM
		EMPLOYEE_POSITIONS
	WHERE
		POSITION_CODE = #attributes.POSITION_CODE#
		AND
		POSITION_STATUS = 1
</cfquery>
