<cfquery name="GET_COMPANY_CAT" datasource="#DSN#">
	SELECT 
		COMPANYCAT_ID, 
		#dsn#.Get_Dynamic_Language(COMPANYCAT_ID,'#session.ep.language#','COMPANY_CAT','COMPANYCAT',NULL,NULL,COMPANY_CAT.COMPANYCAT) AS COMPANYCAT	 
	FROM 
		COMPANY_CAT
	ORDER BY
		COMPANYCAT
</cfquery>
