<!--- Unionsuz sekli  member/query/get_emp_par.cfm  mevcuttur. FB20070523  --->
<cfquery name="get_all_emp_par" datasource="#dsn#">
	SELECT 
		1 TYPE,
		EMPLOYEE_POSITIONS.POSITION_CODE MEMBER_ID,
		-1 COMPANY_ID,
		EMPLOYEE_POSITIONS.EMPLOYEE_NAME MEMBER_NAME,
		EMPLOYEE_POSITIONS.EMPLOYEE_SURNAME MEMBER_SURNAME,
		' ' NICKNAME,
		WORKGROUP_EMP_PAR.OUR_COMPANY_ID OUR_COMPANY,
		WORKGROUP_EMP_PAR.ROLE_ID ROLE,
		WORKGROUP_EMP_PAR.IS_MASTER MASTER
	FROM 
		EMPLOYEE_POSITIONS,
		WORKGROUP_EMP_PAR
	WHERE 
		EMPLOYEE_POSITIONS.POSITION_CODE = WORKGROUP_EMP_PAR.POSITION_CODE AND 
		<cfif isDefined("url.cpid")>
			WORKGROUP_EMP_PAR.COMPANY_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#url.cpid#"> AND
			WORKGROUP_EMP_PAR.COMPANY_ID IS NOT NULL AND
		<cfelseif isDefined("url.cid")>
			WORKGROUP_EMP_PAR.CONSUMER_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#url.cid#"> AND
			WORKGROUP_EMP_PAR.CONSUMER_ID IS NOT NULL AND
		</cfif>
		WORKGROUP_EMP_PAR.POSITION_CODE IS NOT NULL AND
		WORKGROUP_EMP_PAR.OUR_COMPANY_ID IS NOT NULL
	UNION
	SELECT 
		2 TYPE,
		COMPANY_PARTNER.PARTNER_ID MEMBER_ID,
		COMPANY_PARTNER.COMPANY_ID COMPANY_ID,
		COMPANY_PARTNER.COMPANY_PARTNER_NAME MEMBER_NAME,
		COMPANY_PARTNER.COMPANY_PARTNER_SURNAME MEMBER_SURNAME,
		COMPANY.NICKNAME NICKNAME,
		WORKGROUP_EMP_PAR.OUR_COMPANY_ID OUR_COMPANY,
		WORKGROUP_EMP_PAR.ROLE_ID ROLE,
		WORKGROUP_EMP_PAR.IS_MASTER MASTER
	FROM 
		COMPANY_PARTNER,
		COMPANY,
		WORKGROUP_EMP_PAR
	 WHERE 
		COMPANY_PARTNER.PARTNER_ID = WORKGROUP_EMP_PAR.PARTNER_ID AND
		COMPANY.COMPANY_ID = COMPANY_PARTNER.COMPANY_ID AND
		<cfif isDefined("url.cpid")>
			WORKGROUP_EMP_PAR.COMPANY_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#url.cpid#"> AND
			WORKGROUP_EMP_PAR.COMPANY_ID IS NOT NULL AND
		<cfelseif isDefined("url.cid")>
			WORKGROUP_EMP_PAR.CONSUMER_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#url.cid#"> AND
			WORKGROUP_EMP_PAR.CONSUMER_ID IS NOT NULL AND
		</cfif>
	 	WORKGROUP_EMP_PAR.PARTNER_ID IS NOT NULL AND
		WORKGROUP_EMP_PAR.OUR_COMPANY_ID IS NOT NULL
	 ORDER BY
		OUR_COMPANY,
		MEMBER_ID		
</cfquery>
