<cfquery name="GET_MEMBER_ANALYSIS" datasource="#DSN#">
	SELECT 
		ANALYSIS_ID,
		ANALYSIS_HEAD,
		ANALYSIS_PARTNERS	
	FROM 
		MEMBER_ANALYSIS,
		COMPANY_PARTNER
	WHERE
		MEMBER_ANALYSIS.IS_ACTIVE = 1 AND
		MEMBER_ANALYSIS.IS_PUBLISHED = 1 AND
		COMPANY_PARTNER.PARTNER_ID = #attributes.pid# AND
		MEMBER_ANALYSIS.ANALYSIS_PARTNERS LIKE '%,#get_partner.companycat_id#,%'
</cfquery>
