<cfquery name="GET_COMPANY_BRANCH" datasource="#DSN#">
		SELECT
			CB.COUNTY_ID,
			CB.COMPBRANCH_ID,
			CB.COMPBRANCH__NAME,
			CB.COMPBRANCH_ADDRESS,
			CB.COMPBRANCH_POSTCODE,
			CB.COMPBRANCH_TELCODE,
			CB.COMPBRANCH_TEL1,
			CB.COMPBRANCH_FAX,					 
			CB.SEMT,
			CB.CITY_ID,
			SC.COUNTY_NAME,
			STPC.CITY_NAME
		FROM 
			COMPANY_BRANCH CB,
			SETUP_COUNTY SC,
			SETUP_CITY STPC 
		WHERE 
			CB.COMPANY_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#url.compid#"> AND
			SC.COUNTY_ID = CB.COUNTY_ID AND
			STPC.CITY_ID = CB.CITY_ID	
	UNION	
		SELECT
			CB.COUNTY_ID,
			CB.COMPBRANCH_ID,
			CB.COMPBRANCH__NAME,
			CB.COMPBRANCH_ADDRESS,
			CB.COMPBRANCH_POSTCODE,
			CB.COMPBRANCH_TELCODE,
			CB.COMPBRANCH_TEL1,
			CB.COMPBRANCH_FAX,					 
			CB.SEMT,
			CB.CITY_ID,
			'' COUNTY_NAME,
			STPC.CITY_NAME
		FROM 
			COMPANY_BRANCH CB,
			SETUP_CITY STPC 
		WHERE 
			CB.COMPANY_ID =  <cfqueryparam cfsqltype="cf_sql_integer" value="#url.compid#"> AND
			STPC.CITY_ID = CB.CITY_ID AND
			CB.COUNTY_ID IS NULL		
	UNION
		SELECT
			CB.COUNTY_ID,
			CB.COMPBRANCH_ID,
			CB.COMPBRANCH__NAME,
			CB.COMPBRANCH_ADDRESS,
			CB.COMPBRANCH_POSTCODE,
			CB.COMPBRANCH_TELCODE,
			CB.COMPBRANCH_TEL1,
			CB.COMPBRANCH_FAX,					 
			CB.SEMT,
			CB.CITY_ID,
			'' COUNTY_NAME,
			'' CITY_NAME
		FROM 
			COMPANY_BRANCH CB
		WHERE 
			CB.COMPANY_ID =  <cfqueryparam cfsqltype="cf_sql_integer" value="#url.compid#"> AND
			CB.CITY_ID IS NULL AND
			CB.COUNTY_ID IS NULL
		ORDER BY
			COMPBRANCH__NAME
</cfquery>
