<cfquery name="GET_PARTNER_POSITIONS" datasource="#DSN#">
	SELECT
		PARTNER_POSITION_ID,
		#dsn#.Get_Dynamic_Language(PARTNER_POSITION_ID,'#session.ep.language#','SETUP_PARTNER_POSITION','PARTNER_POSITION',NULL,NULL,PARTNER_POSITION) AS PARTNER_POSITION
	FROM
		SETUP_PARTNER_POSITION WITH (NOLOCK)
	ORDER BY
		PARTNER_POSITION
</cfquery>
