<cfquery name="GET_EMPLOYE" datasource="#dsn#">
	SELECT
		E.EMPLOYEE_ID, 
		D.BRANCH_ID,
		E.EMPLOYEE_NAME, 
		E.EMPLOYEE_SURNAME 
	FROM
		EMPLOYEES E, 
		EMPLOYEE_POSITIONS EP,
		DEPARTMENT D
	WHERE
		E.EMPLOYEE_ID = EP.EMPLOYEE_ID 
		AND EP.DEPARTMENT_ID = D.DEPARTMENT_ID	
		<cfif isDefined("URL.DEPT")>
			AND BRANCH_ID=#URL.DEPT#
		</cfif>
</cfquery>
