<cfquery name="GET_PRO_MATERIAL_DETAIL" datasource="#DSN#">
	SELECT 
		PRO_MATERIAL.*
	FROM 
		PRO_MATERIAL,
		PRO_MATERIAL_ROW
	WHERE 
		PRO_MATERIAL.PRO_MATERIAL_ID = #attributes.UPD_ID#
		AND PRO_MATERIAL_ROW.PRO_MATERIAL_ID = PRO_MATERIAL.PRO_MATERIAL_ID
</cfquery>

