<cfquery name="GET_ORDER_PRODUCTS" datasource="#dsn3#">
	SELECT
		ORR.*,
		STOCKS.STOCK_CODE,
		STOCKS.BARCOD,
		STOCKS.MANUFACT_CODE
	FROM 
		ORDER_ROW ORR,
		PRODUCT,
		STOCKS
	WHERE
		ORR.ORDER_ID = #attributes.ORDER_ID# AND
		STOCKS.STOCK_ID = ORR.STOCK_ID AND
		PRODUCT.PRODUCT_ID = STOCKS.PRODUCT_ID		
</cfquery>
