<!-- Description : Wodiba API tanım tablosuna şirket bazında çalışması için alanlar eklendi.
Developer: Mahmut Çifçi
Company : Gramoni
Destination: Main -->
<querytag>
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WODIBA_API_DEFINITIONS' AND COLUMN_NAME = 'DEF_ID')
    BEGIN
        ALTER TABLE WODIBA_API_DEFINITIONS ADD [DEF_ID] [int] IDENTITY(1,1) NOT NULL
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WODIBA_API_DEFINITIONS' AND COLUMN_NAME = 'OUR_COMPANY_ID')
    BEGIN
        ALTER TABLE WODIBA_API_DEFINITIONS ADD [OUR_COMPANY_ID] [int] NULL
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WODIBA_API_DEFINITIONS' AND COLUMN_NAME = 'REC_USER')
    BEGIN
        ALTER TABLE WODIBA_API_DEFINITIONS ADD [REC_USER] [int] NULL
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WODIBA_API_DEFINITIONS' AND COLUMN_NAME = 'REC_DATE')
    BEGIN
        ALTER TABLE WODIBA_API_DEFINITIONS ADD [REC_DATE] [datetime] NULL
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WODIBA_API_DEFINITIONS' AND COLUMN_NAME = 'REC_IP')
    BEGIN
        ALTER TABLE WODIBA_API_DEFINITIONS ADD [REC_IP] [nvarchar](50) NULL
    END;
</querytag>