<!-- Description : Process template tablosuna yeni kayıt.
Developer: Melek KOCABEY
Company : Workcube
Destination: Main -->
<querytag>
    IF NOT EXISTS (SELECT WRK_PROCESS_TEMPLATE_NAME FROM WRK_PROCESS_TEMPLATES WHERE WRK_PROCESS_TEMPLATE_NAME = 'budget_compliance_check.cfm')
    BEGIN
        INSERT [WRK_PROCESS_TEMPLATES] ( [WRK_PROCESS_TEMPLATE_NAME], [IS_ACTIVE], [IS_ACTION], [IS_DISPLAY], [IS_STAGE], [IS_MAIN], [BEST_PRACTISE_CODE], [PROCESS_TEMPLATE_DETAIL], [WORKCUBE_PRODUCT_ID], [LICENCE_TYPE], [RELATED_WO], [AUTHOR_PARTNER_ID], [AUTHOR_NAME], [PROCESS_TEMPLATE_ICON_PATH], [PROCESS_TEMPLATE_PATH], [PROCESS_TEMPLATE_SECTORS], [WRK_PROCESS_STAGE], [MODULE_ID], [PROCESS_TEMPLATE_VERSION], [RECORD_DATE], [RECORD_EMP], [RECORD_IP], [UPDATE_DATE], [UPDATE_EMP], [UPDATE_IP]) VALUES (N'budget_compliance_check.cfm', 1, 1, 0, 0, 0, N'', N'<div>Bütçe&nbsp;UYGUNLUK&nbsp;KONTROLU&nbsp;süreci amaçlı yazılmıştır.Yetersiz bütçe olduğu durumda ilgili birimlere mail atılır.</div><div><strong>Örnek Kullanım::</strong></div><div>kontrol_surec : 42 &gt;&gt;&gt;&nbsp;bu değer hangi süreçte kontrol edilecek ise o sürecin id si verilir. Bütçe Kontrol aşaması gibi</div><div>onay_surec : 162 &gt;&gt;&gt;&nbsp;bu değer hangi süreçte onay verilecek ise o sürecin id si verilir.Bütçe Onay aşaması gibi</div>', NULL, 1, N'purchase.list_order', NULL, N'Melek KOCABEY', N'', N'budget_compliance_check.cfm', N'41,1,2,56,42,3,4,43,57,44,62,5,6,7,45,8,9,10,11,12,58,13,14,15,16,46,47,17,18,48,59,19,20,21,22,23,24,25,49,50,26,27,28,51,52,60,29,30,53,61,31,54,32,33,34,55,35,36,37,38,39,40', 166, 11, N'', CAST(N'2020-12-15T12:32:13.000' AS DateTime), 15, N'127.0.0.1', CAST(N'2020-12-16T12:57:16.000' AS DateTime), 15, N'127.0.0.1')
    END;
    IF NOT EXISTS (SELECT WRK_PROCESS_TEMPLATE_NAME FROM WRK_PROCESS_TEMPLATES WHERE WRK_PROCESS_TEMPLATE_NAME = 'purchase_order_project_kontrol.cfm')
    BEGIN
        INSERT [WRK_PROCESS_TEMPLATES] ( [WRK_PROCESS_TEMPLATE_NAME], [IS_ACTIVE], [IS_ACTION], [IS_DISPLAY], [IS_STAGE], [IS_MAIN], [BEST_PRACTISE_CODE], [PROCESS_TEMPLATE_DETAIL], [WORKCUBE_PRODUCT_ID], [LICENCE_TYPE], [RELATED_WO], [AUTHOR_PARTNER_ID], [AUTHOR_NAME], [PROCESS_TEMPLATE_ICON_PATH], [PROCESS_TEMPLATE_PATH], [PROCESS_TEMPLATE_SECTORS], [WRK_PROCESS_STAGE], [MODULE_ID], [PROCESS_TEMPLATE_VERSION], [RECORD_DATE], [RECORD_EMP], [RECORD_IP], [UPDATE_DATE], [UPDATE_EMP], [UPDATE_IP]) VALUES (N'purchase_order_project_kontrol.cfm', 1, 0, 1, 1, 0, N'', N'<div><div>&nbsp; &nbsp; Satınalma&nbsp;siparişinde&nbsp;proje&nbsp;kontrol için yazılmıştır. Seçilen projenin XML de ki katogorilere bağlı proje listesi getiriyor ve bu listede siparişe bağlı talepde varsa ve aynı ise kayıt işlem gerçekleşiyor değil ise&nbsp; kayıt işlemi gerçekleşmiyor ve uyarı veriyor</div></div>', NULL, 2, N'purchase.list_order', NULL, N'Melek KOCABEY', N'', N'purchase_order_project_kontrol.cfm', N'41,1,2,56,42,3,4,43,57,44,62,5,6,7,45,8,9,10,11,12,58,13,14,15,16,46,47,17,18,48,59,19,20,21,22,23,24,25,49,50,26,27,28,51,52,60,29,30,53,61,31,54,32,33,34,55,35,36,37,38,39,40', 166, 11, N'', CAST(N'2020-12-16T13:02:39.000' AS DateTime), 15, N'127.0.0.1', CAST(N'2020-12-19T00:21:31.000' AS DateTime), 15, N'127.0.0.1')     
    END;
    IF NOT EXISTS (SELECT WRK_PROCESS_TEMPLATE_NAME FROM WRK_PROCESS_TEMPLATES WHERE WRK_PROCESS_TEMPLATE_NAME = 'budget_transfer_display_file.cfm')
    BEGIN
         INSERT [WRK_PROCESS_TEMPLATES] ( [WRK_PROCESS_TEMPLATE_NAME], [IS_ACTIVE], [IS_ACTION], [IS_DISPLAY], [IS_STAGE], [IS_MAIN], [BEST_PRACTISE_CODE], [PROCESS_TEMPLATE_DETAIL], [WORKCUBE_PRODUCT_ID], [LICENCE_TYPE], [RELATED_WO], [AUTHOR_PARTNER_ID], [AUTHOR_NAME], [PROCESS_TEMPLATE_ICON_PATH], [PROCESS_TEMPLATE_PATH], [PROCESS_TEMPLATE_SECTORS], [WRK_PROCESS_STAGE], [MODULE_ID], [PROCESS_TEMPLATE_VERSION], [RECORD_DATE], [RECORD_EMP], [RECORD_IP], [UPDATE_DATE], [UPDATE_EMP], [UPDATE_IP]) VALUES (N'budget_transfer_display_file.cfm', 1, 0, 1, 1, 0, N'', N'', NULL, 1, N'budget.budget_transfer_demand', NULL, N'Melek KOCABEY', N'', N'budget_transfer_display_file.cfm', N'41,1,2,56,42,3,4,43,57,5,6,7', 166, 46, N'', CAST(N'2021-01-16T12:53:08.000' AS DateTime), 15, N'127.0.0.1', CAST(N'2021-01-18T17:38:40.000' AS DateTime), 15, N'127.0.0.1')
    END;
    IF NOT EXISTS (SELECT WRK_PROCESS_TEMPLATE_NAME FROM WRK_PROCESS_TEMPLATES WHERE WRK_PROCESS_TEMPLATE_NAME = 'bütce_transfer_main_action.cfm')
    BEGIN
        INSERT [WRK_PROCESS_TEMPLATES] ( [WRK_PROCESS_TEMPLATE_NAME], [IS_ACTIVE], [IS_ACTION], [IS_DISPLAY], [IS_STAGE], [IS_MAIN], [BEST_PRACTISE_CODE], [PROCESS_TEMPLATE_DETAIL], [WORKCUBE_PRODUCT_ID], [LICENCE_TYPE], [RELATED_WO], [AUTHOR_PARTNER_ID], [AUTHOR_NAME], [PROCESS_TEMPLATE_ICON_PATH], [PROCESS_TEMPLATE_PATH], [PROCESS_TEMPLATE_SECTORS], [WRK_PROCESS_STAGE], [MODULE_ID], [PROCESS_TEMPLATE_VERSION], [RECORD_DATE], [RECORD_EMP], [RECORD_IP], [UPDATE_DATE], [UPDATE_EMP], [UPDATE_IP]) VALUES (N'bütce_transfer_main_action.cfm', 1, 1, 0, 0, 1, N'', N'', NULL, 2, N'budget.budget_transfer_demand', NULL, N'Melek KOCABEY', N'', N'bütce_transfer_main_action.cfm', N'41,1,2,56,42,3,4,43,5,6', 166, 46, N'', CAST(N'2021-01-18T17:31:19.000' AS DateTime), 15, N'127.0.0.1', CAST(N'2021-01-18T17:38:57.000' AS DateTime), 15, N'127.0.0.1')
    END;
</querytag>
