<!-- Description : Watalogy kategori WRO
Developer: Emine Yılmaz
Company : Workcube
Destination: Product -->

<querytag>      
    IF  EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WATALOGY_GOOGLE_PRODUCT_CAT' AND TABLE_SCHEMA = '@_dsn_main_@')
    BEGIN   
        ALTER SCHEMA @_dsn_product_@ TRANSFER @_dsn_main_@.WATALOGY_GOOGLE_PRODUCT_CAT
    END;
    IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' and TABLE_NAME='WATALOGY_GOOGLE_PRODUCT_CAT' AND COLUMN_NAME='CATEGORY_NAME' )
    BEGIN   
        ALTER TABLE WATALOGY_GOOGLE_PRODUCT_CAT ADD CATEGORY_NAME nvarchar(255) NULL 
    END;
    IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' and TABLE_NAME='WATALOGY_GOOGLE_PRODUCT_CAT' AND COLUMN_NAME='HIERARCHY' )
    BEGIN   
        ALTER TABLE WATALOGY_GOOGLE_PRODUCT_CAT ADD HIERARCHY nvarchar(255) NULL 
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WATALOGY_GOOGLE_PRODUCT_CAT' AND TABLE_SCHEMA = '@_dsn_product_@')
    BEGIN
    CREATE TABLE [WATALOGY_GOOGLE_PRODUCT_CAT](	  
        [GOOGLE_PRODUCT_CAT_ID] float NULL, 
        [CATEGORY1] nvarchar(255) NULL, 
        [CATEGORY2] nvarchar(255) NULL, 
        [CATEGORY3] nvarchar(255) NULL, 
        [CATEGORY4] nvarchar(255) NULL, 
        [CATEGORY5] nvarchar(255) NULL,
        [CATEGORY6] nvarchar(255) NULL, 
        [CATEGORY7] nvarchar(255) NULL, 
        [CATEGORY_NAME] nvarchar(255) NULL, 
        [HIERARCHY] nvarchar(255) NULL, 
        [WATALOGY_PRODUCT_CAT_ID] int NOT NULL IDENTITY(1,1), 
        CONSTRAINT [PK_WATALOGY_GOOGLE_PRODUCT_CAT] PRIMARY KEY ([WATALOGY_PRODUCT_CAT_ID] ASC)
    );
    END;
</querytag>