<!-- Description : W3 Menu Designer icin WRK_MENU,EMPLOYEE_POSITIONS,USER_GROUP tablolarina yeni alanlar eklenmistir.
Developer: Semih Akartuna
Company : YAZILIMSA
Destination: Main -->
<querytag>
       IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='WRK_MENU' AND INFORMATION_SCHEMA.TABLES.TABLE_SCHEMA <> 'dbo' )
        BEGIN 
            IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_MENU' AND COLUMN_NAME ='WRK_MODUL_ID' AND TABLE_SCHEMA <> 'dbo' )
            BEGIN 
            ALTER TABLE WRK_MENU DROP COLUMN WRK_MODUL_ID
            END;

            IF EXISTS ( SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_MENU' AND COLUMN_NAME = 'DICTIONARY_ID' AND TABLE_SCHEMA <> 'dbo')
            BEGIN
            ALTER TABLE WRK_MENU DROP COLUMN DICTIONARY_ID
            END;

            IF EXISTS ( SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_MENU' AND COLUMN_NAME = 'FUSEACTION' AND TABLE_SCHEMA <> 'dbo')
            BEGIN
            ALTER TABLE WRK_MENU DROP COLUMN FUSEACTION
            END;

            IF EXISTS ( SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_MENU' AND COLUMN_NAME = 'FUSEACTION_ADD' AND TABLE_SCHEMA <> 'dbo')
            BEGIN
            ALTER TABLE WRK_MENU DROP COLUMN FUSEACTION_ADD
            END;

            IF EXISTS ( SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_MENU' AND COLUMN_NAME = 'WRK_MENU_WO' AND TABLE_SCHEMA <> 'dbo')
            BEGIN
            ALTER TABLE WRK_MENU DROP COLUMN WRK_MENU_WO
            END;

            IF EXISTS ( SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_MENU' AND COLUMN_NAME = 'WRK_MENU_DETAIL' AND TABLE_SCHEMA <> 'dbo')
            BEGIN
            ALTER TABLE WRK_MENU DROP COLUMN WRK_MENU_DETAIL
            END;
                        
            IF EXISTS ( SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_MENU' AND COLUMN_NAME = 'WRK_MODUL_NAME' AND TABLE_SCHEMA <> 'dbo')
            BEGIN
            ALTER TABLE WRK_MENU DROP COLUMN WRK_MODUL_NAME
            END;

            IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_MENU' AND COLUMN_NAME = 'MENU_STATUS')
            BEGIN
            ALTER TABLE WRK_MENU ADD
            MENU_STATUS int NULL
            END;

            IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_MENU' AND COLUMN_NAME = 'BEST_PRACTISE')
            BEGIN
            ALTER TABLE WRK_MENU ADD
            BEST_PRACTISE text NULL
            END;

            IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_MENU' AND COLUMN_NAME = 'AUTHOR')
            BEGIN
            ALTER TABLE WRK_MENU ADD
            AUTHOR nvarchar(140) NULL
            END;

            IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_MENU' AND COLUMN_NAME = 'MENU_JSON')
            BEGIN
            ALTER TABLE WRK_MENU ADD
            MENU_JSON text NULL
            END;
                    
            IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EMPLOYEE_POSITIONS' AND COLUMN_NAME = 'WRK_MENU')
            BEGIN
            ALTER TABLE EMPLOYEE_POSITIONS ADD
            WRK_MENU nvarchar(50) NULL
            END;

            IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'USER_GROUP' AND COLUMN_NAME = 'WRK_MENU')
            BEGIN
            ALTER TABLE USER_GROUP ADD
            WRK_MENU nvarchar(500) NULL
            END;
        END 
        ELSE
        BEGIN

        CREATE TABLE [WRK_MENU](
            [WRK_MENU_ID] [int] IDENTITY(1,1) NOT NULL,
            [WRK_MENU_NAME] [nvarchar](250) NULL,
            [RECORD_DATE] [datetime] NULL,
            [UPDATE_DATE] [datetime] NULL,
            [MENU_STATUS] [int] NULL,
            [BEST_PRACTISE] [text] NULL,
            [AUTHOR] [nvarchar](140) NULL,
            [USER_GROUP] [text] NULL,
            [MENU_JSON] [text] NULL,
         CONSTRAINT [PK_WRK_MENU] PRIMARY KEY CLUSTERED 
        (
            [WRK_MENU_ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
        
        END;
</querytag>
