<!-- Description : Proje ile ilgili hareket görmüş ürünler getirilirken giriş proje kontrol edilecek şekilde düzenleme yapıldı.
Developer: Sevim Çelik
Company : Birsis
Destination: Period -->
<querytag>
    ALTER VIEW [GET_ACTION_PROJECT_PRODUCTS] AS
		SELECT DISTINCT
			SFR.STOCK_ID,
			ISNULL(SF.PROJECT_ID,SF.PROJECT_ID_IN) PROJECT_ID,
			SF.FIS_TYPE AS PROCESS_TYPE,
			SF.FIS_DATE AS ACTION_DATE,
			2 AS PURCHASE_SALES,
			'STOCK_FIS' AS ACTION_TYPE
		FROM
			@_dsn_period_@.STOCK_FIS SF,
			@_dsn_period_@.STOCK_FIS_ROW SFR
		WHERE
			SF.FIS_ID = SFR.FIS_ID	
			AND (SF.PROJECT_ID IS NOT NULL OR SF.PROJECT_ID_IN IS NOT NULL)
	UNION
		SELECT DISTINCT
			SHIP_ROW.STOCK_ID,
			ISNULL(SHIP.PROJECT_ID,SHIP.PROJECT_ID_IN) PROJECT_ID,
			SHIP.SHIP_TYPE AS PROCESS_TYPE,
			SHIP.SHIP_DATE AS ACTION_DATE,
			SHIP.PURCHASE_SALES,
			'SHIP' AS ACTION_TYPE
		FROM
			@_dsn_period_@.SHIP,
			@_dsn_period_@.SHIP_ROW
		WHERE
			SHIP.SHIP_ID = SHIP_ROW.SHIP_ID
			AND SHIP.IS_SHIP_IPTAL=0
			AND (SHIP.PROJECT_ID_IN IS NOT NULL OR SHIP.PROJECT_ID IS NOT NULL)
	UNION
		SELECT DISTINCT
			INVOICE_ROW.STOCK_ID,
			INVOICE.PROJECT_ID,
			INVOICE.INVOICE_CAT AS PROCESS_TYPE,
			INVOICE.INVOICE_DATE AS ACTION_DATE,
			INVOICE.PURCHASE_SALES,
			'INVOICE' AS ACTION_TYPE
		FROM
			@_dsn_period_@.INVOICE,
			@_dsn_period_@.INVOICE_ROW
		WHERE
			INVOICE.INVOICE_ID = INVOICE_ROW.INVOICE_ID
			AND INVOICE.IS_IPTAL = 0
			AND INVOICE.PROJECT_ID IS NOT NULL
			AND INVOICE_CAT <> 67
			AND INVOICE_CAT <> 69
	UNION
		SELECT DISTINCT
			ORR.STOCK_ID,
			ORD.PROJECT_ID,
			0 AS PROCESS_TYPE,
			ORD.ORDER_DATE AS ACTION_DATE,
			0 AS PURCHASE_SALES,
			'ORDER_SALE' AS ACTION_TYPE
		FROM
			@_dsn_company_@.ORDERS ORD,
			@_dsn_company_@.ORDER_ROW ORR
		WHERE
			ORR.ORDER_ID = ORD.ORDER_ID
			AND ORD.PROJECT_ID IS NOT NULL
			AND ORD.ORDER_STATUS = 1
			AND ORD.PURCHASE_SALES=0
	UNION
		SELECT DISTINCT
			ORR.STOCK_ID,
			ORD.PROJECT_ID,
			0 AS PROCESS_TYPE,
			ORD.ORDER_DATE AS ACTION_DATE,
			1 AS PURCHASE_SALES,
			'ORDERS' AS ACTION_TYPE
		FROM
			@_dsn_company_@.ORDERS ORD,
			@_dsn_company_@.ORDER_ROW ORR
		WHERE
			ORR.ORDER_ID = ORD.ORDER_ID
			AND ORD.PROJECT_ID IS NOT NULL
			AND ORD.ORDER_STATUS = 1
			AND
			(	
				(ORD.PURCHASE_SALES = 1 AND ORD.ORDER_ZONE = 0)  	OR
				(ORD.PURCHASE_SALES = 0 AND ORD.ORDER_ZONE = 1)	
			)
	UNION
		SELECT DISTINCT
			PMR.STOCK_ID,
			PM.PROJECT_ID,
			0 AS PROCESS_TYPE,
			'' AS ACTION_DATE,
			2 AS PURCHASE_SALES,
			'PROMATERIAL' AS ACTION_TYPE
		FROM
			@_dsn_main_@.PRO_MATERIAL PM,
			@_dsn_main_@.PRO_MATERIAL_ROW PMR
		WHERE 
			PM.PRO_MATERIAL_ID=PMR.PRO_MATERIAL_ID AND
			PM.PROJECT_ID IS NOT NULL
	UNION
		SELECT DISTINCT
			INDR.STOCK_ID,
			IND.PROJECT_ID,
			0 AS PROCESS_TYPE,
			IND.RECORD_DATE AS ACTION_DATE,
			2 AS PURCHASE_SALES,
			'INTERNAL' AS ACTION_TYPE
		FROM
			@_dsn_company_@.INTERNALDEMAND IND,
			@_dsn_company_@.INTERNALDEMAND_ROW INDR
		WHERE
			INDR.I_ID = IND.INTERNAL_ID
			AND IND.PROJECT_ID IS NOT NULL
	UNION
		SELECT DISTINCT
			PORD.STOCK_ID,
			PORD.PROJECT_ID,
			0 AS PROCESS_TYPE,
			PORD.START_DATE AS ACTION_DATE,
			2 AS PURCHASE_SALES,
			'PRODUCTION_ORDERS' AS ACTION_TYPE
		FROM
			@_dsn_company_@.PRODUCTION_ORDERS PORD
		WHERE
			PORD.PROJECT_ID IS NOT NULL
</querytag>