<!-- Description : WRK_MESSAGE_GROUP ve WRK_MESSAGE_GROUP_EMP tabloları oluşturuldu
Developer: Uğur Hamurpet
Company : Workcube
Destination: Main -->
<querytag>
    IF (NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'WRK_MESSAGE_GROUP' ) )
    BEGIN

        CREATE TABLE [WRK_MESSAGE_GROUP](
            [WG_ID] [int] IDENTITY(1,1) NOT NULL,
            [WG_NAME] [nvarchar](500) NULL,
            [WG_ACTION_WO] [nvarchar](200) NULL,
            [WG_ACTION_WO_EVENT] [nvarchar](50) NULL,
            [WG_ACTION_PARAMETER] [nvarchar](200) NULL,
            [WG_ACTION_ID] [int] NULL,
            [RECORD_EMP] [int] NULL,
            [RECORD_DATE] [datetime] NULL,
            [RECORD_IP] [nvarchar](50) NULL,
            [UPDATE_EMP] [int] NULL,
            [UPDATE_DATE] [datetime] NULL,
            [UPDATE_IP] [nvarchar](50) NULL,
        CONSTRAINT [PK_WRK_MESSAGE_GROUP] PRIMARY KEY CLUSTERED 
        (
            [WG_ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ) ON [PRIMARY]
    
    END;

    IF (NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'WRK_MESSAGE_GROUP_EMP' ) )
    BEGIN

        CREATE TABLE [WRK_MESSAGE_GROUP_EMP](
            [WGE_ID] [int] IDENTITY(1,1) NOT NULL,
            [WG_ID] [int] NOT NULL,
            [EMPLOYEE_ID] [int] NULL,
        CONSTRAINT [PK_WRK_MESSAGE_GROUP_EMP] PRIMARY KEY CLUSTERED 
        (
            [WGE_ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ) ON [PRIMARY]
    
    END;

    IF (NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'WRK_MESSAGE_GROUP_EMP_MSG' ) )
    BEGIN

        CREATE TABLE [WRK_MESSAGE_GROUP_EMP_MSG](
            [WGEM_ID] [int] IDENTITY(1,1) NOT NULL,
            [WG_ID] [int] NOT NULL,
            [WRK_MESSAGE_ID] [int] NOT NULL,
            [EMPLOYEE_ID] [int] NOT NULL,
            [IS_ALERTED] [bit] NULL CONSTRAINT [DF_WRK_MESSAGE_GROUP_EMP_MSG_IS_ALERTED]  DEFAULT ((0)),
            [IS_DELETED] [bit] NULL CONSTRAINT [DF_WRK_MESSAGE_GROUP_EMP_MSG_IS_DELETED]  DEFAULT ((0)),
        CONSTRAINT [PK_WRK_MESSAGE_GROUP_EMP_MSG] PRIMARY KEY CLUSTERED 
        (
            [WGEM_ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ) ON [PRIMARY]
    
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_MESSAGE' AND COLUMN_NAME = 'WARNING_PARENT_ID')
    BEGIN
        ALTER TABLE WRK_MESSAGE ADD WARNING_PARENT_ID int NULL
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_MESSAGE' AND COLUMN_NAME = 'IS_DELETED')
    BEGIN
        ALTER TABLE WRK_MESSAGE ADD IS_DELETED bit NULL
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_MESSAGE' AND COLUMN_NAME = 'IS_DELIVERED')
    BEGIN
        ALTER TABLE WRK_MESSAGE ADD IS_DELIVERED bit NULL
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_MESSAGE' AND COLUMN_NAME = 'DELETED_DATE')
    BEGIN
        ALTER TABLE WRK_MESSAGE ADD DELETED_DATE datetime NULL
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_MESSAGE' AND COLUMN_NAME = 'WG_ID')
    BEGIN
        ALTER TABLE WRK_MESSAGE ADD WG_ID int NULL
    END;

</querytag>