<!-- Description : SETUP_PROCESS_CAT tablosuna IS_EXPENSING_OIV VE IS_EXPENSING_OIV alanları eklendi
Developer: Pınar Yıldız
Company : Workcube
Destination: Company -->
<querytag>
    IF NOT EXISTS( SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'SETUP_PROCESS_CAT' AND COLUMN_NAME = 'IS_EXPENSING_OIV' )
    BEGIN
        ALTER TABLE SETUP_PROCESS_CAT ADD IS_EXPENSING_OIV BIT NULL DEFAULT 0
    END
    IF NOT EXISTS( SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'SETUP_PROCESS_CAT' AND COLUMN_NAME = 'IS_EXPENSING_OTV' )
    BEGIN
        ALTER TABLE SETUP_PROCESS_CAT ADD IS_EXPENSING_OTV BIT NULL DEFAULT 0
    END
</querytag>