<!-- Description : USER_FRIENDLY_URLS tablosuna protein_page, protein_event, protein_site  alanı açıldı
Developer: Semih Akartuna
Company : Yazılımsa
Destination: main -->
<querytag>
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'USER_FRIENDLY_URLS' AND COLUMN_NAME = 'PROTEIN_PAGE' AND TABLE_SCHEMA = '@_dsn_@')
    BEGIN
        ALTER TABLE USER_FRIENDLY_URLS ADD
        PROTEIN_PAGE int NULL
    END;   
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'USER_FRIENDLY_URLS' AND COLUMN_NAME = 'PROTEIN_EVENT' AND TABLE_SCHEMA = '@_dsn_@')
    BEGIN
        ALTER TABLE USER_FRIENDLY_URLS ADD
        PROTEIN_EVENT nvarchar(50) NULL
    END; 
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'USER_FRIENDLY_URLS' AND COLUMN_NAME = 'PROTEIN_SITE' AND TABLE_SCHEMA = '@_dsn_@')
    BEGIN
        ALTER TABLE USER_FRIENDLY_URLS ADD
        PROTEIN_SITE int NULL
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'USER_FRIENDLY_URLS' AND COLUMN_NAME = 'STATUS' AND TABLE_SCHEMA = '@_dsn_@')
    BEGIN
        ALTER TABLE USER_FRIENDLY_URLS ADD
        STATUS int NULL
    END; 
</querytag>