<!-- Description : IS_INVENTORY_VALUATION alanı açıldı.INVENTORY_VALUATION tablosu oluşturuldu.
Developer: Melek KOCABEY
Company : Workcube
Destination: Company -->
<querytag>
    IF NOT EXISTS( SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'SETUP_PROCESS_CAT' AND COLUMN_NAME = 'IS_INVENTORY_VALUATION' )
    BEGIN
        ALTER TABLE SETUP_PROCESS_CAT ADD IS_INVENTORY_VALUATION BIT NULL DEFAULT 0
    END;

    IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '@_dsn_company_@' and TABLE_NAME='INVENTORY_VALUATION ')
    BEGIN
        CREATE TABLE [INVENTORY_VALUATION ](
            [INVENTORY_VALUATION_ID] [int] IDENTITY(1,1) NOT NULL,
            [OLD_INVENTORY_ID] [int] NULL,
            [NEW_INVENTORY_ID] [int] NULL,
            [OLD_INVENTORY_MONEY] [float] NULL,
            [NEW_INVENTORY_MONEY] [float] NULL,
            [VALUATION_DATE] [datetime] NULL,
            [VALUATION_METHOD] [int] NULL, 
            [AMORTIZATION_TYPE] [int] NULL,
            [AMORTIZATION_COUNT] [int] NULL,
            [USEABLE_TIME] [int] NULL,
            [PROCESS_CAT] [int] NULL,
            [ACTION_TYPE] [int]NULL,
            [PROCESS_STAGE ] [int] NULL,
            [PAPER_NO] [nvarchar](100) NULL,
            [VALUATION_EMP_ID] [int] NULL,
            [VALUATION_DETAIL] [nvarchar](500) NULL,
            [NEW_VALUE_MONEY] [float] NULL,
            [NEW_VALUE_OTHER_MONEY] [float] NULL,
            [RECORD_DATE] [datetime] NULL,
            [RECORD_EMP] [int] NULL,
            [RECORD_IP] [nvarchar](50) NULL,
            [UPDATE_DATE] [datetime] NULL,
            [UPDATE_EMP] [int] NULL,
            [UPDATE_IP] [nvarchar](50) NULL,
        CONSTRAINT [PK__WRK_EXTE__4CCFB490590FD432] PRIMARY KEY CLUSTERED 
        (
            [INVENTORY_VALUATION_ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ) ON [PRIMARY]
    END;

    IF NOT EXISTS( SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'INVENTORY_AMORTIZATON' AND COLUMN_NAME = 'INVENTORY_VALUATION_ID' )
    BEGIN
        ALTER TABLE INVENTORY_AMORTIZATON ADD INVENTORY_VALUATION_ID INT NULL
    END;
    IF NOT EXISTS( SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'INVENTORY_AMORTIZATON_IFRS' AND COLUMN_NAME = 'INVENTORY_VALUATION_ID' )
    BEGIN
        ALTER TABLE INVENTORY_AMORTIZATON_IFRS ADD INVENTORY_VALUATION_ID INT NULL
    END;
</querytag>