<!-- Description : Model Tablosuna Solution ve Family bilgileri eklendi
Developer: Halit Yurttaş
Company : Workcube
Destination: Main -->
<querytag>
    IF ( EXISTS ( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'WRK_MODEL' AND INFORMATION_SCHEMA.TABLES.TABLE_SCHEMA <> 'dbo' ) )
    BEGIN
        
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_MODEL' AND COLUMN_NAME = 'RECORD_IP')
        BEGIN
        ALTER TABLE WRK_MODEL ADD
        RECORD_IP NVARCHAR(50) NULL
        END;
    
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_MODEL' AND COLUMN_NAME = 'RECORD_EMP')
        BEGIN
        ALTER TABLE WRK_MODEL ADD
        RECORD_EMP INT NULL
        END;
    
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_MODEL' AND COLUMN_NAME = 'RECORD_DATE')
        BEGIN
        ALTER TABLE WRK_MODEL ADD
        RECORD_DATE DATETIME NULL
        END;
    
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_MODEL' AND COLUMN_NAME = 'UPDATE_IP')
        BEGIN
        ALTER TABLE WRK_MODEL ADD
        UPDATE_IP NVARCHAR(50) NULL
        END;
    
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_MODEL' AND COLUMN_NAME = 'UPDATE_EMP')
        BEGIN
        ALTER TABLE WRK_MODEL ADD
        UPDATE_EMP INT NULL
        END;
    
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_MODEL' AND COLUMN_NAME = 'UPDATE_EMP')
        BEGIN
        ALTER TABLE WRK_MODEL ADD
        UPDATE_EMP INT NULL
        END;
    
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_MODEL' AND COLUMN_NAME = 'UPDATE_DATE')
        BEGIN
        ALTER TABLE WRK_MODEL ADD
        UPDATE_DATE DATETIME NULL
        END;
    
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_MODEL' AND COLUMN_NAME = 'MODELSOLUTION')
        BEGIN
        ALTER TABLE WRK_MODEL ADD
        MODELSOLUTION nvarchar(100) NULL
        END;
    
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_MODEL' AND COLUMN_NAME = 'MODELFAMILY')
        BEGIN
        ALTER TABLE WRK_MODEL ADD
        MODELFAMILY nvarchar(100) NULL
        END;
    
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_MODEL' AND COLUMN_NAME = 'MODELSOLUTIONID')
        BEGIN
        ALTER TABLE WRK_MODEL ADD
        MODELSOLUTIONID int NULL
        END;
    
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_MODEL' AND COLUMN_NAME = 'MODELFAMILYID')
        BEGIN
        ALTER TABLE WRK_MODEL ADD
        MODELFAMILYID int NULL
        END
        
    END
    ELSE
    BEGIN
        CREATE TABLE [WRK_MODEL](
            [MODELID] [int] IDENTITY(1,1) NOT NULL,
            [MODEL_FUSEACTION] [nvarchar](250) NULL,
            [MODELNAME] [nvarchar](100) NULL,
            [MODELLANG] [int] NULL,
            [MODELTYPE] [int] NULL,
            [MODELINDEX] [int] NULL,
            [MODELRELATION] [nvarchar](100) NULL,
            [MODELMETHOD] [nvarchar](250) NULL,
            [MODELMAXROW] [int] NULL,
            [MODELADDROW] [int] NULL,
            [MODELDEPEND] [bit] NULL,
            [MODELJSON] [nvarchar](max) NULL,
            [MODELCOMPONENT] [nvarchar](max) NULL,
            [MODELSOLUTION] [nvarchar](100) NULL,
            [MODELFAMILY] [nvarchar](100) NULL,
            [MODELSOLUTIONID] [int] NULL,
            [MODELFAMILYID] [int] NULL,
         CONSTRAINT [PK_MODELSLOOPS] PRIMARY KEY CLUSTERED 
        (
            [MODELID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
    END; 
</querytag>