<!-- Description : Widget Tablosuna Solution ve Family bilgileri eklendi
Developer: Halit Yurttaş
Company : Workcube
Destination: Main -->
<querytag>
    IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'WRK_WIDGET' AND INFORMATION_SCHEMA.TABLES.TABLE_SCHEMA <> 'dbo')
    BEGIN
    
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_WIDGET' AND COLUMN_NAME = 'WIDGET_DESCRIPTION')
        BEGIN
        ALTER TABLE WRK_WIDGET ADD
        WIDGET_DESCRIPTION nvarchar(MAX) NULL
        END;
    
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_WIDGET' AND COLUMN_NAME = 'WIDGETMODULEID')
        BEGIN
        ALTER TABLE WRK_WIDGET ADD
        WIDGETMODULEID int NULL
        END;
        
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_WIDGET' AND COLUMN_NAME = 'WIDGETMODULE')
        BEGIN
        ALTER TABLE WRK_WIDGET ADD
        WIDGETMODULE nvarchar(100) NULL
        END;
        
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_WIDGET' AND COLUMN_NAME = 'WIDGET_LICENSE')
        BEGIN
        ALTER TABLE WRK_WIDGET ADD
        WIDGET_LICENSE nvarchar(50) NULL
        END;
        
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_WIDGET' AND COLUMN_NAME = 'WIDGET_AUTHOR')
        BEGIN
        ALTER TABLE WRK_WIDGET ADD
        WIDGET_AUTHOR nvarchar(50) NULL
        END;
    
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_WIDGET' AND COLUMN_NAME = 'WIDGET_STAGE')
        BEGIN
        ALTER TABLE WRK_WIDGET ADD
        WIDGET_STAGE NVARCHAR(25) NULL
        END;
        
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_WIDGET' AND COLUMN_NAME = 'RECORD_IP')
        BEGIN
        ALTER TABLE WRK_WIDGET ADD
        RECORD_IP NVARCHAR(50) NULL
        END;
        
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_WIDGET' AND COLUMN_NAME = 'RECORD_EMP')
        BEGIN
        ALTER TABLE WRK_WIDGET ADD
        RECORD_EMP INT NULL
        END;
        
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_WIDGET' AND COLUMN_NAME = 'RECORD_DATE')
        BEGIN
        ALTER TABLE WRK_WIDGET ADD
        RECORD_DATE DATETIME NULL
        END;
        
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_WIDGET' AND COLUMN_NAME = 'UPDATE_IP')
        BEGIN
        ALTER TABLE WRK_WIDGET ADD
        UPDATE_IP NVARCHAR(50) NULL
        END;
        
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_WIDGET' AND COLUMN_NAME = 'UPDATE_EMP')
        BEGIN
        ALTER TABLE WRK_WIDGET ADD
        UPDATE_EMP INT NULL
        END;
        
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_WIDGET' AND COLUMN_NAME = 'UPDATE_DATE')
        BEGIN
        ALTER TABLE WRK_WIDGET ADD
        UPDATE_DATE DATETIME NULL
        END;
        
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_WIDGET' AND COLUMN_NAME = 'WIDGETSOLUTIONID')
        BEGIN
        ALTER TABLE WRK_WIDGET ADD
        WIDGETSOLUTIONID int NULL
        END;
        
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_WIDGET' AND COLUMN_NAME = 'WIDGETSOLUTION')
        BEGIN
        ALTER TABLE WRK_WIDGET ADD
        WIDGETSOLUTION nvarchar(100) NULL
        END;
        
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_WIDGET' AND COLUMN_NAME = 'WIDGETFAMILYID')
        BEGIN
        ALTER TABLE WRK_WIDGET ADD
        WIDGETFAMILYID int NULL
        END;
        
        IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WRK_WIDGET' AND COLUMN_NAME = 'WIDGETFAMILY')
        BEGIN
        ALTER TABLE WRK_WIDGET ADD
        WIDGETFAMILY nvarchar(100) NULL
        END
    
    
    END
    ELSE
    BEGIN
    
        CREATE TABLE [WRK_WIDGET](
            [WIDGETID] [int] IDENTITY(1,1) NOT NULL,
            [WIDGET_FUSEACTION] [nvarchar](250) NOT NULL,
            [WIDGET_TITLE] [nvarchar](250) NOT NULL,
            [WIDGET_EVENT_TYPE] [nvarchar](50) NOT NULL,
            [WIDGET_VERSION] [nvarchar](50) NOT NULL,
            [WIDGET_STRUCTURE] [nvarchar](max) NULL,
            [WIDGET_CODE] [nvarchar](max) NULL,
            [WIDGET_STATUS] [nvarchar](25) NOT NULL,
            [WIDGET_STAGE] [nvarchar](25) NULL,
            [WIDGET_TOOL] [nvarchar](25) NOT NULL,
            [WIDGET_FILE_PATH] [nvarchar](250) NULL,
            [WIDGETSOLUTIONID] [int] NULL,
            [WIDGETSOLUTION] [nvarchar](100) NULL,
            [WIDGETFAMILYID] [int] NULL,
            [WIDGETFAMILY] [nvarchar](100) NULL,
            [WIDGETMODULEID] [int] NULL,
            [WIDGETMODULE] [nvarchar](100) NULL,
            [WIDGET_DESCRIPTION] [nvarchar](max) NULL,
            [WIDGET_LICENSE] [nvarchar](50) NULL,
            [WIDGET_AUTHOR] [nvarchar](50) NULL,
            [WIDGET_DEPENDS] [nvarchar](max) NULL,
            [RECORD_IP] [nvarchar](50) NULL,
            [RECORD_EMP] [int] NULL,
            [RECORD_DATE] [datetime] NULL,
            [UPDATE_IP] [nvarchar](50) NULL,
            [UPDATE_EMP] [int] NULL,
            [UPDATE_DATE] [datetime] NULL,
         CONSTRAINT [PK_COMPONENT] PRIMARY KEY CLUSTERED 
        (
            [WIDGETID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
    
    END;
</querytag>