<!-- Description : Workdev DB aracının log kayıtlarını tutması için gerekli tablolar
Developer: Halit Yurttaş
Company : Workcube
Destination: Main -->
<querytag>
	IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='WRK_DBLOG')
	BEGIN

		CREATE TABLE [WRK_DBLOG](
			[DBLOG_ID] [int] IDENTITY(1,1) NOT NULL,
			[EVENT_TYPE] [nvarchar](20) NULL,
			[PARAMETERS_DUMP] [nvarchar](max) NULL,
			[RECORD_DATE] [datetime] NOT NULL,
			[RECORD_IP] [nvarchar](20) NULL,
			[RECORD_USER] [int] NULL,
		CONSTRAINT [PK_WRK_DBLOG] PRIMARY KEY CLUSTERED 
		(
			[DBLOG_ID] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
		) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
	END;
	
	IF NOT EXISTS ( SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_DBLOG' AND COLUMN_NAME='RECORD_DATE')
	BEGIN
	ALTER TABLE WRK_DBLOG ADD RECORD_DATE datatime NOT NULL
	END;
	
</querytag>