<!-- Description : holistic 21.3 sürümü tablolar ve kolon değişiklikleri
Developer: Fatih Kara
Company : Workcube
Destination: Company -->
<querytag>  
    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'PROGRESS_PAYMENT' AND COLUMN_NAME = 'RELATED_OPERATION_ID')
    BEGIN
        ALTER TABLE PROGRESS_PAYMENT ALTER COLUMN RELATED_OPERATION_ID varchar(max) NULL;
    END;
    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'PROGRESS_PAYMENT' AND COLUMN_NAME = 'REVENUE_COLLECTOR')
    BEGIN
        ALTER TABLE PROGRESS_PAYMENT ALTER COLUMN REVENUE_COLLECTOR varchar(100) NULL;
    END;
    IF  EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'PROGRESS_PAYMENT' AND COLUMN_NAME = 'PAYROLL_NO')
    BEGIN
        ALTER TABLE PROGRESS_PAYMENT ALTER COLUMN PAYROLL_NO varchar(50) NULL;
    END;
    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'PROGRESS_PAYMENT' AND COLUMN_NAME = 'BASKET_MONEY_TYPE')
    BEGIN
        ALTER TABLE PROGRESS_PAYMENT ALTER COLUMN BASKET_MONEY_TYPE varchar(30) NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'OPPORTUNITIES' AND COLUMN_NAME = 'SALES_POSITION_CODE')
    BEGIN
        ALTER TABLE OPPORTUNITIES ADD SALES_POSITION_CODE int;
    END;
</querytag>