<!-- Description : holistic 21.4 sürümü tablolar ve kolon değişiklikleri
Developer: Uğur Hamurpet
Company : Workcube
Destination: Main -->
<querytag>  
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'BRANCH' AND COLUMN_NAME = 'SALARY_SYNDIC_POS_ID')
    BEGIN
        ALTER TABLE BRANCH ADD SALARY_SYNDIC_POS_ID int;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'BRANCH' AND COLUMN_NAME = 'FULFILLMENT_OFFICER_POS_ID')
    BEGIN
        ALTER TABLE BRANCH ADD FULFILLMENT_OFFICER_POS_ID int;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'BRANCH' AND COLUMN_NAME = 'EXPENSE_USER_POS_ID')
    BEGIN
        ALTER TABLE BRANCH ADD EXPENSE_USER_POS_ID int;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PROCESS_TYPE_ROWS' AND COLUMN_NAME = 'IS_CONFIRM_FIRST_CHIEF_RECORDING')
    BEGIN
        ALTER TABLE PROCESS_TYPE_ROWS ADD IS_CONFIRM_FIRST_CHIEF_RECORDING bit;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PROCESS_TYPE_ROWS' AND COLUMN_NAME = 'IS_CONFIRM_SECOND_CHIEF_RECORDING')
    BEGIN
        ALTER TABLE PROCESS_TYPE_ROWS ADD IS_CONFIRM_SECOND_CHIEF_RECORDING bit;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PROCESS_TYPE_ROWS' AND COLUMN_NAME = 'POSITION_CODE_ARGUMENT_NAME')
    BEGIN
        ALTER TABLE PROCESS_TYPE_ROWS ADD POSITION_CODE_ARGUMENT_NAME nvarchar(250);
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'OUR_COMPANY_INFO' AND COLUMN_NAME = 'CLIENT_SECRET')
    BEGIN
        ALTER TABLE OUR_COMPANY_INFO ADD CLIENT_SECRET bigint;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'OUR_COMPANY_INFO' AND COLUMN_NAME = 'KEP_CLIENT_ID')
    BEGIN
        ALTER TABLE OUR_COMPANY_INFO ADD KEP_CLIENT_ID nvarchar(250);
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'OUR_COMPANY_INFO' AND COLUMN_NAME = 'KEP_CLIENT_SECRET')
    BEGIN
        ALTER TABLE OUR_COMPANY_INFO ADD KEP_CLIENT_SECRET nvarchar(250);
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'OUR_COMPANY_INFO' AND COLUMN_NAME = 'SERVER_URL')
    BEGIN
        ALTER TABLE OUR_COMPANY_INFO ADD SERVER_URL nvarchar(250);
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'SETUP_PAYMENT_INTERRUPTION' AND COLUMN_NAME = 'IS_UNION_INFORMATION')
    BEGIN
        ALTER TABLE SETUP_PAYMENT_INTERRUPTION ADD IS_UNION_INFORMATION bit;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'SETUP_PAYMENT_INTERRUPTION' AND COLUMN_NAME = 'UNION_INFORMATION_BANK_NAME')
    BEGIN
        ALTER TABLE SETUP_PAYMENT_INTERRUPTION ADD UNION_INFORMATION_BANK_NAME nvarchar(100);
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'SETUP_PAYMENT_INTERRUPTION' AND COLUMN_NAME = 'UNION_INFORMATION_BRANCH_NAME')
    BEGIN
        ALTER TABLE SETUP_PAYMENT_INTERRUPTION ADD UNION_INFORMATION_BRANCH_NAME nvarchar(100);
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'SETUP_PAYMENT_INTERRUPTION' AND COLUMN_NAME = 'UNION_INFORMATION_NAME')
    BEGIN
        ALTER TABLE SETUP_PAYMENT_INTERRUPTION ADD UNION_INFORMATION_NAME nvarchar(100);
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'SETUP_PAYMENT_INTERRUPTION' AND COLUMN_NAME = 'UNION_INFORMATION_ACCOUNT_NAME')
    BEGIN
        ALTER TABLE SETUP_PAYMENT_INTERRUPTION ADD UNION_INFORMATION_ACCOUNT_NAME nvarchar(100);
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'SETUP_PAYMENT_INTERRUPTION' AND COLUMN_NAME = 'UNION_INFORMATION_ADDRESS')
    BEGIN
        ALTER TABLE SETUP_PAYMENT_INTERRUPTION ADD UNION_INFORMATION_ADDRESS nvarchar(100);
    END;
    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WRK_OUTPUT_TEMPLATES' AND COLUMN_NAME = 'WRK_OUTPUT_TEMPLATE_NAME')
    BEGIN
        ALTER TABLE WRK_OUTPUT_TEMPLATES ALTER COLUMN WRK_OUTPUT_TEMPLATE_NAME nvarchar(500) NULL;
    END;
    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WRK_OUTPUT_TEMPLATES' AND COLUMN_NAME = 'RELATED_WO')
    BEGIN
        ALTER TABLE WRK_OUTPUT_TEMPLATES ALTER COLUMN RELATED_WO nvarchar(1000) NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PAGE_WARNINGS' AND COLUMN_NAME = 'IS_CONFIRM_FIRST_CHIEF_RECORDING')
    BEGIN
        ALTER TABLE PAGE_WARNINGS ADD IS_CONFIRM_FIRST_CHIEF_RECORDING bit;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PAGE_WARNINGS' AND COLUMN_NAME = 'IS_CONFIRM_SECOND_CHIEF_RECORDING')
    BEGIN
        ALTER TABLE PAGE_WARNINGS ADD IS_CONFIRM_SECOND_CHIEF_RECORDING bit;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'SUBSCRIPTION_COUNTER_ROWS' AND COLUMN_NAME = 'COMPANY_IDENTIFIER')
    BEGIN
        ALTER TABLE SUBSCRIPTION_COUNTER_ROWS ADD COMPANY_IDENTIFIER nvarchar(50);
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'TRAINING_GROUP_ATTENDERS' AND COLUMN_NAME = 'JOIN_REQUEST')
    BEGIN
        ALTER TABLE TRAINING_GROUP_ATTENDERS ADD JOIN_REQUEST bit;
    END;
    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'GDPR_DECLERATION' AND COLUMN_NAME = 'GDPR_DECLERATION_TEXT')
    BEGIN
        ALTER TABLE GDPR_DECLERATION ALTER COLUMN GDPR_DECLERATION_TEXT nvarchar(max) NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'ASSET_HISTORY' AND COLUMN_NAME = 'REVISION_NO')
    BEGIN
        ALTER TABLE ASSET_HISTORY ADD REVISION_NO int;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WRK_COOKIE' AND COLUMN_NAME = 'TIME_STAMP')
    BEGIN
        ALTER TABLE WRK_COOKIE ADD TIME_STAMP datetime;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WRK_COOKIE' AND COLUMN_NAME = 'CGI_STRUCT')
    BEGIN
        ALTER TABLE WRK_COOKIE ADD CGI_STRUCT nvarchar(max);
    END;
</querytag>