<!-- Description : Best Practice new columns
Developer: Uğur Hamurpet
Company : Workcube
Destination: Main-->
<querytag>

    IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='WRK_BESTPRACTICE' AND INFORMATION_SCHEMA.TABLES.TABLE_SCHEMA <> 'dbo' )
    BEGIN
        CREATE TABLE [WRK_BESTPRACTICE](
            [BESTPRACTICE_ID] [int] IDENTITY(1,1) NOT NULL,
            [BESTPRACTICE_NAME] [nvarchar](250) NOT NULL,
            [BESTPRACTICE_DETAIL] [nvarchar](max) NULL,
            [BESTPRACTICE_AUTHOR] [nvarchar](150) NOT NULL,
            [BESTPRACTICE_AUTHORID] [int] NOT NULL,
            [BESTPRACTICE_STOCK_ID] [int] NULL,
            [BESTPRACTICE_PRODUCT_ID] [int] NULL,
            [BESTPRACTICE_PRODUCT_NAME] [nvarchar](250) NULL,
            [BESTPRACTICE_FILE_PATH] [nvarchar](250) NULL,
            [BESTPRACTICE_LICENSE] [int] NOT NULL,
            [BESTPRACTICE_IS_ACTIVE] [bit] NULL,
            [BESTPRACTICE_STAGE] [int] NULL,
            [BESTPRACTICE_SECTORS] [nvarchar](150) NULL,
            [BESTPRACTICE_ICON_PATH] [nvarchar](150) NULL,
            [BESTPRACTICE_PUBLISH_DATE] [datetime] NULL,
            [BESTPRACTICE_PRODUCT_CODE] [nvarchar](50) NOT NULL,
            [RECORD_EMP] [int] NULL,
            [RECORD_DATE] [datetime] NULL,
            [RECORD_IP] [nvarchar](25) NULL,
            [UPDATE_EMP] [int] NULL,
            [UPDATE_DATE] [datetime] NULL,
            [UPDATE_IP] [nvarchar](25) NULL,
        CONSTRAINT [PK_WRK_BESTPRACTICE] PRIMARY KEY CLUSTERED 
        (
            [BESTPRACTICE_ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
    END
    ELSE
    BEGIN
        IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_BESTPRACTICE' AND COLUMN_NAME='BESTPRACTICE_STOCK_ID')
        BEGIN
            ALTER TABLE WRK_BESTPRACTICE ADD 
            BESTPRACTICE_STOCK_ID int NULL;
        END;
        IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_BESTPRACTICE' AND COLUMN_NAME='BESTPRACTICE_PRODUCT_ID')
        BEGIN
            ALTER TABLE WRK_BESTPRACTICE ADD 
            BESTPRACTICE_PRODUCT_ID int NULL;
        END;
        IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_BESTPRACTICE' AND COLUMN_NAME='BESTPRACTICE_PRODUCT_NAME')
        BEGIN
            ALTER TABLE WRK_BESTPRACTICE ADD 
            BESTPRACTICE_PRODUCT_NAME nvarchar(250) NULL;
        END;
        IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_BESTPRACTICE' AND COLUMN_NAME='BESTPRACTICE_FILE_PATH')
        BEGIN
            ALTER TABLE WRK_BESTPRACTICE ADD 
            BESTPRACTICE_FILE_PATH nvarchar(250) NULL;
        END;
        IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_BESTPRACTICE' AND COLUMN_NAME='BESTPRACTICE_IS_ACTIVE')
        BEGIN
            ALTER TABLE WRK_BESTPRACTICE ADD 
            BESTPRACTICE_IS_ACTIVE bit NULL;
        END;
        IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_BESTPRACTICE' AND COLUMN_NAME='BESTPRACTICE_STAGE')
        BEGIN
            ALTER TABLE WRK_BESTPRACTICE ADD 
            BESTPRACTICE_STAGE int NULL;
        END;
        IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_BESTPRACTICE' AND COLUMN_NAME='BESTPRACTICE_SECTORS')
        BEGIN
            ALTER TABLE WRK_BESTPRACTICE ADD 
            BESTPRACTICE_SECTORS nvarchar(150) NULL;
        END;
        IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_BESTPRACTICE' AND COLUMN_NAME='BESTPRACTICE_ICON_PATH')
        BEGIN
            ALTER TABLE WRK_BESTPRACTICE ADD 
            BESTPRACTICE_ICON_PATH nvarchar(150) NULL;
        END;
        IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_BESTPRACTICE' AND COLUMN_NAME='BESTPRACTICE_PUBLISH_DATE')
        BEGIN
            ALTER TABLE WRK_BESTPRACTICE ADD 
            BESTPRACTICE_PUBLISH_DATE datetime NULL;
        END;
    END
</querytag>