<!-- Description : Gelen E-faturada irsaliye seçimi için kullanılan popup WBO
Developer: Mahmut Çifçi
Company : Gramoni
Destination: Main -->
<querytag>
    IF NOT EXISTS(SELECT WRK_OBJECTS_ID FROM WRK_OBJECTS WHERE FULL_FUSEACTION = 'objects.popup_list_choice_ship_receiving_einvoice')
    BEGIN
    INSERT INTO WRK_OBJECTS (IS_ACTIVE, MODULE_NO, HEAD, DICTIONARY_ID, FRIENDLY_URL, FULL_FUSEACTION, FULL_FUSEACTION_VARIABLES, FILE_PATH, CONTROLLER_FILE_PATH, STANDART_ADDON, LICENCE, EVENT_TYPE, STATUS, IS_DEFAULT, IS_MENU, WINDOW, VERSION, IS_CATALYST_MOD, MENU_SORT_NO, USE_PROCESS_CAT, USE_SYSTEM_NO, USE_WORKFLOW, DETAIL, AUTHOR, OBJECTS_COUNT, DESTINATION_MODUL, RECORD_IP, RECORD_EMP, RECORD_DATE, UPDATE_IP, UPDATE_EMP, UPDATE_DATE, SECURITY, STAGE, MODUL, BASE, MODUL_SHORT_NAME, FUSEACTION, FUSEACTION2, FOLDER, FILE_NAME, IS_ADD, IS_UPDATE, IS_DELETE, LEFT_MENU_NAME, IS_WBO_DENIED, IS_WBO_FORM_LOCK, IS_WBO_LOCK, IS_WBO_LOG, IS_SPECIAL, IS_TEMP, EVENT_ADD, EVENT_DASHBOARD, EVENT_DEFAULT, EVENT_DETAIL, EVENT_LIST, EVENT_UPD, TYPE, POPUP_TYPE, RANK_NUMBER, EXTERNAL_FUSEACTION, IS_LEGACY, ADDOPTIONS_CONTROLLER_FILE_PATH) VALUES (CONVERT(bit, 'True'), 47, N'E-Fatura - İrsaliye Bağlantısı', NULL, N'popup_list_choice_ship_receiving_einvoice', N'objects.popup_list_choice_ship_receiving_einvoice', NULL, N'objects/display/list_choice_ship_receiving_einvoice.cfm', NULL, NULL, 1, NULL, N'Deployment', NULL, CONVERT(bit, 'False'), N'popup', N'1.0', NULL, NULL, CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), N'<p>Gelen efatura sayfasında faturaya irsaliye bağlantısı oluşturmak için kullanılır.</p><p>Gramoni-Mahmut &lt;mahmut.cifci@gramoni.com&gt;</p>', N'Workcube Core', 20310, NULL, N'192.168.18.34', 1898, '2020-01-03 15:53:42.823', N'192.168.71.8', 57, '2020-01-04 09:32:09.053', N'HTTP', 2176, N'Objects', NULL, N'Objects', N'popup_list_choice_ship_receiving_einvoice', NULL, NULL, N'list_choice_ship_receiving_einvoice.cfm', CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), NULL, CONVERT(bit, 'False'), NULL, CONVERT(bit, 'False'), NULL, CONVERT(bit, 'False'), NULL, CONVERT(bit, 'False'), CONVERT(bit, 'False'), NULL, CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 10, NULL, NULL, NULL, 1, NULL)
    END;
</querytag>