<!-- Description : Period şemasına yeni alanlar
Developer: Gülbahar Inan
Company : Workcube
Destination: PERIOD-->
<querytag>

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' AND TABLE_NAME = 'EXPENSE_ITEM_PLAN_REQUESTS' AND COLUMN_NAME = 'EXPENSE_HR_ALLOWANCE')
    BEGIN
        ALTER TABLE EXPENSE_ITEM_PLAN_REQUESTS ADD EXPENSE_HR_ALLOWANCE int;
    END

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' AND TABLE_NAME = 'EXPENSE_ITEM_PLAN_REQUESTS' AND COLUMN_NAME = 'RECEIVING_ID')
    BEGIN
        ALTER TABLE EXPENSE_ITEM_PLAN_REQUESTS ADD RECEIVING_ID int;
    END

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' AND TABLE_NAME = 'EXPENSE_ITEM_PLAN_REQUESTS' AND COLUMN_NAME = 'HEALTH_APPROVE')
    BEGIN
        ALTER TABLE EXPENSE_ITEM_PLAN_REQUESTS ADD HEALTH_APPROVE bit;   
    END

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' AND TABLE_NAME = 'EXPENSE_ITEMS_ROWS' AND COLUMN_NAME = 'DISCOUNT_TOTAL')
    BEGIN
        ALTER TABLE EXPENSE_ITEMS_ROWS ADD DISCOUNT_TOTAL float;
    END

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' AND TABLE_NAME = 'EXPENSE_ITEMS_ROWS' AND COLUMN_NAME = 'DISCOUNT_PRICE')
    BEGIN
        ALTER TABLE EXPENSE_ITEMS_ROWS ADD DISCOUNT_PRICE float;
    END

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' AND TABLE_NAME = 'EXPENSE_ITEMS_ROWS' AND COLUMN_NAME = 'DISCOUNT_RATE')
    BEGIN
        ALTER TABLE EXPENSE_ITEMS_ROWS ADD DISCOUNT_RATE nvarchar(43);
    END

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' AND TABLE_NAME = 'SETUP_STOPPAGE_RATES' AND COLUMN_NAME = 'INWARD_PROCESS_CODE')
    BEGIN
        ALTER TABLE SETUP_STOPPAGE_RATES ADD INWARD_PROCESS_CODE nvarchar(50);
    END

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' AND TABLE_NAME = 'SETUP_STOPPAGE_RATES' AND COLUMN_NAME = 'EXP_PURCHASE_CODE')
    BEGIN
        ALTER TABLE SETUP_STOPPAGE_RATES ADD EXP_PURCHASE_CODE nvarchar(50);
    END

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' AND TABLE_NAME = 'SETUP_STOPPAGE_RATES' AND COLUMN_NAME = 'EXP_SALES_CODE')
    BEGIN
        ALTER TABLE SETUP_STOPPAGE_RATES ADD EXP_SALES_CODE nvarchar(50);
    END
</querytag>



