<!-- Description : Fatura History  tabloları açıldı.
Developer: Gülbahar Inan
Company : Workcube
Destination: Period -->
<querytag>

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'INVOICE_HISTORY' AND TABLE_SCHEMA = '@_dsn_period_@')
    BEGIN
    CREATE TABLE [INVOICE_HISTORY](
        [INVOICE_HISTORY_ID] [int] IDENTITY(1,1) NOT NULL,
        [INVOICE_ID] [int] NOT NULL,
        [INVOICE_MULTI_ID] [int] NULL,
        [WRK_ID] [nvarchar](43) NULL,
        [PURCHASE_SALES] [bit] NULL,
        [INVOICE_CAT] [int] NULL,
        [INVOICE_DATE] [datetime] NULL,
        [SHIP_DATE] [datetime] NULL,
        [SERIAL_NUMBER] [nvarchar](50) NULL,
        [SERIAL_NO] [nvarchar](50) NULL,
        [INVOICE_NUMBER] [nvarchar](100) NULL,
        [COMPANY_ID] [int] NULL,
        [PARTNER_ID] [int] NULL,
        [CONSUMER_ID] [int] NULL,
        [EMPLOYEE_ID] [int] NULL,
        [DEPARTMENT_LOCATION] [int] NULL,
        [DEPARTMENT_ID] [int] NULL,
        [GROSSTOTAL] [float] NULL,
        [GROSSTOTAL_WITHOUT_ROUND] [float] NULL,
        [NETTOTAL] [float] NULL,
        [TAXTOTAL] [float] NULL,
        [OTV_TOTAL] [float] NULL,
        [SA_DISCOUNT] [float] NULL,
        [PAY_METHOD] [int] NULL,
        [DUE_DATE] [datetime] NULL,
        [NOTE] [nvarchar](max) NULL,
        [ORDER_ID] [int] NULL,
        [OFFER_ID] [int] NULL,
        [DELIVER_EMP] [nvarchar](50) NULL,
        [SHIP_METHOD] [int] NULL,
        [IS_PROCESSED] [bit] NULL,
        [IS_CASH] [bit] NULL,
        [IS_ACCOUNTED] [bit] NULL,
        [CASH_ID] [int] NULL,
        [KASA_ID] [int] NULL,
        [UPDATE_DATE] [datetime] NULL,
        [UPDATE_EMP] [int] NULL,
        [SALE_EMP] [int] NULL,
        [SALE_PARTNER] [int] NULL,
        [ZONE_ID] [int] NULL,
        [PROJECT_ID] [int] NULL,
        [UPD_STATUS] [bit] NULL,
        [OTHER_MONEY] [nvarchar](43) NULL,
        [OTHER_MONEY_VALUE] [float] NULL,
        [PROCESS_CAT] [int] NOT NULL,
        [IS_WITH_SHIP] [bit] NULL,
        [STOPAJ] [float] NULL,
        [STOPAJ_ORAN] [float] NULL,
        [PRINT_COUNT] [int] NULL,
        [IS_IPTAL] [bit] NULL,
        [ROUND_MONEY] [float] NULL,
        [IS_ORDERED] [bit] NULL,
        [REF_NO] [nvarchar](2000) NULL,
        [IS_COST] [bit] NULL,
        [GENERAL_PROM_ID] [int] NULL,
        [GENERAL_PROM_LIMIT] [int] NULL,
        [GENERAL_PROM_DISCOUNT] [float] NULL,
        [GENERAL_PROM_AMOUNT] [float] NULL,
        [FREE_PROM_ID] [int] NULL,
        [FREE_PROM_LIMIT] [int] NULL,
        [FREE_PROM_COST] [float] NULL,
        [FREE_PROM_AMOUNT] [int] NULL,
        [FREE_PROM_STOCK_ID] [int] NULL,
        [FREE_STOCK_PRICE] [float] NULL,
        [FREE_STOCK_MONEY] [nvarchar](43) NULL,
        [SHIP_ADDRESS] [nvarchar](500) NULL,
        [SHIP_ADDRESS_ID] [int] NULL,
        [IS_RETURN] [bit] NULL,
        [TEVKIFAT] [bit] NULL,
        [TEVKIFAT_ORAN] [float] NULL,
        [CARD_PAYMETHOD_ID] [int] NULL,
        [CARD_PAYMETHOD_RATE] [float] NULL,
        [RESOURCE_ID] [int] NULL,
        [IMS_CODE_ID] [int] NULL,
        [CUSTOMER_VALUE_ID] [int] NULL,
        [STOPAJ_RATE_ID] [int] NULL,
        [COMMETHOD_ID] [int] NULL,
        [IS_TAX_OF_OTV] [bit] NULL,
        [CONSUMER_REFERENCE_CODE] [nvarchar](500) NULL,
        [EXPENSE_CENTER_ID] [int] NULL,
        [EXPENSE_ITEM_ID] [int] NULL,
        [PARTNER_REFERENCE_CODE] [nvarchar](250) NULL,
        [POS_CASH_ID] [int] NULL,
        [SALES_CONSUMER_ID] [int] NULL,
        [SALES_PARTNER_ID] [int] NULL,
        [SALES_TEAM_ID] [int] NULL,
        [ADD_FLAG] [bit] NULL,
        [CARI_ACTION_TYPE] [int] NULL,
        [IS_ACC_FLAG] [bit] NULL,
        [CANCEL_TYPE_ID] [int] NULL,
        [ASSETP_ID] [int] NULL,
        [ACC_DEPARTMENT_ID] [int] NULL,
        [PRINT_DATE] [datetime] NULL,
        [SUBSCRIPTION_ID] [int] NULL,
        [CITY_ID] [int] NULL,
        [COUNTY_ID] [int] NULL,
        [DELIVER_COMP_ID] [int] NULL,
        [DELIVER_CONS_ID] [int] NULL,
        [CONTRACT_ID] [int] NULL,
        [PROGRESS_ID] [int] NULL,
        [PROFILE_ID] [nvarchar](50) NULL,
        [FROM_PROGRESS] [bit] NULL,
        [ACC_TYPE_ID] [int] NULL,
        [UUID] [nvarchar](50) NULL,
        [HOBIM_ID] [int] NULL,
        [IS_PDF] [bit] NULL,
        [RECORD_CONS] [int] NULL,
        [RECORD_DATE] [datetime] NULL,
        [RECORD_EMP] [int] NULL,
        [TAX_CODE] [nvarchar](20) NULL,
        [BANK_ACTION_ID] [int] NULL,
        [BANK_PERIOD_ID] [int] NULL,
        [TEVKIFAT_ID] [int] NULL,
        [CREDITCARD_PAYMENT_ID] [int] NULL,
        [SERVICE_ID] [int] NULL,
        [IS_CREDIT] [int] NULL,
        [RELATED_INVOICE_ID] [int] NULL,
        [IS_RECEIVED_WEBSERVICE] [bit] NULL,
        [IS_RATE_EXTRA_COST] [int] NULL,
        [REALIZATION_DATE] [datetime] NULL,
        [PROCESS_TIME] [datetime] NULL,
        [BSMV_TOTAL] [float] NULL,
        [OIV_TOTAL] [float] NULL,
        [PROCESS_STAGE] [int] NULL,
        [IS_EXPORT_REGISTRATION] [bit] NULL,
        [IS_EXPORT_PRODUCT] [bit] NULL,
        [VAT_EXCEPTION_ID] [int] NULL,
        [PROCESS_DATE] [datetime] NULL,
     CONSTRAINT [PK_INVOICE_HISTORY_INVOICE_ID_HISTORY] PRIMARY KEY CLUSTERED 
    (
        [INVOICE_HISTORY_ID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    ) ON [PRIMARY]
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'INVOICE_ROW_HISTORY' AND TABLE_SCHEMA = '@_dsn_period_@')
    BEGIN
    CREATE TABLE [INVOICE_ROW_HISTORY](
        [INVOICE_ROW_HISTORY_ID] [int] IDENTITY(1,1) NOT NULL,
        [INVOICE_HISTORY_ID] [int] NOT NULL,
        [INVOICE_ID] [int] NOT NULL,
        [INVOICE_ROW_ID] [int] NOT NULL,
        [PURCHASE_SALES] [bit] NULL,
        [STOCK_ID] [int] NULL,
        [DESCRIPTION] [nvarchar](100) NULL,
        [AMOUNT] [float] NULL,
        [PRICE] [float] NULL,
        [PRICE_OTHER] [float] NULL,
        [UNIT] [nvarchar](50) NULL,
        [UNIT_ID] [int] NULL,
        [COST_ID] [int] NULL,
        [COST_PRICE] [float] NULL,
        [MARGIN] [float] NULL,
        [EXTRA_COST] [float] NULL,
        [DISCOUNTTOTAL] [float] NULL,
        [GROSSTOTAL] [float] NULL,
        [NETTOTAL] [float] NULL,
        [TAXTOTAL] [float] NULL,
        [ORDER_ID] [int] NULL,
        [PAY_METHOD] [int] NULL,
        [DUE_DATE] [int] NULL,
        [PROM_ID] [int] NULL,
        [NAME_PRODUCT] [nvarchar](500) NULL,
        [PRODUCT_ID] [int] NULL,
        [TAX] [float] NULL,
        [DISCOUNT1] [float] NULL,
        [DISCOUNT2] [float] NULL,
        [DISCOUNT3] [float] NULL,
        [DISCOUNT4] [float] NULL,
        [DISCOUNT5] [float] NULL,
        [DISCOUNT6] [float] NULL,
        [DISCOUNT7] [float] NULL,
        [DISCOUNT8] [float] NULL,
        [DISCOUNT9] [float] NULL,
        [DISCOUNT10] [float] NULL,
        [DELIVER_DATE] [datetime] NULL,
        [DELIVER_DEPT] [int] NULL,
        [DELIVER_LOC] [int] NULL,
        [OTHER_MONEY] [nvarchar](43) NULL,
        [OTHER_MONEY_VALUE] [float] NULL,
        [OTHER_MONEY_GROSS_TOTAL] [float] NULL,
        [SPECT_VAR_ID] [int] NULL,
        [SPECT_VAR_NAME] [nvarchar](500) NULL,
        [LOT_NO] [nvarchar](100) NULL,
        [DARA] [float] NULL,
        [SHIP_ID] [int] NULL,
        [DARALI] [float] NULL,
        [PROM_COMISSION] [float] NULL,
        [PROM_COST] [float] NULL,
        [DISCOUNT_COST] [float] NULL,
        [IS_PROMOTION] [bit] NULL,
        [PROM_STOCK_ID] [int] NULL,
        [IS_COMMISSION] [bit] NULL,
        [UNIQUE_RELATION_ID] [nvarchar](100) NULL,
        [PRODUCT_NAME2] [nvarchar](650) NULL,
        [AMOUNT2] [float] NULL,
        [UNIT2] [nvarchar](50) NULL,
        [EXTRA_PRICE] [float] NULL,
        [SHELF_NUMBER] [int] NULL,
        [PRODUCT_MANUFACT_CODE] [nvarchar](250) NULL,
        [INVENTORY_ID] [int] NULL,
        [EXTRA_PRICE_TOTAL] [float] NULL,
        [OTV_ORAN] [float] NULL,
        [OTVTOTAL] [float] NULL,
        [SHIP_PERIOD_ID] [int] NULL,
        [BASKET_EXTRA_INFO_ID] [int] NULL,
        [SELECT_INFO_EXTRA] [int] NULL,
        [DETAIL_INFO_EXTRA] [nvarchar](500) NULL,
        [PROM_RELATION_ID] [nvarchar](100) NULL,
        [BASKET_EMPLOYEE_ID] [int] NULL,
        [LIST_PRICE] [float] NULL,
        [NUMBER_OF_INSTALLMENT] [int] NULL,
        [KARMA_PRODUCT_ID] [int] NULL,
        [EXTRA_PRICE_OTHER_TOTAL] [float] NULL,
        [PRICE_CAT] [int] NULL,
        [EK_TUTAR_PRICE] [float] NULL,
        [CATALOG_ID] [int] NULL,
        [WRK_ROW_ID] [nvarchar](40) NULL,
        [WRK_ROW_RELATION_ID] [nvarchar](40) NULL,
        [RELATED_ACTION_ID] [int] NULL,
        [RELATED_ACTION_TABLE] [nvarchar](43) NULL,
        [DEPTH_VALUE] [float] NULL,
        [WIDTH_VALUE] [float] NULL,
        [HEIGHT_VALUE] [float] NULL,
        [ROW_PROJECT_ID] [int] NULL,
        [ROW_PAYMETHOD_ID] [int] NULL,
        [PBS_ID] [int] NULL,
        [ROW_WORK_ID] [int] NULL,
        [ROW_EXP_CENTER_ID] [int] NULL,
        [ROW_EXP_ITEM_ID] [int] NULL,
        [ROW_ACC_CODE] [nvarchar](50) NULL,
        [REASON_NAME] [nvarchar](250) NULL,
        [REASON_CODE] [nvarchar](10) NULL,
        [DELIVERY_CONDITION] [nvarchar](50) NULL,
        [CONTAINER_TYPE] [nvarchar](50) NULL,
        [CONTAINER_NUMBER] [nvarchar](50) NULL,
        [CONTAINER_QUANTITY] [nvarchar](50) NULL,
        [DELIVERY_COUNTRY] [nvarchar](50) NULL,
        [DELIVERY_CITY] [nvarchar](50) NULL,
        [DELIVERY_COUNTY] [nvarchar](50) NULL,
        [DELIVERY_TYPE] [nvarchar](50) NULL,
        [GTIP_NUMBER] [nvarchar](50) NULL,
        [ACTIVITY_TYPE_ID] [int] NULL,
        [SUBSCRIPTION_ID] [int] NULL,
        [ASSETP_ID] [int] NULL,
        [BSMV_RATE] [float] NULL,
        [BSMV_AMOUNT] [float] NULL,
        [BSMV_CURRENCY] [float] NULL,
        [OIV_RATE] [float] NULL,
        [OIV_AMOUNT] [float] NULL,
        [TEVKIFAT_RATE] [float] NULL,
        [TEVKIFAT_AMOUNT] [float] NULL,
     CONSTRAINT [PK_INVOICE_ROW_HISTORY_INVOICE_ROW_HISTORY_ID] PRIMARY KEY CLUSTERED 
    (
        [INVOICE_ROW_HISTORY_ID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    ) ON [PRIMARY]
    END;
</querytag>
