<!-- Description : Magic Auditor Tabloları
Developer: İlker Altındal
Company : Workcube
Destination: Main -->

<querytag>

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ACCOUNT_AUDITOR_WIZARD' AND TABLE_SCHEMA = '@_dsn_main_@')

    BEGIN
        CREATE TABLE [ACCOUNT_AUDITOR_WIZARD](
        [WIZARD_ID] [int] IDENTITY(1,1) NOT NULL,
        [WIZARD_NAME] [nvarchar](50) NULL,
        [WIZARD_DESIGNER] [int] NULL,
        [WIZARD_STAGE] [int] NULL,
        [WIZARD_DATE] [date] NULL,
        [RECORD_EMP] [int] NULL,
        [RECORD_IP] [nvarchar](50) NULL,
        [RECORD_DATE] [datetime] NULL,
        [UPDATE_EMP] [int] NULL,
        [UPDATE_IP] [nvarchar](50) NULL,
        [UPDATE_DATE] [datetime] NULL,
        [PERIOD_MONTH] [int] NULL,
        [PERIOD_DAY] [int] NULL,
        [PROCESS_CAT] [int] NULL,
        [TARGET_TYPE] [int] NULL,
    CONSTRAINT [PK_ACCOUNT_AUDITOR_WIZARD] PRIMARY KEY CLUSTERED 
    (
        [WIZARD_ID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    ) ON [PRIMARY]

    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ACCOUNT_AUDITOR_WIZARD_BLOCK' AND TABLE_SCHEMA = '@_dsn_main_@')

    BEGIN
        CREATE TABLE [ACCOUNT_AUDITOR_WIZARD_BLOCK](
        [WIZARD_BLOCK_ID] [int] IDENTITY(1,1) NOT NULL,
        [WIZARD_ID] [nchar](10) NULL,
        [BLOCK_NAME_LEFT] [nvarchar](50) NULL,
        [BLOCK_NAME_RIGHT] [nvarchar](50) NULL,
        [BLOCK_OPERATION] [int] NULL,
        [BLOCK_RATE] [float] NULL,
    CONSTRAINT [PK_ACCOUNT_AUDITOR_WIZARD_BLOCK] PRIMARY KEY CLUSTERED 
    (
        [WIZARD_BLOCK_ID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    ) ON [PRIMARY]

    END;


    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ACCOUNT_AUDITOR_WIZARD_BLOCK_ROW' AND TABLE_SCHEMA = '@_dsn_main_@')

    BEGIN
        CREATE TABLE [ACCOUNT_AUDITOR_WIZARD_BLOCK_ROW](
            [WIZARD_BLOCK_ROW_ID] [int] IDENTITY(1,1) NOT NULL,
            [WIZARD_BLOCK_ID] [int] NULL,
            [BLOCK_COLUMN] [int] NULL,
            [ACCOUNT_CODE] [nvarchar](50) NULL,
            [RATE] [float] NULL,
            [DESCRIPTION] [nvarchar](50) NULL,
            [BA] [int] NULL,
        CONSTRAINT [PK_ACCOUNT_AUDITOR_WIZARD_BLOCK_ROW] PRIMARY KEY CLUSTERED 
        (
            [WIZARD_BLOCK_ROW_ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ) ON [PRIMARY]
    END;

</querytag>