<!-- Description : Holistic.21.6 main wro
Developer: Uğur Hamurpet
Company : Workcube
Destination: Main -->
<querytag>
IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME='EMPLOYEES_COMPETENCIES')
BEGIN
    CREATE TABLE [EMPLOYEES_COMPETENCIES](	  [COMPETENCIES_ID] int NOT NULL IDENTITY(1,1)	, [EMPLOYEE_ID] int NULL	, [REQ_TYPE_ID] int NULL	, [RECORD_EMP] int NULL	, [RECORD_IP] nvarchar(50) NULL	, [UPDATE_EMP] int NULL	, [RECORD_DATE] datetime NULL	, [UPDATE_DATE] datetime NULL	, [COMPETENCIES_WEIGHT] int NULL	, [COMPETENCIES_COMMENT] nvarchar(1000) NULL	, [COMPETENCIES_SCORE] float NULL	, [COMPETENCIES_TOTAL] float NULL	, CONSTRAINT [PK__EMPLOYEE__839F2C4F0A57A8AC] PRIMARY KEY ([COMPETENCIES_ID] ASC));
END;
IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME='RECYCLE_GROUP')
BEGIN
    CREATE TABLE [RECYCLE_GROUP](	  [RECYCLE_GROUP_ID] int NOT NULL IDENTITY(1,1)	, [RECYCLE_GROUP] nvarchar(200) NOT NULL	, [RECORD_EMP] int NULL	, [RECORD_DATE] datetime NULL	, [RECORD_IP] nvarchar(50) NULL	, [UPDATE_EMP] int NULL	, [UPDATE_DATE] datetime NULL	, [UPDATE_IP] nvarchar(50) NULL	, CONSTRAINT [PK_RECYCLE_GROUP] PRIMARY KEY ([RECYCLE_GROUP_ID] ASC));
END;
IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME='RECYCLE_SUB_GROUP')
BEGIN
    CREATE TABLE [RECYCLE_SUB_GROUP](	  [RECYCLE_SUB_GROUP_ID] int NOT NULL IDENTITY(1,1)	, [RECYCLE_SUB_GROUP] nvarchar(200) NOT NULL	, [RECYCLE_GROUP_ID] int NOT NULL	, [RECORD_EMP] int NULL	, [RECORD_DATE] datetime NULL	, [RECORD_IP] nvarchar(50) NULL	, [UPDATE_EMP] int NULL	, [UPDATE_DATE] datetime NULL	, [UPDATE_IP] nvarchar(50) NULL	, CONSTRAINT [PK_RECYCLE_SUB_GROUP] PRIMARY KEY ([RECYCLE_SUB_GROUP_ID] ASC));
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'TRAINING_GROUP_ATTENDERS' AND COLUMN_NAME = 'JOIN_STATU')
BEGIN
    ALTER TABLE TRAINING_GROUP_ATTENDERS ADD JOIN_STATU int;
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PAPER_CARGO_COURIER' AND COLUMN_NAME = 'PROCESS_STAGE')
BEGIN
    ALTER TABLE PAPER_CARGO_COURIER ADD PROCESS_STAGE int;
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'TRAINING_GROUP_ATTENDERS_DELETE' AND COLUMN_NAME = 'DELETED_ATTENDER_ID')
BEGIN
    ALTER TABLE TRAINING_GROUP_ATTENDERS_DELETE ADD DELETED_ATTENDER_ID int;
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'COMMANDMENT' AND COLUMN_NAME = 'RATE_VALUE_STATIC')
BEGIN
    ALTER TABLE COMMANDMENT ADD RATE_VALUE_STATIC float;
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WORKNET_RELATION_COMPANY' AND COLUMN_NAME = 'USER_NAME_MAIL')
BEGIN
    ALTER TABLE WORKNET_RELATION_COMPANY ADD USER_NAME_MAIL nvarchar(250);
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WORKNET_RELATION_COMPANY' AND COLUMN_NAME = 'INTEGRATION_TEST_DATE')
BEGIN
    ALTER TABLE WORKNET_RELATION_COMPANY ADD INTEGRATION_TEST_DATE date;
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WORKNET_RELATION_COMPANY' AND COLUMN_NAME = 'IS_INTEGRATION_TESTED')
BEGIN
    ALTER TABLE WORKNET_RELATION_COMPANY ADD IS_INTEGRATION_TESTED bit;
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WORKNET_RELATION_COMPANY' AND COLUMN_NAME = 'STORE_URL')
BEGIN
    ALTER TABLE WORKNET_RELATION_COMPANY ADD STORE_URL nvarchar(250);
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WORKNET_RELATION_COMPANY' AND COLUMN_NAME = 'WATALOGY_CODE')
BEGIN
    ALTER TABLE WORKNET_RELATION_COMPANY ADD WATALOGY_CODE nvarchar(250);
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WORKNET_RELATION_COMPANY' AND COLUMN_NAME = 'SUBSCRIPTION_NO')
BEGIN
    ALTER TABLE WORKNET_RELATION_COMPANY ADD SUBSCRIPTION_NO nvarchar(250);
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WORKNET_RELATION_COMPANY' AND COLUMN_NAME = 'CLIENT_KEY')
BEGIN
    ALTER TABLE WORKNET_RELATION_COMPANY ADD CLIENT_KEY nvarchar(250);
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WORKNET_RELATION_COMPANY' AND COLUMN_NAME = 'NETWORG_COMPANY_ID')
BEGIN
    ALTER TABLE WORKNET_RELATION_COMPANY ADD NETWORG_COMPANY_ID int;
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WORKNET_RELATION_COMPANY' AND COLUMN_NAME = 'USE_WATALOGY_STORE')
BEGIN
    ALTER TABLE WORKNET_RELATION_COMPANY ADD USE_WATALOGY_STORE bit;
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WORKNET_RELATION_COMPANY' AND COLUMN_NAME = 'OUR_COMPANY_ID')
BEGIN
    ALTER TABLE WORKNET_RELATION_COMPANY ADD OUR_COMPANY_ID int;
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WORKNET_RELATION_COMPANY' AND COLUMN_NAME = 'SELLER')
BEGIN
    ALTER TABLE WORKNET_RELATION_COMPANY ADD SELLER nvarchar(250);
END;

IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'COMMANDMENT_HISTORY' AND COLUMN_NAME = 'RATE_VALUE_STATIC')
BEGIN
    ALTER TABLE COMMANDMENT_HISTORY ADD RATE_VALUE_STATIC float;
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'COMPANY_LAW_REQUEST' AND COLUMN_NAME = 'CREDIT_DATE')
BEGIN
    ALTER TABLE COMPANY_LAW_REQUEST ADD CREDIT_DATE datetime;
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'TRAINING_CLASS_GROUPS' AND COLUMN_NAME = 'STATU')
BEGIN
    ALTER TABLE TRAINING_CLASS_GROUPS ADD STATU int;
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'SUBSCRIPTION_COUNTER_ROWS' AND COLUMN_NAME = 'WEX_COMPANY_ID')
BEGIN
    ALTER TABLE SUBSCRIPTION_COUNTER_ROWS ADD WEX_COMPANY_ID int;
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'SUBSCRIPTION_COUNTER_ROWS' AND COLUMN_NAME = 'WEX_INTEGRATOR')
BEGIN
    ALTER TABLE SUBSCRIPTION_COUNTER_ROWS ADD WEX_INTEGRATOR nvarchar(50);
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'SUBSCRIPTION_COUNTER_ROWS' AND COLUMN_NAME = 'WEX_TYPE')
BEGIN
    ALTER TABLE SUBSCRIPTION_COUNTER_ROWS ADD WEX_TYPE nvarchar(30);
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'SPEC_PLP' AND COLUMN_NAME = 'COLOUR_K')
BEGIN
    ALTER TABLE SPEC_PLP ADD COLOUR_K nvarchar(10);
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'SPEC_PLP' AND COLUMN_NAME = 'COLOUR_M')
BEGIN
    ALTER TABLE SPEC_PLP ADD COLOUR_M nvarchar(10);
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'SPEC_PLP' AND COLUMN_NAME = 'COLOUR_Y')
BEGIN
    ALTER TABLE SPEC_PLP ADD COLOUR_Y nvarchar(10);
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'SPEC_PLP' AND COLUMN_NAME = 'ORDER_NO')
BEGIN
    ALTER TABLE SPEC_PLP ADD ORDER_NO nvarchar(50);
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'SPEC_PLP' AND COLUMN_NAME = 'SPECT_ID')
BEGIN
    ALTER TABLE SPEC_PLP ADD SPECT_ID int;
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'SPEC_PLP' AND COLUMN_NAME = 'COLOUR_C')
BEGIN
    ALTER TABLE SPEC_PLP ADD COLOUR_C nvarchar(10);
END;
IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WORKNET' AND COLUMN_NAME = 'APPLICATION_WEB_ADRESS')
BEGIN
    ALTER TABLE WORKNET ADD APPLICATION_WEB_ADRESS nvarchar(50);
END;
</querytag>