<!-- Description : 19.12.5 ile holistic sürümü tablolar ve kolon değişiklikleri
Developer: Fatih Kara
Company : Workcube
Destination: Product -->
<querytag>  
    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT_PROPERTY' AND COLUMN_NAME = 'PROPERTY_LEN')
    BEGIN
        ALTER TABLE PRODUCT_PROPERTY ALTER COLUMN PROPERTY_LEN bit NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT' AND COLUMN_NAME = 'IS_SAMPLE')
    BEGIN
        ALTER TABLE PRODUCT ADD IS_SAMPLE int;
    END;
    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT' AND COLUMN_NAME = 'PURCHASE_CARBON_VALUE')
    BEGIN
        ALTER TABLE PRODUCT ALTER COLUMN PURCHASE_CARBON_VALUE decimal NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT' AND COLUMN_NAME = 'P_SAMPLE_ID')
    BEGIN
        ALTER TABLE PRODUCT ADD P_SAMPLE_ID bigint;
    END;
    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT' AND COLUMN_NAME = 'SALES_CARBON_VALUE')
    BEGIN
        ALTER TABLE PRODUCT ALTER COLUMN SALES_CARBON_VALUE decimal NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'STOCKS' AND COLUMN_NAME = 'ASSORTMENT_DEFAULT_AMOUNT')
    BEGIN
        ALTER TABLE STOCKS ADD ASSORTMENT_DEFAULT_AMOUNT int;
    END;
    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT_IMAGES' AND COLUMN_NAME = 'VIDEO_PATH')
    BEGIN
        ALTER TABLE PRODUCT_IMAGES ALTER COLUMN VIDEO_PATH nvarchar(500) NULL;
    END;
    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT_IMAGES' AND COLUMN_NAME = 'PRD_IMG_NAME')
    BEGIN
        ALTER TABLE PRODUCT_IMAGES ALTER COLUMN PRD_IMG_NAME nvarchar(500) NULL;
    END;
    IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME='BUILDING_POZ_TANIM')
    BEGIN
        CREATE TABLE [BUILDING_POZ_TANIM](	  [ID] int NOT NULL IDENTITY(1,1)	, [POZ_NO] nvarchar(50) NULL	, [POZ_DETAIL] nvarchar(MAX) NULL);
    END;
    IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME='BUILDING_ANALYSE')
    BEGIN
        CREATE TABLE [BUILDING_ANALYSE](	  [ANALIZ_ROW_ID] int NOT NULL IDENTITY(1,1)	, [MAIN_POZ] nvarchar(50) NULL	, [PRODUCT_CAT_ID] int NULL	, [PRODUCT_ID] int NULL	, [STOCK_ID] int NULL	, [METRAJ_STOCK_ID] int NULL	, [TARIH] datetime NULL	, [POZ] nvarchar(75) NULL	, [STOCK_NAME] nvarchar(MAX) NULL	, [BIRIM] nvarchar(75) NULL	, [ACIKLAMA_ROW] nvarchar(MAX) NULL	, [MAHAL] nvarchar(50) NULL	, [ADET] float NULL	, [BENZER] float NULL	, [EN] float NULL	, [BOY] float NULL	, [H] float NULL	, [TOPMIKTAR] float NULL	, [FIYAT] float NULL	, [TUTAR] float NULL	, CONSTRAINT [ANALIZ_ROW_ID] PRIMARY KEY ([ANALIZ_ROW_ID] ASC));
    END;
    IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME='BUILDING_POZ_LIST')
    BEGIN
        CREATE TABLE [BUILDING_POZ_LIST](	  [ID] int NOT NULL IDENTITY(1,1)	, [POZ_NO] nvarchar(50) NULL	, [POZ_NAME] nvarchar(MAX) NULL	, [POZ_DETAIL] nvarchar(MAX) NULL	, [BIRIM] int NULL	, [ALIS_FIYAT] float NULL	, [SATIS_FIYAT] float NULL	, [CATEGORY] nvarchar(50) NULL	, [COMP_CATEGORY] nvarchar(150) NULL	, [PRODUCT_ID] int NULL	, [STOCK_ID] int NULL	, [PRODUCT_CAT_ID] int NULL	, [IS_OWN] int NULL);
    END;
    IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME='LOT_NO_COUNTER')
    BEGIN
        CREATE TABLE [LOT_NO_COUNTER](	  [LOT_NO] nvarchar(100) NOT NULL	, [STOCK_ID] int NOT NULL	, [LOT_NUMBER] nvarchar(50) NOT NULL);
    END;
</querytag>