<!-- Description : Holistic.22.1 main objects
Developer: Fatih Kara
Company : Workcube
Destination: Main -->
<querytag>  

    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WRK_OUTPUT_TEMPLATES' AND COLUMN_NAME = 'BEST_PRACTISE_CODE')
    BEGIN
    ALTER TABLE WRK_OUTPUT_TEMPLATES ALTER COLUMN BEST_PRACTISE_CODE nvarchar(4000) NULL;
    END;

    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WRK_OUTPUT_TEMPLATES' AND COLUMN_NAME = 'OUTPUT_TEMPLATE_SECTORS')
    BEGIN
    ALTER TABLE WRK_OUTPUT_TEMPLATES ALTER COLUMN OUTPUT_TEMPLATE_SECTORS nvarchar(4000) NULL;
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PRODUCTION_ORDER_RESULTS_ROW' AND COLUMN_NAME = 'PURCHASE_NET_MONEY_2')
    BEGIN
    ALTER TABLE PRODUCTION_ORDER_RESULTS_ROW ADD PURCHASE_NET_MONEY_2 nvarchar(43);
    END;

    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WRK_MENU' AND COLUMN_NAME = 'USER_GROUP')
    BEGIN
    ALTER TABLE WRK_MENU ALTER COLUMN USER_GROUP text NULL;
    END;
    
    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WRK_MENU' AND COLUMN_NAME = 'BEST_PRACTISE')
    BEGIN
    ALTER TABLE WRK_MENU ALTER COLUMN BEST_PRACTISE text NULL;
    END;

    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WRK_MENU' AND COLUMN_NAME = 'MENU_JSON')
    BEGIN
    ALTER TABLE WRK_MENU ALTER COLUMN MENU_JSON text NULL;
    END;

    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PROTEIN_DESIGN_BLOCKS' AND COLUMN_NAME = 'BLOCK_CONTENT')
    BEGIN
    ALTER TABLE PROTEIN_DESIGN_BLOCKS ALTER COLUMN BLOCK_CONTENT text NULL;
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'ASSET_P_IT' AND COLUMN_NAME = 'NUMBER_OF_USERS')
    BEGIN
    ALTER TABLE ASSET_P_IT ADD NUMBER_OF_USERS int;
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'ASSET_P_IT' AND COLUMN_NAME = 'PASSWORD')
    BEGIN
    ALTER TABLE ASSET_P_IT ADD PASSWORD nvarchar(500);
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'ASSET_P_IT' AND COLUMN_NAME = 'USERNAME')
    BEGIN
    ALTER TABLE ASSET_P_IT ADD USERNAME nvarchar(250);
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PROCESS_TYPE_HISTORY' AND COLUMN_NAME = 'PAGE_NAME')
    BEGIN
    ALTER TABLE PROCESS_TYPE_HISTORY ADD PAGE_NAME nvarchar(max);
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PROCESS_TYPE' AND COLUMN_NAME = 'PAGE_NAME')
    BEGIN
    ALTER TABLE PROCESS_TYPE ADD PAGE_NAME nvarchar(max);
    END;

    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'HELP_DESK' AND COLUMN_NAME = 'HELP_FUSEACTION')
    BEGIN
    ALTER TABLE HELP_DESK ALTER COLUMN HELP_FUSEACTION nvarchar(250) NULL;
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WRK_OUTPUT_JOB' AND COLUMN_NAME = 'IS_NEW_TEMPLATE')
    BEGIN
    ALTER TABLE WRK_OUTPUT_JOB ADD IS_NEW_TEMPLATE bit;
    END;
</querytag>