<!-- Description : Add new columns to PAGE_WARNINGS and PROCESS_TYPE_ROWS tables
Developer: Uğur Hamurpet
Company : Workcube
Destination: Main -->
<querytag>
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PROCESS_TYPE_ROWS' AND COLUMN_NAME = 'COMMENT_REQUEST')
    BEGIN
        ALTER TABLE PROCESS_TYPE_ROWS ADD 
        COMMENT_REQUEST bit NULL
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PROCESS_TYPE_ROWS' AND COLUMN_NAME = 'CHECKER_NUMBER')
    BEGIN
        ALTER TABLE PROCESS_TYPE_ROWS ADD 
        CHECKER_NUMBER int NULL
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PROCESS_TYPE_ROWS' AND COLUMN_NAME = 'IS_CHECKER_UPDATE_AUTHORITY')
    BEGIN
        ALTER TABLE PROCESS_TYPE_ROWS ADD 
        IS_CHECKER_UPDATE_AUTHORITY bit NULL
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PROCESS_TYPE_ROWS' AND COLUMN_NAME = 'IS_ADD_ACCESS_CODE')
    BEGIN
        ALTER TABLE PROCESS_TYPE_ROWS ADD 
        IS_ADD_ACCESS_CODE bit NULL
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PROCESS_TYPE_ROWS' AND COLUMN_NAME = 'IS_CREATE_PASSWORD')
    BEGIN
        ALTER TABLE PROCESS_TYPE_ROWS ADD 
        IS_CREATE_PASSWORD bit NULL
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PROCESS_TYPE_ROWS' AND COLUMN_NAME = 'IS_CONFIRM_COMMENT_REQUIRED')
    BEGIN
        ALTER TABLE PROCESS_TYPE_ROWS ADD 
        IS_CONFIRM_COMMENT_REQUIRED bit NULL
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PROCESS_TYPE_ROWS' AND COLUMN_NAME = 'IS_REFUSE_COMMENT_REQUIRED')
    BEGIN
        ALTER TABLE PROCESS_TYPE_ROWS ADD 
        IS_REFUSE_COMMENT_REQUIRED bit NULL
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PROCESS_TYPE_ROWS' AND COLUMN_NAME = 'IS_AGAIN_COMMENT_REQUIRED')
    BEGIN
        ALTER TABLE PROCESS_TYPE_ROWS ADD 
        IS_AGAIN_COMMENT_REQUIRED bit NULL
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PROCESS_TYPE_ROWS' AND COLUMN_NAME = 'IS_SUPPORT_COMMENT_REQUIRED')
    BEGIN
        ALTER TABLE PROCESS_TYPE_ROWS ADD 
        IS_SUPPORT_COMMENT_REQUIRED bit NULL
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PROCESS_TYPE_ROWS' AND COLUMN_NAME = 'IS_CANCEL_COMMENT_REQUIRED')
    BEGIN
        ALTER TABLE PROCESS_TYPE_ROWS ADD 
        IS_CANCEL_COMMENT_REQUIRED bit NULL
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PAGE_WARNINGS' AND COLUMN_NAME = 'COMMENT_REQUEST')
    BEGIN
        ALTER TABLE PAGE_WARNINGS ADD 
        COMMENT_REQUEST bit NULL
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PAGE_WARNINGS' AND COLUMN_NAME = 'CHECKER_NUMBER')
    BEGIN
        ALTER TABLE PAGE_WARNINGS ADD 
        CHECKER_NUMBER int NULL
    END;
    
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PAGE_WARNINGS' AND COLUMN_NAME = 'IS_CHECKER_UPDATE_AUTHORITY')
    BEGIN
        ALTER TABLE PAGE_WARNINGS ADD 
        IS_CHECKER_UPDATE_AUTHORITY bit NULL
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PAGE_WARNINGS' AND COLUMN_NAME = 'ACCESS_CODE')
    BEGIN
        ALTER TABLE PAGE_WARNINGS ADD 
        ACCESS_CODE nvarchar(50) NULL
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PAGE_WARNINGS' AND COLUMN_NAME = 'WARNING_PASSWORD')
    BEGIN
        ALTER TABLE PAGE_WARNINGS ADD 
        WARNING_PASSWORD nvarchar(50) NULL
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PAGE_WARNINGS' AND COLUMN_NAME = 'IS_CONFIRM_COMMENT_REQUIRED')
    BEGIN
        ALTER TABLE PAGE_WARNINGS ADD 
        IS_CONFIRM_COMMENT_REQUIRED bit NULL
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PAGE_WARNINGS' AND COLUMN_NAME = 'IS_REFUSE_COMMENT_REQUIRED')
    BEGIN
        ALTER TABLE PAGE_WARNINGS ADD 
        IS_REFUSE_COMMENT_REQUIRED bit NULL
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PAGE_WARNINGS' AND COLUMN_NAME = 'IS_AGAIN_COMMENT_REQUIRED')
    BEGIN
        ALTER TABLE PAGE_WARNINGS ADD 
        IS_AGAIN_COMMENT_REQUIRED bit NULL
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PAGE_WARNINGS' AND COLUMN_NAME = 'IS_SUPPORT_COMMENT_REQUIRED')
    BEGIN
        ALTER TABLE PAGE_WARNINGS ADD 
        IS_SUPPORT_COMMENT_REQUIRED bit NULL
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PAGE_WARNINGS' AND COLUMN_NAME = 'IS_CANCEL_COMMENT_REQUIRED')
    BEGIN
        ALTER TABLE PAGE_WARNINGS ADD 
        IS_CANCEL_COMMENT_REQUIRED bit NULL
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'PAGE_WARNINGS' AND COLUMN_NAME = 'IS_MANUEL_NOTIFICATION')
    BEGIN
        ALTER TABLE PAGE_WARNINGS ADD 
        IS_MANUEL_NOTIFICATION bit NULL
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_main_@' AND TABLE_NAME = 'WRK_MESSAGE' AND COLUMN_NAME = 'WARNING_PARENT_ID')
    BEGIN
        ALTER TABLE WRK_MESSAGE ADD 
        WARNING_PARENT_ID int NULL
    END;

</querytag>