<!-- Description : CARI_CLOSED TABLOSUNA DETAYLI ACIKLAMA ICIN ALAN EKLENDI
Developer: İlker Altındal
Company : Workcube
Destination: Period -->
<querytag>
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CARI_CLOSED' AND TABLE_SCHEMA = '@_dsn_period_@' AND COLUMN_NAME = 'ADDITIONAL_DETAIL')
    BEGIN
        ALTER TABLE CARI_CLOSED ADD
        ADDITIONAL_DETAIL nvarchar(1000) NULL;
    END;
</querytag>