<!-- Description : EXPENSE_ITEM_PLAN_REQUESTS TABLOSUNA ASSURANCE_TYPE_ID ALANI EKLENDI
Developer: Botan Kaygan
Company : Workcube
Destination: Period -->
<querytag>
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EXPENSE_ITEM_PLAN_REQUESTS' AND TABLE_SCHEMA = '@_dsn_period_@' AND COLUMN_NAME = 'ASSURANCE_TYPE_ID')
    BEGIN
        ALTER TABLE EXPENSE_ITEM_PLAN_REQUESTS ADD
        ASSURANCE_TYPE_ID int NULL;
    END;
</querytag>