<!-- Description : Period WRO
Developer: Uğur Hamurpet
Company : Workcube
Destination: Period -->

<querytag>      
    IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' and TABLE_NAME='ESHIPMENT_RELATION' AND COLUMN_NAME='RECEIPMENT_ID' )
    BEGIN   
        ALTER TABLE ESHIPMENT_RELATION ADD RECEIPMENT_ID nvarchar(250) NULL 
    END;

    IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' and TABLE_NAME='ESHIPMENT_RELATION' AND COLUMN_NAME='RECEIPMENT_UUID' )
    BEGIN   
        ALTER TABLE ESHIPMENT_RELATION ADD RECEIPMENT_UUID nvarchar(250) NULL 
    END;

    IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' and TABLE_NAME='SHIP_RESULT' AND COLUMN_NAME='SERVICE_CONSUMER_MEMBER_ID' )
    BEGIN   
        ALTER TABLE SHIP_RESULT ADD SERVICE_CONSUMER_MEMBER_ID int NULL 
    END;

    IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' and TABLE_NAME='SHIP_RESULT' AND COLUMN_NAME='SERVICE_CONSUMER_ID' )
    BEGIN   
        ALTER TABLE SHIP_RESULT ADD SERVICE_CONSUMER_ID int NULL 
    END;

    IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' and TABLE_NAME='CARI_CLOSED_HISTORY' AND COLUMN_NAME='ADDITIONAL_DETAIL' )
    BEGIN   
        ALTER TABLE CARI_CLOSED_HISTORY ADD ADDITIONAL_DETAIL nvarchar(1000) NULL 
    END;

    IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' and TABLE_NAME='INTEREST_YIELD_VALUATION' AND COLUMN_NAME='RECORD_EMP' )
    BEGIN   
        ALTER TABLE INTEREST_YIELD_VALUATION ADD RECORD_EMP int NULL 
    END;

    IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' and TABLE_NAME='INTEREST_YIELD_VALUATION' AND COLUMN_NAME='RECORD_IP' )
    BEGIN   
        ALTER TABLE INTEREST_YIELD_VALUATION ADD RECORD_IP nvarchar(50) NULL 
    END;

    IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' and TABLE_NAME='INTEREST_YIELD_VALUATION' AND COLUMN_NAME='DATE_DIFF' )
    BEGIN   
        ALTER TABLE INTEREST_YIELD_VALUATION ADD DATE_DIFF int NULL 
    END;

    IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' and TABLE_NAME='INTEREST_YIELD_VALUATION' AND COLUMN_NAME='RECORD_DATE' )
    BEGIN   
        ALTER TABLE INTEREST_YIELD_VALUATION ADD RECORD_DATE datetime NULL 
    END;

    IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' and TABLE_NAME='INVOICE' AND COLUMN_NAME='BANK_ID' )
    BEGIN   
        ALTER TABLE INVOICE ADD BANK_ID int NULL 
    END;

    IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' and TABLE_NAME='INVOICE_ROW' AND COLUMN_NAME='TEVKIFAT_ID' )
    BEGIN   
        ALTER TABLE INVOICE_ROW ADD TEVKIFAT_ID int NULL 
    END;

    IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' and TABLE_NAME='INTEREST_YIELD_PLAN_ROWS' AND COLUMN_NAME='TERM_BANK_TO_BANK' )
    BEGIN   
        ALTER TABLE INTEREST_YIELD_PLAN_ROWS ADD TERM_BANK_TO_BANK int NULL 
    END;
    
    IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' and TABLE_NAME='STOCK_EXCHANGE' AND COLUMN_NAME='AMOUNT2' )
    BEGIN   
        ALTER TABLE STOCK_EXCHANGE ADD AMOUNT2 float NULL 
    END;

    IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' and TABLE_NAME='STOCK_EXCHANGE' AND COLUMN_NAME='EXIT_AMOUNT2' )
    BEGIN   
        ALTER TABLE STOCK_EXCHANGE ADD EXIT_AMOUNT2 float NULL 
    END;

    IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' and TABLE_NAME='INVOICE_HISTORY' AND COLUMN_NAME='BANK_ID' )
    BEGIN   
        ALTER TABLE INVOICE_HISTORY ADD BANK_ID int NULL 
    END;

    IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' and TABLE_NAME='SHIP' AND COLUMN_NAME='ACTION_DATE' )
    BEGIN   
        ALTER TABLE SHIP ADD ACTION_DATE datetime NULL 
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'BUDGET_TRANSFER_DEMAND' AND TABLE_SCHEMA = '@_dsn_period_@')
    BEGIN
        CREATE TABLE [BUDGET_TRANSFER_DEMAND](	  [DEMAND_ID] int NOT NULL IDENTITY(1,1)	, [BUDGET_ID] int NULL	, [DEMAND_EMP_ID] int NULL	, [DEMAND_DATE] datetime NULL	, [DEMAND_NO] nvarchar(100) NULL	, [DEMAND_STAGE] int NULL	, [DETAIL] nvarchar(MAX) NULL	, [RECORD_EMP] int NULL	, [RECORD_IP] nvarchar(50) NULL	, [RECORD_DATE] datetime NULL	, [UPDATE_EMP] int NULL	, [UPDATE_IP] nvarchar(50) NULL	, [UPDATE_DATE] datetime NULL	, CONSTRAINT [PK_BUDGET_TRANSFER_DEMAND_DEMAND_ID] PRIMARY KEY ([DEMAND_ID] ASC));
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'BUDGET_TRANSFER_DEMAND_ROWS' AND TABLE_SCHEMA = '@_dsn_period_@')
    BEGIN
        CREATE TABLE [BUDGET_TRANSFER_DEMAND_ROWS](	  [DEMAND_ROWS_ID] int NOT NULL IDENTITY(1,1)	, [DEMAND_ID] int NULL	, [DEMAND_EXP_CENTER] int NULL	, [DEMAND_EXP_ITEM] int NULL	, [DEMAND_ACTIVITY_TYPE] int NULL	, [DEMAND_PROJECT_ID] int NULL	, [AMOUNT] float NULL	, [USABLE_MONEY] float NULL	, [MONEY_CURRENCY] nvarchar(43) NULL	, [TRANSFER_EXP_CENTER] int NULL	, [TRANSFER_EXP_ITEM] int NULL	, [TRANSFER_ACTIVITY_TYPE] int NULL	, [TRANSFER_PROJECT_ID] int NULL	, [USABLE_TRANSFER_MONEY] float NULL	, [RECORD_EMP] int NULL	, [RECORD_IP] nvarchar(50) NULL	, [RECORD_DATE] datetime NULL	, [UPDATE_EMP] int NULL	, [UPDATE_IP] nvarchar(50) NULL	, [UPDATE_DATE] datetime NULL	, CONSTRAINT [PK_BUDGET_TRANSFER_DEMAND_ROWS_DEMAND_ROWS_ID] PRIMARY KEY ([DEMAND_ROWS_ID] ASC));
    END;
</querytag>