<!-- Description : Ürün detayında muhasebe kodu ve Satış siparişleri ekranında istisna nedeni için ilgili tablolara alan açıldı. 
Developer: Botan Kayğan
Company : Workcube
Destination: Company -->
<querytag>
    IF NOT EXISTS( SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='PRODUCT_PERIOD' AND TABLE_SCHEMA = '@_dsn_company_@' AND COLUMN_NAME='REASON_CODE')
    BEGIN
        ALTER TABLE PRODUCT_PERIOD ADD 
        REASON_CODE nvarchar(MAX) NULL
    END;

    IF NOT EXISTS( SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SUBSCRIPTION_PAYMENT_PLAN_ROW' AND TABLE_SCHEMA = '@_dsn_company_@' AND COLUMN_NAME='REASON_CODE')
    BEGIN
        ALTER TABLE SUBSCRIPTION_PAYMENT_PLAN_ROW ADD 
        REASON_CODE nvarchar(MAX) NULL
    END;

    IF NOT EXISTS( SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ORDER_ROW' AND TABLE_SCHEMA = '@_dsn_company_@' AND COLUMN_NAME='REASON_CODE')
    BEGIN
        ALTER TABLE ORDER_ROW ADD 
        REASON_CODE int NULL
    END;

    IF NOT EXISTS( SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ORDER_ROW' AND TABLE_SCHEMA = '@_dsn_company_@' AND COLUMN_NAME='REASON_NAME')
    BEGIN
        ALTER TABLE ORDER_ROW ADD 
        REASON_NAME nvarchar(250) NULL
    END;
</querytag>