<!-- Description : Vadeli Mevduat Reeskont Kayıt Tablosuna Ek Alanlar 
Developer: İlker Altındal
Company : Workcube
Destination: Period -->
<querytag>

    IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' and TABLE_NAME='INTEREST_YIELD_VALUATION')
        BEGIN

        CREATE TABLE [INTEREST_YIELD_VALUATION](
            [YIELD_VALUATION_ID] [int] IDENTITY(1,1) NOT NULL,
            [YIELD_ROWS_ID] [int] NULL,
            [YIELD_VALUATION_DATE] [datetime] NULL,
            [YIELD_VALUATION_AMOUNT] [float] NULL,
            [BUDGET_PLAN_ROW_ID] [int] NULL,
            [DATE_DIFF] [int] NULL,   
            [RECORD_DATE] [int] NULL, 
            [RECORD_EMP] [int] NULL, 
            [RECORD_IP] [int] NULL,
        CONSTRAINT [PK_INTEREST_YIELD_VALUATION] PRIMARY KEY CLUSTERED 
        (
            [YIELD_VALUATION_ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ) ON [PRIMARY]
        END;

    ELSE
    
        BEGIN
        IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' and TABLE_NAME='INTEREST_YIELD_VALUATION' AND COLUMN_NAME='DATE_DIFF' )
        BEGIN   
            ALTER TABLE INTEREST_YIELD_VALUATION ADD DATE_DIFF int NULL 
        END;

        IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' and TABLE_NAME='INTEREST_YIELD_VALUATION' AND COLUMN_NAME='RECORD_DATE' )
        BEGIN   
            ALTER TABLE INTEREST_YIELD_VALUATION ADD RECORD_DATE datetime NULL 
        END;

        IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' and TABLE_NAME='INTEREST_YIELD_VALUATION' AND COLUMN_NAME='RECORD_EMP' )
        BEGIN   
            ALTER TABLE INTEREST_YIELD_VALUATION ADD RECORD_EMP int NULL 
        END;

        IF NOT EXISTS(SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_period_@' and TABLE_NAME='INTEREST_YIELD_VALUATION' AND COLUMN_NAME='RECORD_IP' )
        BEGIN   
            ALTER TABLE INTEREST_YIELD_VALUATION ADD RECORD_IP nvarchar(50) NULL 
        END;

    END;

</querytag>