<!-- Description : Holistic.22.1 product objects
Developer: Uğur Hamurpet
Company : Workcube
Destination: Product -->
<querytag> 
    IF EXISTS(SELECT 'Y' FROM sys.indexes WHERE name='NCL_PRODUCT_1' AND object_id = OBJECT_ID('@_dsn_product_@.PRODUCT'))
    BEGIN
        DROP INDEX [NCL_PRODUCT_1] ON [PRODUCT];
    END;
    IF EXISTS(SELECT 'Y' FROM sys.indexes WHERE name='NCL_PRODUCT_2' AND object_id = OBJECT_ID('@_dsn_product_@.PRODUCT'))
    BEGIN
        DROP INDEX [NCL_PRODUCT_2] ON [PRODUCT];
    END;
    IF EXISTS(SELECT 'Y' FROM sys.indexes WHERE name='NCL_PRODUCT_3' AND object_id = OBJECT_ID('@_dsn_product_@.PRODUCT'))
    BEGIN
        DROP INDEX [NCL_PRODUCT_3] ON [PRODUCT];
    END;
    IF EXISTS(SELECT 'Y' FROM sys.indexes WHERE name='NCL_PRODUCT_4' AND object_id = OBJECT_ID('@_dsn_product_@.PRODUCT'))
    BEGIN
        DROP INDEX [NCL_PRODUCT_4] ON [PRODUCT];
    END;
    IF EXISTS(SELECT 'Y' FROM sys.indexes WHERE name='NCL_PRODUCT_5' AND object_id = OBJECT_ID('@_dsn_product_@.PRODUCT'))
    BEGIN
        DROP INDEX [NCL_PRODUCT_5] ON [PRODUCT];
    END;
    IF EXISTS(SELECT 'Y' FROM sys.indexes WHERE name='NCL_PRODUCT_6' AND object_id = OBJECT_ID('@_dsn_product_@.PRODUCT'))
    BEGIN
        DROP INDEX [NCL_PRODUCT_6] ON [PRODUCT];
    END;
    IF EXISTS(SELECT 'Y' FROM sys.indexes WHERE name='NCL_PRODUCT_7' AND object_id = OBJECT_ID('@_dsn_product_@.PRODUCT'))
    BEGIN
        DROP INDEX [NCL_PRODUCT_7] ON [PRODUCT];
    END;
    IF EXISTS(SELECT 'Y' FROM sys.indexes WHERE name='NCL_PRODUCT_8' AND object_id = OBJECT_ID('@_dsn_product_@.PRODUCT'))
    BEGIN
        DROP INDEX [NCL_PRODUCT_8] ON [PRODUCT];
    END;
    IF EXISTS(SELECT 'Y' FROM sys.indexes WHERE name='NCL_PRODUCT_9' AND object_id = OBJECT_ID('@_dsn_product_@.PRODUCT'))
    BEGIN
        DROP INDEX [NCL_PRODUCT_9] ON [PRODUCT];
    END;
    IF EXISTS(SELECT 'Y' FROM sys.indexes WHERE name='NCL_PRODUCT_TEST_' AND object_id = OBJECT_ID('@_dsn_product_@.PRODUCT'))
    BEGIN
        DROP INDEX [NCL_PRODUCT_TEST_] ON [PRODUCT];
    END;
    IF EXISTS(SELECT 'Y' FROM sys.indexes WHERE name='IX_PRODUCT_5' AND object_id = OBJECT_ID('@_dsn_product_@.PRODUCT'))
    BEGIN
        DROP INDEX [IX_PRODUCT_5] ON [PRODUCT];
    END;
    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT' AND COLUMN_NAME = 'CUSTOMS_RECIPE_CODE')
    BEGIN
        ALTER TABLE PRODUCT ALTER COLUMN CUSTOMS_RECIPE_CODE nvarchar(500) NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT' AND COLUMN_NAME = 'DISPOSAL_COST')
    BEGIN
        ALTER TABLE PRODUCT ADD DISPOSAL_COST float NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT' AND COLUMN_NAME = 'KARMA_FOR_PRODUCT_ID')
    BEGIN
        ALTER TABLE PRODUCT ADD KARMA_FOR_PRODUCT_ID int NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT' AND COLUMN_NAME = 'RECYCLE_GROUP_ID')
    BEGIN
        ALTER TABLE PRODUCT ADD RECYCLE_GROUP_ID int NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT' AND COLUMN_NAME = 'DISPOSAL_COST_CURRENCY')
    BEGIN
        ALTER TABLE PRODUCT ADD DISPOSAL_COST_CURRENCY nvarchar(500) NULL;
    END;
    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT' AND COLUMN_NAME = 'SHELF_LIFE')
    BEGIN
        ALTER TABLE PRODUCT ALTER COLUMN SHELF_LIFE nvarchar(300) NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT' AND COLUMN_NAME = 'KARMA_PROPERTY_DETAIL_ID')
    BEGIN
        ALTER TABLE PRODUCT ADD KARMA_PROPERTY_DETAIL_ID int NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT' AND COLUMN_NAME = 'IS_IMPORTED')
    BEGIN
        ALTER TABLE PRODUCT ADD IS_IMPORTED bit NULL;
    END;
    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT' AND COLUMN_NAME = 'PRODUCT_CODE')
    BEGIN
        ALTER TABLE PRODUCT ALTER COLUMN PRODUCT_CODE nvarchar(500) NULL;
    END;

    CREATE NONCLUSTERED INDEX [NCL_PRODUCT_1] ON [PRODUCT] ([PRODUCT_CATID] ASC,[PRODUCT_ID] ASC) 
    CREATE NONCLUSTERED INDEX [NCL_PRODUCT_2] ON [PRODUCT] ([UPDATE_DATE] ASC) 
    CREATE NONCLUSTERED INDEX [NCL_PRODUCT_3] ON [PRODUCT] ([RECORD_DATE] ASC) 
    CREATE NONCLUSTERED INDEX [NCL_PRODUCT_4] ON [PRODUCT] ([PRODUCT_CODE] ASC) 
    CREATE NONCLUSTERED INDEX [NCL_PRODUCT_5] ON [PRODUCT] ([PRODUCT_MANAGER] ASC,[PRODUCT_ID] ASC) 
    CREATE NONCLUSTERED INDEX [NCL_PRODUCT_6] ON [PRODUCT] ([COMPANY_ID] ASC,[PRODUCT_ID] ASC) 
    CREATE NONCLUSTERED INDEX [NCL_PRODUCT_7] ON [PRODUCT] ([BRAND_ID] ASC,[PRODUCT_ID] ASC) 
    CREATE NONCLUSTERED INDEX [NCL_PRODUCT_8] ON [PRODUCT] ([PRODUCT_STAGE] ASC) 
    CREATE NONCLUSTERED INDEX [NCL_PRODUCT_9] ON [PRODUCT] ([IS_INVENTORY] ASC,[PRODUCT_ID] ASC,[PRODUCT_NAME] ASC) 
    CREATE NONCLUSTERED INDEX [NCL_PRODUCT_TEST_] ON [PRODUCT] ([IS_COST] ASC,[PRODUCT_ID] ASC) 
    CREATE NONCLUSTERED INDEX [IX_PRODUCT_5] ON [PRODUCT] ([PRODUCT_CODE] ASC) 

    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'HSCODE_CHAPTER' AND COLUMN_NAME = 'HSCHAPTER_NO')
    BEGIN
        ALTER TABLE HSCODE_CHAPTER ALTER COLUMN HSCHAPTER_NO int NULL;
    END;
    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'HSCODE_CHAPTER' AND COLUMN_NAME = 'HSCHAPTER_DETAIL')
    BEGIN
        ALTER TABLE HSCODE_CHAPTER ALTER COLUMN HSCHAPTER_DETAIL nvarchar(300) NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT_GENERAL_PARAMETERS' AND COLUMN_NAME = 'IS_IMPORTED')
    BEGIN
        ALTER TABLE PRODUCT_GENERAL_PARAMETERS ADD IS_IMPORTED bit NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT_UNIT' AND COLUMN_NAME = 'PATH')
    BEGIN
        ALTER TABLE PRODUCT_UNIT ADD PATH nvarchar(500) NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT_UNIT' AND COLUMN_NAME = 'INSTRUCTION')
    BEGIN
        ALTER TABLE PRODUCT_UNIT ADD INSTRUCTION nvarchar(200) NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT_UNIT' AND COLUMN_NAME = 'PACKAGES')
    BEGIN
        ALTER TABLE PRODUCT_UNIT ADD PACKAGES int NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT_UNIT' AND COLUMN_NAME = 'PACKAGE_CONTROL_TYPE')
    BEGIN
        ALTER TABLE PRODUCT_UNIT ADD PACKAGE_CONTROL_TYPE int NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT_UNIT' AND COLUMN_NAME = 'PACKAGE_CONTROL_TYPE')
    BEGIN
        ALTER TABLE PRODUCT_UNIT ADD PACKAGE_CONTROL_TYPE int NULL;
    END;
    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'HSCODE' AND COLUMN_NAME = 'HSCODE_')
    BEGIN
        ALTER TABLE HSCODE ALTER COLUMN HSCODE_ nvarchar(200) NULL;
    END;
    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'HSCODE' AND COLUMN_NAME = 'HSCODE_DETAIL')
    BEGIN
        ALTER TABLE HSCODE ALTER COLUMN HSCODE_DETAIL text NULL;
    END;
    IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME='PRODUCT_DESIGN_DATA')
    BEGIN
        CREATE TABLE [PRODUCT_DESIGN_DATA](	  [PRODUCT_DESIGN_DATA_ID] int NOT NULL IDENTITY(1,1)	, [PRODUCT_ID] int NULL	, [PRODUCT_DESIGN_DATA_SETTINGS_ID] int NULL	, [DESIGN_DATA_FILE_PATH] nvarchar(250) NULL	, [RECORD_DATE] datetime NULL	, [RECORD_EMP] int NULL	, [RECORD_IP] nvarchar(50) NULL	, CONSTRAINT [PK__PRODUCT___3F2506164936506F] PRIMARY KEY ([PRODUCT_DESIGN_DATA_ID] ASC));
    END;
    IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME='PRODUCT_DESIGN_DATA_SETTINGS')
    BEGIN
        CREATE TABLE [PRODUCT_DESIGN_DATA_SETTINGS](	  [PRODUCT_DESIGN_DATA_SETTINGS_ID] int NOT NULL IDENTITY(1,1)	, [APPLICATION_TYPE] nvarchar(50) NULL	, [DESIGN_DATA_JSON] nvarchar(MAX) NULL	, [RECORD_EMP] int NULL	, [RECORD_DATE] datetime NULL	, [RECORD_IP] nvarchar(50) NULL	, [UPDATE_EMP] int NULL	, [UPDATE_DATE] datetime NULL	, [UPDATE_IP] nvarchar(50) NULL	, CONSTRAINT [PK__PRODUCT___E9BAC40037C58314] PRIMARY KEY ([PRODUCT_DESIGN_DATA_SETTINGS_ID] ASC));
    END;
</querytag>