<!-- Description : Holistic 22.2 sürümü tablolar ve kolon değişiklikleri
Developer: Fatih Kara
Company : Workcube
Destination: Product -->
<querytag>  

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT' AND COLUMN_NAME = 'KARMA_PROPERTY_COLLAR_ID')
    BEGIN
        ALTER TABLE PRODUCT ADD KARMA_PROPERTY_COLLAR_ID int;   
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT' AND COLUMN_NAME = 'KARMA_PROPERTY_SIZE_ID')
    BEGIN
        ALTER TABLE PRODUCT ADD KARMA_PROPERTY_SIZE_ID int;
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'PRODUCT_DT_PROPERTIES' AND COLUMN_NAME = 'PRODUCT_PROPERTY_ID')
    BEGIN
        ALTER TABLE PRODUCT_DT_PROPERTIES ADD PRODUCT_PROPERTY_ID int;
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'KARMA_PRODUCTS' AND COLUMN_NAME = 'PROPERTY_1')
    BEGIN
        ALTER TABLE KARMA_PRODUCTS ADD PROPERTY_1 nvarchar(100);
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'KARMA_PRODUCTS' AND COLUMN_NAME = 'PEROPERTY_NAME_2')
    BEGIN
        ALTER TABLE KARMA_PRODUCTS ADD PEROPERTY_NAME_2 nvarchar(100);
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'KARMA_PRODUCTS' AND COLUMN_NAME = 'PEROPERTY_NAME_1')
    BEGIN
        ALTER TABLE KARMA_PRODUCTS ADD PEROPERTY_NAME_1 nvarchar(100);
    END;

    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_product_@' AND TABLE_NAME = 'KARMA_PRODUCTS' AND COLUMN_NAME = 'PROPERTY_2')
    BEGIN
        ALTER TABLE KARMA_PRODUCTS ADD PROPERTY_2 nvarchar(100);
    END;
    
</querytag>