<!-- Description : Chatflow düzenlemeleri için dil - tablo - wo eklenmesi 
Developer: İlker Altındal
Company : Workcube
Destination: Main -->
<querytag>

    IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='WRK_MESSAGE_FILES' )
    BEGIN
		CREATE TABLE [WRK_MESSAGE_FILES](
            [MESSAGE_FILE_ID] [int] IDENTITY(1,1) NOT NULL,
            [MESSAGE_ID] [int] NOT NULL,
            [MESSAGE_FILE_NAME] [nvarchar](50) NOT NULL,
            [MESSAGE_FILE_ENCRYPTED_NAME] [nvarchar](50) NOT NULL,
            [MESSAGE_FILE_FULL_NAME] [nvarchar](50) NOT NULL,
            [MESSAGE_FILE_ENCRYPTED_FULL_NAME] [nvarchar](50) NOT NULL,
            [MESSAGE_FILE_EXTENTION] [nvarchar](50) NOT NULL,
            [MESSAGE_FILE_SIZE] [int] NOT NULL,
            [MESSAGE_FILE_MIME_TYPE] [nvarchar](50) NOT NULL,
        CONSTRAINT [PK_WRK_MESSAGE_FILES] PRIMARY KEY CLUSTERED 
        (
            [MESSAGE_FILE_ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ) ON [PRIMARY]
	END;

    IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_MESSAGE' AND COLUMN_NAME = 'ACTION_ID' )
    BEGIN
        ALTER TABLE WRK_MESSAGE ADD 
        ACTION_ID int
    END;

    IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_MESSAGE' AND COLUMN_NAME = 'ACTION_PAGE' )
    BEGIN
        ALTER TABLE WRK_MESSAGE ADD 
        ACTION_PAGE nvarchar(150)
    END;

    IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_MESSAGE' AND COLUMN_NAME = 'FUSEACTION' )
    BEGIN
        ALTER TABLE WRK_MESSAGE ADD 
        FUSEACTION nvarchar(250)
    END;

    IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_MESSAGE' AND COLUMN_NAME = 'ACTION_COLUMN' )
    BEGIN
        ALTER TABLE WRK_MESSAGE ADD 
        ACTION_COLUMN nvarchar(250)
    END;

    IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_MESSAGE' AND COLUMN_NAME = 'WARNING_HEAD' )
    BEGIN
        ALTER TABLE WRK_MESSAGE ADD 
        WARNING_HEAD nvarchar(250)
    END;

    IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WRK_MESSAGE' AND COLUMN_NAME = 'MESSAGE_FILE' )
    BEGIN
        ALTER TABLE WRK_MESSAGE ADD 
        MESSAGE_FILE int
    END;

    UPDATE SETUP_LANGUAGE_TR SET ITEM='Gelen Süreç Mesajları', ITEM_TR='Gelen Süreç Mesajları', ITEM_ENG='Incoming Process Messages' WHERE DICTIONARY_ID = 51392
    UPDATE SETUP_LANGUAGE_TR SET ITEM='Giden Süreç Mesajları', ITEM_TR='Giden Süreç Mesajları', ITEM_ENG='Outgoing Process Messages' WHERE DICTIONARY_ID = 51393
    UPDATE SETUP_LANGUAGE_TR SET ITEM='Tüm Süreç Mesajları', ITEM_TR='Tüm Süreç Mesajları', ITEM_ENG='All Process Messages' WHERE DICTIONARY_ID = 51394
    UPDATE SETUP_LANGUAGE_TR SET ITEM='Mesajı Silmek İstediğinize Emin misiniz ?', ITEM_TR='Mesajı Silmek İstediğinize Emin misiniz ?', ITEM_ENG='Are you sure you want to delete the message ?' WHERE DICTIONARY_ID = 51395
    UPDATE SETUP_LANGUAGE_TR SET ITEM='Süreç Detayı', ITEM_TR='Süreç Detayı', ITEM_ENG='Process Detail' WHERE DICTIONARY_ID = 51944
    
    IF NOT EXISTS(SELECT WRK_OBJECTS_ID FROM WRK_OBJECTS WHERE FULL_FUSEACTION = 'objects.workflowpages')
    BEGIN
     INSERT [WRK_OBJECTS] ([IS_ACTIVE], [MODULE_NO], [HEAD], [DICTIONARY_ID], [FRIENDLY_URL], [FULL_FUSEACTION], [FULL_FUSEACTION_VARIABLES], [FILE_PATH], [CONTROLLER_FILE_PATH], [STANDART_ADDON], [LICENCE], [EVENT_TYPE], [STATUS], [IS_DEFAULT], [IS_MENU], [WINDOW], [VERSION], [IS_CATALYST_MOD], [MENU_SORT_NO], [USE_PROCESS_CAT], [USE_SYSTEM_NO], [USE_WORKFLOW], [DETAIL], [AUTHOR], [OBJECTS_COUNT], [DESTINATION_MODUL], [RECORD_IP], [RECORD_EMP], [RECORD_DATE], [UPDATE_IP], [UPDATE_EMP], [UPDATE_DATE], [SECURITY], [STAGE], [MODUL], [BASE], [MODUL_SHORT_NAME], [FUSEACTION], [FUSEACTION2], [FOLDER], [FILE_NAME], [IS_ADD], [IS_UPDATE], [IS_DELETE], [LEFT_MENU_NAME], [IS_WBO_DENIED], [IS_WBO_FORM_LOCK], [IS_WBO_LOCK], [IS_WBO_LOG], [IS_SPECIAL], [IS_TEMP], [EVENT_ADD], [EVENT_DASHBOARD], [EVENT_DEFAULT], [EVENT_DETAIL], [EVENT_LIST], [EVENT_UPD], [TYPE], [POPUP_TYPE], [RANK_NUMBER], [EXTERNAL_FUSEACTION], [IS_LEGACY], [ADDOPTIONS_CONTROLLER_FILE_PATH], [THEME_PATH], [DISPLAY_BEFORE_PATH], [DISPLAY_AFTER_PATH], [ACTION_BEFORE_PATH], [ACTION_AFTER_PATH], [ICON]) VALUES (1, 47, N'İş Akışları', 31032, N'WorkFlowPages', N'objects.workflowpages', NULL, N'objects/display/workflowPages.cfm', NULL, NULL, 1, NULL, N'Development', NULL, 0, NULL, N'v16', NULL, NULL, 0, 0, 0, N'<p>Chat&nbsp; / Workflow / Thinkflow / Knowledge objelerini barındırır.</p>', N'Workcube Core', NULL, NULL, N'127.0.0.1', 67, CAST(N'2019-08-15 11:31:57.000' AS DateTime), N'127.0.0.1', 67, CAST(N'2019-08-15 11:32:29.460' AS DateTime), N'HTTP', 2176, NULL, NULL, N'objects', N'workflowpages', NULL, N'W3WorkDev', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, 0, 1, 0, 0, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
    END
</querytag>