<!-- Description : holistic 21.2 sürümü tablolar ve kolon değişiklikleri
Developer: Fatih Kara
Company : Workcube
Destination: Company -->
<querytag>  
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'PROGRESS_PAYMENT' AND COLUMN_NAME = 'RELATED_OPERATION_ID')
    BEGIN
        ALTER TABLE PROGRESS_PAYMENT ADD RELATED_OPERATION_ID nvarchar(max) NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'PROGRESS_PAYMENT' AND COLUMN_NAME = 'COLLECTOR_ID')
    BEGIN
        ALTER TABLE PROGRESS_PAYMENT ADD COLLECTOR_ID int;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'PROGRESS_PAYMENT' AND COLUMN_NAME = 'REVENUE_COLLECTOR')
    BEGIN
        ALTER TABLE PROGRESS_PAYMENT ADD REVENUE_COLLECTOR nvarchar(100) NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'PROGRESS_PAYMENT' AND COLUMN_NAME = 'PAYROLL_NO')
    BEGIN
        ALTER TABLE PROGRESS_PAYMENT ADD PAYROLL_NO nvarchar(50) NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'PROGRESS_PAYMENT' AND COLUMN_NAME = 'BASKET_MONEY_TYPE')
    BEGIN
        ALTER TABLE PROGRESS_PAYMENT ADD BASKET_MONEY_TYPE nvarchar(30) NULL;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'PROGRESS_PAYMENT' AND COLUMN_NAME = 'RELATED_OPERATION_TYPE')
    BEGIN
        ALTER TABLE PROGRESS_PAYMENT ADD RELATED_OPERATION_TYPE int;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'PROGRESS_PAYMENT' AND COLUMN_NAME = 'REVENUE_COLLECTOR_ID')
    BEGIN
        ALTER TABLE PROGRESS_PAYMENT ADD REVENUE_COLLECTOR_ID int;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'PROGRESS_PAYMENT_ROW')
    BEGIN
        CREATE TABLE [PROGRESS_PAYMENT_ROW](	  
        [PROGRESS_ID] int NOT NULL, 
        [STOCK_ID] int NULL, 
        [DETAIL] nvarchar(250) NULL
        );
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'order_row_reserved_15122021_0949500')
    BEGIN
        CREATE TABLE [order_row_reserved_15122021_0949500](	  
        [ROW_RESERVED_ID] int NOT NULL IDENTITY(1,1), 
        [STOCK_ID] int NULL, 
        [PRODUCT_ID] int NULL, 
        [SPECT_VAR_ID] int NULL, 
        [ORDER_ID] int NULL, 
        [ORDER_ROW_ID] int NULL, 
        [SHIP_ID] int NULL, 
        [INVOICE_ID] int NULL, 
        [PERIOD_ID] int NULL, 
        [RESERVE_STOCK_IN] float NULL, 
        [RESERVE_STOCK_OUT] float NULL, 
        [RESERVE_CANCEL_AMOUNT] float NULL, 
        [STOCK_IN] float NULL, 
        [STOCK_OUT] float NULL, 
        [DEPARTMENT_ID] int NULL, 
        [LOCATION_ID] int NULL, 
        [SHELF_NUMBER] int NULL,
        [PRE_ORDER_ID] nvarchar(60) NULL, 
        [STOCK_STRATEGY_ID] int NULL, 
        [IS_BASKET] int NULL, 
        [ORDER_WRK_ROW_ID] nvarchar(40) NULL
        );
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'PRODUCTION_ORDER_RESULTS' AND COLUMN_NAME = 'CONSUMER_ID')
    BEGIN
        ALTER TABLE PRODUCTION_ORDER_RESULTS ADD CONSUMER_ID int;
    END;
    IF NOT EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'PRODUCTION_ORDER_RESULTS' AND COLUMN_NAME = 'COMPANY_ID')
    BEGIN
        ALTER TABLE PRODUCTION_ORDER_RESULTS ADD COMPANY_ID int;
    END;
    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'SETUP_PROCESS_CAT' AND COLUMN_NAME = 'RECORD_IP')
    BEGIN
        ALTER TABLE SETUP_PROCESS_CAT ALTER COLUMN RECORD_IP nvarchar(50)  NULL;
    END;
    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'SETUP_PROCESS_CAT' AND COLUMN_NAME = 'RECORD_DATE')
    BEGIN
        ALTER TABLE SETUP_PROCESS_CAT ALTER COLUMN RECORD_DATE datetime NULL;
    END;
    IF EXISTS (SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@_dsn_company_@' AND TABLE_NAME = 'CAMPAIGN_CATS' AND COLUMN_NAME = 'CAMP_CAT_ID_')
    BEGIN
        ALTER TABLE CAMPAIGN_CATS ALTER COLUMN CAMP_CAT_ID_ int;
    END;
</querytag>