<!-- Description : Gelir Senaryo Viewine Proje eklendi
Developer: Fatih Kara
Company : Workcube
Destination: Period -->

<querytag>

    ALTER VIEW [GET_SCEN_INCOME] AS
			SELECT
				-1 AS SCEN_TYPE_ID, 
				C.CHEQUE_DUEDATE AS TARIH, 
				SUM(C.CHEQUE_VALUE*(SM.RATE2/SM.RATE1)) AS CHEQUE_TOTAL,
				0 VOUCHER_TOTAL,
				0 CC_BANK_PAYM,		
				0 CREDIT_CONTRACT_TOTAL,
				0 BANK_ORDER_TOTAL,
				0 BUDGET_TOTAL,
				0 SCEN_EXPENSE_TOTAL,
				P.PROJECT_ID PROJECT_ID
			FROM
                @_dsn_period_@.CHEQUE C,
				@_dsn_period_@.SETUP_MONEY	SM,
				@_dsn_period_@.PAYROLL P,
				@_dsn_period_@.CHEQUE_HISTORY CH
			WHERE
				C.CHEQUE_STATUS_ID IN (1,2,13) AND
				C.CURRENCY_ID = SM.MONEY AND
				CH.PAYROLL_ID=P.ACTION_ID AND
				C.CHEQUE_ID = CH.CHEQUE_ID
			GROUP BY
				C.CHEQUE_DUEDATE,
				P.PROJECT_ID
		UNION ALL
			SELECT
				-2 AS SCEN_TYPE_ID, 
				V.VOUCHER_DUEDATE AS TARIH,
				0 CHEQUE_TOTAL,
				SUM(V.VOUCHER_VALUE*(SM.RATE2/SM.RATE1)) VOUCHER_TOTAL,
				0 CC_BANK_PAYM,		
				0 CREDIT_CONTRACT_TOTAL,
				0 BANK_ORDER_TOTAL,
				0 BUDGET_TOTAL,
				0 SCEN_EXPENSE_TOTAL,
				VP.PROJECT_ID PROJECT_ID
			FROM
                @_dsn_period_@.VOUCHER V,
                @_dsn_period_@.SETUP_MONEY	SM,
				@_dsn_period_@.VOUCHER_PAYROLL VP,
				@_dsn_period_@.VOUCHER_HISTORY VH
			WHERE
				V.VOUCHER_STATUS_ID IN (1,2,13) AND
				V.CURRENCY_ID = SM.MONEY AND
				VH.PAYROLL_ID=VP.ACTION_ID AND
				V.VOUCHER_ID = VH.VOUCHER_ID
			GROUP BY
				V.VOUCHER_DUEDATE,
				VP.PROJECT_ID
		UNION ALL
			SELECT
				-3 AS SCEN_TYPE_ID,
				CR.BANK_ACTION_DATE AS TARIH,
				0 CHEQUE_TOTAL,
				0 VOUCHER_TOTAL,
				SUM((CASE WHEN CCP.ACTION_TYPE_ID = 245 THEN -CR.AMOUNT ELSE CR.AMOUNT END)) AS CC_BANK_PAYM,
				0 CREDIT_CONTRACT_TOTAL,
				0 BANK_ORDER_TOTAL,
				0 BUDGET_TOTAL,
				0 SCEN_EXPENSE_TOTAL,
				CCP.PROJECT_ID PROJECT_ID
			FROM
				@_dsn_company_@.CREDIT_CARD_BANK_PAYMENTS_ROWS CR,
				@_dsn_company_@.CREDIT_CARD_BANK_PAYMENTS CCP
			WHERE
				CR.CREDITCARD_PAYMENT_ID = CCP.CREDITCARD_PAYMENT_ID AND
				ISNULL(CCP.IS_VOID,0) <> 1 AND
				ISNULL(CCP.RELATION_CREDITCARD_PAYMENT_ID,0) NOT IN (SELECT CCBP.CREDITCARD_PAYMENT_ID FROM @_dsn_company_@.CREDIT_CARD_BANK_PAYMENTS CCBP WHERE ISNULL(CCBP.IS_VOID,0) = 1) AND
				CR.BANK_ACTION_ID IS NULL AND
				CR.AMOUNT > 0
			GROUP BY
				CR.BANK_ACTION_DATE,
				CCP.PROJECT_ID
		UNION ALL
			SELECT
				-4 AS SCEN_TYPE_ID,
				PROCESS_DATE AS TARIH,
				0 CHEQUE_TOTAL,
				0 VOUCHER_TOTAL,
				0 CC_BANK_PAYM,		
				(TOTAL_PRICE * (SM.RATE2 / SM.RATE1)) CREDIT_CONTRACT_TOTAL,
				0 BANK_ORDER_TOTAL,
				0 BUDGET_TOTAL,
				0 SCEN_EXPENSE_TOTAL,
				C.PROJECT_ID PROJECT_ID
			FROM
                @_dsn_company_@.CREDIT_CONTRACT_ROW CC,
                @_dsn_company_@.CREDIT_CONTRACT C,
				@_dsn_period_@.SETUP_MONEY SM
			WHERE
				C.CREDIT_CONTRACT_ID = CC.CREDIT_CONTRACT_ID AND
				C.IS_SCENARIO = 1 AND
				CREDIT_CONTRACT_TYPE = 2 AND
				TOTAL_PRICE > 0 AND
			
				((CC.OTHER_MONEY = 'YTL' AND SM.MONEY = 'TL') OR SM.MONEY = CC.OTHER_MONEY) AND
				
				CC.IS_PAID = 0 AND
				(CC.IS_PAID_ROW  = 0 OR CC.IS_PAID_ROW IS NULL)
		UNION ALL
			SELECT
				-5 AS SCEN_TYPE_ID,
				PAYMENT_DATE AS TARIH,
				0 CHEQUE_TOTAL,
				0 VOUCHER_TOTAL,
				0 CC_EXPENSE_TOTAL,
				0 CREDIT_CONTRACT_TOTAL,
				SUM(BON.ACTION_VALUE*(SM.RATE2/SM.RATE1)) AS BANK_ORDER_TOTAL,
				0 BUDGET_TOTAL,
				0 SCEN_EXPENSE_TOTAL,
				BON.PROJECT_ID PROJECT_ID
			FROM
                @_dsn_period_@.BANK_ORDERS BON,
				@_dsn_period_@.SETUP_MONEY SM
			WHERE
				(BON.IS_PAID = 0 OR BON.IS_PAID IS NULL)
				AND BON.ACTION_MONEY = SM.MONEY
				AND BANK_ORDER_TYPE = 251
			GROUP BY
				PAYMENT_DATE,
				SM.RATE2, 
				SM.RATE1,
				BON.PROJECT_ID
		UNION ALL
			SELECT
				-6 AS SCEN_TYPE_ID,
				BPR.PLAN_DATE AS TARIH,
				0 CHEQUE_TOTAL,
				0 VOUCHER_TOTAL,
				0 CC_EXPENSE_TOTAL,
				0 CREDIT_CONTRACT_TOTAL,
				0 BANK_ORDER_TOTAL,
				SUM(BPR.OTHER_ROW_TOTAL_INCOME*(SM.RATE2/SM.RATE1)) AS BUDGET_TOTAL,
				0 SCEN_EXPENSE_TOTAL,
				BPR.PROJECT_ID PROJECT_ID
			FROM
                @_dsn_main_@.BUDGET_PLAN BP,
				@_dsn_main_@.BUDGET_PLAN_ROW BPR,
				@_dsn_period_@.SETUP_MONEY SM
			WHERE
				BP.BUDGET_PLAN_ID = BPR.BUDGET_PLAN_ID 
				AND BP.OTHER_MONEY = SM.MONEY
				AND BP.IS_SCENARIO = 1
			GROUP BY
				BPR.PLAN_DATE,
				SM.RATE2, 
				SM.RATE1,
				BPR.PROJECT_ID
		UNION ALL
			SELECT
				SE.SCENARIO_TYPE_ID AS SCEN_TYPE_ID, 
				SE.START_DATE AS TARIH, 
				0 CHEQUE_TOTAL,
				0 VOUCHER_TOTAL,
				0 CC_BANK_PAYM,		
				0 CREDIT_CONTRACT_TOTAL,
				0 BANK_ORDER_TOTAL,
				0 BUDGET_TOTAL,
				SUM(SE.PERIOD_VALUE * (SM.RATE2 / SM.RATE1)) SCEN_EXPENSE_TOTAL,
				SE.PROJECT_ID PROJECT_ID
			FROM
                @_dsn_company_@.SCEN_EXPENSE_PERIOD_ROWS SE, 
				@_dsn_period_@.SETUP_MONEY SM
			WHERE
				SE.TYPE = 1 AND 
				SE.SCEN_EXPENSE_STATUS = 1 AND
				SM.MONEY = SE.PERIOD_CURRENCY
			GROUP BY
				SE.START_DATE, 
				SE.PERIOD_VALUE, 
				SM.RATE2, 
				SM.RATE1,
				SE.SCENARIO_TYPE_ID,
				SE.PROJECT_ID
		UNION ALL
			SELECT 
				-7 AS SCEN_TYPE_ID, 
				SSR.BANK_ACTION_DATE AS TARIH, 
				0 CHEQUE_TOTAL,
				0 VOUCHER_TOTAL,
				0 CC_BANK_PAYM,		
				0 CREDIT_CONTRACT_TOTAL,
				0 BANK_ORDER_TOTAL,
				0 BUDGET_TOTAL,
				SSR.AMOUNT AS MK_INCOME_TOTAL,
				'' PROJECT_ID
			FROM
                @_dsn_company_@.STOCKBONDS_YIELD_PLAN_ROWS AS SSR
			GROUP BY
				SSR.BANK_ACTION_DATE,
				SSR.AMOUNT

</querytag>