<cfquery name="TEMPLATES" datasource="#DSN#">
	SELECT 
		IS_PURSUIT_TEMPLATE,
		TEMPLATE_CONTENT,
		TEMPLATE_HEAD,
		TEMPLATE_ID,
		TEMPLATE_MODULE 
	FROM 
		TEMPLATE_FORMS
	ORDER BY 
		TEMPLATE_HEAD	
</cfquery>
