<cfquery name="GET_EMPLOYEES" datasource="#dsn#">
	SELECT 
		POSITION_CODE,
		EMPLOYEE_NAME,
		EMPLOYEE_SURNAME
	FROM 
		EMPLOYEE_POSITIONS
	WHERE 
		DEPARTMENT_ID IN (SELECT DEPARTMENT.DEPARTMENT_ID FROM DEPARTMENT,BRANCH WHERE BRANCH.BRANCH_ID = DEPARTMENT.BRANCH_ID AND DEPARTMENT_STATUS = 1 AND BRANCH.BRANCH_ID = #attributes.BRANCH_ID#)
		AND
		POSITION_STATUS = 1
</cfquery>
