<cfquery name="GET_PARTNERS" datasource="#DSN#">
	SELECT 
		CP.PARTNER_ID,
		CP.COMPANY_PARTNER_NAME,
		CP.COMPANY_PARTNER_SURNAME
	FROM 
		COMPANY_PARTNER CP,
		COMPANY C
	WHERE
		CP.COMPANY_PARTNER_STATUS = 1 AND
		C.COMPANY_ID = CP.COMPANY_ID AND
		C.COMPANYCAT_ID = #attributes.companycat_id#
</cfquery>		

