<cfquery name="GET_MAIN_PROCESS_CATS" datasource="#dsn#">
	SELECT 
		MAIN_PROCESS_CAT_ID,
		#dsn#.Get_Dynamic_Language(MAIN_PROCESS_CAT_ID,'#session.ep.language#','SETUP_MAIN_PROCESS_CAT','MAIN_PROCESS_CAT',NULL,NULL,MAIN_PROCESS_CAT) AS MAIN_PROCESS_CAT,
		MAIN_PROCESS_MODULE,
		MAIN_PROCESS_TYPE,
		RECORD_DATE,
		RECORD_EMP,
		RECORD_IP,
		UPDATE_DATE,
		UPDATE_EMP,
		UPDATE_IP
	FROM 
		SETUP_MAIN_PROCESS_CAT
	ORDER BY
		MAIN_PROCESS_CAT
</cfquery>
