<cfquery name="GET_PRINT_FILES_POSITIONS" datasource="#DSN#">
	SELECT 
		SPFP.POS_CODE,
		EP.POSITION_NAME,
		EP.EMPLOYEE_NAME,
		EP.EMPLOYEE_SURNAME
	FROM 
		SETUP_PRINT_FILES_POSITION SPFP,
		EMPLOYEE_POSITIONS EP
	WHERE
		SPFP.FORM_ID = #attributes.form_id# AND
		EP.POSITION_CODE = SPFP.POS_CODE AND
        SPFP.OUR_COMPANY_ID = #session.ep.company_id#
</cfquery>

