<cfquery name="get_offtime_requests" datasource="#dsn#">
	SELECT
		OFFTIME.VALID,
		OFFTIME.OFFTIME_ID,
		OFFTIME.EMPLOYEE_ID,
		OFFTIME.VALIDATOR_POSITION_CODE,
		OFFTIME.STARTDATE,
		OFFTIME.FINISHDATE,
		OFFTIME.TOTAL_HOURS,
		EMPLOYEES.EMPLOYEE_NAME,
		EMPLOYEES.EMPLOYEE_SURNAME
	FROM
		OFFTIME,
		EMPLOYEES
	WHERE
		OFFTIME.VALID IS NULL
		AND
		OFFTIME.VALIDATOR_POSITION_CODE = #SESSION.EP.POSITION_CODE#
		AND
		EMPLOYEES.EMPLOYEE_ID = OFFTIME.EMPLOYEE_ID
</cfquery>
