<cfquery name="GET_PARTNER_COMPANY_AND_AUTHORITY" datasource="#dsn#">
	SELECT
		COMPANY_PARTNER.COMPANY_PARTNER_NAME,
		COMPANY_PARTNER.COMPANY_PARTNER_SURNAME,
		COMPANY.FULLNAME,
		COMPANY.COMPANY_ID
	FROM
		COMPANY,
		COMPANY_PARTNER
	WHERE
		COMPANY_PARTNER.PARTNER_ID = #PARTNER_ID# AND
		COMPANY.COMPANY_ID = COMPANY_PARTNER.COMPANY_ID
</cfquery>

