<cfquery name="GET_PARTNER_DETAIL" datasource="#DSN#">
	SELECT
		*
	FROM
		COMPANY_PARTNER,
		COMPANY,
		COMPANY_CAT
	WHERE
		COMPANY_PARTNER.COMPANY_ID = COMPANY.COMPANY_ID AND
		COMPANY_PARTNER.PARTNER_ID = #PARTNER_ID# AND
		COMPANY_CAT.COMPANYCAT_ID = COMPANY.COMPANYCAT_ID
</cfquery>
