IF NOT EXISTS( SELECT 'Y' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'JEDI_PACKAGES' AND TABLE_SCHEMA = '@_dsn_main_@' )
BEGIN

    CREATE TABLE [JEDI_PACKAGES](
	[PACKAGE_ID] [int] IDENTITY(1,1) NOT NULL,
	[USERID] [int] NOT NULL,
	[HEAD] [nvarchar](250) NOT NULL,
	[PATH] [nvarchar](100) NOT NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[RECORD_DATE] [datetime] NOT NULL,
	[RECORD_IP] [nvarchar](25) NOT NULL,
    CONSTRAINT [PK_JEDI_PACKAGES] PRIMARY KEY CLUSTERED 
    (
        [PACKAGE_ID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    ) ON [PRIMARY]

END

IF NOT EXISTS( SELECT 'Y' FROM WRK_OBJECTS WHERE FULL_FUSEACTION = 'jedi.package' )
BEGIN
	INSERT [WRK_OBJECTS] ([WRK_OBJECTS_ID], [IS_ACTIVE], [MODULE_NO], [HEAD], [DICTIONARY_ID], [FRIENDLY_URL], [FULL_FUSEACTION], [FULL_FUSEACTION_VARIABLES], [FILE_PATH], [CONTROLLER_FILE_PATH], [STANDART_ADDON], [LICENCE], [EVENT_TYPE], [STATUS], [IS_DEFAULT], [IS_MENU], [WINDOW], [VERSION], [IS_CATALYST_MOD], [MENU_SORT_NO], [USE_PROCESS_CAT], [USE_SYSTEM_NO], [USE_WORKFLOW], [DETAIL], [AUTHOR], [OBJECTS_COUNT], [DESTINATION_MODUL], [RECORD_IP], [RECORD_EMP], [RECORD_DATE], [UPDATE_IP], [UPDATE_EMP], [UPDATE_DATE], [SECURITY], [STAGE], [MODUL], [BASE], [MODUL_SHORT_NAME], [FUSEACTION], [FUSEACTION2], [FOLDER], [FILE_NAME], [IS_ADD], [IS_UPDATE], [IS_DELETE], [LEFT_MENU_NAME], [IS_WBO_DENIED], [IS_WBO_FORM_LOCK], [IS_WBO_LOCK], [IS_WBO_LOG], [IS_SPECIAL], [IS_TEMP], [EVENT_ADD], [EVENT_DASHBOARD], [EVENT_DEFAULT], [EVENT_DETAIL], [EVENT_LIST], [EVENT_UPD], [TYPE], [POPUP_TYPE], [RANK_NUMBER], [EXTERNAL_FUSEACTION], [IS_LEGACY], [ADDOPTIONS_CONTROLLER_FILE_PATH], [THEME_PATH], [IS_ONLY_SHOW_PAGE], [DISPLAY_BEFORE_PATH], [DISPLAY_AFTER_PATH], [ACTION_BEFORE_PATH], [ACTION_AFTER_PATH], [ICON], [XML_PATH]) VALUES (17446, 1, 9, N'Paket', 45548, NULL, N'jedi.package', NULL, N'AddOns/Jedi/packagemanager/views/list.cfm', N'AddOns/Jedi/controllers/packagecontroller.cfm', NULL, 2, NULL, N'Development', NULL, 1, NULL, N'1', NULL, NULL, 0, 0, 0, N'<p><br></p>', N'Halit Yurttaş', NULL, NULL, N'127.0.0.1', 16, CAST(N'2020-10-26T02:27:33.000' AS DateTime), N'127.0.0.1', 16, CAST(N'2020-10-26T02:28:23.680' AS DateTime), N'Dark', NULL, NULL, NULL, N'jedi', N'package', NULL, N'W3WorkDev', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
END

IF NOT EXISTS( SELECT 'Y' FROM WRK_OBJECTS WHERE FULL_FUSEACTION = 'jedi.playground' )
BEGIN
	INSERT [WRK_OBJECTS] ([WRK_OBJECTS_ID], [IS_ACTIVE], [MODULE_NO], [HEAD], [DICTIONARY_ID], [FRIENDLY_URL], [FULL_FUSEACTION], [FULL_FUSEACTION_VARIABLES], [FILE_PATH], [CONTROLLER_FILE_PATH], [STANDART_ADDON], [LICENCE], [EVENT_TYPE], [STATUS], [IS_DEFAULT], [IS_MENU], [WINDOW], [VERSION], [IS_CATALYST_MOD], [MENU_SORT_NO], [USE_PROCESS_CAT], [USE_SYSTEM_NO], [USE_WORKFLOW], [DETAIL], [AUTHOR], [OBJECTS_COUNT], [DESTINATION_MODUL], [RECORD_IP], [RECORD_EMP], [RECORD_DATE], [UPDATE_IP], [UPDATE_EMP], [UPDATE_DATE], [SECURITY], [STAGE], [MODUL], [BASE], [MODUL_SHORT_NAME], [FUSEACTION], [FUSEACTION2], [FOLDER], [FILE_NAME], [IS_ADD], [IS_UPDATE], [IS_DELETE], [LEFT_MENU_NAME], [IS_WBO_DENIED], [IS_WBO_FORM_LOCK], [IS_WBO_LOCK], [IS_WBO_LOG], [IS_SPECIAL], [IS_TEMP], [EVENT_ADD], [EVENT_DASHBOARD], [EVENT_DEFAULT], [EVENT_DETAIL], [EVENT_LIST], [EVENT_UPD], [TYPE], [POPUP_TYPE], [RANK_NUMBER], [EXTERNAL_FUSEACTION], [IS_LEGACY], [ADDOPTIONS_CONTROLLER_FILE_PATH], [THEME_PATH], [IS_ONLY_SHOW_PAGE], [DISPLAY_BEFORE_PATH], [DISPLAY_AFTER_PATH], [ACTION_BEFORE_PATH], [ACTION_AFTER_PATH], [ICON], [XML_PATH]) VALUES (17447, 1, 9, N'Çalıştırmak için tıklayın', 40597, NULL, N'jedi.playground', NULL, N'.', N'AddOns/Jedi/controllers/playgroundcontroller.cfm', NULL, 2, NULL, N'Development', NULL, 0, NULL, N'1', NULL, NULL, 0, 0, 0, N'<p><br></p>', N'Halit Yurttaş', NULL, NULL, N'127.0.0.1', 16, CAST(N'2020-10-26T04:52:58.000' AS DateTime), NULL, NULL, NULL, N'Standart', NULL, NULL, NULL, N'jedi', N'playground', NULL, N'W3WorkDev', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
END