CREATE TABLE [@_dsn_main_@].[OFFICER_PAYROLL_ROW](	  
    [OFFICER_PAYROLL_ID] int NOT NULL IDENTITY(1,1), 
    [PAYROLL_ID] int NULL	, [EMPLOYEE_PAYROLL_ID] int NULL, 
    [ADDITIONAL_INDICATORS] float NULL	, [SEVERANCE_PENSION] float NULL, 
    [BUSINESS_RISK] float NULL	, [UNIVERSITY_ALLOWANCE] float NULL, 
    [PRIVATE_SERVICE_COMPENSATION] float NULL, 
    [LANGUAGE_ALLOWANCE] float NULL, 
    [EXECUTIVE_INDICATOR_COMPENSATION] float NULL, 
    [ADMINISTRATIVE_COMPENSATION] float NULL, 
    [ADMINISTRATIVE_DUTY_ALLOWANCE] float NULL, 
    [EDUCATION_ALLOWANCE] float NULL, 
    [FAMILY_ASSISTANCE] float NULL, 
    [CHILD_ASSISTANCE] float NULL, 
    [PROMOTION_DIFFERENCE] float NULL, 
    [EXTRA_PAY] float NULL, 
    [GRADE] int NULL, 
    [STEP] int NULL, 
    [IN_OUT_ID] int NULL, 
    [INDICATOR_SCORE] float NULL, 
    [BASE_SALARY] float NULL,
    [NORMAL_STEP] float NULL,
    [HIGH_EDUCATION_COMPENSATION_PAYROLL] float NULL,
    [RETIREMENT_ALLOWANCE_PERSONAL_INTERRUPTION] float NULL,
    [AUDIT_COMPENSATION_AMOUNT] float NULL,
    [GENERAL_HEALTH_INSURANCE] float NULL,
    [HEALTH_INSURANCE_PREMIUM_5510] float NULL,
    [PENANCE_DEDUCTION] float NULL,
    [SGK_BASE] float NULL,
    [ADDITIONAL_SCORE] float NULL,
    [COLLECTIVE_AGREEMENT_BONUS] float NULL,
    [NORMAL_ADDITIONAL_SCORE] float NULL,
    [RETIREMENT_ALLOWANCE_PERSONAL] float NULL,
    [HEALTH_INSURANCE_PREMIUM_PERSONAL_5510] float NULL,
    [PLUS_RETIRED] float NULL,
    [ADDITIONAL_INDICATOR_COMPENSATION] float NULL,
    [PLUS_RETIRED_PERSONAL] float NULL,
    [RETIREMENT_ALLOWANCE] float NULL,
    [ACADEMIC_INCENTIVE_ALLOWANCE_AMOUNT] float NULL,
    [RETIREMENT_ALLOWANCE_5510] float NULL,
    [RETIREMENT_ALLOWANCE_PERSONAL_5510] float NULL,
    [NORMAL_GRADE] float NULL,
    [RETIRED_ACADEMIC] float NULL,
    [LAND_COMPENSATION_AMOUNT] float NULL,
CONSTRAINT [PK__OFFICER___7EAF9F803F4FD375] PRIMARY KEY ([OFFICER_PAYROLL_ID] ASC));

CREATE TABLE [@_dsn_main_@].[PLVN_GOPCHA](	  
    [GOPCHA_ID] int NOT NULL IDENTITY(1,1), 
    [USER_ID] int NOT NULL, 
    [GOPCHA_TYPE] int NOT NULL, 
    [GOPCHA_KEY] nvarchar(150) NOT NULL, 
    [GOPCHA_CODE] nvarchar(25) NOT NULL, 
    [ADDRESS] nvarchar(250) NULL, 
    [GOPCHA_UNTIL] datetime NULL, 
    [IP] nvarchar(40) NOT NULL, 
CONSTRAINT [PK_PLVN_GOPCHA] PRIMARY KEY ([GOPCHA_ID] ASC));

CREATE TABLE [@_dsn_main_@].[SANTIYE_POSITIONS](	  
    [ROW_ID] int NOT NULL IDENTITY(1,1), 
    [FIELD_TYPE] int NULL, 
    [FIELD_TEXT_VALUE] nvarchar(500) NULL);

CREATE TABLE [@_dsn_main_@].[ADDITIONAL_COURSE_TABLE](
    [ADDITIONAL_COURSE_ID] int NOT NULL IDENTITY(1,1), 
    [START_DATE] datetime NULL, 
    [FINISH_DATE] datetime NULL, 
    [TITLE] nvarchar(150) NULL, 
    [DAYTIME_EDUCATION_1] float NULL, 
    [DAYTIME_EDUCATION_2] float NULL, 
    [DAYTIME_EDUCATION_3] float NULL, 
    [DAYTIME_EDUCATION_4] float NULL, 
    [DAYTIME_EDUCATION_5] float NULL, 
    [PUBLIC_HOLIDAY_1] float NULL, 
    [PUBLIC_HOLIDAY_2] float NULL, 
    [PUBLIC_HOLIDAY_3] float NULL, 
    [PUBLIC_HOLIDAY_4] float NULL, 
    [PUBLIC_HOLIDAY_5] float NULL, 
    [EVENING_EDUCATION_1] float NULL,
    [EVENING_EDUCATION_2] float NULL, 
    [EVENING_EDUCATION_3] float NULL, 
    [EVENING_EDUCATION_4] float NULL, 
    [EVENING_EDUCATION_5] float NULL, 
    [RECORD_DATE] datetime NULL, 
    [RECORD_IP] nvarchar(50) NULL, 
    [RECORD_EMP] int NULL, 
    [UPDATE_DATE] datetime NULL, 
    [UPDATE_IP] nvarchar(50) NULL, 
    [UPDATE_EMP] int NULL, 
CONSTRAINT [PK__ADDITION__B4582F733C0D07AF] PRIMARY KEY ([ADDITIONAL_COURSE_ID] ASC));

CREATE TABLE [@_dsn_main_@].[BITBUCKET_HOOKS](	 
    [HOOKID] int NOT NULL IDENTITY(1,1), 
    [PROC_TYPE] nvarchar(150) NOT NULL, 
    [TITLE] nvarchar(500) NOT NULL, 
    [DESCRIPTION] nvarchar(MAX) NULL, 
    [VIEW_URL] nvarchar(250) NULL, 
    [AUTHOR] nvarchar(150) NULL, 
    [AUTHOR_DATA] nvarchar(MAX) NULL, 
    [TASK_ID] int NULL, 
    [BBID] int NULL, 
    [DESTINATION_BRANCH] nvarchar(150) NULL, 
    [SOURCE_BRANCH] nvarchar(150) NULL, 
    [STATE] nvarchar(50) NULL, 
    [PARTICIPANTS] nvarchar(MAX) NULL, 
    [CREATED] datetime NULL, 
CONSTRAINT [PK_BITBUCKET_HOOKS] PRIMARY KEY ([HOOKID] ASC));

CREATE TABLE [@_dsn_main_@].[PROTEIN_MENUS](	  
    [MENU_ID] int NOT NULL IDENTITY(1,1), 
    [SITE] int NOT NULL, 
    [MENU_NAME] nvarchar(250) NULL, 
    [MENU_STATUS] int NULL, 
    [IS_DEFAULT] int NULL, 
    [MENU_DATA] text NULL,
    [RECORD_DATE] datetime NULL, 
    [RECORD_EMP] int NULL, 
    [RECORD_IP] nvarchar(50) NULL, 
    [UPDATE_DATE] datetime NULL, 
    [UPDATE_EMP] int NULL, 
    [UPDATE_IP] nvarchar(50) NULL, 
    [MENU_LANGUAGE] varchar(10) NULL, 
CONSTRAINT [PK_PROTEIN_MENUS] PRIMARY KEY ([MENU_ID] ASC));

CREATE TABLE [@_dsn_main_@].[PROJECT_ALLOWANCE](	 
    [PROJECT_ALLOWANCE_ID] int NOT NULL IDENTITY(1,1), 
    [PAPER_NO] nvarchar(15) NULL, 
    [SAL_YEAR] int NULL, 
    [SAL_MON] int NULL, 
    [SSK_STATUE] int NULL, 
    [STATUE_TYPE] int NULL, 
    [DIRECTOR_SHARE] float NULL, 
    [DISTRIBUTION] float NULL, 
    [DIRECTOR_AMOUNT] float NULL, 
    [EMPLOYEE_AMOUNT] float NULL, 
    [TOTAL_AMOUNT] float NULL, 
    [CURRENCY_UNIT] nvarchar(15) NULL, 
    [PROJECT_ID] int NULL, 
    [BUDGET_ID] int NULL, 
    [PROCESS_ID] int NULL, 
    [BRANCH_ID] int NULL, 
    [RECORD_DATE] datetime NULL, 
    [RECORD_EMP] int NULL, 
    [RECORD_IP] nvarchar(50) NULL, 
    [UPDATE_DATE] datetime NULL, 
    [UPDATE_EMP] int NULL, 
    [UPDATE_IP] nvarchar(50) NULL, 
CONSTRAINT [PK__PROJECT___EA232804B7FB23C9] PRIMARY KEY ([PROJECT_ALLOWANCE_ID] ASC));

CREATE TABLE [@_dsn_main_@].[PROJECT_ALLOWANCE_ROW](	  
    [PROJECT_ALLOWANCE_ROW_ID] int NOT NULL IDENTITY(1,1), 
    [IN_OUT_ID] int NULL, 
    [EMPLOYEE_ID] int NULL, 
    [HOUR_PAYMENT] float NULL, 
    [HOURLY_WORK] float NULL, 
    [AMOUNT] float NULL, 
    [IS_ALLOWANCE] bit NULL, 
    [TYPE] bit NULL,
    [COMMENT_PAY_ID] int NULL, 
    [PROJECT_ALLOWANCE_ID] int NULL, 
    [SHARE] float NULL, 
CONSTRAINT [PK__PROJECT___EA232804ADE3FD72] PRIMARY KEY ([PROJECT_ALLOWANCE_ROW_ID] ASC));

CREATE TABLE [@_dsn_main_@].[GUNLUK_RAPOR](	  
    [REPORT_ID] int NOT NULL IDENTITY(1,1), 
    [REPORT_DATE] datetime NOT NULL, 
    [PROJECT_ID] int NULL, 
    [WEATHER_TYPE] int NULL, 
    [DON] int NULL, 
    [DEGREE] int NULL, 
    [INSAAT] nvarchar(50) NULL, 
    [ELEKTRIK] nvarchar(50) NULL, 
    [MEKANIK] nvarchar(50) NULL, 
    [OLAYLAR] nvarchar(50) NULL, 
    [SUB_REAL_WORK] float NULL DEFAULT((0)), 
    [REAL_WORK] float NULL DEFAULT((0)), 
    [RECORD_EMP] int NULL, 
    [RECORD_DATE] datetime NULL, 
    [RECORD_IP] nvarchar(50) NULL,
    [UPDATE_EMP] int NULL, 
    [UPDATE_DATE] datetime NULL,
    [UPDATE_IP] nvarchar(50) NULL, 
    [STAGE] int NULL, 
    [IS_LOCKED] int NULL);

CREATE TABLE [@_dsn_main_@].[PLVN_SETTINGS](	  
    [SETTING_ID] int NOT NULL IDENTITY(1,1), 
    [SETTING_KEY] nvarchar(150) NOT NULL,
    [SETTING_VALUE] nvarchar(MAX) NULL, 
    [STATUS] int NOT NULL, 
CONSTRAINT [PK_PLVN_SETTINGS] PRIMARY KEY ([SETTING_ID] ASC));

CREATE TABLE [@_dsn_main_@].[PLVN_INTERCEPTORS](	  
    [INTERCEPTOR_ID] int NOT NULL IDENTITY(1,1), 
    [INTERCEPTOR_CATEGORY] int NOT NULL, 
    [INTERCEPTOR_PATH] nvarchar(MAX) NULL, 
    [STATUS] int NOT NULL, 
CONSTRAINT [PK_PLVN_INTERCEPTORS] PRIMARY KEY ([INTERCEPTOR_ID] ASC));

CREATE TABLE [@_dsn_main_@].[EMPLOYEES_GRADE_STEP_PARAMS](	  
    [GRADE_STEP_PARAMS_ID] int NOT NULL IDENTITY(1,1), 
    [GRADE] int NULL, 
    [STEP_1] int NULL, 
    [STEP_2] int NULL, 
    [STEP_3] int NULL, 
    [STEP_4] int NULL, 
    [STEP_5] int NULL, 
    [STEP_6] int NULL, 
    [STEP_7] int NULL,
    [STEP_8] int NULL, 
    [STEP_9] int NULL, 
    [START_DATE] datetime NULL, 
    [FINISH_DATE] datetime NULL, 
    [RECORD_DATE] datetime NULL, 
    [RECORD_IP] nvarchar(50) NULL, 
    [RECORD_EMP] int NULL,
    [UPDATE_DATE] date NULL, 
    [UPDATE_IP] nvarchar(50) NULL, 
    [UPDATE_EMP] bigint NULL, 
    [TITLE] varchar(150) NULL,
CONSTRAINT [PK__EMPLOYEE__3F9CB4423EF44F10] PRIMARY KEY ([GRADE_STEP_PARAMS_ID] ASC));

CREATE TABLE [@_dsn_main_@].[OUR_COMPANY_HISTORY](	  
    [HISTORY_ID] int NOT NULL IDENTITY(1,1), 
    [COMP_ID] int NOT NULL, 
    [COMPANY_NAME] nvarchar(200) NULL, 
    [NICK_NAME] nvarchar(50) NULL, 
    [TAX_OFFICE] nvarchar(50) NULL, 
    [TAX_NO] nvarchar(50) NULL, 
    [TEL_CODE] nvarchar(43) NULL, 
    [TEL] nvarchar(43) NULL, 
    [FAX] nvarchar(43) NULL, 
    [MANAGER] nvarchar(40) NULL, 
    [MANAGER_POSITION_CODE] int NULL, 
    [MANAGER_POSITION_CODE2] int NULL, 
    [WEB] nvarchar(50) NULL, 
    [EMAIL] nvarchar(50) NULL, 
    [ADDRESS] nvarchar(MAX) NULL, 
    [ADMIN_MAIL] nvarchar(MAX) NULL, 
    [TEL2] nvarchar(43) NULL, 
    [TEL3] nvarchar(43) NULL, 
    [TEL4] nvarchar(43) NULL, 
    [FAX2] nvarchar(43) NULL, 
    [T_NO] nvarchar(50) NULL, 
    [SERMAYE] nvarchar(43) NULL, 
    [CHAMBER] nvarchar(150) NULL, 
    [CHAMBER_NO] nvarchar(50) NULL, 
    [CHAMBER2] nvarchar(150) NULL, 
    [CHAMBER2_NO] nvarchar(50) NULL, 
    [ASSET_FILE_NAME1] nvarchar(100) NULL, 
    [ASSET_FILE_NAME1_SERVER_ID] int NULL, 
    [ASSET_FILE_NAME2] nvarchar(100) NULL, 
    [ASSET_FILE_NAME2_SERVER_ID] int NULL, 
    [ASSET_FILE_NAME3] nvarchar(100) NULL, 
    [ASSET_FILE_NAME3_SERVER_ID] int NULL, 
    [HEADQUARTERS_ID] int NULL, 
    [IS_ORGANIZATION] bit NULL, 
    [HIERARCHY] nvarchar(75) NULL, 
    [HIERARCHY2] nvarchar(75) NULL, 
    [COMP_STATUS] bit NULL, 
    [RECORD_EMP] int NULL, 
    [RECORD_DATE] datetime NULL, 
    [RECORD_IP] nvarchar(50) NULL, 
    [UPDATE_EMP] int NULL, 
    [UPDATE_DATE] datetime NULL,
    [UPDATE_IP] nvarchar(50) NULL, 
    [AUTHORITY_DOC_FINISH] datetime NULL, 
    [AUTHORITY_DOC_START] datetime NULL, 
    [AUTHORITY_DOC_NUMBER] nvarchar(100) NULL,
    [AUTHORITY_DOC_TYPE] nvarchar(50) NULL, 
    [AUTHORITY_DOC_WARNING] int NULL, 
    [COORDINATE_1] nvarchar(50) NULL, 
    [COORDINATE_2] nvarchar(50) NULL, 
    [COUNTRY_ID] int NULL, 
    [POSTAL_CODE] nvarchar(50) NULL, 
    [CITY_ID] int NULL, 
    [CITY_SUBDIVISION_NAME] nvarchar(50) NULL, 
    [BUILDING_NUMBER] nvarchar(50) NULL, 
    [STREET_NAME] nvarchar(50) NULL, 
    [DISTRICT_NAME] nvarchar(50) NULL, 
    [COUNTY_ID] int NULL, 
    [MERSIS_NO] nvarchar(50) NULL, 
    [NACE_CODE] nvarchar(50) NULL, 
CONSTRAINT [PK_OUR_COMPANY_HISTORY] PRIMARY KEY ([HISTORY_ID] ASC));

CREATE TABLE [@_dsn_main_@].[PLVN_LOGS](	 
    [LOG_ID] int NOT NULL IDENTITY(1,1), 
    [SOURCE] nvarchar(150) NOT NULL, 
    [SOURCE_ID] int NOT NULL, 
    [MESSAGE] nvarchar(1000) NOT NULL,
    [TYPE] int NOT NULL,
    [TRACE] nvarchar(MAX) NULL, 
    [LOGDATE] datetime NOT NULL,
CONSTRAINT [PK_PLVN_LOGS] PRIMARY KEY ([LOG_ID] ASC));

CREATE TABLE [@_dsn_main_@].[PLVN_EXPRESSIONS](	  
    [EXPRESSION_ID] int NOT NULL IDENTITY(1,1), 
    [EXPRESSION_CATEGORY] int NOT NULL, 
    [EXPRESSION_BODY] nvarchar(MAX) NULL, 
    [STATUS] int NOT NULL, 
CONSTRAINT [PK_PLVN_EXPRESSIONS] PRIMARY KEY ([EXPRESSION_ID] ASC));

CREATE TABLE [@_dsn_main_@].[WASTE_OPERATION_DOCUMENTS](	  
    [DOC_ID] int NOT NULL IDENTITY(1,1), 
    [CATEGORY] nvarchar(50) NULL,
    [ASSET_MODULE] nvarchar(50) NULL, 
    [ASSET_MODULE_ID] int NULL, 
    [ASSETCAT_ID] int NULL, 
    [ASSET_ACTION] nvarchar(50) NULL, 
    [RELATED_WO_FIELDS] nvarchar(200) NULL, 
    [DOC_NAME] nvarchar(100) NULL, 
    [DOC_CODE] nvarchar(50) NULL, 
    [OUR_COMPANY_ID] int NULL, 
    [DOC_STATUS] bit NULL, 
CONSTRAINT [PK__WASTE_OP__C41D45C2B8196C9D] PRIMARY KEY ([DOC_ID] ASC));

CREATE TABLE [@_dsn_main_@].[PLVN_RESPONSES](	  
    [RESPONSE_ID] int NOT NULL IDENTITY(1,1), 
    [TYPE] int NOT NULL, 
    [HEADER] nvarchar(250) NOT NULL, 
    [RESPONSE_DATA] nvarchar(MAX) NULL, 
    [STATUS] int NOT NULL DEFAULT((1)), 
CONSTRAINT [PK_PLVN_RESPONSE] PRIMARY KEY ([RESPONSE_ID] ASC));

CREATE TABLE [@_dsn_main_@].[GUNLUK_RAPOR_ROWS](	  
    [ROW_ID] int NOT NULL IDENTITY(1,1), 
    [REPORT_ID] int NULL, 
    [FIELD_TYPE] int NULL, 
    [FIELD_TEXT_VALUE] nvarchar(500) NULL, 
    [FIELD_NUMBER_VALUE] float NULL, 
    [FIELD_BIRIM] nvarchar(50) NULL);

CREATE TABLE [@_dsn_main_@].[PLVN_INTERCEPTOR_CATEGORIES](	  
    [INTERCEPTOR_CATEGORY_ID] int NOT NULL IDENTITY(1,1), 
    [INTERCEPTOR_KIND] int NOT NULL, 
    [TITLE] nvarchar(150) NOT NULL, 
    [STATUS] int NOT NULL, 
CONSTRAINT [PK_PLVN_INTERCEPTOR_CATEGORIES] PRIMARY KEY ([INTERCEPTOR_CATEGORY_ID] ASC));

CREATE TABLE [@_dsn_main_@].[SETUP_LANGUAGE_ALLOWANCE](	  
    [LANGUAGE_ALLOWANCE_ID] int NOT NULL IDENTITY(1,1), 
    [LANGUANGE_STATUE] int NULL, 
    [LANGUAGE_LEVEL] nvarchar(150) NULL, 
    [LANGUAGE_AMOUNT] float NULL, 
    [RECORD_DATE] datetime NULL, 
    [RECORD_IP] nvarchar(50) NULL, 
    [RECORD_EMP] int NULL, 
    [UPDATE_DATE] datetime NULL, 
    [UPDATE_IP] nvarchar(50) NULL, 
    [UPDATE_EMP] int NULL, 
CONSTRAINT [PK__SETUP_LA__B0CDBCEB1DF996BF] PRIMARY KEY ([LANGUAGE_ALLOWANCE_ID] ASC));

CREATE TABLE [@_dsn_main_@].[WOCIAL_BRAND](	  
    [BRAND_ID] int NOT NULL IDENTITY(1,1), 
    [PLATFORM_ID] int NOT NULL, 
    [BRAND_NAME] nvarchar(250) NOT NULL, 
    [BRAND_SOCIAL_MEDIA_URL] nvarchar(250) NOT NULL, 
    [BRAND_WEBSITE_URL] nvarchar(250) NULL, 
    [BRAND_MANAGER] int NOT NULL, 
    [BRAND_DESCRIPTION] nvarchar(MAX) NULL, 
    [BRAND_KEYWORD] nvarchar(MAX) NULL, 
    [BRAND_STATUS] bit NOT NULL, 
    [RECORD_EMP] int NULL, 
    [RECORD_DATE] datetime NULL, 
    [RECORD_IP] nvarchar(50) NULL, 
    [UPDATE_EMP] int NULL, 
    [UPDATE_DATE] datetime NULL,
    [UPDATE_IP] nvarchar(50) NULL, 
CONSTRAINT [PK_WOCIAL_BRAND] PRIMARY KEY ([BRAND_ID] ASC));

CREATE TABLE [@_dsn_main_@].[WOCIAL_PLATFORM](	  
    [PLATFORM_ID] int NOT NULL IDENTITY(1,1), 
    [PLATFORM_NAME] nvarchar(50) NOT NULL, 
    [PLATFORM_STATUS] bit NOT NULL, 
    [PLATFORM_PROVIDER_NAME] nvarchar(250) NULL, 
    [PLATFORM_ICON] nvarchar(250) NULL,
CONSTRAINT [PK_WOCIAL_PLATFORM] PRIMARY KEY ([PLATFORM_ID] ASC));

CREATE TABLE [@_dsn_main_@].[WOCIAL_ACCESS_TOKEN](	  
    [ACCESS_TOKEN_ID] int NOT NULL IDENTITY(1,1), 
    [ACCESS_TOKEN] nvarchar(MAX) NULL, 
    [STATE] nvarchar(MAX) NULL, 
    [PLATFORM_ID] int NULL, 
    [BRAND_ID] int NULL, 
    [ACCESS_TOKEN_START_DATE] datetime NULL, 
    [ACCESS_TOKEN_EXPIRED_DATE] datetime NULL, 
    [STATUS] bit NULL DEFAULT((1)), 
    [RECORD_EMP] int NULL, 
    [RECORD_DATE] datetime NULL, 
    [RECORD_IP] nvarchar(50) NULL, 
    [UPDATE_EMP] int NULL, 
    [UPDATE_DATE] datetime NULL, 
    [UPDATE_IP] nvarchar(50) NULL, 
CONSTRAINT [PK_WOCIAL_ACCESS_TOKEN] PRIMARY KEY ([ACCESS_TOKEN_ID] ASC));

CREATE TABLE [@_dsn_main_@].[SUBSCRIPTION_IAM](	  
    [IAM_ID] int NOT NULL IDENTITY(1,1), 
    [SUBSCRIPTION_ID] int NULL, 
    [SUBSCRIPTION_NO] nvarchar(200) NULL,
    [IAM_ACTIVE] bit NULL, 
    [IAM_USER_NAME] nvarchar(200) NULL, 
    [IAM_NAME] nvarchar(200) NULL, 
    [IAM_SURNAME] nvarchar(200) NULL, 
    [IAM_PASSWORD] nvarchar(200) NULL, 
    [IAM_EMAIL_FIRST] nvarchar(200) NULL, 
    [IAM_EMAİL_SECOND] nvarchar(200) NULL,
    [IAM_MOBILE_CODE] nvarchar(20) NULL, 
    [IAM_MOBILE_NUMBER] nvarchar(20) NULL, 
    [IAM_USER_COMPANY_NAME] nvarchar(200) NULL, 
    [COMPANY_PARTNER_ID] int NULL, 
    [REFERRAL_DOMAIN] nvarchar(200) NULL, 
    [RECORD_DATE] datetime NULL, 
    [UPDATE_DATE] datetime NULL, 
    [RECORD_IP] nvarchar(50) NULL, 
    [UPDATE_IP] nvarchar(50) NULL, 
    [RECORD_EMP] int NULL, 
    [UPDATE_EMP] int NULL, 
CONSTRAINT [PK_SUBSCRIPTION_IAM] PRIMARY KEY ([IAM_ID] ASC));

CREATE TABLE [@_dsn_main_@].[BUILDING_POZ_LIST](	  
    [ID] int NOT NULL IDENTITY(1,1), 
    [POZ_NO] nvarchar(50) NULL, 
    [POZ_NAME] nvarchar(MAX) NULL, 
    [POZ_DETAIL] nvarchar(MAX) NULL, 
    [BIRIM] int NULL, 
    [ALIS_FIYAT] float NULL, 
    [SATIS_FIYAT] float NULL, 
    [CATEGORY] nvarchar(50) NULL, 
    [COMP_CATEGORY] nvarchar(150) NULL, 
    [PRODUCT_ID] int NULL, 
    [STOCK_ID] int NULL,
    [PRODUCT_CAT_ID] int NULL, 
    [IS_OWN] int NULL);

CREATE TABLE [@_dsn_main_@].[ERECEIPT_RELATION](	  
    [RELATION_ID] int NOT NULL IDENTITY(1,1), 
    [ACTION_ID] int NULL, 
    [ACTION_TYPE] nvarchar(50) NULL, 
    [ERECEIPT_ID] nvarchar(50) NULL, 
    [UUID] nvarchar(50) NULL, 
    [PATH] nvarchar(250) NULL, 
    [PROFILE_ID] nvarchar(50) NULL, 
    [INTEGRATION_ID] nvarchar(50) NULL, 
    [IS_PAPER_UPDATE] bit NULL, 
    [STATUS_CODE] int NULL, 
    [STATUS_DESCRIPTION] nvarchar(250) NULL, 
    [STATUS_DATE] datetime NULL, 
    [RECORD_DATE] datetime NULL, 
    [RECORD_EMP] int NULL, 
    [RECORD_IP] nvarchar(50) NULL, 
    [RECEIPT_UUID] nvarchar(250) NULL, 
    [RECEIPT_ID] nvarchar(250) NULL, 
CONSTRAINT [PK_ERECEIPT_RELATION] PRIMARY KEY ([RELATION_ID] ASC));

CREATE TABLE [@_dsn_main_@].[PLVN_EXPRESSION_CATEGORIES](	  
    [EXPRESSION_CATEGORY_ID] int NOT NULL IDENTITY(1,1), 
    [EXPRESSION_KIND] int NOT NULL, 
    [TITLE] nvarchar(150) NOT NULL, 
    [STATUS] int NOT NULL, 
    [RECORD_DATE] datetime NULL,
    [RECORD_EMP] int NULL, 
    [RECORD_IP] nvarchar(50) NULL, 
    [UPDATE_DATE] datetime NULL, 
    [UPDATE_EMP] int NULL, 
    [UPDATE_IP] nvarchar(50) NULL,
CONSTRAINT [PK_PLVN_EXPRESSION_CATEGORIES] PRIMARY KEY ([EXPRESSION_CATEGORY_ID] ASC));

CREATE TABLE [@_dsn_main_@].[PRODUCT_TREE_TYPE](
    [TYPE_ID] int NOT NULL IDENTITY(1,1),
    [TYPE] nvarchar(150) NULL,
    [WASTE_RATE] float NULL,
CONSTRAINT [PK__PRODUCT___41F99A52D46A4A8C] PRIMARY KEY ([TYPE_ID] ASC));

CREATE TABLE [@_dsn_main_@].[EVENT_WITNESS_STATEMENT](	  
    [WITNESS_STATEMENT_ID] int NOT NULL IDENTITY(1,1), 
    [EVENT_ID] int NOT NULL, 
    [SIGN_DATE] datetime NULL, 
    [WITNESS_1] int NULL, 
    [WITNESS1_DETAIL] nvarchar(MAX) NULL, 
    [WITNESS_2] int NULL, 
    [WITNESS2_DETAIL] nvarchar(MAX) NULL, 
    [WITNESS_3] int NULL, 
    [WITNESS3_DETAIL] nvarchar(MAX) NULL, 
    [RECORD_DATE] datetime NULL, 
    [RECORD_EMP] int NULL, 
    [RECORD_IP] nvarchar(43) NULL, 
    [UPDATE_DATE] datetime NULL, 
    [UPDATE_EMP] int NULL, 
    [UPDATE_IP] nvarchar(43) NULL,
CONSTRAINT [PK_EVENT_WITNESS_STATEMENT_WITNESS_STATEMENT_ID] PRIMARY KEY ([WITNESS_STATEMENT_ID] ASC));

CREATE TABLE [@_dsn_main_@].[WRK_THEME](	  
    [THEME_ID] int NOT NULL IDENTITY(1,1), 
    [THEME_NAME] nvarchar(250) NOT NULL, 
    [THEME_DETAIL] nvarchar(MAX) NULL, 
    [THEME_AUTHOR] nvarchar(150) NOT NULL, 
    [THEME_AUTHORID] int NOT NULL, 
    [THEME_STOCK_ID] int NULL, 
    [THEME_PRODUCT_ID] int NULL, 
    [THEME_PRODUCT_NAME] nvarchar(250) NULL, 
    [THEME_FILE_PATH] nvarchar(250) NULL, 
    [THEME_LICENSE] int NOT NULL, 
    [THEME_IS_ACTIVE] bit NULL, 
    [THEME_STAGE] int NULL, 
    [THEME_SECTORS] nvarchar(150) NULL, 
    [THEME_PUBLISH_DATE] datetime NULL, 
    [THEME_PRODUCT_CODE] nvarchar(50) NOT NULL, 
    [RECORD_EMP] int NULL, 
    [RECORD_DATE] datetime NULL, 
    [RECORD_IP] nvarchar(25) NULL, 
    [UPDATE_EMP] int NULL, 
    [UPDATE_DATE] datetime NULL, 
    [UPDATE_IP] nvarchar(25) NULL, 
CONSTRAINT [PK_WRK_THEME] PRIMARY KEY ([THEME_ID] ASC));

CREATE TABLE [@_dsn_main_@].[BUILDING_DOCUMENT](	  
    [ID] int NOT NULL IDENTITY(1,1), 
    [OLD_DOCUMENT_ID] int NULL, 
    [REPORT_ID] int NULL, 
    [DOCUMENT_NAME] nvarchar(550) NULL, 
    [DOCUMENT_TYPE] int NULL, 
    [DOCUMENT_NAME2] nvarchar(550) NULL, 
    [DOCUMENT_DATE] datetime NULL, 
    [RECORD_DATE] datetime NULL, 
    [RECORD_EMP] int NULL, 
    [RELEASE_DATE_START] datetime NULL, 
    [RELEASE_DATE_FINISH] datetime NULL, 
    [IS_INTERNET] int NULL, 
    [VERSIYON] int NULL, 
    [AKTIF] int NULL);

CREATE TABLE [@_dsn_main_@].[SETUP_LANGUAGES_DOCUMENTS](	  
    [DOCUMENT_ID] int NOT NULL IDENTITY(1,1), 
    [DOCUMENT_NAME] nvarchar(43) NULL, 
    [DOCUMENT_SHORT_NAME] nvarchar(43) NULL, 
    [DOCUMENT_PERIOD_VALID] nvarchar(50) NULL, 
    [DOCUMENT_PERIOD_VALID_TYPE] nvarchar(50) NULL, 
    [IS_ACTIVE] bit NULL, 
    [RECORD_DATE] datetime NULL, 
    [RECORD_EMP] int NULL, 
    [RECORD_IP] nvarchar(50) NULL,
    [UPDATE_DATE] datetime NULL, 
    [UPDATE_EMP] int NULL, 
    [UPDATE_IP] nvarchar(50) NULL, 
CONSTRAINT [PK_SETUP_LANGUAGES_DOCUMENTS_DOCUMENT_ID] PRIMARY KEY ([DOCUMENT_ID] ASC));

CREATE TABLE [@_dsn_main_@].[PLVN_LEVEL_PROCESS](	  
    [LEVEL_PROCESS_ID] int NOT NULL IDENTITY(1,1), 
    [PROCESS_KIND] int NOT NULL, 
    [PROCESS_TYPE] int NOT NULL, 
    [RELATION_ID] int NOT NULL, 
    [CONTRAST] nvarchar(50) NULL, 
CONSTRAINT [PK_PLVN_LEVEL_PROCESS] PRIMARY KEY ([LEVEL_PROCESS_ID] ASC));

CREATE TABLE [@_dsn_main_@].[WRK_MOCKUP_WORK](	  
    [MOCKUP_WORK_ID] int NOT NULL IDENTITY(1,1), 
    [MOCKUP_ID] int NOT NULL, 
    [WORK_ID] int NOT NULL, 
CONSTRAINT [PK_WRK_MOCKUP_WORK] PRIMARY KEY ([MOCKUP_WORK_ID] ASC));

CREATE TABLE [@_dsn_main_@].[BUILDING_POZ_TANIM](	  
    [ID] int NOT NULL IDENTITY(1,1), 
    [POZ_NO] nvarchar(50) NULL, 
    [POZ_DETAIL] nvarchar(MAX) NULL);

CREATE TABLE [@_dsn_main_@].[ERECEIPT_SENDING_DETAIL](	  
    [SENDING_DETAIL_ID] int NOT NULL IDENTITY(1,1), 
    [SERVICE_RESULT] nvarchar(50) NULL, 
    [UUID] nvarchar(50) NULL, 
    [ERECEIPT_ID] nvarchar(50) NULL, 
    [STATUS_DESCRIPTION] nvarchar(50) NULL, 
    [STATUS_CODE] nvarchar(50) NULL, 
    [ERROR_CODE] nvarchar(50) NULL, 
    [ACTION_ID] int NULL, 
    [ACTION_TYPE] nvarchar(50) NULL, 
    [SERVICE_RESULT_DESCRIPTION] nvarchar(250) NULL,
    [RECORD_DATE] datetime NULL, 
    [RECORD_EMP] int NULL, 
    [RECORD_IP] nvarchar(50) NULL, 
CONSTRAINT [PK_ERECEIPT_SENDING_DETAIL] PRIMARY KEY ([SENDING_DETAIL_ID] ASC));

CREATE TABLE [@_dsn_main_@].[WRK_MESSAGE_VISITOR](	  
    [WMV_ID] int NOT NULL IDENTITY(1,1), 
    [EMPLOYEE_ID] int NOT NULL, 
    [VISITOR_ID] nvarchar(100) NOT NULL, 
    [VISITOR_TYPE] int NOT NULL, 
    [VISITOR_KEY] nvarchar(100) NOT NULL, 
    [VISITOR_NAME] nvarchar(200) NOT NULL, 
    [VISITOR_SURNAME] nvarchar(200) NOT NULL, 
    [VISITOR_EMAIL] nvarchar(200) NOT NULL, 
    [ENC_KEY] nvarchar(250) NOT NULL, 
    [STATUS] bit NOT NULL DEFAULT((1)), 
    [RECORD_DATE] datetime NOT NULL, 
    [UPDATE_DATE] datetime NULL, 
CONSTRAINT [PK_WRK_MESSAGE_VISITOR] PRIMARY KEY ([WMV_ID] ASC));

CREATE TABLE [@_dsn_main_@].[BUILDING_ANALYSE](	  
    [ANALIZ_ROW_ID] int NOT NULL IDENTITY(1,1), 
    [MAIN_POZ] nvarchar(50) NULL, 
    [PRODUCT_CAT_ID] int NULL, 
    [PRODUCT_ID] int NULL, 
    [STOCK_ID] int NULL, 
    [METRAJ_STOCK_ID] int NULL, 
    [TARIH] datetime NULL, 
    [POZ] nvarchar(75) NULL, 
    [STOCK_NAME] nvarchar(MAX) NULL, 
    [BIRIM] nvarchar(75) NULL, 
    [ACIKLAMA_ROW] nvarchar(MAX) NULL, 
    [MAHAL] nvarchar(50) NULL, 
    [ADET] float NULL, 
    [BENZER] float NULL, 
    [EN] float NULL, 
    [BOY] float NULL,
    [H] float NULL,
    [TOPMIKTAR] float NULL, 
    [FIYAT] float NULL, 
    [TUTAR] float NULL, 
CONSTRAINT [ANALIZ_ROW_ID] PRIMARY KEY ([ANALIZ_ROW_ID] ASC));

CREATE TABLE [@_dsn_main_@].[EMPLOYEES_TEST_TIME_TYPE](
	[EMPLOYEES_TEST_TIME_TYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[TEST_TIME_TYPE_NAME] [nvarchar](150) NULL,
	[RECORD_DATE] [datetime] NULL,
	[RECORD_EMP] [int] NULL,
	[RECORD_IP] [nvarchar](50) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_EMP] [int] NULL,
	[UPDATE_IP] [nvarchar](50) NULL,
 CONSTRAINT [PK_EMPLOYEES_TEST_TIME_TYPE] PRIMARY KEY CLUSTERED 
(
	[EMPLOYEES_TEST_TIME_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [@_dsn_main_@].[MEASUREMENT_PARAMETERS_ROWS](
	[ROW_ID] [int] IDENTITY(1,1) NOT NULL,
	[UNIT_NAME] [nvarchar](150) NULL,
	[SHORT_UNIT_NAME] [nvarchar](50) NULL,
	[MEASUREMENT_ID] [int] NULL,
 CONSTRAINT [PK_MEASUREMENT_PARAMETERS_ROWS] PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [@_dsn_main_@].[MEASUREMENT_PARAMETERS](
	[MEASUREMENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[MEASUREMENT_NAME] [nvarchar](150) NULL,
 CONSTRAINT [PK_MEASUREMENT_PARAMETERS] PRIMARY KEY CLUSTERED 
(
	[MEASUREMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [@_dsn_main_@].[SETTINGS_CERTIFICATE](
	[CERTIFICATE_ID] [int] IDENTITY(1,1) NOT NULL,
	[CERTIFICATE_NAME] [nvarchar](100) NULL,
	[CERTIFICATE_DETAIL] [nvarchar](500) NULL,
	[IS_ACTIVE] [bit] NULL,
	[CERTIFICATE_PERIOD] [int] NULL,
	[CERTIFICATE_PERIOD_TYPE] [nvarchar](100) NULL,
	[RECORD_DATE] [datetime] NULL,
	[RECORD_EMP] [int] NULL,
	[RECORD_IP] [nvarchar](43) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_EMP] [int] NULL,
	[UPDATE_IP] [nvarchar](43) NULL,
 CONSTRAINT [PK_SETTINGS_CERTIFICATE_CERTIFICATE_ID] PRIMARY KEY CLUSTERED 
(
	[CERTIFICATE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [@_dsn_main_@].[WRK_DATA_SERVICE](
	[WRK_DATA_SERVICE_ID] [int] IDENTITY(1,1) NOT NULL,
	[HEAD] [nvarchar](150) NULL,
	[DETAIL] [nvarchar](max) NULL,
	[ZONE] [nvarchar](5) NULL,
	[AUTHOR] [nvarchar](50) NULL,
	[RECORD_DATE] [datetime] NULL,
	[IS_WORK] [bit] NULL,
	[UPDATE_DATE] [datetime] NULL,
	[VERSION] [nvarchar](50) NULL,
	[WEX_ID] [int] NULL,
	[MAIN_VERSION] [nvarchar](50) NULL,
	[PUBLISHING_DATE] [datetime] NULL,
	[RECORD_IP] [nvarchar](50) NULL,
	[RECORD_EMP] [int] NULL,
	[UPDATE_IP] [nvarchar](50) NULL,
	[UPDATE_EMP] [int] NULL,
 CONSTRAINT [PK_WRK_DATA_SERVICE] PRIMARY KEY CLUSTERED 
(
	[WRK_DATA_SERVICE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [@_dsn_main_@].[WRK_WATOMIC_SOLUTION](
	[WRK_WATOMIC_SOLUTION_ID] [int] IDENTITY(1,1) NOT NULL,
	[WRK_WATOMIC_SOLUTION_DICTIONARY_ID] [int] NULL,
	[WRK_WATOMIC_SOLUTION_NAME] [nvarchar](500) NULL,
	[WRK_WATOMIC_SOLITION_RANK_NUMBER] [int] NULL,
	[WRK_WATOMİC_SOLUTION_ICON] [nvarchar](250) NULL,
 CONSTRAINT [PK_WRK_WATOMIC_SOLUTION] PRIMARY KEY CLUSTERED 
(
	[WRK_WATOMIC_SOLUTION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'' , @level0type=N'SCHEMA',@level0name=N'@_dsn_main_@', @level1type=N'TABLE',@level1name=N'WRK_WATOMIC_SOLUTION', @level2type=N'COLUMN',@level2name=N'WRK_WATOMIC_SOLUTION_ID'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'WO classification by Watomic' , @level0type=N'SCHEMA',@level0name=N'@_dsn_main_@', @level1type=N'TABLE',@level1name=N'WRK_WATOMIC_SOLUTION'

CREATE TABLE [@_dsn_main_@].[WRK_WATOMIC_FAMILY](
	[WRK_WATOMIC_FAMILY_ID] [int] IDENTITY(1,1) NOT NULL,
	[WRK_WATOMIC_FAMILY_DICTONARY_ID] [int] NULL,
	[WATOMIC_FAMILY_NAME] [nvarchar](500) NULL,
	[WRK_WATOMIC_SOLUTION_ID] [int] NULL,
	[WATOMIC_FAMILY_RANK_NUMBER] [int] NULL,
	[WRK_WATOMIC_FAMILY_ICON] [nvarchar](50) NULL,
 CONSTRAINT [PK__WRK_WATO__9DD2BB2F385442BD] PRIMARY KEY CLUSTERED 
(
	[WRK_WATOMIC_FAMILY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'WO classification' , @level0type=N'SCHEMA',@level0name=N'@_dsn_main_@', @level1type=N'TABLE',@level1name=N'WRK_WATOMIC_FAMILY'